// packages/lib/src/bom/tariff-301-memberships.ts

/**
 * Section 301 list membership for every 8-digit HTSUS subheading
 * (plans/money/tasks/32-tariff-starter-catalogue.md §1.4, revised).
 *
 * `tariff-301-memberships.json` is generated by
 * `packages/lib/scripts/fetch-hts-301-lists.ts` from the four enumerations in
 * U.S. note 20 to subchapter III of chapter 99, and checked in. It is
 * generated, never edited by hand: rerun the script on a new HTS revision and
 * commit the diff.
 *
 * ## Why this is not in the hand-kept half any more
 *
 * 32 §1.4 split the catalogue into a GENERATED half (the HTS general rates)
 * and a HAND-KEPT half (`TARIFF_ACTIONS` + `TARIFF_MEMBERSHIPS`), on the
 * reasoning that list membership is expensive research. That was wrong, and it
 * was measurably wrong: the hand-kept table reached six entries and **three of
 * the six were incorrect** when checked against the note on 2026-09-01 —
 * `7318.15` was filed under List 1 and is List 3; `8536.50` was filed under
 * List 3 and is split across List 1 and List 2; `8501.10` was filed under List
 * 4A at 7.5% and is List 1/List 2 at 25%, understating every code under it by
 * 17.5 points.
 *
 * Membership is not research. It is ~10,000 subheadings enumerated in a
 * government document, and the only reason it looked expensive is that the
 * document is a PDF. So it belongs beside `tariff-hts-general.json`, on the
 * generated side, where nobody types a subheading by hand.
 *
 * 🛑 `8536.50` is also the proof that a 6-digit key CANNOT express this:
 * `8536.50.40` and `8536.50.90` are List 1 while `8536.50.70` is List 2. USTR
 * publishes at 8 digits and so does this file. `membershipsFor` already tried
 * the 8-digit prefix first; only the data was coarser than the lookup.
 *
 * 🛑 **Never export this module (or the JSON) through `bom/client.ts`.** Same
 * rule and same reason as `tariff-hts-general.ts`: the web bundle must not
 * carry the schedule. `expandTariffStarter` and `membershipsFor` stay pure and
 * client-safe by taking the table as an argument; the server loads it here.
 */

/** `{ '8481.80.90': ['301-3'] }` — 8-digit subheading to the list keys covering it. */
export type TariffMemberships = Readonly<Record<string, readonly string[]>>

interface RawMembershipFile {
  fetchedAt: string
  source: string
  memberships: Record<string, string[]>
}

/** The generated table plus the provenance the file carries. */
export interface Tariff301Memberships {
  fetchedAt: string
  source: string
  memberships: TariffMemberships
}

let cached: Tariff301Memberships | undefined

/**
 * Lazily imports the generated JSON on first call and memoises it for the
 * lifetime of the process.
 *
 * **Lazy on purpose**, the same argument `loadHtsGeneral` makes: the file
 * parses in a few milliseconds, but most process boots never price a tariff,
 * so there is no reason to pay that parse on every boot of every process.
 */
export async function loadTariff301Memberships(): Promise<Tariff301Memberships> {
  if (!cached) {
    const mod = await import('./tariff-301-memberships.json')
    const data = ((mod as { default?: unknown }).default ?? mod) as RawMembershipFile
    cached = { fetchedAt: data.fetchedAt, source: data.source, memberships: data.memberships }
  }
  return cached
}

/** The table alone, for the callers that do not need the provenance. */
export async function loadTariffMemberships(): Promise<TariffMemberships> {
  return (await loadTariff301Memberships()).memberships
}
