// components/pickers/emoji-picker/emoji-categories.ts
import { Smile, TreePine, Coffee, Gamepad2, MapPin, Package, Hash, Flag } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export interface EmojiItem {
  id: string
  label: string
  emoji: string
}

export interface EmojiGroup {
  id: string
  label: string
  icon: LucideIcon
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  { id: 'smileys', label: 'Smileys and People', icon: Smile },
  { id: 'animals', label: 'Animals and Nature', icon: TreePine },
  { id: 'food', label: 'Food and Drink', icon: Coffee },
  { id: 'activity', label: 'Activity', icon: Gamepad2 },
  { id: 'travel', label: 'Travel and Places', icon: MapPin },
  { id: 'objects', label: 'Objects', icon: Package },
  { id: 'symbols', label: 'Symbols', icon: Hash },
  { id: 'flags', label: 'Flags', icon: Flag },
]

const createEmojiItem = (emoji: string, label?: string): EmojiItem => ({
  id: `:${label?.toLowerCase().replace(/\s+/g, '_') || emoji}:`,
  label: label || emoji,
  emoji,
})

export const EMOJI_DATA: Record<string, EmojiItem[]> = {
  smileys: [
    createEmojiItem('😀', 'Grinning face'),
    createEmojiItem('😃', 'Grinning face with big eyes'),
    createEmojiItem('😄', 'Grinning face with smiling eyes'),
    createEmojiItem('😁', 'Beaming face with smiling eyes'),
    createEmojiItem('😆', 'Grinning squinting face'),
    createEmojiItem('😅', 'Grinning face with sweat'),
    createEmojiItem('🤣', 'Rolling on the floor laughing'),
    createEmojiItem('😂', 'Face with tears of joy'),
    createEmojiItem('🙂', 'Slightly smiling face'),
    createEmojiItem('🙃', 'Upside down face'),
    createEmojiItem('😉', 'Winking face'),
    createEmojiItem('😊', 'Smiling face with smiling eyes'),
    createEmojiItem('😇', 'Smiling face with halo'),
    createEmojiItem('🥰', 'Smiling face with hearts'),
    createEmojiItem('😍', 'Smiling face with heart-eyes'),
    createEmojiItem('🤩', 'Star-struck'),
    createEmojiItem('😘', 'Face blowing a kiss'),
    createEmojiItem('😗', 'Kissing face'),
    createEmojiItem('☺️', 'Smiling face'),
    createEmojiItem('😚', 'Kissing face with closed eyes'),
    createEmojiItem('😙', 'Kissing face with smiling eyes'),
    createEmojiItem('😋', 'Face savoring food'),
    createEmojiItem('😛', 'Face with tongue'),
    createEmojiItem('😜', 'Winking face with tongue'),
    createEmojiItem('🤪', 'Zany face'),
    createEmojiItem('😝', 'Squinting face with tongue'),
    createEmojiItem('🤑', 'Money-mouth face'),
    createEmojiItem('🤗', 'Smiling face with open hands'),
    createEmojiItem('🤭', 'Face with hand over mouth'),
    createEmojiItem('🤫', 'Shushing face'),
    createEmojiItem('🤔', 'Thinking face'),
    createEmojiItem('🤐', 'Zipper-mouth face'),
    createEmojiItem('🤨', 'Face with raised eyebrow'),
    createEmojiItem('😐', 'Neutral face'),
    createEmojiItem('😑', 'Expressionless face'),
    createEmojiItem('😶', 'Face without mouth'),
    createEmojiItem('😏', 'Smirking face'),
    createEmojiItem('😒', 'Unamused face'),
    createEmojiItem('🙄', 'Face with rolling eyes'),
    createEmojiItem('😬', 'Grimacing face'),
    createEmojiItem('🤥', 'Lying face'),
    createEmojiItem('😔', 'Pensive face'),
    createEmojiItem('😪', 'Sleepy face'),
    createEmojiItem('🤤', 'Drooling face'),
    createEmojiItem('😴', 'Sleeping face'),
    createEmojiItem('😷', 'Face with medical mask'),
    createEmojiItem('🤒', 'Face with thermometer'),
    createEmojiItem('🤕', 'Face with head-bandage'),
    createEmojiItem('🤢', 'Nauseated face'),
    createEmojiItem('🤮', 'Face vomiting'),
    createEmojiItem('🤧', 'Sneezing face'),
    createEmojiItem('🥵', 'Hot face'),
    createEmojiItem('🥶', 'Cold face'),
    createEmojiItem('🥴', 'Woozy face'),
    createEmojiItem('😵', 'Face with crossed-out eyes'),
    createEmojiItem('🤯', 'Exploding head'),
    createEmojiItem('🤠', 'Cowboy hat face'),
    createEmojiItem('🥳', 'Partying face'),
    createEmojiItem('😎', 'Smiling face with sunglasses'),
    createEmojiItem('🤓', 'Nerd face'),
    createEmojiItem('🧐', 'Face with monocle'),
    // Hand gestures
    createEmojiItem('👋', 'Waving hand'),
    createEmojiItem('🤚', 'Raised back of hand'),
    createEmojiItem('🖐️', 'Hand with fingers splayed'),
    createEmojiItem('✋', 'Raised hand'),
    createEmojiItem('🖖', 'Vulcan salute'),
    createEmojiItem('👌', 'OK hand'),
    createEmojiItem('🤌', 'Pinched fingers'),
    createEmojiItem('🤏', 'Pinching hand'),
    createEmojiItem('✌️', 'Victory hand'),
    createEmojiItem('🤞', 'Crossed fingers'),
    createEmojiItem('🤟', 'Love-you gesture'),
    createEmojiItem('🤘', 'Sign of the horns'),
    createEmojiItem('🤙', 'Call me hand'),
    createEmojiItem('👈', 'Backhand index pointing left'),
    createEmojiItem('👉', 'Backhand index pointing right'),
    createEmojiItem('👆', 'Backhand index pointing up'),
    createEmojiItem('👇', 'Backhand index pointing down'),
    createEmojiItem('☝️', 'Index pointing up'),
    createEmojiItem('👍', 'Thumbs up'),
    createEmojiItem('👎', 'Thumbs down'),
    createEmojiItem('✊', 'Raised fist'),
    createEmojiItem('👊', 'Oncoming fist'),
    createEmojiItem('🤛', 'Left-facing fist'),
    createEmojiItem('🤜', 'Right-facing fist'),
    createEmojiItem('👏', 'Clapping hands'),
    createEmojiItem('🙌', 'Raising hands'),
    createEmojiItem('👐', 'Open hands'),
    createEmojiItem('🤲', 'Palms up together'),
    createEmojiItem('🤝', 'Handshake'),
    createEmojiItem('🙏', 'Folded hands'),
    // People
    createEmojiItem('👶', 'Baby'),
    createEmojiItem('🧒', 'Child'),
    createEmojiItem('👦', 'Boy'),
    createEmojiItem('👧', 'Girl'),
    createEmojiItem('🧑', 'Person'),
    createEmojiItem('👨', 'Man'),
    createEmojiItem('👩', 'Woman'),
    createEmojiItem('🧓', 'Older person'),
    createEmojiItem('👴', 'Old man'),
    createEmojiItem('👵', 'Old woman'),
  ],

  animals: [
    createEmojiItem('🐶', 'Dog face'),
    createEmojiItem('🐱', 'Cat face'),
    createEmojiItem('🐭', 'Mouse face'),
    createEmojiItem('🐹', 'Hamster'),
    createEmojiItem('🐰', 'Rabbit face'),
    createEmojiItem('🦊', 'Fox'),
    createEmojiItem('🐻', 'Bear'),
    createEmojiItem('🐼', 'Panda'),
    createEmojiItem('🐨', 'Koala'),
    createEmojiItem('🐯', 'Tiger face'),
    createEmojiItem('🦁', 'Lion'),
    createEmojiItem('🐮', 'Cow face'),
    createEmojiItem('🐷', 'Pig face'),
    createEmojiItem('🐸', 'Frog'),
    createEmojiItem('🐵', 'Monkey face'),
    createEmojiItem('🙈', 'See-no-evil monkey'),
    createEmojiItem('🙉', 'Hear-no-evil monkey'),
    createEmojiItem('🙊', 'Speak-no-evil monkey'),
    createEmojiItem('🐒', 'Monkey'),
    createEmojiItem('🐔', 'Chicken'),
    createEmojiItem('🐧', 'Penguin'),
    createEmojiItem('🐦', 'Bird'),
    createEmojiItem('🐤', 'Baby chick'),
    createEmojiItem('🐣', 'Hatching chick'),
    createEmojiItem('🐥', 'Front-facing baby chick'),
    createEmojiItem('🦆', 'Duck'),
    createEmojiItem('🦅', 'Eagle'),
    createEmojiItem('🦉', 'Owl'),
    createEmojiItem('🦇', 'Bat'),
    createEmojiItem('🐺', 'Wolf'),
    createEmojiItem('🐗', 'Boar'),
    createEmojiItem('🐴', 'Horse face'),
    createEmojiItem('🦄', 'Unicorn'),
    createEmojiItem('🐝', 'Honeybee'),
    createEmojiItem('🐛', 'Bug'),
    createEmojiItem('🦋', 'Butterfly'),
    createEmojiItem('🐌', 'Snail'),
    createEmojiItem('🐞', 'Lady beetle'),
    createEmojiItem('🐜', 'Ant'),
    createEmojiItem('🕷️', 'Spider'),
    createEmojiItem('🕸️', 'Spider web'),
    createEmojiItem('🦂', 'Scorpion'),
    createEmojiItem('🐢', 'Turtle'),
    createEmojiItem('🐍', 'Snake'),
    createEmojiItem('🦎', 'Lizard'),
    createEmojiItem('🦖', 'T-Rex'),
    createEmojiItem('🦕', 'Sauropod'),
    createEmojiItem('🐙', 'Octopus'),
    createEmojiItem('🦑', 'Squid'),
    createEmojiItem('🦐', 'Shrimp'),
    createEmojiItem('🦞', 'Lobster'),
    createEmojiItem('🦀', 'Crab'),
    createEmojiItem('🐡', 'Blowfish'),
    createEmojiItem('🐠', 'Tropical fish'),
    createEmojiItem('🐟', 'Fish'),
    createEmojiItem('🐬', 'Dolphin'),
    createEmojiItem('🐳', 'Spouting whale'),
    createEmojiItem('🐋', 'Whale'),
    createEmojiItem('🦈', 'Shark'),
    createEmojiItem('🐊', 'Crocodile'),
    createEmojiItem('🐅', 'Tiger'),
    createEmojiItem('🐆', 'Leopard'),
    createEmojiItem('🦓', 'Zebra'),
    createEmojiItem('🦍', 'Gorilla'),
    createEmojiItem('🦧', 'Orangutan'),
    createEmojiItem('🐘', 'Elephant'),
    createEmojiItem('🦏', 'Rhinoceros'),
    createEmojiItem('🦛', 'Hippopotamus'),
    createEmojiItem('🐪', 'Camel'),
    createEmojiItem('🐫', 'Two-hump camel'),
    createEmojiItem('🦒', 'Giraffe'),
    createEmojiItem('🦘', 'Kangaroo'),
    createEmojiItem('🐃', 'Water buffalo'),
    createEmojiItem('🐂', 'Ox'),
    createEmojiItem('🐄', 'Cow'),
    createEmojiItem('🐎', 'Horse'),
    createEmojiItem('🐖', 'Pig'),
    createEmojiItem('🐏', 'Ram'),
    createEmojiItem('🐑', 'Ewe'),
    createEmojiItem('🦙', 'Llama'),
    createEmojiItem('🐐', 'Goat'),
    createEmojiItem('🦌', 'Deer'),
    createEmojiItem('🐕', 'Dog'),
    createEmojiItem('🐩', 'Poodle'),
    createEmojiItem('🐈', 'Cat'),
    createEmojiItem('🐾', 'Paw prints'),
    // Plants and nature
    createEmojiItem('🌱', 'Seedling'),
    createEmojiItem('🌿', 'Herb'),
    createEmojiItem('☘️', 'Shamrock'),
    createEmojiItem('🍀', 'Four leaf clover'),
    createEmojiItem('🌲', 'Evergreen tree'),
    createEmojiItem('🌳', 'Deciduous tree'),
    createEmojiItem('🌴', 'Palm tree'),
    createEmojiItem('🌵', 'Cactus'),
    createEmojiItem('🌷', 'Tulip'),
    createEmojiItem('🌸', 'Cherry blossom'),
    createEmojiItem('🌹', 'Rose'),
    createEmojiItem('🌺', 'Hibiscus'),
    createEmojiItem('🌻', 'Sunflower'),
    createEmojiItem('🌼', 'Blossom'),
    createEmojiItem('💐', 'Bouquet'),
    createEmojiItem('🍄', 'Mushroom'),
    createEmojiItem('🍁', 'Maple leaf'),
    createEmojiItem('🍂', 'Fallen leaves'),
    createEmojiItem('🍃', 'Leaf fluttering in wind'),
  ],

  food: [
    createEmojiItem('🍇', 'Grapes'),
    createEmojiItem('🍈', 'Melon'),
    createEmojiItem('🍉', 'Watermelon'),
    createEmojiItem('🍊', 'Tangerine'),
    createEmojiItem('🍋', 'Lemon'),
    createEmojiItem('🍌', 'Banana'),
    createEmojiItem('🍍', 'Pineapple'),
    createEmojiItem('🥭', 'Mango'),
    createEmojiItem('🍎', 'Red apple'),
    createEmojiItem('🍏', 'Green apple'),
    createEmojiItem('🍐', 'Pear'),
    createEmojiItem('🍑', 'Peach'),
    createEmojiItem('🍒', 'Cherries'),
    createEmojiItem('🍓', 'Strawberry'),
    createEmojiItem('🥝', 'Kiwi fruit'),
    createEmojiItem('🍅', 'Tomato'),
    createEmojiItem('🥑', 'Avocado'),
    createEmojiItem('🍆', 'Eggplant'),
    createEmojiItem('🥔', 'Potato'),
    createEmojiItem('🥕', 'Carrot'),
    createEmojiItem('🌽', 'Corn'),
    createEmojiItem('🌶️', 'Hot pepper'),
    createEmojiItem('🥒', 'Cucumber'),
    createEmojiItem('🥬', 'Leafy greens'),
    createEmojiItem('🥦', 'Broccoli'),
    createEmojiItem('🧄', 'Garlic'),
    createEmojiItem('🧅', 'Onion'),
    createEmojiItem('🥜', 'Peanuts'),
    createEmojiItem('🌰', 'Chestnut'),
    createEmojiItem('🍞', 'Bread'),
    createEmojiItem('🥐', 'Croissant'),
    createEmojiItem('🥖', 'Baguette bread'),
    createEmojiItem('🥨', 'Pretzel'),
    createEmojiItem('🥯', 'Bagel'),
    createEmojiItem('🥞', 'Pancakes'),
    createEmojiItem('🧇', 'Waffle'),
    createEmojiItem('🧀', 'Cheese wedge'),
    createEmojiItem('🍖', 'Meat on bone'),
    createEmojiItem('🍗', 'Poultry leg'),
    createEmojiItem('🥩', 'Cut of meat'),
    createEmojiItem('🥓', 'Bacon'),
    createEmojiItem('🍔', 'Hamburger'),
    createEmojiItem('🍟', 'French fries'),
    createEmojiItem('🍕', 'Pizza'),
    createEmojiItem('🌭', 'Hot dog'),
    createEmojiItem('🥪', 'Sandwich'),
    createEmojiItem('🌮', 'Taco'),
    createEmojiItem('🌯', 'Burrito'),
    createEmojiItem('🥚', 'Egg'),
    createEmojiItem('🍳', 'Cooking'),
    createEmojiItem('🥘', 'Shallow pan of food'),
    createEmojiItem('🍲', 'Pot of food'),
    createEmojiItem('🥣', 'Bowl with spoon'),
    createEmojiItem('🥗', 'Green salad'),
    createEmojiItem('🍿', 'Popcorn'),
    createEmojiItem('🧈', 'Butter'),
    createEmojiItem('🧂', 'Salt'),
    createEmojiItem('🥫', 'Canned food'),
    createEmojiItem('🍱', 'Bento box'),
    createEmojiItem('🍘', 'Rice cracker'),
    createEmojiItem('🍙', 'Rice ball'),
    createEmojiItem('🍚', 'Cooked rice'),
    createEmojiItem('🍛', 'Curry rice'),
    createEmojiItem('🍜', 'Steaming bowl'),
    createEmojiItem('🍝', 'Spaghetti'),
    createEmojiItem('🍠', 'Roasted sweet potato'),
    createEmojiItem('🍢', 'Oden'),
    createEmojiItem('🍣', 'Sushi'),
    createEmojiItem('🍤', 'Fried shrimp'),
    createEmojiItem('🍥', 'Fish cake with swirl'),
    createEmojiItem('🥟', 'Dumpling'),
    createEmojiItem('🥠', 'Fortune cookie'),
    createEmojiItem('🥡', 'Takeout box'),
    // Desserts and sweets
    createEmojiItem('🍦', 'Soft ice cream'),
    createEmojiItem('🍧', 'Shaved ice'),
    createEmojiItem('🍨', 'Ice cream'),
    createEmojiItem('🍩', 'Doughnut'),
    createEmojiItem('🍪', 'Cookie'),
    createEmojiItem('🎂', 'Birthday cake'),
    createEmojiItem('🍰', 'Shortcake'),
    createEmojiItem('🧁', 'Cupcake'),
    createEmojiItem('🥧', 'Pie'),
    createEmojiItem('🍫', 'Chocolate bar'),
    createEmojiItem('🍬', 'Candy'),
    createEmojiItem('🍭', 'Lollipop'),
    createEmojiItem('🍮', 'Custard'),
    createEmojiItem('🍯', 'Honey pot'),
    // Drinks
    createEmojiItem('🍼', 'Baby bottle'),
    createEmojiItem('🥛', 'Glass of milk'),
    createEmojiItem('☕', 'Hot beverage'),
    createEmojiItem('🍵', 'Teacup without handle'),
    createEmojiItem('🍶', 'Sake'),
    createEmojiItem('🍾', 'Bottle with popping cork'),
    createEmojiItem('🍷', 'Wine glass'),
    createEmojiItem('🍸', 'Cocktail glass'),
    createEmojiItem('🍹', 'Tropical drink'),
    createEmojiItem('🍺', 'Beer mug'),
    createEmojiItem('🍻', 'Clinking beer mugs'),
    createEmojiItem('🥂', 'Clinking glasses'),
    createEmojiItem('🥃', 'Tumbler glass'),
    createEmojiItem('🥤', 'Cup with straw'),
    createEmojiItem('🧋', 'Bubble tea'),
    createEmojiItem('🧃', 'Beverage box'),
    createEmojiItem('🧉', 'Mate'),
    createEmojiItem('🧊', 'Ice'),
  ],

  activity: [
    createEmojiItem('⚽', 'Soccer ball'),
    createEmojiItem('🏀', 'Basketball'),
    createEmojiItem('🏈', 'American football'),
    createEmojiItem('⚾', 'Baseball'),
    createEmojiItem('🥎', 'Softball'),
    createEmojiItem('🎾', 'Tennis'),
    createEmojiItem('🏐', 'Volleyball'),
    createEmojiItem('🏉', 'Rugby football'),
    createEmojiItem('🥏', 'Flying disc'),
    createEmojiItem('🎱', '8 ball'),
    createEmojiItem('🏓', 'Ping pong'),
    createEmojiItem('🏸', 'Badminton'),
    createEmojiItem('🏒', 'Ice hockey'),
    createEmojiItem('🏑', 'Field hockey'),
    createEmojiItem('🥍', 'Lacrosse'),
    createEmojiItem('🏏', 'Cricket game'),
    createEmojiItem('🥅', 'Goal net'),
    createEmojiItem('⛳', 'Flag in hole'),
    createEmojiItem('🏹', 'Bow and arrow'),
    createEmojiItem('🎣', 'Fishing pole'),
    createEmojiItem('🤿', 'Diving mask'),
    createEmojiItem('🥊', 'Boxing glove'),
    createEmojiItem('🥋', 'Martial arts uniform'),
    createEmojiItem('🎽', 'Running shirt'),
    createEmojiItem('🛹', 'Skateboard'),
    createEmojiItem('🛷', 'Sled'),
    createEmojiItem('⛸️', 'Ice skate'),
    createEmojiItem('🥌', 'Curling stone'),
    createEmojiItem('🎿', 'Skis'),
    createEmojiItem('⛷️', 'Skier'),
    createEmojiItem('🏂', 'Snowboarder'),
    createEmojiItem('🏋️', 'Person lifting weights'),
    createEmojiItem('🤼', 'People wrestling'),
    createEmojiItem('🤸', 'Person cartwheeling'),
    createEmojiItem('⛹️', 'Person bouncing ball'),
    createEmojiItem('🤺', 'Person fencing'),
    createEmojiItem('🤾', 'Person playing handball'),
    createEmojiItem('🏌️', 'Person golfing'),
    createEmojiItem('🏇', 'Horse racing'),
    createEmojiItem('🧘', 'Person in lotus position'),
    createEmojiItem('🏄', 'Person surfing'),
    createEmojiItem('🏊', 'Person swimming'),
    createEmojiItem('🤽', 'Person playing water polo'),
    createEmojiItem('🚣', 'Person rowing boat'),
    createEmojiItem('🧗', 'Person climbing'),
    createEmojiItem('🚵', 'Person mountain biking'),
    createEmojiItem('🚴', 'Person biking'),
    createEmojiItem('🏆', 'Trophy'),
    createEmojiItem('🥇', '1st place medal'),
    createEmojiItem('🥈', '2nd place medal'),
    createEmojiItem('🥉', '3rd place medal'),
    createEmojiItem('🏅', 'Sports medal'),
    createEmojiItem('🎖️', 'Military medal'),
    createEmojiItem('🏵️', 'Rosette'),
    createEmojiItem('🎗️', 'Reminder ribbon'),
    createEmojiItem('🎫', 'Ticket'),
    createEmojiItem('🎟️', 'Admission tickets'),
    createEmojiItem('🎪', 'Circus tent'),
    createEmojiItem('🤹', 'Person juggling'),
    createEmojiItem('🎭', 'Performing arts'),
    createEmojiItem('🎨', 'Artist palette'),
    createEmojiItem('🎬', 'Clapper board'),
    createEmojiItem('🎤', 'Microphone'),
    createEmojiItem('🎧', 'Headphone'),
    createEmojiItem('🎼', 'Musical score'),
    createEmojiItem('🎵', 'Musical note'),
    createEmojiItem('🎶', 'Musical notes'),
    createEmojiItem('🥁', 'Drum'),
    createEmojiItem('🎹', 'Musical keyboard'),
    createEmojiItem('🎷', 'Saxophone'),
    createEmojiItem('🎺', 'Trumpet'),
    createEmojiItem('🎸', 'Guitar'),
    createEmojiItem('🎻', 'Violin'),
    createEmojiItem('🎲', 'Game die'),
    createEmojiItem('🎯', 'Direct hit'),
    createEmojiItem('🎳', 'Bowling'),
    createEmojiItem('🎮', 'Video game'),
    createEmojiItem('🕹️', 'Joystick'),
    createEmojiItem('🎰', 'Slot machine'),
    createEmojiItem('🎴', 'Flower playing cards'),
    createEmojiItem('🃏', 'Joker'),
    createEmojiItem('🀄', 'Mahjong red dragon'),
  ],

  travel: [
    createEmojiItem('🌍', 'Globe showing Europe-Africa'),
    createEmojiItem('🌎', 'Globe showing Americas'),
    createEmojiItem('🌏', 'Globe showing Asia-Australia'),
    createEmojiItem('🌐', 'Globe with meridians'),
    createEmojiItem('🗺️', 'World map'),
    createEmojiItem('🧭', 'Compass'),
    createEmojiItem('🏔️', 'Snow-capped mountain'),
    createEmojiItem('⛰️', 'Mountain'),
    createEmojiItem('🌋', 'Volcano'),
    createEmojiItem('🗻', 'Mount Fuji'),
    createEmojiItem('🏕️', 'Camping'),
    createEmojiItem('🏖️', 'Beach with umbrella'),
    createEmojiItem('🏜️', 'Desert'),
    createEmojiItem('🏝️', 'Desert island'),
    createEmojiItem('🏞️', 'National park'),
    createEmojiItem('🏟️', 'Stadium'),
    createEmojiItem('🏛️', 'Classical building'),
    createEmojiItem('🏗️', 'Building construction'),
    createEmojiItem('🏘️', 'Houses'),
    createEmojiItem('🏚️', 'Derelict house'),
    createEmojiItem('🏠', 'House'),
    createEmojiItem('🏡', 'House with garden'),
    createEmojiItem('🏢', 'Office building'),
    createEmojiItem('🏣', 'Japanese post office'),
    createEmojiItem('🏤', 'Post office'),
    createEmojiItem('🏥', 'Hospital'),
    createEmojiItem('🏦', 'Bank'),
    createEmojiItem('🏨', 'Hotel'),
    createEmojiItem('🏩', 'Love hotel'),
    createEmojiItem('🏪', 'Convenience store'),
    createEmojiItem('🏫', 'School'),
    createEmojiItem('🏬', 'Department store'),
    createEmojiItem('🏭', 'Factory'),
    createEmojiItem('🏯', 'Japanese castle'),
    createEmojiItem('🏰', 'Castle'),
    createEmojiItem('💒', 'Wedding'),
    createEmojiItem('🗼', 'Tokyo tower'),
    createEmojiItem('🗽', 'Statue of Liberty'),
    createEmojiItem('⛪', 'Church'),
    createEmojiItem('🕌', 'Mosque'),
    createEmojiItem('🛕', 'Hindu temple'),
    createEmojiItem('🕍', 'Synagogue'),
    createEmojiItem('⛩️', 'Shinto shrine'),
    createEmojiItem('🕋', 'Kaaba'),
    createEmojiItem('⛲', 'Fountain'),
    createEmojiItem('⛺', 'Tent'),
    createEmojiItem('🌁', 'Foggy'),
    createEmojiItem('🌃', 'Night with stars'),
    createEmojiItem('🏙️', 'Cityscape'),
    createEmojiItem('🌄', 'Sunrise over mountains'),
    createEmojiItem('🌅', 'Sunrise'),
    createEmojiItem('🌆', 'Cityscape at dusk'),
    createEmojiItem('🌇', 'Sunset'),
    createEmojiItem('🌉', 'Bridge at night'),
    createEmojiItem('♨️', 'Hot springs'),
    createEmojiItem('🎠', 'Carousel horse'),
    createEmojiItem('🎡', 'Ferris wheel'),
    createEmojiItem('🎢', 'Roller coaster'),
    createEmojiItem('💈', 'Barber pole'),
    createEmojiItem('🎪', 'Circus tent'),
    // Transportation
    createEmojiItem('🚂', 'Locomotive'),
    createEmojiItem('🚃', 'Railway car'),
    createEmojiItem('🚄', 'High-speed train'),
    createEmojiItem('🚅', 'Bullet train'),
    createEmojiItem('🚆', 'Train'),
    createEmojiItem('🚇', 'Metro'),
    createEmojiItem('🚈', 'Light rail'),
    createEmojiItem('🚉', 'Station'),
    createEmojiItem('🚊', 'Tram'),
    createEmojiItem('🚝', 'Monorail'),
    createEmojiItem('🚞', 'Mountain railway'),
    createEmojiItem('🚋', 'Tram car'),
    createEmojiItem('🚌', 'Bus'),
    createEmojiItem('🚍', 'Oncoming bus'),
    createEmojiItem('🚎', 'Trolleybus'),
    createEmojiItem('🚐', 'Minibus'),
    createEmojiItem('🚑', 'Ambulance'),
    createEmojiItem('🚒', 'Fire engine'),
    createEmojiItem('🚓', 'Police car'),
    createEmojiItem('🚔', 'Oncoming police car'),
    createEmojiItem('🚕', 'Taxi'),
    createEmojiItem('🚖', 'Oncoming taxi'),
    createEmojiItem('🚗', 'Automobile'),
    createEmojiItem('🚘', 'Oncoming automobile'),
    createEmojiItem('🚙', 'Sport utility vehicle'),
    createEmojiItem('🚚', 'Delivery truck'),
    createEmojiItem('🚛', 'Articulated lorry'),
    createEmojiItem('🚜', 'Tractor'),
    createEmojiItem('🏎️', 'Racing car'),
    createEmojiItem('🏍️', 'Motorcycle'),
    createEmojiItem('🛴', 'Kick scooter'),
    createEmojiItem('🚲', 'Bicycle'),
    createEmojiItem('🛺', 'Auto rickshaw'),
    createEmojiItem('🚁', 'Helicopter'),
    createEmojiItem('🛰️', 'Satellite'),
    createEmojiItem('🚀', 'Rocket'),
    createEmojiItem('🛸', 'Flying saucer'),
    createEmojiItem('🛶', 'Canoe'),
    createEmojiItem('⛵', 'Sailboat'),
    createEmojiItem('🚤', 'Speedboat'),
    createEmojiItem('🚢', 'Ship'),
    createEmojiItem('✈️', 'Airplane'),
    createEmojiItem('🛩️', 'Small airplane'),
    createEmojiItem('🛫', 'Airplane departure'),
    createEmojiItem('🛬', 'Airplane arrival'),
    createEmojiItem('💺', 'Seat'),
    createEmojiItem('🚨', 'Police car light'),
    createEmojiItem('🚥', 'Horizontal traffic light'),
    createEmojiItem('🚦', 'Vertical traffic light'),
    createEmojiItem('🛑', 'Stop sign'),
    createEmojiItem('🚧', 'Construction'),
  ],

  objects: [
    createEmojiItem('⌚', 'Watch'),
    createEmojiItem('📱', 'Mobile phone'),
    createEmojiItem('📲', 'Mobile phone with arrow'),
    createEmojiItem('💻', 'Laptop'),
    createEmojiItem('⌨️', 'Keyboard'),
    createEmojiItem('🖥️', 'Desktop computer'),
    createEmojiItem('🖨️', 'Printer'),
    createEmojiItem('🖱️', 'Computer mouse'),
    createEmojiItem('🖲️', 'Trackball'),
    createEmojiItem('🕹️', 'Joystick'),
    createEmojiItem('💽', 'Computer disk'),
    createEmojiItem('💾', 'Floppy disk'),
    createEmojiItem('💿', 'Optical disk'),
    createEmojiItem('📀', 'DVD'),
    createEmojiItem('📼', 'Videocassette'),
    createEmojiItem('📷', 'Camera'),
    createEmojiItem('📸', 'Camera with flash'),
    createEmojiItem('📹', 'Video camera'),
    createEmojiItem('🎥', 'Movie camera'),
    createEmojiItem('📽️', 'Film projector'),
    createEmojiItem('🎞️', 'Film strip'),
    createEmojiItem('📞', 'Telephone receiver'),
    createEmojiItem('☎️', 'Telephone'),
    createEmojiItem('📟', 'Pager'),
    createEmojiItem('📠', 'Fax machine'),
    createEmojiItem('📺', 'Television'),
    createEmojiItem('📻', 'Radio'),
    createEmojiItem('🎙️', 'Studio microphone'),
    createEmojiItem('🎚️', 'Level slider'),
    createEmojiItem('🎛️', 'Control knobs'),
    createEmojiItem('⏱️', 'Stopwatch'),
    createEmojiItem('⏲️', 'Timer clock'),
    createEmojiItem('⏰', 'Alarm clock'),
    createEmojiItem('🕰️', 'Mantelpiece clock'),
    createEmojiItem('⌛', 'Hourglass done'),
    createEmojiItem('⏳', 'Hourglass not done'),
    createEmojiItem('📡', 'Satellite antenna'),
    createEmojiItem('🔋', 'Battery'),
    createEmojiItem('🔌', 'Electric plug'),
    createEmojiItem('💡', 'Light bulb'),
    createEmojiItem('🔦', 'Flashlight'),
    createEmojiItem('🕯️', 'Candle'),
    createEmojiItem('🧯', 'Fire extinguisher'),
    createEmojiItem('🛢️', 'Oil drum'),
    createEmojiItem('💸', 'Money with wings'),
    createEmojiItem('💵', 'Dollar banknote'),
    createEmojiItem('💴', 'Yen banknote'),
    createEmojiItem('💶', 'Euro banknote'),
    createEmojiItem('💷', 'Pound banknote'),
    createEmojiItem('💰', 'Money bag'),
    createEmojiItem('💳', 'Credit card'),
    createEmojiItem('💎', 'Gem stone'),
    createEmojiItem('⚖️', 'Balance scale'),
    createEmojiItem('🧰', 'Toolbox'),
    createEmojiItem('🔧', 'Wrench'),
    createEmojiItem('🔨', 'Hammer'),
    createEmojiItem('⚒️', 'Hammer and pick'),
    createEmojiItem('🛠️', 'Hammer and wrench'),
    createEmojiItem('⛏️', 'Pick'),
    createEmojiItem('🔩', 'Nut and bolt'),
    createEmojiItem('⚙️', 'Gear'),
    createEmojiItem('🧱', 'Brick'),
    createEmojiItem('⛓️', 'Chains'),
    createEmojiItem('🧲', 'Magnet'),
    createEmojiItem('🔫', 'Water pistol'),
    createEmojiItem('💣', 'Bomb'),
    createEmojiItem('🧨', 'Firecracker'),
    createEmojiItem('🔪', 'Kitchen knife'),
    createEmojiItem('🗡️', 'Dagger'),
    createEmojiItem('⚔️', 'Crossed swords'),
    createEmojiItem('🛡️', 'Shield'),
    createEmojiItem('🚬', 'Cigarette'),
    createEmojiItem('⚰️', 'Coffin'),
    createEmojiItem('⚱️', 'Funeral urn'),
    createEmojiItem('🏺', 'Amphora'),
    createEmojiItem('🔮', 'Crystal ball'),
    createEmojiItem('📿', 'Prayer beads'),
    createEmojiItem('🧿', 'Nazar amulet'),
    createEmojiItem('💈', 'Barber pole'),
    createEmojiItem('⚗️', 'Alembic'),
    createEmojiItem('🔭', 'Telescope'),
    createEmojiItem('🔬', 'Microscope'),
    createEmojiItem('🕳️', 'Hole'),
    createEmojiItem('💊', 'Pill'),
    createEmojiItem('💉', 'Syringe'),
    createEmojiItem('🌡️', 'Thermometer'),
    createEmojiItem('🧹', 'Broom'),
    createEmojiItem('🧺', 'Basket'),
    createEmojiItem('🧻', 'Roll of paper'),
    createEmojiItem('🚽', 'Toilet'),
    createEmojiItem('🚿', 'Shower'),
    createEmojiItem('🛁', 'Bathtub'),
    createEmojiItem('🧴', 'Lotion bottle'),
    createEmojiItem('🧷', 'Safety pin'),
    createEmojiItem('🧸', 'Teddy bear'),
    createEmojiItem('🖼️', 'Framed picture'),
    createEmojiItem('🛏️', 'Bed'),
    createEmojiItem('🛋️', 'Couch and lamp'),
    createEmojiItem('🚪', 'Door'),
    createEmojiItem('🧳', 'Luggage'),
    createEmojiItem('⛱️', 'Umbrella on ground'),
    createEmojiItem('🎒', 'Backpack'),
    createEmojiItem('👝', 'Clutch bag'),
    createEmojiItem('👛', 'Purse'),
    createEmojiItem('👜', 'Handbag'),
    createEmojiItem('💼', 'Briefcase'),
    createEmojiItem('🧥', 'Coat'),
    createEmojiItem('👔', 'Necktie'),
    createEmojiItem('👕', 'T-shirt'),
    createEmojiItem('👖', 'Jeans'),
    createEmojiItem('🧣', 'Scarf'),
    createEmojiItem('🧤', 'Gloves'),
    createEmojiItem('🧦', 'Socks'),
    createEmojiItem('👗', 'Dress'),
    createEmojiItem('👘', 'Kimono'),
    createEmojiItem('👙', 'Bikini'),
    createEmojiItem('👚', 'Womans clothes'),
    createEmojiItem('👞', 'Mans shoe'),
    createEmojiItem('👟', 'Running shoe'),
    createEmojiItem('👠', 'High-heeled shoe'),
    createEmojiItem('👡', 'Sandal'),
    createEmojiItem('👢', 'Boot'),
    createEmojiItem('👑', 'Crown'),
    createEmojiItem('👒', 'Hat'),
    createEmojiItem('🎩', 'Top hat'),
    createEmojiItem('🎓', 'Graduation cap'),
    createEmojiItem('🧢', 'Baseball cap'),
    createEmojiItem('⛑️', 'Rescue workers helmet'),
    createEmojiItem('💄', 'Lipstick'),
    createEmojiItem('💍', 'Ring'),
  ],

  symbols: [
    createEmojiItem('❤️', 'Red heart'),
    createEmojiItem('🧡', 'Orange heart'),
    createEmojiItem('💛', 'Yellow heart'),
    createEmojiItem('💚', 'Green heart'),
    createEmojiItem('💙', 'Blue heart'),
    createEmojiItem('💜', 'Purple heart'),
    createEmojiItem('🖤', 'Black heart'),
    createEmojiItem('🤍', 'White heart'),
    createEmojiItem('🤎', 'Brown heart'),
    createEmojiItem('💔', 'Broken heart'),
    createEmojiItem('❣️', 'Heart exclamation'),
    createEmojiItem('💕', 'Two hearts'),
    createEmojiItem('💞', 'Revolving hearts'),
    createEmojiItem('💓', 'Beating heart'),
    createEmojiItem('💗', 'Growing heart'),
    createEmojiItem('💖', 'Sparkling heart'),
    createEmojiItem('💘', 'Heart with arrow'),
    createEmojiItem('💝', 'Heart with ribbon'),
    createEmojiItem('💟', 'Heart decoration'),
    createEmojiItem('☮️', 'Peace symbol'),
    createEmojiItem('✝️', 'Latin cross'),
    createEmojiItem('☪️', 'Star and crescent'),
    createEmojiItem('🕉️', 'Om'),
    createEmojiItem('☸️', 'Wheel of dharma'),
    createEmojiItem('✡️', 'Star of David'),
    createEmojiItem('🔯', 'Dotted six-pointed star'),
    createEmojiItem('🕎', 'Menorah'),
    createEmojiItem('☯️', 'Yin yang'),
    createEmojiItem('☦️', 'Orthodox cross'),
    createEmojiItem('🛐', 'Place of worship'),
    createEmojiItem('⚛️', 'Atom symbol'),
    createEmojiItem('💯', 'Hundred points'),
    createEmojiItem('🔴', 'Red circle'),
    createEmojiItem('🟠', 'Orange circle'),
    createEmojiItem('🟡', 'Yellow circle'),
    createEmojiItem('🟢', 'Green circle'),
    createEmojiItem('🔵', 'Blue circle'),
    createEmojiItem('🟣', 'Purple circle'),
    createEmojiItem('⚫', 'Black circle'),
    createEmojiItem('⚪', 'White circle'),
    createEmojiItem('🟤', 'Brown circle'),
    createEmojiItem('🔺', 'Red triangle pointed up'),
    createEmojiItem('🔻', 'Red triangle pointed down'),
    createEmojiItem('🔸', 'Small orange diamond'),
    createEmojiItem('🔹', 'Small blue diamond'),
    createEmojiItem('🔶', 'Large orange diamond'),
    createEmojiItem('🔷', 'Large blue diamond'),
    createEmojiItem('🔳', 'White square button'),
    createEmojiItem('🔲', 'Black square button'),
    createEmojiItem('▪️', 'Black small square'),
    createEmojiItem('▫️', 'White small square'),
    createEmojiItem('◾', 'Black medium-small square'),
    createEmojiItem('◽', 'White medium-small square'),
    createEmojiItem('◼️', 'Black medium square'),
    createEmojiItem('◻️', 'White medium square'),
    createEmojiItem('⬛', 'Black large square'),
    createEmojiItem('⬜', 'White large square'),
    createEmojiItem('🟥', 'Red square'),
    createEmojiItem('🟧', 'Orange square'),
    createEmojiItem('🟨', 'Yellow square'),
    createEmojiItem('🟩', 'Green square'),
    createEmojiItem('🟦', 'Blue square'),
    createEmojiItem('🟪', 'Purple square'),
    createEmojiItem('🟫', 'Brown square'),
    createEmojiItem('⭐', 'Star'),
    createEmojiItem('🌟', 'Glowing star'),
    createEmojiItem('💫', 'Dizzy'),
    createEmojiItem('🌠', 'Shooting star'),
    createEmojiItem('🌌', 'Milky Way'),
    createEmojiItem('☄️', 'Comet'),
    createEmojiItem('💥', 'Collision'),
    createEmojiItem('💢', 'Anger symbol'),
    createEmojiItem('💦', 'Sweat droplets'),
    createEmojiItem('💨', 'Dashing away'),
    createEmojiItem('💬', 'Speech balloon'),
    createEmojiItem('🗨️', 'Left speech bubble'),
    createEmojiItem('🗯️', 'Right anger bubble'),
    createEmojiItem('💭', 'Thought balloon'),
    createEmojiItem('💤', 'Zzz'),
    // Arrows
    createEmojiItem('⬆️', 'Up arrow'),
    createEmojiItem('↗️', 'Up-right arrow'),
    createEmojiItem('➡️', 'Right arrow'),
    createEmojiItem('↘️', 'Down-right arrow'),
    createEmojiItem('⬇️', 'Down arrow'),
    createEmojiItem('↙️', 'Down-left arrow'),
    createEmojiItem('⬅️', 'Left arrow'),
    createEmojiItem('↖️', 'Up-left arrow'),
    createEmojiItem('↕️', 'Up-down arrow'),
    createEmojiItem('↔️', 'Left-right arrow'),
    createEmojiItem('↩️', 'Right arrow curving left'),
    createEmojiItem('↪️', 'Left arrow curving right'),
    createEmojiItem('⤴️', 'Right arrow curving up'),
    createEmojiItem('⤵️', 'Right arrow curving down'),
    createEmojiItem('🔃', 'Clockwise vertical arrows'),
    createEmojiItem('🔄', 'Counterclockwise arrows button'),
    createEmojiItem('🔙', 'Back arrow'),
    createEmojiItem('🔚', 'End arrow'),
    createEmojiItem('🔛', 'On! arrow'),
    createEmojiItem('🔜', 'Soon arrow'),
    createEmojiItem('🔝', 'Top arrow'),
    createEmojiItem('⚕️', 'Medical symbol'),
    createEmojiItem('♻️', 'Recycling symbol'),
    createEmojiItem('⚜️', 'Fleur-de-lis'),
    createEmojiItem('🔱', 'Trident emblem'),
    createEmojiItem('📛', 'Name badge'),
    createEmojiItem('🔰', 'Japanese symbol for beginner'),
    createEmojiItem('⭕', 'Heavy large circle'),
    createEmojiItem('✅', 'Check mark button'),
    createEmojiItem('☑️', 'Check box with check'),
    createEmojiItem('✔️', 'Check mark'),
    createEmojiItem('❌', 'Cross mark'),
    createEmojiItem('❎', 'Cross mark button'),
    createEmojiItem('➕', 'Plus'),
    createEmojiItem('➖', 'Minus'),
    createEmojiItem('➗', 'Divide'),
    createEmojiItem('➰', 'Curly loop'),
    createEmojiItem('➿', 'Double curly loop'),
    createEmojiItem('〽️', 'Part alternation mark'),
    createEmojiItem('✳️', 'Eight-spoked asterisk'),
    createEmojiItem('✴️', 'Eight-pointed star'),
    createEmojiItem('❇️', 'Sparkle'),
    createEmojiItem('‼️', 'Double exclamation mark'),
    createEmojiItem('⁉️', 'Exclamation question mark'),
    createEmojiItem('❓', 'Question mark'),
    createEmojiItem('❔', 'White question mark'),
    createEmojiItem('❕', 'White exclamation mark'),
    createEmojiItem('❗', 'Exclamation mark'),
    createEmojiItem('〰️', 'Wavy dash'),
    createEmojiItem('©️', 'Copyright'),
    createEmojiItem('®️', 'Registered'),
    createEmojiItem('™️', 'Trade mark'),
    createEmojiItem('#️⃣', 'Keycap: #'),
    createEmojiItem('*️⃣', 'Keycap: *'),
    createEmojiItem('0️⃣', 'Keycap: 0'),
    createEmojiItem('1️⃣', 'Keycap: 1'),
    createEmojiItem('2️⃣', 'Keycap: 2'),
    createEmojiItem('3️⃣', 'Keycap: 3'),
    createEmojiItem('4️⃣', 'Keycap: 4'),
    createEmojiItem('5️⃣', 'Keycap: 5'),
    createEmojiItem('6️⃣', 'Keycap: 6'),
    createEmojiItem('7️⃣', 'Keycap: 7'),
    createEmojiItem('8️⃣', 'Keycap: 8'),
    createEmojiItem('9️⃣', 'Keycap: 9'),
    createEmojiItem('🔟', 'Keycap: 10'),
  ],

  flags: [
    createEmojiItem('🏁', 'Chequered flag'),
    createEmojiItem('🚩', 'Triangular flag'),
    createEmojiItem('🎌', 'Crossed flags'),
    createEmojiItem('🏴', 'Black flag'),
    createEmojiItem('🏳️', 'White flag'),
    createEmojiItem('🏳️‍🌈', 'Rainbow flag'),
    createEmojiItem('🏳️‍⚧️', 'Transgender flag'),
    createEmojiItem('🏴‍☠️', 'Pirate flag'),
    // Country flags
    createEmojiItem('🇺🇸', 'United States'),
    createEmojiItem('🇨🇦', 'Canada'),
    createEmojiItem('🇲🇽', 'Mexico'),
    createEmojiItem('🇧🇷', 'Brazil'),
    createEmojiItem('🇦🇷', 'Argentina'),
    createEmojiItem('🇨🇱', 'Chile'),
    createEmojiItem('🇫🇷', 'France'),
    createEmojiItem('🇩🇪', 'Germany'),
    createEmojiItem('🇮🇹', 'Italy'),
    createEmojiItem('🇪🇸', 'Spain'),
    createEmojiItem('🇵🇹', 'Portugal'),
    createEmojiItem('🇳🇱', 'Netherlands'),
    createEmojiItem('🇧🇪', 'Belgium'),
    createEmojiItem('🇨🇭', 'Switzerland'),
    createEmojiItem('🇦🇹', 'Austria'),
    createEmojiItem('🇸🇪', 'Sweden'),
    createEmojiItem('🇳🇴', 'Norway'),
    createEmojiItem('🇩🇰', 'Denmark'),
    createEmojiItem('🇫🇮', 'Finland'),
    createEmojiItem('🇮🇸', 'Iceland'),
    createEmojiItem('🇮🇪', 'Ireland'),
    createEmojiItem('🇬🇧', 'United Kingdom'),
    createEmojiItem('🇷🇺', 'Russia'),
    createEmojiItem('🇺🇦', 'Ukraine'),
    createEmojiItem('🇵🇱', 'Poland'),
    createEmojiItem('🇯🇵', 'Japan'),
    createEmojiItem('🇰🇷', 'South Korea'),
    createEmojiItem('🇨🇳', 'China'),
    createEmojiItem('🇮🇳', 'India'),
    createEmojiItem('🇦🇺', 'Australia'),
    createEmojiItem('🇳🇿', 'New Zealand'),
    createEmojiItem('🇿🇦', 'South Africa'),
    createEmojiItem('🇪🇬', 'Egypt'),
    createEmojiItem('🇸🇦', 'Saudi Arabia'),
    createEmojiItem('🇦🇪', 'United Arab Emirates'),
    createEmojiItem('🇰🇪', 'Kenya'),
    createEmojiItem('🇳🇬', 'Nigeria'),
    createEmojiItem('🇬🇭', 'Ghana'),
    createEmojiItem('🇹🇭', 'Thailand'),
    createEmojiItem('🇻🇳', 'Vietnam'),
    createEmojiItem('🇸🇬', 'Singapore'),
    createEmojiItem('🇲🇾', 'Malaysia'),
    createEmojiItem('🇮🇩', 'Indonesia'),
    createEmojiItem('🇵🇭', 'Philippines'),
  ],
}
