// packages/lib/src/inventory/tariffs/tariff-232-derivatives.ts

/**
 * Section 232 membership for the codes heading `9903.82.02` covers
 * (plans/money/tasks/61-section-232-derivatives.md §2).
 *
 * `tariff-232-derivatives.json` is generated by
 * `packages/lib/scripts/fetch-hts-lists.ts` from subdivisions (c)(i)-(v) of
 * U.S. note 16 to subchapter III of chapter 99, and checked in. Generated,
 * never edited by hand.
 *
 * ## Why this exists at all, when 29 §10 excluded Section 232
 *
 * The exclusion's premise was that a derivative duty "applies to the steel or
 * aluminium content value, not the full customs value", which a single
 * percentage cannot express. **The note says the opposite.** Note 16(c):
 *
 *   "Headings 9903.82.02-9903.82.26 apply to the FULL CUSTOMS VALUE of articles
 *   classifiable in the provisions of the HTSUS enumerated in the following
 *   lists."
 *
 * So `unitPrice x rate/100` expresses it exactly, and no per-offer metal-content
 * field is needed by anything.
 *
 * ⚠️ The note's second sentence adds a 15%-by-weight test for listed codes
 * OUTSIDE chapters 72, 73, 74 and 76. **As generated on 2026-09-18 that set is
 * empty** - all 279 codes in lists (i)-(v) are already in those chapters - so
 * `weightTested` is present, honest and unused. If a future revision puts a code
 * outside them, it lands there rather than silently becoming a membership, and
 * the surface that warns about it is owed at that point (61 §3.3).
 *
 * 🛑 Only lists (i)-(v) are here. `9903.82.02` reads "as provided for in
 * subdivisions (c)(i)-(v)"; lists (vi)-(xi) belong to the sibling headings
 * 9903.82.04-9903.82.26, which carry note 16(e)'s smelt-and-cast conditions and
 * are not modelled. Note 16(a) makes the headings mutually exclusive, so
 * modelling only `.02` cannot double-count.
 *
 * 🛑 **Never export this module (or the JSON) through `inventory/tariffs/client.ts`.**
 * Same rule and same reason as `tariff-hts-general.ts` and the 301 table.
 */

import type { TariffMemberships } from './tariff-301-memberships'

interface Raw232File {
  fetchedAt: string
  source: string
  memberships: Record<string, string[]>
  weightTested: Record<string, string[]>
}

/** The generated table plus the provenance the file carries. */
export interface Tariff232Derivatives {
  fetchedAt: string
  source: string
  /** Codes the duty applies to unconditionally. */
  memberships: TariffMemberships
  /** Listed codes outside ch. 72/73/74/76, gated on a 15%-by-weight test. */
  weightTested: TariffMemberships
}

let cached: Tariff232Derivatives | undefined

/**
 * Lazily imports the generated JSON on first call and memoises it for the
 * lifetime of the process - the same argument `loadHtsGeneral` makes.
 */
export async function loadTariff232Derivatives(): Promise<Tariff232Derivatives> {
  if (!cached) {
    const mod = await import('./tariff-232-derivatives.json')
    const data = ((mod as { default?: unknown }).default ?? mod) as Raw232File
    cached = {
      fetchedAt: data.fetchedAt,
      source: data.source,
      memberships: data.memberships,
      weightTested: data.weightTested,
    }
  }
  return cached
}
