// packages/lib/src/ai/kopilot/types.ts

/** Open-ended UI context bag. Known fields provide autocomplete; any key is valid. */
export interface SessionContext extends Record<string, unknown> {
  /** Current page the user is viewing (e.g. 'mail', 'contacts', 'workflows') */
  page?: string
  /** Active thread the user has open, if any */
  activeThreadId?: string
  /** Active contact the user has open, if any */
  activeContactId?: string
  /** Active record (generic) the user has open, if any */
  activeRecordId?: string
  /** Active meeting (EntityInstance) the user has open, if any */
  activeMeetingId?: string
  /** Active call recording the user has open, if any */
  activeCallRecordingId?: string
  /** Active transcript-selection (e.g. user has highlighted a span on a transcript) */
  activeTranscriptSelection?: { callRecordingId: string; startMs: number; endMs: number }
  /** Active filter payload the user has applied to the current page */
  activeFilters?: Record<string, unknown>
}

/** Status of a single plan step — drives the icon and color in the auxx:plan-steps fence renderer. */
export type PlanStepStatus = 'pending' | 'running' | 'completed' | 'failed'

/** A single step in the agent's active plan. Server-generated id; not surfaced in the rendered fence. */
export interface PlanStep {
  /** Stable id — generated by `plan_create`, used by `plan_update_step`. */
  id: string
  /** Short imperative title. Capped at 200 chars by `plan_create`. */
  label: string
  /** Current status — transitions pending → running → (completed | failed). */
  status: PlanStepStatus
  /** Optional one-line outcome / blocker / progress note. */
  detail?: string
}

/** The active plan owned by the kopilot session. Persists across iterations and turns until replaced by another `plan_create`. */
export interface PlanState {
  steps: PlanStep[]
  createdAt: number
  updatedAt: number
}

/**
 * Domain state carried through the Kopilot turn.
 *
 * Holds:
 *   - UI context (replaced wholesale on each message via applyContext)
 *   - Static capability descriptions
 *   - The active multi-step plan (persists across iterations and turns;
 *     undefined until `plan_create` is called)
 */
export interface KopilotDomainState {
  /** UI context — replaced wholesale on each message via applyContext */
  context: SessionContext
  /** Human-friendly capability descriptions surfaced when the user asks what Kopilot can do */
  capabilities?: string[]
  /** Active plan, persisted across iterations and turns until replaced */
  plan?: PlanState
}
