// packages/lib/src/ai/kopilot/types.ts

/**
 * Kind discriminator for references the user has in focus during a turn.
 *
 * Surfaces contribute these via `<KopilotContext>` and the editor `@`-mention
 * picker contributes them via `extractMentionRefs`. The kind set is small on
 * purpose — new kinds appear only when a real caller emits one.
 */
export type SessionRefKind =
  | 'thread' // mail thread id
  | 'record' // any RecordId — `contact:<id>`, `<defId>:<id>`, etc. Contacts are records.
  | 'resource' // an entity TYPE the user is viewing — id is the entityDefinitionId. Records-table page.
  | 'kb' // knowledge base id
  | 'article' // article id
  | 'actor' // `user:<id>` or `group:<id>`
  | 'agent' // user-authored agent id — present on the builder page
  | 'workflow' // WorkflowApp id — present on the workflow builder page

/**
 * A single thing the user has in focus this turn — either because a page
 * surface declared it (chip-strip) or because the user `@`-mentioned it in
 * the composer.
 */
export interface SessionRef {
  kind: SessionRefKind
  id: string
  /** Display label rendered in the chip / prompt line. */
  label?: string
  /**
   * Provenance — drives prompt phrasing ("explicitly mentioned" vs "currently
   * open on the page"), chip rendering (mentions don't chip — they're already
   * inline badges in the prose), and engine-side default-injection
   * precedence (mention wins over surface).
   */
  origin: 'surface' | 'mention'
  /**
   * ADVISORY dirty flag contributed by the `workflow` builder chip: the open
   * canvas has unsaved changes, so the DB draft the graph-edit tools would
   * mutate is stale relative to what the user sees. Workflow mutations refuse
   * while it is true. Tolerate absence — the chip is a courtesy; the hash-CAS
   * inside graph-edit is the real concurrency guard.
   */
  isDirty?: boolean
}

/** Open-ended UI context bag. Known fields provide autocomplete; any key is valid. */
export interface SessionContext extends Record<string, unknown> {
  /** Current page the user is viewing (e.g. 'mail', 'contacts', 'workflows') */
  page?: string
  /**
   * Active references the user has in focus this turn — concat of page-surface
   * refs and editor `@`-mentions. Rendered into the agent prompt's `## Active
   * references` block and consumed by `findRef` / `applyContextDefaults`.
   */
  references?: SessionRef[]
}

/** Status of a single plan step — drives the icon and color in the auxx:plan-steps fence renderer. */
export type PlanStepStatus = 'pending' | 'running' | 'completed' | 'failed'

/** A single step in the agent's active plan. Server-generated id; not surfaced in the rendered fence. */
export interface PlanStep {
  /** Stable id — generated by `plan_create`, used by `plan_update_step`. */
  id: string
  /** Short imperative title. Capped at 200 chars by `plan_create`. */
  label: string
  /** Current status — transitions pending → running → (completed | failed). */
  status: PlanStepStatus
  /** Optional one-line outcome / blocker / progress note. */
  detail?: string
}

/** The active plan owned by the kopilot session. Persists across iterations and turns until replaced by another `plan_create`. */
export interface PlanState {
  steps: PlanStep[]
  createdAt: number
  updatedAt: number
}

/**
 * Domain state carried through the Kopilot turn.
 *
 * Holds:
 *   - UI context (replaced wholesale on each message via applyContext)
 *   - Static capability descriptions
 *
 * The active multi-step plan now lives in `var:plan` (chat v9 context store),
 * managed by the plan tools via `ctx.context` — not on domainState.
 *
 * The index signature is load-bearing, not laziness: the engine also stashes
 * bare-keyed slices on this bag (`__proc_step` / `__proc` from
 * `agents/procedures/persist`, `__context` for the context store), and every
 * slice reader is typed against `Record<string, unknown>`. Without it a
 * `KopilotDomainState` is not assignable to `Record<string, unknown>` at all
 * (interfaces get no implicit index signature) and each read needs a cast.
 */
export interface KopilotDomainState {
  /** UI context — replaced wholesale on each message via applyContext */
  context: SessionContext
  /** Human-friendly capability descriptions surfaced when the user asks what Kopilot can do */
  capabilities?: string[]
  /** Engine-managed slices keyed by bare string constants (see above). */
  [slice: string]: unknown
}
