// packages/lib/src/import/index.ts

// Shared write-policy vocabulary. Re-exported here so the importer's consumers
// (router, wizard) have ONE place to reach the identity/merge unions instead of
// depending on a second @auxx/lib subpath.
export {
  type FieldMergeStrategy,
  type IdentityRole,
  IMPORT_MERGE_STRATEGIES,
  type ImportMergeStrategy,
  isImportMergeStrategy,
  type OnAmbiguous,
} from '../write-policy'
// Events (SSE)
export {
  type AnyImportEvent,
  createEventPublisher,
  type ErrorEvent,
  type EventCallback,
  type ExecutionCompleteEvent,
  type ExecutionProgressEvent,
  type ImportEvent,
  ImportEventPublisher,
  ImportEventSubscriber,
  type ImportEventType,
  type JobStatusEvent,
  type PlanningCompleteEvent,
  type PlanningProgressEvent,
  type PlanningRowEvent,
  type ResolutionProgressEvent,
  type UploadProgressEvent,
} from './events'
// Execution
export {
  type BatchRecord,
  type BatchRecordData,
  buildMultipleRecordData,
  buildRecordData,
  claimImportManifestConsumed,
  type ExecuteBatchContext,
  type ExecutePlanOptions,
  type ExecuteStrategyContext,
  executeBatch,
  executePlan,
  executeStrategy,
  getImportManifest,
  getSourceValue,
  isBlankValue,
  keysWithStrategy,
  loadNonBlankFieldKeys,
  type MergeStrategyByKey,
  markJobCompleted,
  markJobExecuting,
  markJobFailed,
  parseMergeStrategies,
  type SourceRow,
  type StrategyExecutionResult,
  saveImportManifest,
  stripBlankValues,
  type UpdatePolicy,
  updateJobProgress,
} from './execution'
// Field utilities
export {
  type AutoMapOptions,
  autoMapColumns,
  type ColumnAutoMapping,
  type ColumnHeader,
  type ColumnHeaderWithSamples,
  type FieldGroup,
  type GetImportableFieldsOptions,
  getIdentifiableFields,
  getIdentifierEligibility,
  getIdentifierOptions,
  getImportableFields,
  getRequiredFields,
  getResolutionTypeLabel,
  getValidResolutionTypes,
  type IdentifierEligibility,
  type IdentifierOption,
  type IdentifierTier,
  type ImportableField,
  orchestrateAutoMap,
  RESOLUTION_TYPE_LABELS,
  type ResolutionTypeLabel,
  sortByIdentifierPreference,
  suggestResolutionType,
  TIER_2_IDENTIFIER_NOTE,
} from './fields'
// Hashing utilities
export { countOccurrences, hashValue } from './hashing'
// Job management
export {
  allowPlanGeneration,
  type CreateJobInput,
  type CreateJobResult,
  createImportJob,
  type DeleteJobInput,
  deleteJob,
  finalizeUpload,
  getJobByOrg,
  getJobWithMapping,
  getJobWithMappingProperties,
  incrementReceivedChunks,
  type ListJobsInput,
  listJobsByOrg,
  markJobPlanning,
  markJobReady,
  updateJobStatus,
} from './job'
// Mapping utilities
export {
  type AutoMapStrategy,
  type AutoMapUpdateInput,
  assertNoDuplicateTargetMapping,
  batchUpdateMappingsFromAutoMap,
  deriveIdentifierFieldKeys,
  type GetMappedColumnsInput,
  getColumnSamples,
  getMappablePropertiesWithSamples,
  getMappedColumnsWithStats,
  IMPORT_STRATEGY_MODES,
  isImportStrategyMode,
  isMatchRole,
  type MappablePropertyWithSamples,
  type MappedColumnRef,
  type MappedColumnWithStats,
  type MappingIdentityState,
  parseResolutionConfig,
  // `RelationConfig` is re-exported from `./resolution` below, one declaration,
  // derived from the persisted `ResolutionConfig['relationConfig']` shape.
  type RunAutoMapInput,
  type RunAutoMapResult,
  runAutoMap,
  type SaveMappingInput,
  sanitizeIdentityRole,
  saveMappingProperty,
  serializeResolutionConfig,
  syncMappingIdentity,
  toImportStrategyMode,
  type UpdateImportStrategyInput,
  type UpdateMappingTitleInput,
  updateImportStrategy,
  updateMappingTitle,
} from './mapping'
// Planning
export {
  type AnalyzedRow,
  type AnalyzeRowContext,
  type AssignRowInput,
  analyzeRow,
  assignRowToStrategy,
  batchAssignRows,
  type CreateStrategyInput,
  calculateEstimates,
  calculateEstimatesFromCounts,
  createDefaultStrategies,
  createFindExistingRecord,
  createPlan,
  createStrategy,
  type FindExistingRecord,
  type FindExistingRecordOptions,
  type FindExistingRecordResult,
  type GeneratePlanOptions,
  type GeneratePlanResult,
  type GetPlanPreviewOptions,
  generatePlan,
  getPlanErrors,
  getPlanPreviewRows,
  getPlanWarnings,
  getPlanWithEstimates,
  type IdentifierValues,
  markPlanCompleted,
  type PlanError,
  type PlanPreviewResult,
  type PlanPreviewRow,
  type PlanWarning,
  type PlanWarningsResult,
  type PlanWithEstimates,
} from './planning'
// Raw data operations
export {
  getBatchRowData,
  getColumnUniqueValues,
  getColumnValues,
  getRawData,
  getRawDataAsArray,
  getRawDataAsMap,
  getRowData,
  type RawDataCell,
  storeRawData,
  storeRawDataChunk,
} from './raw-data'
// Resolution
export {
  batchCacheResolutions,
  buildRelationColumnPolicy,
  type CacheResolutionInput,
  type CurrencyParseFailure,
  type CurrencyParseOptions,
  type CurrencyParseResult,
  type CurrencyParseSuccess,
  cacheResolution,
  canCreateOnNoMatch,
  createRelationTargetWriter,
  defaultOnNoMatch,
  defaultRelationLinkMode,
  deriveRelationResolutionType,
  type EffectiveStatus,
  effectiveOnNoMatch,
  explainCreateUnavailable,
  getAllJobResolutions,
  getAvailableResolutionTypes,
  getCachedResolutions,
  getPendingRelationLookups,
  getRelationCreateCounts,
  getResolutionProgress,
  getResolver,
  getSelectCreateCounts,
  getUniqueValuesWithResolution,
  isPendingRelationLookup,
  isRelationMatchableType,
  isValidResolutionType,
  type MaterializeRelationCreatesOptions,
  type MaterializeRelationCreatesResult,
  type MaterializeSelectCreatesOptions,
  type MaterializeSelectCreatesResult,
  matchesDisplayField,
  materializeRelationCreates,
  materializeSelectCreates,
  type PendingCreateRow,
  type PendingRelationLookup,
  type PendingSelectCreateRow,
  type ProcessColumnValuesOptions,
  parseCurrencyMajorToMinor,
  processColumnValues,
  RELATION_MATCH_ARRAY_TYPES,
  RELATION_MATCH_ENUM_TYPES,
  RELATION_MATCH_NUMERIC_TYPES,
  RELATION_MATCH_TEXT_TYPES,
  RELATION_MATCHABLE_BASE_TYPES,
  type RelationColumnPolicy,
  type RelationConfig,
  type RelationCreateColumnCount,
  type RelationCreateCounts,
  type RelationLookupResult,
  type RelationTargetWriter,
  type RelationTargetWriterOptions,
  type ResolutionProgress,
  type ResolutionStatus,
  type ResolveColumnCurrencyCodesInput,
  type ResolveColumnOptionsInput,
  relationCreateKey,
  relationFieldWriteMode,
  resolveArraySplit,
  resolveBoolean,
  resolveColumnCurrencyCodes,
  resolveColumnOptions,
  resolveCurrencyMajor,
  resolveDateCustom,
  resolveDateIso,
  resolveDatetimeCustom,
  resolveDatetimeIso,
  resolveDecimal,
  resolveDisplayFieldKey,
  resolveDomain,
  resolveEmail,
  resolveEmailSplit,
  resolveInteger,
  resolveMatchFieldKey,
  resolveMultiselectSplit,
  resolvePhone,
  resolvePhoneSplit,
  resolveRelationCreate,
  // Relation lookups
  resolveRelationLookups,
  resolveRelationMatch,
  resolveSelectCreate,
  resolveSelectValue,
  resolveTextCuid,
  // Resolvers
  resolveTextValue,
  resolveUrlSplit,
  resolveValue,
  type SelectCreateColumnCount,
  type SelectCreateCounts,
  type SelectCreateFailure,
  type SelectCreateFieldCount,
  splitMultiValueCell,
  type UniqueValuesWithFieldConfig,
  // Types
  type UniqueValueWithResolution,
  type UpdateResolutionInput,
  updateResolutionsWithLookupResults,
  updateValueResolution,
} from './resolution'
// Types
export * from './types'

// Utilities
export {
  chunkArray,
  createPercentageProgress,
  createThrottledProgress,
  type ProgressCallback,
  type RetryOptions,
  retryWithBackoff,
} from './utils'
