// packages/lib/src/import/index.ts

// Events (SSE)
export {
  type AnyImportEvent,
  createEventPublisher,
  type ErrorEvent,
  type EventCallback,
  type ExecutionCompleteEvent,
  type ExecutionProgressEvent,
  type ImportEvent,
  ImportEventPublisher,
  ImportEventSubscriber,
  type ImportEventType,
  type JobStatusEvent,
  type PlanningCompleteEvent,
  type PlanningProgressEvent,
  type PlanningRowEvent,
  type ResolutionProgressEvent,
  type UploadProgressEvent,
} from './events'
// Execution
export {
  type BatchRecord,
  type BatchRecordData,
  buildMultipleRecordData,
  buildRecordData,
  claimImportManifestConsumed,
  type ExecuteBatchContext,
  type ExecutePlanOptions,
  type ExecuteStrategyContext,
  executeBatch,
  executePlan,
  executeStrategy,
  getImportManifest,
  getSourceValue,
  markJobCompleted,
  markJobExecuting,
  markJobFailed,
  type SourceRow,
  type StrategyExecutionResult,
  saveImportManifest,
  updateJobProgress,
} from './execution'
// Field utilities
export {
  type AutoMapOptions,
  autoMapColumns,
  type ColumnAutoMapping,
  type ColumnHeader,
  type ColumnHeaderWithSamples,
  type FieldGroup,
  type GetImportableFieldsOptions,
  getIdentifiableFields,
  getIdentifierOptions,
  getImportableFields,
  getRequiredFields,
  getValidResolutionTypes,
  type IdentifierOption,
  type ImportableField,
  orchestrateAutoMap,
  suggestResolutionType,
} from './fields'
// Hashing utilities
export { countOccurrences, hashValue } from './hashing'
// Job management
export {
  allowPlanGeneration,
  type CreateJobInput,
  type CreateJobResult,
  createImportJob,
  type DeleteJobInput,
  deleteJob,
  finalizeUpload,
  getJobByOrg,
  getJobWithMapping,
  getJobWithMappingProperties,
  incrementReceivedChunks,
  type ListJobsInput,
  listJobsByOrg,
  markJobPlanning,
  markJobReady,
  updateJobStatus,
} from './job'
// Mapping utilities
export {
  type AutoMapStrategy,
  type AutoMapUpdateInput,
  batchUpdateMappingsFromAutoMap,
  type GetMappedColumnsInput,
  getColumnSamples,
  getMappablePropertiesWithSamples,
  getMappedColumnsWithStats,
  type MappablePropertyWithSamples,
  type MappedColumnWithStats,
  type RelationConfig,
  type RunAutoMapInput,
  type RunAutoMapResult,
  runAutoMap,
  type SaveMappingInput,
  saveMappingProperty,
  type UpdateMappingTitleInput,
  updateMappingTitle,
} from './mapping'
// Planning
export {
  type AnalyzedRow,
  type AnalyzeRowContext,
  type AssignRowInput,
  analyzeRow,
  assignRowToStrategy,
  batchAssignRows,
  type CreateStrategyInput,
  calculateEstimates,
  calculateEstimatesFromCounts,
  createDefaultStrategies,
  createFindExistingRecord,
  createPlan,
  createStrategy,
  type FindExistingRecordOptions,
  type GeneratePlanOptions,
  type GeneratePlanResult,
  type GetPlanPreviewOptions,
  generatePlan,
  getPlanErrors,
  getPlanPreviewRows,
  getPlanWarnings,
  getPlanWithEstimates,
  markPlanCompleted,
  type PlanError,
  type PlanPreviewResult,
  type PlanPreviewRow,
  type PlanWarning,
  type PlanWarningsResult,
  type PlanWithEstimates,
} from './planning'
// Raw data operations
export {
  getBatchRowData,
  getColumnUniqueValues,
  getColumnValues,
  getRawData,
  getRawDataAsArray,
  getRawDataAsMap,
  getRowData,
  type RawDataCell,
  storeRawData,
  storeRawDataChunk,
} from './raw-data'
// Resolution
export {
  batchCacheResolutions,
  type CacheResolutionInput,
  cacheResolution,
  type EffectiveStatus,
  getAllJobResolutions,
  getAvailableResolutionTypes,
  getCachedResolutions,
  getPendingRelationLookups,
  getResolutionProgress,
  getResolver,
  getUniqueValuesWithResolution,
  isPendingRelationLookup,
  isValidResolutionType,
  type PendingRelationLookup,
  type ProcessColumnValuesOptions,
  processColumnValues,
  type RelationLookupResult,
  type ResolutionProgress,
  type ResolutionStatus,
  resolveArraySplit,
  resolveBoolean,
  resolveDateCustom,
  resolveDateIso,
  resolveDatetimeCustom,
  resolveDatetimeIso,
  resolveDecimal,
  resolveDomain,
  resolveEmail,
  resolveEmailSplit,
  resolveInteger,
  resolveMultiselectSplit,
  resolvePhone,
  resolvePhoneSplit,
  resolveRelationCreate,
  // Relation lookups
  resolveRelationLookups,
  resolveRelationMatch,
  resolveSelectCreate,
  resolveSelectValue,
  resolveTextCuid,
  // Resolvers
  resolveTextValue,
  resolveUrlSplit,
  resolveValue,
  splitMultiValueCell,
  type UniqueValuesWithFieldConfig,
  // Types
  type UniqueValueWithResolution,
  type UpdateResolutionInput,
  updateResolutionsWithLookupResults,
  updateValueResolution,
} from './resolution'
// Types
export * from './types'

// Utilities
export {
  chunkArray,
  createPercentageProgress,
  createThrottledProgress,
  type ProgressCallback,
  type RetryOptions,
  retryWithBackoff,
} from './utils'
