// packages/lib/src/ai/providers/deepseek/deepseek-defaults.ts

import { FetchFrom, type ModelCapabilities, ModelType, type ProviderCapabilities } from '../types'

export const DEEPSEEK_CAPABILITIES: ProviderCapabilities = {
  id: 'deepseek',
  displayName: 'DeepSeek',
  icon: 'deepseek',
  color: '#4F46E5',
  supportedModelTypes: [ModelType.LLM],
  defaultModel: 'deepseek-chat',
  requiresApiKey: true,
  toolFormat: 'openai',
  configurateMethods: ['predefined-model', 'customizable-model'],

  credentialSchema: [
    {
      variable: 'deepseek_api_key',
      type: 'secret-input',
      label: 'API Key',
      placeholder: 'Enter your DeepSeek API Key',
      required: true,
      scope: 'both',
      priority: 'model-override',
      helpText: 'Your DeepSeek API key from the DeepSeek platform',
      validation: {
        pattern: '^sk-[a-zA-Z0-9\\-_]{10,}$',
        message: 'DeepSeek API key must start with sk- followed by at least 10 characters',
      },
    },
  ],

  rateLimits: {
    requestsPerMinute: 60,
    tokensPerMinute: 10000,
    cacheTtl: 300,
  },
  description: 'Advanced reasoning AI models by DeepSeek',
  documentationUrl: 'https://platform.deepseek.com/docs',
  setupInstructions:
    'Get your API key from the DeepSeek platform at https://platform.deepseek.com/',
}

export const DEEPSEEK_MODELS: Record<string, ModelCapabilities> = {
  'deepseek-chat': {
    provider: 'deepseek',
    modelId: 'deepseek-chat',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'DeepSeek Chat (V3.2)',
    icon: 'deepseek',
    color: '#4F46E5',
    contextLength: 128000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.00028, output: 0.00042 },
    description: 'DeepSeek V3.2 conversational AI model with tool calling and JSON mode support',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness in responses.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'topP',
        type: 'float',
        label: 'Top P',
        help: 'Nucleus sampling threshold.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'frequencyPenalty',
        type: 'float',
        label: 'Frequency Penalty',
        help: 'Penalizes repeated tokens based on frequency.',
        default: 0,
        min: -2,
        max: 2,
        precision: 2,
        required: false,
        template: 'frequency_penalty',
      },
      {
        name: 'presencePenalty',
        type: 'float',
        label: 'Presence Penalty',
        help: 'Penalizes tokens that have already appeared.',
        default: 0,
        min: -2,
        max: 2,
        precision: 2,
        required: false,
        template: 'presence_penalty',
      },
      {
        name: 'maxOutputTokens',
        type: 'int',
        label: 'Max Output Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'deepseek-reasoner': {
    provider: 'deepseek',
    modelId: 'deepseek-reasoner',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'DeepSeek Reasoner (V3.2)',
    icon: 'deepseek',
    color: '#4F46E5',
    contextLength: 128000,
    maxTokens: 64000,
    modelType: ModelType.LLM,
    features: ['chat', 'reasoning', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.00028, output: 0.00042 },
    description:
      'DeepSeek V3.2 reasoning model with chain-of-thought capabilities. Sampling parameters (temperature, top_p) are ignored.',
    parameterRestrictions: {
      isReasoningModel: true,
      supportedParams: ['max_tokens'],
      unsupportedParams: ['temperature', 'top_p', 'presence_penalty', 'frequency_penalty'],
    },
    parameterRules: [
      {
        name: 'maxOutputTokens',
        type: 'int',
        label: 'Max Output Tokens',
        help: 'Total output length including chain-of-thought reasoning.',
        default: 32000,
        min: 1,
        max: 64000,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
}
