/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ANTHROPIC_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "API_KEY_SALT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GITHUB_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GITHUB_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GOOGLE_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GOOGLE_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuxxAiDocs": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "AuxxAiHomepage": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "AuxxAiRds": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "AuxxAiRedis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "AuxxAiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "AuxxAiVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "AuxxAiWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "AuxxAiWorker": {
      "service": string
      "type": "sst.aws.Service"
    }
    "BEDROCK_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BEDROCK_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BULL_ADMIN_PASS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BULL_ADMIN_USER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DROPBOX_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DROPBOX_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseDeployFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "FACEBOOK_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACEBOOK_APP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACEBOOK_WEBHOOK_VERIFY_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_EMAIL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_PROJECT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_PUBSUB_VERIFICATION_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GRAVATAR_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GROQ_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MAILGUN_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_POSTHOG_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_PUSHER_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OUTLOOK_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OUTLOOK_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OUTLOOK_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUSHER_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUSHER_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUSHER_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrivateAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "PublicAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SHOPIFY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SHOPIFY_API_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPER_ADMIN_EMAIL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ServerFunctionExecutor": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}