/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ANTHROPIC_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "API_KEY_SALT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GITHUB_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GITHUB_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GOOGLE_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GOOGLE_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuxxAiVpcV2": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "AuxxAiWorker": {
      "service": string
      "type": "sst.aws.Service"
    }
    "BEDROCK_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BEDROCK_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BUILD_SESSION_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CREDENTIAL_ENCRYPTION_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DROPBOX_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DROPBOX_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EMAIL_PROVIDER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACEBOOK_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACEBOOK_APP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACEBOOK_WEBHOOK_VERIFY_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_EMAIL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_PROJECT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_PUBSUB_VERIFICATION_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GRAVATAR_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GROQ_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InboundEmailBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "KB_SESSION_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LAMBDA_INVOKE_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LOGIN_TOKEN_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LOGIN_TOKEN_PUBLIC_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MAILGUN_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OUTLOOK_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OUTLOOK_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OUTLOOK_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POSTHOG_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUBLIC_WORKFLOW_JWT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUSHER_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUSHER_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUSHER_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrivateAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "PublicAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "RECALL_AI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RECALL_AI_REGION": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RECALL_AI_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SDK_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SHOPIFY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SHOPIFY_API_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_PASS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_PORT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_SECURE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_USER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPER_ADMIN_EMAIL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ServerFunctionExecutor": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "SesInboundReceiver": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TURNSTILE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}