// packages/database/src/db/relations/commerce.ts
// Grouped relations for commerce domain (generated by scripts/split-relations.ts)

import { relations } from 'drizzle-orm/relations'
import {
  Address,
  Contact,
  CustomerGroup,
  CustomerGroupMember,
  CustomerSource,
  EntityInstance,
  FulfillmentTracking,
  Invoice,
  Message,
  MessageParticipant,
  Order,
  OrderFulfillment,
  OrderLineItem,
  OrderRefund,
  OrderReturn,
  Organization,
  Participant,
  Plan,
  PlanSubscription,
  PlanSubscriptionHistory,
  Product,
  ProductMedia,
  ProductOption,
  ProductVariant,
  ShopifyAuthState,
  ShopifyIntegration,
  Subscription,
  shopify_customers,
  Ticket,
  User,
  VendorPart,
  WebhookEvent,
} from '../schema'

export const shopifyIntegrationRelations = relations(ShopifyIntegration, ({ one, many }) => ({
  createdBy: one(User, {
    fields: [ShopifyIntegration.createdById],
    references: [User.id],
  }),
  organization: one(Organization, {
    fields: [ShopifyIntegration.organizationId],
    references: [Organization.id],
  }),
  orders: many(Order),
  products: many(Product),
  productVariants: many(ProductVariant),
  customers: many(shopify_customers),
  addresses: many(Address),
  subscriptions: many(Subscription),
  webhookEvents: many(WebhookEvent),
}))

export const shopifyAuthStateRelations = relations(ShopifyAuthState, ({ one }) => ({
  organization: one(Organization, {
    fields: [ShopifyAuthState.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [ShopifyAuthState.userId],
    references: [User.id],
  }),
}))

export const contactRelations = relations(Contact, ({ one, many }) => ({
  organization: one(Organization, {
    fields: [Contact.organizationId],
    references: [Organization.id],
  }),
  customerSources: many(CustomerSource),
  customerGroups: many(CustomerGroupMember),
  shopifyCustomers: many(shopify_customers),
  tickets: many(Ticket),
  vendorParts: many(VendorPart),
}))

export const customerSourceRelations = relations(CustomerSource, ({ one }) => ({
  contact: one(Contact, {
    fields: [CustomerSource.contactId],
    references: [Contact.id],
  }),
  organization: one(Organization, {
    fields: [CustomerSource.organizationId],
    references: [Organization.id],
  }),
}))

export const customerGroupRelations = relations(CustomerGroup, ({ one, many }) => ({
  organization: one(Organization, {
    fields: [CustomerGroup.organizationId],
    references: [Organization.id],
  }),
  members: many(CustomerGroupMember),
}))

export const customerGroupMemberRelations = relations(CustomerGroupMember, ({ one }) => ({
  contact: one(Contact, {
    fields: [CustomerGroupMember.contactId],
    references: [Contact.id],
  }),
  customerGroup: one(CustomerGroup, {
    fields: [CustomerGroupMember.customerGroupId],
    references: [CustomerGroup.id],
  }),
}))

export const participantRelations = relations(Participant, ({ one, many }) => ({
  entityInstance: one(EntityInstance, {
    fields: [Participant.entityInstanceId],
    references: [EntityInstance.id],
  }),
  organization: one(Organization, {
    fields: [Participant.organizationId],
    references: [Organization.id],
  }),
  sentMessages: many(Message, {
    relationName: 'message_fromId_participant_id',
  }),
  replyToMessages: many(Message, {
    relationName: 'message_replyToId_participant_id',
  }),
  messageRoles: many(MessageParticipant),
}))

export const orderRelations = relations(Order, ({ one, many }) => ({
  billingAddress: one(Address, {
    fields: [Order.billingAddressId],
    references: [Address.id],
    relationName: 'order_billingAddressId_address_id',
  }),
  customer: one(shopify_customers, {
    fields: [Order.customerId],
    references: [shopify_customers.id],
    relationName: 'order_customerId_shopifyCustomers_id',
  }),
  integration: one(ShopifyIntegration, {
    fields: [Order.integrationId],
    references: [ShopifyIntegration.id],
  }),
  organization: one(Organization, {
    fields: [Order.organizationId],
    references: [Organization.id],
  }),
  shippingAddress: one(Address, {
    fields: [Order.shippingAddressId],
    references: [Address.id],
    relationName: 'order_shippingAddressId_address_id',
  }),
  customerLastOrder: many(shopify_customers, {
    relationName: 'shopifyCustomers_lastOrderId_order_id',
  }),
  refunds: many(OrderRefund),
  returns: many(OrderReturn),
  lineItems: many(OrderLineItem),
  fulfillments: many(OrderFulfillment),
  trackings: many(FulfillmentTracking),
  tickets: many(Ticket),
}))

export const addressRelations = relations(Address, ({ one, many }) => ({
  billingAddresses: many(Order, {
    relationName: 'order_billingAddressId_address_id',
  }),
  shippingAddresses: many(Order, {
    relationName: 'order_shippingAddressId_address_id',
  }),
  defaultAdress: many(shopify_customers, {
    relationName: 'shopifyCustomers_defaultAddressId_address_id',
  }),
  shopifyCustomer: one(shopify_customers, {
    fields: [Address.customerId],
    references: [shopify_customers.id],
    relationName: 'address_customerId_shopifyCustomers_id',
  }),
  integration: one(ShopifyIntegration, {
    fields: [Address.integrationId],
    references: [ShopifyIntegration.id],
  }),
  organization: one(Organization, {
    fields: [Address.organizationId],
    references: [Organization.id],
  }),
}))

export const shopifyCustomersRelations = relations(shopify_customers, ({ one, many }) => ({
  orders: many(Order, {
    relationName: 'order_customerId_shopifyCustomers_id',
  }),
  contact: one(Contact, {
    fields: [shopify_customers.contactId],
    references: [Contact.id],
  }),
  defaultAddress: one(Address, {
    fields: [shopify_customers.defaultAddressId],
    references: [Address.id],
    relationName: 'shopifyCustomers_defaultAddressId_address_id',
  }),
  integration: one(ShopifyIntegration, {
    fields: [shopify_customers.integrationId],
    references: [ShopifyIntegration.id],
  }),
  lastOrder: one(Order, {
    fields: [shopify_customers.lastOrderId],
    references: [Order.id],
    relationName: 'shopifyCustomers_lastOrderId_order_id',
  }),
  organization: one(Organization, {
    fields: [shopify_customers.organizationId],
    references: [Organization.id],
  }),
  addresses: many(Address, {
    relationName: 'address_customerId_shopifyCustomers_id',
  }),
  tickets: many(Ticket),
}))

export const productRelations = relations(Product, ({ one, many }) => ({
  integration: one(ShopifyIntegration, {
    fields: [Product.integrationId],
    references: [ShopifyIntegration.id],
  }),
  organization: one(Organization, {
    fields: [Product.organizationId],
    references: [Organization.id],
  }),
  variants: many(ProductVariant),
  media: many(ProductMedia),
  options: many(ProductOption),
}))

export const productVariantRelations = relations(ProductVariant, ({ one }) => ({
  integration: one(ShopifyIntegration, {
    fields: [ProductVariant.integrationId],
    references: [ShopifyIntegration.id],
  }),
  organization: one(Organization, {
    fields: [ProductVariant.organizationId],
    references: [Organization.id],
  }),
  product: one(Product, {
    fields: [ProductVariant.productId],
    references: [Product.id],
  }),
}))

export const productMediaRelations = relations(ProductMedia, ({ one }) => ({
  product: one(Product, {
    fields: [ProductMedia.productId],
    references: [Product.id],
  }),
}))

export const productOptionRelations = relations(ProductOption, ({ one }) => ({
  product: one(Product, {
    fields: [ProductOption.productId],
    references: [Product.id],
  }),
}))

export const orderRefundRelations = relations(OrderRefund, ({ one }) => ({
  order: one(Order, {
    fields: [OrderRefund.orderId],
    references: [Order.id],
  }),
}))

export const orderReturnRelations = relations(OrderReturn, ({ one }) => ({
  order: one(Order, {
    fields: [OrderReturn.orderId],
    references: [Order.id],
  }),
}))

export const orderLineItemRelations = relations(OrderLineItem, ({ one }) => ({
  order: one(Order, {
    fields: [OrderLineItem.orderId],
    references: [Order.id],
  }),
}))

export const orderFulfillmentRelations = relations(OrderFulfillment, ({ one, many }) => ({
  order: one(Order, {
    fields: [OrderFulfillment.orderId],
    references: [Order.id],
  }),
  trackings: many(FulfillmentTracking),
}))

export const fulfillmentTrackingRelations = relations(FulfillmentTracking, ({ one }) => ({
  fulfillment: one(OrderFulfillment, {
    fields: [FulfillmentTracking.fulfillmentId],
    references: [OrderFulfillment.id],
  }),
  order: one(Order, {
    fields: [FulfillmentTracking.orderId],
    references: [Order.id],
  }),
}))

export const subscriptionRelations = relations(Subscription, ({ one, many }) => ({
  integration: one(ShopifyIntegration, {
    fields: [Subscription.integrationId],
    references: [ShopifyIntegration.id],
  }),
  organization: one(Organization, {
    fields: [Subscription.organizationId],
    references: [Organization.id],
  }),
  events: many(WebhookEvent),
}))

export const planSubscriptionRelations = relations(PlanSubscription, ({ one, many }) => ({
  organization: one(Organization, {
    fields: [PlanSubscription.organizationId],
    references: [Organization.id],
  }),
  plan: one(Plan, {
    fields: [PlanSubscription.planId],
    references: [Plan.id],
  }),
  scheduledPlan: one(Plan, {
    fields: [PlanSubscription.scheduledPlanId],
    references: [Plan.id],
  }),
  invoices: many(Invoice),
  history: many(PlanSubscriptionHistory),
}))

export const planRelations = relations(Plan, ({ many }) => ({
  subscriptions: many(PlanSubscription),
}))

export const planSubscriptionHistoryRelations = relations(PlanSubscriptionHistory, ({ one }) => ({
  organization: one(Organization, {
    fields: [PlanSubscriptionHistory.organizationId],
    references: [Organization.id],
  }),
  subscription: one(PlanSubscription, {
    fields: [PlanSubscriptionHistory.subscriptionId],
    references: [PlanSubscription.id],
  }),
  user: one(User, {
    fields: [PlanSubscriptionHistory.userId],
    references: [User.id],
  }),
}))

export const invoiceRelations = relations(Invoice, ({ one }) => ({
  organization: one(Organization, {
    fields: [Invoice.organizationId],
    references: [Organization.id],
  }),
  subscription: one(PlanSubscription, {
    fields: [Invoice.subscriptionId],
    references: [PlanSubscription.id],
  }),
}))
