// packages/database/src/db/relations/core.ts
// Grouped relations for core domain (generated by scripts/split-relations.ts)

import { relations } from 'drizzle-orm/relations'
import {
  AiAgentSession,
  AiIntegration,
  AiMessageFeedback,
  AiUsage,
  ApiKey,
  ApprovalRequest,
  ApprovalResponse,
  Article,
  ArticleRevision,
  Attachment,
  account,
  ChatWidget,
  Comment,
  CommentReaction,
  Credential,
  CustomField,
  Dataset,
  DatasetSearchQuery,
  Document,
  DocumentSegment,
  EmailEmbedding,
  EmailTemplate,
  EndUser,
  EntityDefinition,
  EntityGroupMember,
  EntityInstance,
  Event,
  ExternalKnowledgeSource,
  FieldValue,
  File,
  Folder,
  FolderFile,
  InboxIntegration,
  Integration,
  IntegrationTagLabel,
  Invoice,
  KnowledgeBase,
  Label,
  LoadBalancingConfig,
  MailDomain,
  MailView,
  MediaAsset,
  Message,
  ModelConfiguration,
  Notification,
  OperatingHours,
  Organization,
  OrganizationInvitation,
  OrganizationMember,
  OrganizationSetting,
  Participant,
  Passkey,
  PasswordResetToken,
  PlanSubscription,
  PlanSubscriptionHistory,
  PromptHistory,
  PromptTemplate,
  ProviderConfiguration,
  ProviderPreference,
  RecordSequence,
  SearchHistory,
  SignatureIntegrationShare,
  Snippet,
  SnippetFolder,
  SyncJob,
  SystemModelDefault,
  session,
  TableView,
  Tag,
  // TagsOnThread, // DEPRECATED: Tags now use FieldValue via RELATIONSHIP field
  Thread,
  ThreadReadStatus,
  TwoFactor,
  UploadSession,
  User,
  UserSetting,
  VerificationToken,
  Webhook,
  Workflow,
  WorkflowApp,
  WorkflowNodeExecution,
  WorkflowRun,
} from '../schema'

export const userRelations = relations(User, ({ one, many }) => ({
  assetsCreated: many(MediaAsset, {
    relationName: 'mediaAsset_createdById_user_id',
  }),
  createdOrganizations: many(Organization, {
    relationName: 'organization_createdById_user_id',
  }),
  systemOrganization: many(Organization, {
    relationName: 'organization_systemUserId_user_id',
  }),
  memberships: many(OrganizationMember),
  acceptedInvitations: many(OrganizationInvitation, {
    relationName: 'organizationInvitation_acceptedById_user_id',
  }),
  sentInvitations: many(OrganizationInvitation, {
    relationName: 'organizationInvitation_invitedById_user_id',
  }),
  userSettings: many(UserSetting),
  verificationTokens: many(VerificationToken),
  passwordResetTokens: many(PasswordResetToken),
  readStatuses: many(ThreadReadStatus),
  messages: many(Message),
  threads: many(Thread),
  articles: many(Article, {
    relationName: 'article_authorId_user_id',
  }),
  publishedArticles: many(Article, {
    relationName: 'article_publishedById_user_id',
  }),
  aiAgentSessions: many(AiAgentSession),
  aiUsages: many(AiUsage),
  aiIntegrations: many(AiIntegration),
  promptHistory: many(PromptHistory),
  ApiKey: many(ApiKey),
  articleRevisions: many(ArticleRevision),
  avatarAsset: one(MediaAsset, {
    fields: [User.avatarAssetId],
    references: [MediaAsset.id],
    relationName: 'user_avatarAssetId_mediaAsset_id',
  }),
  snippetFolders: many(SnippetFolder),
  snippets: many(Snippet),
  promptTemplates: many(PromptTemplate),
  comments: many(Comment, {
    relationName: 'comment_createdById_user_id',
  }),
  pinned: many(Comment, {
    relationName: 'comment_pinnedById_user_id',
  }),
  reactions: many(CommentReaction),
  mailViews: many(MailView),
  triggeredNotifications: many(Notification, {
    relationName: 'notification_actorId_user_id',
  }),
  notifications: many(Notification, {
    relationName: 'notification_userId_user_id',
  }),
  passKeys: many(Passkey),
  accounts: many(account),
  sessions: many(session),
  twoFactor: many(TwoFactor),
  tableViews: many(TableView),
  searchHistory: many(SearchHistory),
  createdWorkflows: many(Workflow),
  createdWorkflowApps: many(WorkflowApp),
  workflowRuns: many(WorkflowRun),
  nodeExecutions: many(WorkflowNodeExecution),
  createdApprovals: many(ApprovalRequest),
  approvalResponses: many(ApprovalResponse),
  files: many(File, {
    relationName: 'file_createdById_user_id',
  }),
  deletedFiles: many(File, {
    relationName: 'file_deletedById_user_id',
  }),
  createdCredential: many(Credential),
  createdDatasets: many(Dataset),
  datasetSearchQueries: many(DatasetSearchQuery),
  createdExternalSources: many(ExternalKnowledgeSource),
  uploadedDocuments: many(Document),
  foldersCreated: many(Folder),
  attachments: many(Attachment),
  folderFilesCreated: many(FolderFile),
  endUsers: many(EndUser),
}))

export const organizationRelations = relations(Organization, ({ one, many }) => ({
  assets: many(MediaAsset),
  createdBy: one(User, {
    fields: [Organization.createdById],
    references: [User.id],
    relationName: 'organization_createdById_user_id',
  }),
  systemUser: one(User, {
    fields: [Organization.systemUserId],
    references: [User.id],
    relationName: 'organization_systemUserId_user_id',
  }),
  members: many(OrganizationMember),
  invitations: many(OrganizationInvitation),
  settings: many(OrganizationSetting),
  participants: many(Participant),
  threadReadStatuses: many(ThreadReadStatus),
  labels: many(Label),
  emails: many(Message),
  threads: many(Thread),
  articles: many(Article),
  integrations: many(Integration),
  aiAgentSessions: many(AiAgentSession),
  aiUsages: many(AiUsage),
  aiIntegrations: many(AiIntegration),
  events: many(Event),
  webhooks: many(Webhook),
  apiKeys: many(ApiKey),
  articleRevisions: many(ArticleRevision),
  recordSequences: many(RecordSequence),
  knowledgeBases: many(KnowledgeBase),
  mailDomains: many(MailDomain),
  emailTemplates: many(EmailTemplate),
  snippetFolders: many(SnippetFolder),
  snippets: many(Snippet),
  promptTemplates: many(PromptTemplate),
  comments: many(Comment),
  mailViews: many(MailView),
  chatWidgets: many(ChatWidget),
  planSubscriptions: many(PlanSubscription),
  planSubscriptionHistory: many(PlanSubscriptionHistory),
  invoices: many(Invoice),
  tags: many(Tag),
  notifications: many(Notification),
  syncJobs: many(SyncJob),
  customFields: many(CustomField),
  tableViews: many(TableView),
  integrationTagLabels: many(IntegrationTagLabel),
  searchHistories: many(SearchHistory),
  loadBalancingConfigs: many(LoadBalancingConfig),
  providerPreferences: many(ProviderPreference),
  modelConfigurations: many(ModelConfiguration),
  workflows: many(Workflow),
  workflowApps: many(WorkflowApp),
  providerConfigurations: many(ProviderConfiguration),
  workflowRuns: many(WorkflowRun),
  workflowNodeExecutions: many(WorkflowNodeExecution),
  approvalRequests: many(ApprovalRequest),
  files: many(File),
  Credential: many(Credential),
  datasets: many(Dataset),
  datasetSearchQueries: many(DatasetSearchQuery),
  externalKnowledgeSources: many(ExternalKnowledgeSource),
  documents: many(Document),
  documentSegments: many(DocumentSegment),
  folders: many(Folder),
  uploadSessions: many(UploadSession),
  attachments: many(Attachment),
  folderFiles: many(FolderFile),
  entityInstances: many(EntityInstance),
  systemModelDefaults: many(SystemModelDefault),
}))

export const organizationMemberRelations = relations(OrganizationMember, ({ one }) => ({
  organization: one(Organization, {
    fields: [OrganizationMember.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [OrganizationMember.userId],
    references: [User.id],
  }),
}))

export const organizationInvitationRelations = relations(OrganizationInvitation, ({ one }) => ({
  acceptedBy: one(User, {
    fields: [OrganizationInvitation.acceptedById],
    references: [User.id],
    relationName: 'organizationInvitation_acceptedById_user_id',
  }),
  invitedBy: one(User, {
    fields: [OrganizationInvitation.invitedById],
    references: [User.id],
    relationName: 'organizationInvitation_invitedById_user_id',
  }),
  organization: one(Organization, {
    fields: [OrganizationInvitation.organizationId],
    references: [Organization.id],
  }),
}))

export const organizationSettingRelations = relations(OrganizationSetting, ({ one }) => ({
  organization: one(Organization, {
    fields: [OrganizationSetting.organizationId],
    references: [Organization.id],
  }),
}))

// Settings v2 re-key: UserSetting is keyed by (userId, organizationId, key)
// directly — no more FK to OrganizationSetting. See
// plans/settings/v2/README.md §Service refactor.
export const userSettingRelations = relations(UserSetting, ({ one }) => ({
  user: one(User, {
    fields: [UserSetting.userId],
    references: [User.id],
  }),
  organization: one(Organization, {
    fields: [UserSetting.organizationId],
    references: [Organization.id],
  }),
}))

export const integrationRelations = relations(Integration, ({ one, many }) => ({
  inboxIntegration: one(InboxIntegration),
  messages: many(Message),
  threads: many(Thread),
  organization: one(Organization, {
    fields: [Integration.organizationId],
    references: [Organization.id],
  }),
  chatWidget: one(ChatWidget),
}))

export const verificationTokenRelations = relations(VerificationToken, ({ one }) => ({
  user: one(User, {
    fields: [VerificationToken.userId],
    references: [User.id],
  }),
}))

export const passwordResetTokenRelations = relations(PasswordResetToken, ({ one }) => ({
  user: one(User, {
    fields: [PasswordResetToken.userId],
    references: [User.id],
  }),
}))

export const emailEmbeddingRelations = relations(EmailEmbedding, ({ one }) => ({
  message: one(Message, {
    fields: [EmailEmbedding.messageId],
    references: [Message.id],
  }),
}))

export const apiKeyRelations = relations(ApiKey, ({ one }) => ({
  organization: one(Organization, {
    fields: [ApiKey.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [ApiKey.userId],
    references: [User.id],
  }),
}))

export const recordSequenceRelations = relations(RecordSequence, ({ one }) => ({
  organization: one(Organization, {
    fields: [RecordSequence.organizationId],
    references: [Organization.id],
  }),
}))

export const mailDomainRelations = relations(MailDomain, ({ one }) => ({
  organization: one(Organization, {
    fields: [MailDomain.organizationId],
    references: [Organization.id],
  }),
}))

export const emailTemplateRelations = relations(EmailTemplate, ({ one }) => ({
  organization: one(Organization, {
    fields: [EmailTemplate.organizationId],
    references: [Organization.id],
  }),
}))

export const mailViewRelations = relations(MailView, ({ one }) => ({
  organization: one(Organization, {
    fields: [MailView.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [MailView.userId],
    references: [User.id],
  }),
}))

export const operatingHoursRelations = relations(OperatingHours, ({ one }) => ({
  chatWidget: one(ChatWidget, {
    fields: [OperatingHours.widgetId],
    references: [ChatWidget.id],
  }),
}))

export const tagRelations = relations(Tag, ({ one, many }) => ({
  organization: one(Organization, {
    fields: [Tag.organizationId],
    references: [Organization.id],
  }),
  parent: one(Tag, {
    fields: [Tag.parentId],
    references: [Tag.id],
    relationName: 'tag_parentId_tag_id',
  }),
  tags: many(Tag, {
    relationName: 'tag_parentId_tag_id',
  }),
  integrationTagLabels: many(IntegrationTagLabel),
  // tagsOnThreads: many(TagsOnThread), // DEPRECATED: Tags now use FieldValue via RELATIONSHIP field
}))

export const notificationRelations = relations(Notification, ({ one }) => ({
  actor: one(User, {
    fields: [Notification.actorId],
    references: [User.id],
    relationName: 'notification_actorId_user_id',
  }),
  organization: one(Organization, {
    fields: [Notification.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [Notification.userId],
    references: [User.id],
    relationName: 'notification_userId_user_id',
  }),
}))

export const passkeyRelations = relations(Passkey, ({ one }) => ({
  user: one(User, {
    fields: [Passkey.userId],
    references: [User.id],
  }),
}))

export const accountRelations = relations(account, ({ one }) => ({
  user: one(User, {
    fields: [account.userId],
    references: [User.id],
  }),
}))

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(User, {
    fields: [session.userId],
    references: [User.id],
  }),
}))

export const twoFactorRelations = relations(TwoFactor, ({ one }) => ({
  user: one(User, {
    fields: [TwoFactor.userId],
    references: [User.id],
  }),
}))

export const customFieldRelations = relations(CustomField, ({ one, many }) => ({
  organization: one(Organization, {
    fields: [CustomField.organizationId],
    references: [Organization.id],
  }),
  entityDefinition: one(EntityDefinition, {
    fields: [CustomField.entityDefinitionId],
    references: [EntityDefinition.id],
  }),
  fieldValues: many(FieldValue),
}))

/**
 * FieldValue relations - typed field value storage
 */
export const fieldValueRelations = relations(FieldValue, ({ one }) => ({
  field: one(CustomField, {
    fields: [FieldValue.fieldId],
    references: [CustomField.id],
  }),
  organization: one(Organization, {
    fields: [FieldValue.organizationId],
    references: [Organization.id],
  }),
  // entityId is polymorphic (Contact, Ticket, EntityInstance, etc.)
  // We define explicit relation to EntityInstance for custom entities
  entityInstance: one(EntityInstance, {
    fields: [FieldValue.entityId],
    references: [EntityInstance.id],
  }),
}))

export const entityDefinitionRelations = relations(EntityDefinition, ({ one, many }) => ({
  organization: one(Organization, {
    fields: [EntityDefinition.organizationId],
    references: [Organization.id],
  }),
  customFields: many(CustomField),
  instances: many(EntityInstance),
  // Display field relations
  primaryDisplayField: one(CustomField, {
    fields: [EntityDefinition.primaryDisplayFieldId],
    references: [CustomField.id],
    relationName: 'entityDefinition_primaryDisplayFieldId_customField_id',
  }),
  secondaryDisplayField: one(CustomField, {
    fields: [EntityDefinition.secondaryDisplayFieldId],
    references: [CustomField.id],
    relationName: 'entityDefinition_secondaryDisplayFieldId_customField_id',
  }),
  avatarField: one(CustomField, {
    fields: [EntityDefinition.avatarFieldId],
    references: [CustomField.id],
    relationName: 'entityDefinition_avatarFieldId_customField_id',
  }),
}))

export const entityInstanceRelations = relations(EntityInstance, ({ one, many }) => ({
  entityDefinition: one(EntityDefinition, {
    fields: [EntityInstance.entityDefinitionId],
    references: [EntityDefinition.id],
  }),
  organization: one(Organization, {
    fields: [EntityInstance.organizationId],
    references: [Organization.id],
  }),
  createdBy: one(User, {
    fields: [EntityInstance.createdById],
    references: [User.id],
  }),
  // Field values for this instance
  values: many(FieldValue),
  // Group members (when this instance IS a group with resourceType: 'entity_group')
  groupMembers: many(EntityGroupMember),
}))

export const tableViewRelations = relations(TableView, ({ one }) => ({
  organization: one(Organization, {
    fields: [TableView.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [TableView.userId],
    references: [User.id],
  }),
}))

export const integrationTagLabelRelations = relations(IntegrationTagLabel, ({ one }) => ({
  label: one(Label, {
    fields: [IntegrationTagLabel.labelId],
    references: [Label.id],
  }),
  organization: one(Organization, {
    fields: [IntegrationTagLabel.organizationId],
    references: [Organization.id],
  }),
  tag: one(Tag, {
    fields: [IntegrationTagLabel.tagId],
    references: [Tag.id],
  }),
}))

export const searchHistoryRelations = relations(SearchHistory, ({ one }) => ({
  organization: one(Organization, {
    fields: [SearchHistory.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [SearchHistory.userId],
    references: [User.id],
  }),
}))

export const loadBalancingConfigRelations = relations(LoadBalancingConfig, ({ one }) => ({
  organization: one(Organization, {
    fields: [LoadBalancingConfig.organizationId],
    references: [Organization.id],
  }),
}))

export const providerPreferenceRelations = relations(ProviderPreference, ({ one }) => ({
  organization: one(Organization, {
    fields: [ProviderPreference.organizationId],
    references: [Organization.id],
  }),
}))

export const modelConfigurationRelations = relations(ModelConfiguration, ({ one }) => ({
  organization: one(Organization, {
    fields: [ModelConfiguration.organizationId],
    references: [Organization.id],
  }),
}))

export const providerConfigurationRelations = relations(ProviderConfiguration, ({ one }) => ({
  organization: one(Organization, {
    fields: [ProviderConfiguration.organizationId],
    references: [Organization.id],
  }),
}))

export const systemModelDefaultRelations = relations(SystemModelDefault, ({ one }) => ({
  organization: one(Organization, {
    fields: [SystemModelDefault.organizationId],
    references: [Organization.id],
  }),
}))

export const aiMessageFeedbackRelations = relations(AiMessageFeedback, ({ one }) => ({
  session: one(AiAgentSession, {
    fields: [AiMessageFeedback.sessionId],
    references: [AiAgentSession.id],
  }),
  organization: one(Organization, {
    fields: [AiMessageFeedback.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [AiMessageFeedback.userId],
    references: [User.id],
  }),
}))
