// packages/database/src/db/relations/files.ts
// Grouped relations for files domain (generated by scripts/split-relations.ts)

import { relations } from 'drizzle-orm/relations'
import {
  Article,
  Attachment,
  Dataset,
  DatasetMetadata,
  DatasetSearchQuery,
  DatasetSearchResult,
  Document,
  DocumentSegment,
  EmailAttachment,
  ExternalKnowledgeSource,
  File,
  FileAttachment,
  FileVersion,
  Folder,
  FolderFile,
  KnowledgeBase,
  MediaAsset,
  MediaAssetVersion,
  Organization,
  StorageLocation,
  UploadSession,
  User,
  WorkflowCredentials,
  WorkflowFile,
} from '../schema'

export const mediaAssetRelations = relations(MediaAsset, ({ one, many }) => ({
  createdBy: one(User, {
    fields: [MediaAsset.createdById],
    references: [User.id],
    relationName: 'mediaAsset_createdById_user_id',
  }),
  currentVersion: one(MediaAssetVersion, {
    fields: [MediaAsset.currentVersionId],
    references: [MediaAssetVersion.id],
    relationName: 'mediaAsset_currentVersionId_mediaAssetVersion_id',
  }),
  organization: one(Organization, {
    fields: [MediaAsset.organizationId],
    references: [Organization.id],
  }),
  versions: many(MediaAssetVersion, {
    relationName: 'mediaAssetVersion_assetId_mediaAsset_id',
  }),
  emailAttachments: many(EmailAttachment),
  knowledgeBaseLogoDark: many(KnowledgeBase, {
    relationName: 'knowledgeBase_logoDarkId_mediaAsset_id',
  }),
  knowledgeBaseLogoLight: many(KnowledgeBase, {
    relationName: 'knowledgeBase_logoLightId_mediaAsset_id',
  }),
  users: many(User, {
    relationName: 'user_avatarAssetId_mediaAsset_id',
  }),
  documents: many(Document),
  attachments: many(Attachment),
}))

export const mediaAssetVersionRelations = relations(MediaAssetVersion, ({ one, many }) => ({
  currentForAsset: many(MediaAsset, {
    relationName: 'mediaAsset_currentVersionId_mediaAssetVersion_id',
  }),
  asset: one(MediaAsset, {
    fields: [MediaAssetVersion.assetId],
    references: [MediaAsset.id],
    relationName: 'mediaAssetVersion_assetId_mediaAsset_id',
  }),
  derivedFrom: one(MediaAssetVersion, {
    fields: [MediaAssetVersion.derivedFromVersionId],
    references: [MediaAssetVersion.id],
    relationName: 'mediaAssetVersion_derivedFromVersionId_mediaAssetVersion_id',
  }),
  derivatives: many(MediaAssetVersion, {
    relationName: 'mediaAssetVersion_derivedFromVersionId_mediaAssetVersion_id',
  }),
  storageLocation: one(StorageLocation, {
    fields: [MediaAssetVersion.storageLocationId],
    references: [StorageLocation.id],
  }),
  attachments: many(Attachment),
}))

export const storageLocationRelations = relations(StorageLocation, ({ one, many }) => ({
  assetVersions: many(MediaAssetVersion),
  credential: one(WorkflowCredentials, {
    fields: [StorageLocation.credentialId],
    references: [WorkflowCredentials.id],
  }),
  fileVersions: many(FileVersion),
}))

export const fileRelations = relations(File, ({ one, many }) => ({
  article: one(Article, {
    fields: [File.articleId],
    references: [Article.id],
  }),
  createdBy: one(User, {
    fields: [File.createdById],
    references: [User.id],
    relationName: 'file_createdById_user_id',
  }),
  deletedByUser: one(User, {
    fields: [File.deletedById],
    references: [User.id],
    relationName: 'file_deletedById_user_id',
  }),
  knowledgeBase: one(KnowledgeBase, {
    fields: [File.knowledgeBaseId],
    references: [KnowledgeBase.id],
  }),
  organization: one(Organization, {
    fields: [File.organizationId],
    references: [Organization.id],
  }),
  attachments: many(FileAttachment),
  workflowFiles: many(WorkflowFile),
}))

export const fileAttachmentRelations = relations(FileAttachment, ({ one }) => ({
  file: one(File, {
    fields: [FileAttachment.fileId],
    references: [File.id],
  }),
}))

export const datasetRelations = relations(Dataset, ({ one, many }) => ({
  createdBy: one(User, {
    fields: [Dataset.createdById],
    references: [User.id],
  }),
  organization: one(Organization, {
    fields: [Dataset.organizationId],
    references: [Organization.id],
  }),
  searchQueries: many(DatasetSearchQuery),
  externalSources: many(ExternalKnowledgeSource),
  documents: many(Document),
  metadata: many(DatasetMetadata),
}))

export const datasetSearchQueryRelations = relations(DatasetSearchQuery, ({ one, many }) => ({
  dataset: one(Dataset, {
    fields: [DatasetSearchQuery.datasetId],
    references: [Dataset.id],
  }),
  organization: one(Organization, {
    fields: [DatasetSearchQuery.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [DatasetSearchQuery.userId],
    references: [User.id],
  }),
  results: many(DatasetSearchResult),
}))

export const datasetSearchResultRelations = relations(DatasetSearchResult, ({ one }) => ({
  query: one(DatasetSearchQuery, {
    fields: [DatasetSearchResult.queryId],
    references: [DatasetSearchQuery.id],
  }),
  segment: one(DocumentSegment, {
    fields: [DatasetSearchResult.segmentId],
    references: [DocumentSegment.id],
  }),
}))

export const documentSegmentRelations = relations(DocumentSegment, ({ one, many }) => ({
  searchResults: many(DatasetSearchResult),
  document: one(Document, {
    fields: [DocumentSegment.documentId],
    references: [Document.id],
  }),
  organization: one(Organization, {
    fields: [DocumentSegment.organizationId],
    references: [Organization.id],
  }),
}))

export const externalKnowledgeSourceRelations = relations(ExternalKnowledgeSource, ({ one }) => ({
  createdBy: one(User, {
    fields: [ExternalKnowledgeSource.createdById],
    references: [User.id],
  }),
  dataset: one(Dataset, {
    fields: [ExternalKnowledgeSource.datasetId],
    references: [Dataset.id],
  }),
  organization: one(Organization, {
    fields: [ExternalKnowledgeSource.organizationId],
    references: [Organization.id],
  }),
}))

export const documentRelations = relations(Document, ({ one, many }) => ({
  dataset: one(Dataset, {
    fields: [Document.datasetId],
    references: [Dataset.id],
  }),
  mediaAsset: one(MediaAsset, {
    fields: [Document.mediaAssetId],
    references: [MediaAsset.id],
  }),
  organization: one(Organization, {
    fields: [Document.organizationId],
    references: [Organization.id],
  }),
  uploadedBy: one(User, {
    fields: [Document.uploadedById],
    references: [User.id],
  }),
  segments: many(DocumentSegment),
}))

export const datasetMetadataRelations = relations(DatasetMetadata, ({ one }) => ({
  dataset: one(Dataset, {
    fields: [DatasetMetadata.datasetId],
    references: [Dataset.id],
  }),
}))

export const folderRelations = relations(Folder, ({ one, many }) => ({
  createdBy: one(User, {
    fields: [Folder.createdById],
    references: [User.id],
  }),
  organization: one(Organization, {
    fields: [Folder.organizationId],
    references: [Organization.id],
  }),
  parent: one(Folder, {
    fields: [Folder.parentId],
    references: [Folder.id],
    relationName: 'folder_parentId_folder_id',
  }),
  children: many(Folder, {
    relationName: 'folder_parentId_folder_id',
  }),
  files: many(FolderFile),
}))

export const fileVersionRelations = relations(FileVersion, ({ one, many }) => ({
  file: one(FolderFile, {
    fields: [FileVersion.fileId],
    references: [FolderFile.id],
    relationName: 'fileVersion_fileId_folderFile_id',
  }),
  storageLocation: one(StorageLocation, {
    fields: [FileVersion.storageLocationId],
    references: [StorageLocation.id],
  }),
  attachments: many(Attachment),
  currentForFile: many(FolderFile, {
    relationName: 'folderFile_currentVersionId_fileVersion_id',
  }),
}))

export const folderFileRelations = relations(FolderFile, ({ one, many }) => ({
  versions: many(FileVersion, {
    relationName: 'fileVersion_fileId_folderFile_id',
  }),
  attachments: many(Attachment),
  createdBy: one(User, {
    fields: [FolderFile.createdById],
    references: [User.id],
  }),
  currentVersion: one(FileVersion, {
    fields: [FolderFile.currentVersionId],
    references: [FileVersion.id],
    relationName: 'folderFile_currentVersionId_fileVersion_id',
  }),
  folder: one(Folder, {
    fields: [FolderFile.folderId],
    references: [Folder.id],
  }),
  organization: one(Organization, {
    fields: [FolderFile.organizationId],
    references: [Organization.id],
  }),
}))

export const uploadSessionRelations = relations(UploadSession, ({ one }) => ({
  organization: one(Organization, {
    fields: [UploadSession.organizationId],
    references: [Organization.id],
  }),
}))

export const attachmentRelations = relations(Attachment, ({ one }) => ({
  asset: one(MediaAsset, {
    fields: [Attachment.assetId],
    references: [MediaAsset.id],
  }),
  assetVersion: one(MediaAssetVersion, {
    fields: [Attachment.assetVersionId],
    references: [MediaAssetVersion.id],
  }),
  createdBy: one(User, {
    fields: [Attachment.createdById],
    references: [User.id],
  }),
  file: one(FolderFile, {
    fields: [Attachment.fileId],
    references: [FolderFile.id],
  }),
  fileVersion: one(FileVersion, {
    fields: [Attachment.fileVersionId],
    references: [FileVersion.id],
  }),
  organization: one(Organization, {
    fields: [Attachment.organizationId],
    references: [Organization.id],
  }),
}))
