// packages/database/src/db/relations/knowledge.ts
// Grouped relations for knowledge domain (generated by scripts/split-relations.ts)

import { relations } from 'drizzle-orm/relations'
import {
  Article,
  ArticleRevision,
  ArticleTag,
  Comment,
  CommentMention,
  CommentReaction,
  File,
  KnowledgeBase,
  MediaAsset,
  Organization,
  PromptTemplate,
  Snippet,
  SnippetFolder,
  TagsOnArticle,
  User,
} from '../schema'

export const articleRelations = relations(Article, ({ one, many }) => ({
  author: one(User, {
    fields: [Article.authorId],
    references: [User.id],
  }),
  knowledgeBase: one(KnowledgeBase, {
    fields: [Article.knowledgeBaseId],
    references: [KnowledgeBase.id],
  }),
  organization: one(Organization, {
    fields: [Article.organizationId],
    references: [Organization.id],
  }),
  parent: one(Article, {
    fields: [Article.parentId],
    references: [Article.id],
    relationName: 'article_parentId_article_id',
  }),
  children: many(Article, {
    relationName: 'article_parentId_article_id',
  }),
  revisions: many(ArticleRevision),
  files: many(File),
  tags: many(TagsOnArticle),
}))

export const knowledgeBaseRelations = relations(KnowledgeBase, ({ one, many }) => ({
  articles: many(Article),
  logoDarkAsset: one(MediaAsset, {
    fields: [KnowledgeBase.logoDarkId],
    references: [MediaAsset.id],
    relationName: 'knowledgeBase_logoDarkId_mediaAsset_id',
  }),
  logoLightAsset: one(MediaAsset, {
    fields: [KnowledgeBase.logoLightId],
    references: [MediaAsset.id],
    relationName: 'knowledgeBase_logoLightId_mediaAsset_id',
  }),
  organization: one(Organization, {
    fields: [KnowledgeBase.organizationId],
    references: [Organization.id],
  }),
  files: many(File),
}))

export const articleTagRelations = relations(ArticleTag, ({ one, many }) => ({
  organization: one(Organization, {
    fields: [ArticleTag.organizationId],
    references: [Organization.id],
  }),
  articles: many(TagsOnArticle),
}))

export const articleRevisionRelations = relations(ArticleRevision, ({ one }) => ({
  article: one(Article, {
    fields: [ArticleRevision.articleId],
    references: [Article.id],
  }),
  editor: one(User, {
    fields: [ArticleRevision.editorId],
    references: [User.id],
  }),
  organization: one(Organization, {
    fields: [ArticleRevision.organizationId],
    references: [Organization.id],
  }),
}))

export const snippetFolderRelations = relations(SnippetFolder, ({ one, many }) => ({
  createdBy: one(User, {
    fields: [SnippetFolder.createdById],
    references: [User.id],
  }),
  organization: one(Organization, {
    fields: [SnippetFolder.organizationId],
    references: [Organization.id],
  }),
  parent: one(SnippetFolder, {
    fields: [SnippetFolder.parentId],
    references: [SnippetFolder.id],
    relationName: 'snippetFolder_parentId_snippetFolder_id',
  }),
  subfolders: many(SnippetFolder, {
    relationName: 'snippetFolder_parentId_snippetFolder_id',
  }),
  snippets: many(Snippet),
}))

export const snippetRelations = relations(Snippet, ({ one }) => ({
  createdBy: one(User, {
    fields: [Snippet.createdById],
    references: [User.id],
  }),
  folder: one(SnippetFolder, {
    fields: [Snippet.folderId],
    references: [SnippetFolder.id],
  }),
  organization: one(Organization, {
    fields: [Snippet.organizationId],
    references: [Organization.id],
  }),
  // Note: shares removed - migrated to ResourceAccess
}))

export const commentRelations = relations(Comment, ({ one, many }) => ({
  createdBy: one(User, {
    fields: [Comment.createdById],
    references: [User.id],
    relationName: 'comment_createdById_user_id',
  }),
  organization: one(Organization, {
    fields: [Comment.organizationId],
    references: [Organization.id],
  }),
  parent: one(Comment, {
    fields: [Comment.parentId],
    references: [Comment.id],
    relationName: 'comment_parentId_comment_id',
  }),
  replies: many(Comment, {
    relationName: 'comment_parentId_comment_id',
  }),
  pinnedBy: one(User, {
    fields: [Comment.pinnedById],
    references: [User.id],
    relationName: 'comment_pinnedById_user_id',
  }),
  mentions: many(CommentMention),
  reactions: many(CommentReaction),
}))

export const commentMentionRelations = relations(CommentMention, ({ one }) => ({
  comment: one(Comment, {
    fields: [CommentMention.commentId],
    references: [Comment.id],
  }),
  user: one(User, {
    fields: [CommentMention.userId],
    references: [User.id],
  }),
}))

export const commentReactionRelations = relations(CommentReaction, ({ one }) => ({
  comment: one(Comment, {
    fields: [CommentReaction.commentId],
    references: [Comment.id],
  }),
  user: one(User, {
    fields: [CommentReaction.userId],
    references: [User.id],
  }),
}))

export const promptTemplateRelations = relations(PromptTemplate, ({ one }) => ({
  organization: one(Organization, {
    fields: [PromptTemplate.organizationId],
    references: [Organization.id],
  }),
  createdBy: one(User, {
    fields: [PromptTemplate.createdById],
    references: [User.id],
  }),
}))
