// packages/database/src/db/relations/messaging.ts
// Grouped relations for messaging domain (generated by scripts/split-relations.ts)

import { relations } from 'drizzle-orm/relations'
import {
  ChatAttachment,
  ChatMessage,
  ChatSession,
  ChatWidget,
  EmailAttachment,
  EmailEmbedding,
  EntityInstance,
  InboxIntegration,
  Integration,
  IntegrationTagLabel,
  Label,
  LabelsOnThread,
  Message,
  MessageParticipant,
  OperatingHours,
  Organization,
  Participant,
  PromptHistory,
  Signature,
  Tag,
  TagsOnThread,
  Thread,
  ThreadParticipant,
  ThreadReadStatus,
  User,
  UserInboxUnreadCount,
} from '../schema'

/**
 * InboxIntegration relations
 * Links to EntityInstance (inbox) and Integration
 */
export const inboxIntegrationRelations = relations(InboxIntegration, ({ one }) => ({
  inbox: one(EntityInstance, {
    fields: [InboxIntegration.inboxId],
    references: [EntityInstance.id],
  }),
  integration: one(Integration, {
    fields: [InboxIntegration.integrationId],
    references: [Integration.id],
  }),
}))

export const threadReadStatusRelations = relations(ThreadReadStatus, ({ one }) => ({
  organization: one(Organization, {
    fields: [ThreadReadStatus.organizationId],
    references: [Organization.id],
  }),
  thread: one(Thread, {
    fields: [ThreadReadStatus.threadId],
    references: [Thread.id],
  }),
  user: one(User, {
    fields: [ThreadReadStatus.userId],
    references: [User.id],
  }),
}))

export const threadRelations = relations(Thread, ({ one, many }) => ({
  readStatusEntries: many(ThreadReadStatus),
  messages: many(Message),
  assignee: one(User, {
    fields: [Thread.assigneeId],
    references: [User.id],
  }),
  integration: one(Integration, {
    fields: [Thread.integrationId],
    references: [Integration.id],
  }),
  organization: one(Organization, {
    fields: [Thread.organizationId],
    references: [Organization.id],
  }),
  participants: many(ThreadParticipant),
  chatSessions: many(ChatSession),
  chatMessages: many(ChatMessage),
  labels: many(LabelsOnThread),
  tags: many(TagsOnThread),
}))

/**
 * UserInboxUnreadCount relations
 * Links to EntityInstance (inbox), Organization, and User
 */
export const userInboxUnreadCountRelations = relations(UserInboxUnreadCount, ({ one }) => ({
  inbox: one(EntityInstance, {
    fields: [UserInboxUnreadCount.inboxId],
    references: [EntityInstance.id],
  }),
  organization: one(Organization, {
    fields: [UserInboxUnreadCount.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [UserInboxUnreadCount.userId],
    references: [User.id],
  }),
}))

export const labelRelations = relations(Label, ({ one, many }) => ({
  organization: one(Organization, {
    fields: [Label.organizationId],
    references: [Organization.id],
  }),
  integrationTagLabels: many(IntegrationTagLabel),
  threads: many(LabelsOnThread),
}))

export const messageRelations = relations(Message, ({ one, many }) => ({
  emailEmbeddings: many(EmailEmbedding),
  createdBy: one(User, {
    fields: [Message.createdById],
    references: [User.id],
  }),
  from: one(Participant, {
    fields: [Message.fromId],
    references: [Participant.id],
    relationName: 'message_fromId_participant_id',
  }),
  integration: one(Integration, {
    fields: [Message.integrationId],
    references: [Integration.id],
  }),
  organization: one(Organization, {
    fields: [Message.organizationId],
    references: [Organization.id],
  }),
  replyTo: one(Participant, {
    fields: [Message.replyToId],
    references: [Participant.id],
    relationName: 'message_replyToId_participant_id',
  }),
  signature: one(Signature, {
    fields: [Message.signatureId],
    references: [Signature.id],
  }),
  thread: one(Thread, {
    fields: [Message.threadId],
    references: [Thread.id],
  }),
  participants: many(MessageParticipant),
  attachments: many(EmailAttachment),
}))

export const messageParticipantRelations = relations(MessageParticipant, ({ one }) => ({
  message: one(Message, {
    fields: [MessageParticipant.messageId],
    references: [Message.id],
  }),
  participant: one(Participant, {
    fields: [MessageParticipant.participantId],
    references: [Participant.id],
  }),
}))



export const threadParticipantRelations = relations(ThreadParticipant, ({ one }) => ({
  thread: one(Thread, {
    fields: [ThreadParticipant.threadId],
    references: [Thread.id],
  }),
}))


export const promptHistoryRelations = relations(PromptHistory, ({ one }) => ({
  user: one(User, {
    fields: [PromptHistory.userId],
    references: [User.id],
  }),
}))

export const chatWidgetRelations = relations(ChatWidget, ({ one, many }) => ({
  integration: one(Integration, {
    fields: [ChatWidget.integrationId],
    references: [Integration.id],
  }),
  organization: one(Organization, {
    fields: [ChatWidget.organizationId],
    references: [Organization.id],
  }),
  operatingHours: many(OperatingHours),
  sessions: many(ChatSession),
}))

export const chatSessionRelations = relations(ChatSession, ({ one, many }) => ({
  user: one(User, {
    fields: [ChatSession.closedById],
    references: [User.id],
  }),
  organization: one(Organization, {
    fields: [ChatSession.organizationId],
    references: [Organization.id],
  }),
  thread: one(Thread, {
    fields: [ChatSession.threadId],
    references: [Thread.id],
  }),
  widget: one(ChatWidget, {
    fields: [ChatSession.widgetId],
    references: [ChatWidget.id],
  }),
  messages: many(ChatMessage),
  attachments: many(ChatAttachment),
}))

export const chatMessageRelations = relations(ChatMessage, ({ one, many }) => ({
  user: one(User, {
    fields: [ChatMessage.agentId],
    references: [User.id],
  }),
  session: one(ChatSession, {
    fields: [ChatMessage.sessionId],
    references: [ChatSession.id],
  }),
  thread: one(Thread, {
    fields: [ChatMessage.threadId],
    references: [Thread.id],
  }),
  attachments: many(ChatAttachment),
}))

export const chatAttachmentRelations = relations(ChatAttachment, ({ one }) => ({
  message: one(ChatMessage, {
    fields: [ChatAttachment.messageId],
    references: [ChatMessage.id],
  }),
  session: one(ChatSession, {
    fields: [ChatAttachment.sessionId],
    references: [ChatSession.id],
  }),
}))








export const labelsOnThreadRelations = relations(LabelsOnThread, ({ one }) => ({
  label: one(Label, {
    fields: [LabelsOnThread.labelId],
    references: [Label.id],
  }),
  thread: one(Thread, {
    fields: [LabelsOnThread.threadId],
    references: [Thread.id],
  }),
}))

export const tagsOnThreadRelations = relations(TagsOnThread, ({ one }) => ({
  tag: one(Tag, {
    fields: [TagsOnThread.tagId],
    references: [Tag.id],
  }),
  thread: one(Thread, {
    fields: [TagsOnThread.threadId],
    references: [Thread.id],
  }),
}))
