// packages/database/src/db/relations/workflow.ts
// Grouped relations for workflow domain (generated by scripts/split-relations.ts)

import { relations } from 'drizzle-orm/relations'
import {
  AiIntegration,
  AiUsage,
  App,
  AppInstallation,
  ApprovalRequest,
  ApprovalResponse,
  EndUser,
  Event,
  File,
  Organization,
  ShopifyIntegration,
  StorageLocation,
  Subscription,
  SyncJob,
  User,
  Webhook,
  WebhookDelivery,
  WebhookEvent,
  Workflow,
  WorkflowApp,
  WorkflowCredentials,
  WorkflowFile,
  WorkflowJoinState,
  WorkflowNodeExecution,
  WorkflowRun,
} from '../schema'

export const aiUsageRelations = relations(AiUsage, ({ one }) => ({
  organization: one(Organization, {
    fields: [AiUsage.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [AiUsage.userId],
    references: [User.id],
  }),
}))

export const aiIntegrationRelations = relations(AiIntegration, ({ one }) => ({
  organization: one(Organization, {
    fields: [AiIntegration.organizationId],
    references: [Organization.id],
  }),
  user: one(User, {
    fields: [AiIntegration.userId],
    references: [User.id],
  }),
}))

export const webhookEventRelations = relations(WebhookEvent, ({ one }) => ({
  shopifyIntegration: one(ShopifyIntegration, {
    fields: [WebhookEvent.integrationId],
    references: [ShopifyIntegration.id],
  }),
  organization: one(Organization, {
    fields: [WebhookEvent.organizationId],
    references: [Organization.id],
  }),
  subscription: one(Subscription, {
    fields: [WebhookEvent.subscriptionId],
    references: [Subscription.id],
  }),
}))

export const eventRelations = relations(Event, ({ one }) => ({
  organization: one(Organization, {
    fields: [Event.organizationId],
    references: [Organization.id],
  }),
}))

export const webhookRelations = relations(Webhook, ({ one, many }) => ({
  organization: one(Organization, {
    fields: [Webhook.organizationId],
    references: [Organization.id],
  }),
  deliveries: many(WebhookDelivery),
}))

export const webhookDeliveryRelations = relations(WebhookDelivery, ({ one }) => ({
  webhook: one(Webhook, {
    fields: [WebhookDelivery.webhookId],
    references: [Webhook.id],
  }),
}))

export const syncJobRelations = relations(SyncJob, ({ one }) => ({
  organization: one(Organization, {
    fields: [SyncJob.organizationId],
    references: [Organization.id],
  }),
}))

export const workflowRelations = relations(Workflow, ({ one, many }) => ({
  createdBy: one(User, {
    fields: [Workflow.createdById],
    references: [User.id],
  }),
  organization: one(Organization, {
    fields: [Workflow.organizationId],
    references: [Organization.id],
  }),
  workflowApp: one(WorkflowApp, {
    fields: [Workflow.workflowAppId],
    references: [WorkflowApp.id],
    relationName: 'workflow_workflowAppId_workflowApp_id',
  }),
  draftIn: many(WorkflowApp, {
    relationName: 'workflowApp_draftWorkflowId_workflow_id',
  }),
  publishedIn: many(WorkflowApp, {
    relationName: 'workflowApp_workflowId_workflow_id',
  }),
  workflowRuns: many(WorkflowRun),
  nodeExecutions: many(WorkflowNodeExecution),
  approvalRequests: many(ApprovalRequest),
  joinStates: many(WorkflowJoinState),
  workflowFiles: many(WorkflowFile),
}))

export const workflowAppRelations = relations(WorkflowApp, ({ one, many }) => ({
  workflows: many(Workflow, {
    relationName: 'workflow_workflowAppId_workflowApp_id',
  }),
  createdBy: one(User, {
    fields: [WorkflowApp.createdById],
    references: [User.id],
  }),
  draftWorkflow: one(Workflow, {
    fields: [WorkflowApp.draftWorkflowId],
    references: [Workflow.id],
    relationName: 'workflowApp_draftWorkflowId_workflow_id',
  }),
  organization: one(Organization, {
    fields: [WorkflowApp.organizationId],
    references: [Organization.id],
  }),
  publishedWorkflow: one(Workflow, {
    fields: [WorkflowApp.workflowId],
    references: [Workflow.id],
    relationName: 'workflowApp_workflowId_workflow_id',
  }),
  workflowRuns: many(WorkflowRun),
  nodeExecutions: many(WorkflowNodeExecution),
  endUsers: many(EndUser),
}))

export const workflowRunRelations = relations(WorkflowRun, ({ one, many }) => ({
  createdBy: one(User, {
    fields: [WorkflowRun.createdBy],
    references: [User.id],
  }),
  organization: one(Organization, {
    fields: [WorkflowRun.organizationId],
    references: [Organization.id],
  }),
  workflowApp: one(WorkflowApp, {
    fields: [WorkflowRun.workflowAppId],
    references: [WorkflowApp.id],
  }),
  workflow: one(Workflow, {
    fields: [WorkflowRun.workflowId],
    references: [Workflow.id],
  }),
  nodeExecutions: many(WorkflowNodeExecution),
  approvalRequests: many(ApprovalRequest),
  endUser: one(EndUser, {
    fields: [WorkflowRun.endUserId],
    references: [EndUser.id],
  }),
}))

export const workflowNodeExecutionRelations = relations(WorkflowNodeExecution, ({ one }) => ({
  createdBy: one(User, {
    fields: [WorkflowNodeExecution.createdById],
    references: [User.id],
  }),
  organization: one(Organization, {
    fields: [WorkflowNodeExecution.organizationId],
    references: [Organization.id],
  }),
  workflowRun: one(WorkflowRun, {
    fields: [WorkflowNodeExecution.workflowRunId],
    references: [WorkflowRun.id],
  }),
  workflowApp: one(WorkflowApp, {
    fields: [WorkflowNodeExecution.workflowAppId],
    references: [WorkflowApp.id],
  }),
  workflow: one(Workflow, {
    fields: [WorkflowNodeExecution.workflowId],
    references: [Workflow.id],
  }),
}))

export const approvalRequestRelations = relations(ApprovalRequest, ({ one, many }) => ({
  createdBy: one(User, {
    fields: [ApprovalRequest.createdById],
    references: [User.id],
  }),
  organization: one(Organization, {
    fields: [ApprovalRequest.organizationId],
    references: [Organization.id],
  }),
  workflow: one(Workflow, {
    fields: [ApprovalRequest.workflowId],
    references: [Workflow.id],
  }),
  workflowRun: one(WorkflowRun, {
    fields: [ApprovalRequest.workflowRunId],
    references: [WorkflowRun.id],
  }),
  responses: many(ApprovalResponse),
}))

export const approvalResponseRelations = relations(ApprovalResponse, ({ one }) => ({
  approvalRequest: one(ApprovalRequest, {
    fields: [ApprovalResponse.approvalRequestId],
    references: [ApprovalRequest.id],
  }),
  user: one(User, {
    fields: [ApprovalResponse.userId],
    references: [User.id],
  }),
}))

export const workflowJoinStateRelations = relations(WorkflowJoinState, ({ one }) => ({
  workflow: one(Workflow, {
    fields: [WorkflowJoinState.workflowId],
    references: [Workflow.id],
  }),
}))

export const workflowFileRelations = relations(WorkflowFile, ({ one }) => ({
  file: one(File, {
    fields: [WorkflowFile.fileId],
    references: [File.id],
  }),
  workflow: one(Workflow, {
    fields: [WorkflowFile.workflowId],
    references: [Workflow.id],
  }),
}))

export const workflowCredentialsRelations = relations(WorkflowCredentials, ({ one, many }) => ({
  createdBy: one(User, {
    fields: [WorkflowCredentials.createdById],
    references: [User.id],
    relationName: 'workflowCredentials_createdBy',
  }),
  organization: one(Organization, {
    fields: [WorkflowCredentials.organizationId],
    references: [Organization.id],
  }),
  // App connection relations
  user: one(User, {
    fields: [WorkflowCredentials.userId],
    references: [User.id],
    relationName: 'workflowCredentials_user',
  }),
  app: one(App, {
    fields: [WorkflowCredentials.appId],
    references: [App.id],
  }),
  appInstallation: one(AppInstallation, {
    fields: [WorkflowCredentials.appInstallationId],
    references: [AppInstallation.id],
  }),
  storageLocations: many(StorageLocation),
}))

export const endUserRelations = relations(EndUser, ({ one, many }) => ({
  workflowApp: one(WorkflowApp, {
    fields: [EndUser.workflowAppId],
    references: [WorkflowApp.id],
  }),
  user: one(User, {
    fields: [EndUser.userId],
    references: [User.id],
  }),
  workflowRuns: many(WorkflowRun),
}))
