export { default as Gemini } from './Gemini'
export { default as Replit } from './Replit'
export { default as MagicUI } from './MagicUI'
export { default as VSCodium } from './VSCodium'
export { default as MediaWiki } from './MediaWiki'
export { default as GooglePaLM } from './GooglePaLM'

export { Beacon } from './beacon'
export { Bolt } from './bolt'
export { default as Cisco } from './cisco'
export { default as ClaudeAI } from './claude'
export { Cloudflare } from './cloudflare'
export { Hulu } from './hulu'
export { default as LeapWallet } from './leap-wallet'
export { Linear } from './linear'
export { default as OpenAI } from './open-ai'
export { default as PayPal } from './paypal'
export { default as Polars } from './polars'
export { Primevideo } from './prime'
export { default as Spotify } from './spotify'
export { Stripe } from './stripe'
export { default as Supabase } from './supabase'
export { Vercel } from './vercel'
export { default as VisualStudioCode } from './vs-code'

// New logo exports from icons.tsx reorganization
export { default as Anthropic } from './anthropic'
export { default as Aws } from './aws'
export { default as DeepSeek } from './deepseek'
export { default as Dropbox } from './dropbox'
export { default as Gmail } from './gmail'
export { default as Google, GoogleDrive } from './google'
export { default as Github } from './github'
export { default as Groq } from './groq'
export { default as Ollama } from './ollama'
export { default as Outlook } from './outlook'
export { default as Shopify, ShopifyColor } from './shopify'
export { default as Slack } from './slack'
export { default as Facebook } from './facebook'
export { default as Instagram } from './instagram'
export { default as OpenPhone } from './openphone'
export { default as ChatWidget } from './chat-widget'
