// apps/web/src/components/threads/index.ts

// Hooks
export {
  type InboxItem,
  type InboxRecord,
  useInbox,
  useInboxes,
  useIsThreadLoading,
  useIsThreadNotFound,
  useMessage,
  useMessages,
  useParticipant,
  useParticipants,
  useParticipantsArray,
  useSelectionReset,
  useThread,
  useThreadKeyboardNav,
  useThreadList,
  useThreadMutation,
  useThreadReadStatus,
  useThreadSelection,
} from './hooks'
// Providers
export { ThreadActionsProvider, ThreadDataProvider, useThreadActions } from './providers'
// Stores
export {
  type ChannelProvider,
  type ContextPagination,
  createAssignedThreadsSelector,
  // Selector utilities
  createContextKey,
  createInboxThreadsSelector,
  createThreadSelector,
  createUnreadThreadsSelector,
  filterThreadsFromMap,
  getMessageListStoreState,
  getMessageStoreState,
  getParticipantStoreState,
  getThreadSelectionState,
  getThreadStoreState,
  type MessageMeta,
  type ParticipantIdentifierType,
  type ParticipantMeta,
  type ParticipantSummary,
  sortThreads,
  type ThreadFilter,
  type ThreadMeta,
  type ThreadSort,
  type ThreadStatus,
  useActiveThreadId,
  useActiveThreadVersion,
  useFirstSelectedThreadId,
  useHasMultipleSelected,
  useHasSelection,
  useIsEditMode,
  useIsMultiSelectMode,
  useIsThreadActive,
  useIsThreadSelected,
  useMessageListStore,
  useMessageStore,
  useParticipantStore,
  useSelectedThreadIds,
  useSelectionCount,
  useThreadSelectionStore,
  useThreadStore,
  useViewMode,
  // Types
  type ViewMode,
} from './store'
