// packages/sdk/src/util/__tests__/generate-app-fields-types.test.ts

import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { APP_FIELDS_TYPES_FILENAME } from '../../constants/app-fields-files.js'
import { HIDDEN_AUXX_DIRECTORY } from '../../constants/hidden-auxx-directory.js'
import { isComplete } from '../../errors.js'
import { generateAppFieldsTypes } from '../generate-app-fields-types.js'

describe('generateAppFieldsTypes', () => {
  let rootDir: string
  let typesPath: string

  beforeEach(async () => {
    rootDir = await fs.mkdtemp(path.join(os.tmpdir(), 'auxx-fields-'))
    typesPath = path.join(rootDir, HIDDEN_AUXX_DIRECTORY, APP_FIELDS_TYPES_FILENAME)
  })

  afterEach(async () => {
    await fs.rm(rootDir, { recursive: true, force: true })
  })

  it('creates the augmentation file in .auxx and reports "created"', async () => {
    const result = await generateAppFieldsTypes(rootDir)
    expect(isComplete(result) && result.value).toBe('created')

    const content = await fs.readFile(typesPath, 'utf8')
    expect(content).toContain('// Auto-generated by auxx CLI. Do not edit.')
    expect(content).toContain("declare module '@auxx/sdk/server'")
    expect(content).toContain('export interface AppOwnedFieldRegistry')
    expect(content).toContain("import type { app } from '../src/app'")
  })

  it('reports "unchanged" on a second run with identical content', async () => {
    await generateAppFieldsTypes(rootDir)
    const result = await generateAppFieldsTypes(rootDir)
    expect(isComplete(result) && result.value).toBe('unchanged')
  })

  it('rewrites a managed file whose content drifted ("updated")', async () => {
    await generateAppFieldsTypes(rootDir)
    await fs.writeFile(typesPath, '// Auto-generated by auxx CLI. Do not edit.\n// stale\n', 'utf8')
    const result = await generateAppFieldsTypes(rootDir)
    expect(isComplete(result) && result.value).toBe('updated')
    const content = await fs.readFile(typesPath, 'utf8')
    expect(content).toContain('AppOwnedFieldRegistry')
  })

  it('preserves a hand-edited file lacking the marker ("skipped_unmanaged")', async () => {
    await fs.mkdir(path.join(rootDir, HIDDEN_AUXX_DIRECTORY), { recursive: true })
    const handEdited = '// my own augmentation\nexport {}\n'
    await fs.writeFile(typesPath, handEdited, 'utf8')

    const result = await generateAppFieldsTypes(rootDir)
    expect(isComplete(result) && result.value).toBe('skipped_unmanaged')
    expect(await fs.readFile(typesPath, 'utf8')).toBe(handEdited)
  })
})
