// packages/database/src/db/schema/_collations.ts
// Custom column types for non-default Postgres collations.
// Hand-written; not regenerated by scripts/split-schema.ts (only `_shared.ts` is).

import { customType } from 'drizzle-orm/pg-core'

/**
 * Text column with the C (byte-order) collation. Required for any column
 * that stores fractional-indexing keys produced by `@auxx/utils`'s
 * `generateKeyBetween`, because that library orders keys by codepoint
 * (`0…9 < A…Z < a…z`). The default `en_US.utf8` collation interleaves
 * cases (`a < A < b < B …`), which causes Postgres `MAX()` / `ORDER BY`
 * to return a non-greatest key in library order — letting
 * `generateKeyBetween` produce a key that already exists and triggering
 * unique-constraint violations on the corresponding sortKey index.
 */
export const textCollateC = customType<{ data: string }>({
  dataType() {
    return 'text COLLATE "C"'
  },
})
