// packages/database/src/db/schema/_shared.ts
// Shared Drizzle exports and enums (generated by scripts/split-schema.ts)

import { pgEnum } from 'drizzle-orm/pg-core'

// ---- Enums ----
export const actionType = pgEnum('ActionType', [
  'ARCHIVE',
  'LABEL',
  'REPLY',
  'FORWARD',
  'MARK_SPAM',
  'DRAFT_EMAIL',
  'SEND_MESSAGE',
  'APPLY_TAG',
  'REMOVE_TAG',
  'APPLY_LABEL',
  'REMOVE_LABEL',
  'MARK_TRASH',
  'ASSIGN_THREAD',
  'ARCHIVE_THREAD',
  'UNARCHIVE_THREAD',
  'MOVE_TO_TRASH',
  'REACT_TO_MESSAGE',
  'SHARE_MESSAGE',
  'SEND_SMS',
  'MAKE_CALL',
  'ESCALATE',
  'ASSIGN',
  'NOTIFY',
  'CREATE_TICKET',
  'SHOPIFY_ORDER_LOOKUP',
  'SHOPIFY_GENERATE_RESPONSE',
])
export const aiIntegrationStatus = pgEnum('AiIntegrationStatus', ['PENDING', 'VALID', 'INVALID'])
export const approvalAction = pgEnum('ApprovalAction', ['approve', 'deny'])
export const approvalStatus = pgEnum('ApprovalStatus', ['pending', 'approved', 'denied', 'timeout'])
export const articleStatus = pgEnum('ArticleStatus', ['DRAFT', 'PUBLISHED', 'ARCHIVED'])
export const assetVersionStatus = pgEnum('AssetVersionStatus', [
  'PENDING',
  'PROCESSING',
  'READY',
  'FAILED',
])
export const billingCycle = pgEnum('BillingCycle', ['MONTHLY', 'ANNUAL'])
export const chunkingStrategy = pgEnum('ChunkingStrategy', [
  'FIXED_SIZE',
  'SEMANTIC',
  'SENTENCE',
  'PARAGRAPH',
  'DOCUMENT',
])
export const contactFieldType = pgEnum('ContactFieldType', [
  'PHONE',
  'EMAIL',
  'ADDRESS',
  'URL',
  'TAGS',
  'DATE',
  'DATETIME',
  'TIME',
  'CHECKBOX',
  'TEXT',
  'NUMBER',
  'CURRENCY',
  'MULTI_SELECT',
  'SINGLE_SELECT',
  'RICH_TEXT',
  'PHONE_INTL',
  'ADDRESS_STRUCT',
  'FILE',
  'NAME',
  'RELATIONSHIP',
  'CALC',
  'ACTOR',
  'JSON',
])
export const credentialSource = pgEnum('CredentialSource', [
  'SYSTEM', // Platform-provided credentials from env vars
  'CUSTOM', // Organization-provided API key at provider level
  'MODEL_SPECIFIC', // Per-model credential override
  'LOAD_BALANCED', // From load balancing pool
])
export const customerSourceType = pgEnum('CustomerSourceType', [
  'EMAIL',
  'TICKET_SYSTEM',
  'SHOPIFY',
  'MANUAL',
  'OTHER',
  'FACEBOOK_PSID',
])
export const customerStatus = pgEnum('CustomerStatus', ['ACTIVE', 'INACTIVE', 'SPAM', 'MERGED'])
// dataModelType pgEnum removed - now using text() column with ModelType values
// Migration will convert UPPERCASE values to lowercase and drop the enum type
export const datasetStatus = pgEnum('DatasetStatus', ['ACTIVE', 'INACTIVE', 'PROCESSING', 'ERROR'])
export const deliveryStatus = pgEnum('DeliveryStatus', [
  'DELIVERED',
  'BOUNCED',
  'DELAYED',
  'DEFERRED',
  'REJECTED',
])
export const documentStatus = pgEnum('DocumentStatus', [
  'UPLOADED',
  'PROCESSING',
  'INDEXED',
  'FAILED',
  'ARCHIVED',
  'WAITING',
])
export const documentType = pgEnum('DocumentType', [
  'PDF',
  'DOCX',
  'TXT',
  'HTML',
  'MARKDOWN',
  'CSV',
  'JSON',
  'XML',
])
export const domainType = pgEnum('DomainType', ['CUSTOM', 'PROVIDER'])
// DraftMode enum removed - drafts now stored in separate Draft table
export const emailLabel = pgEnum('EmailLabel', ['inbox', 'sent', 'draft'])
export const emailProvider = pgEnum('EmailProvider', ['GMAIL', 'OUTLOOK', 'IMAP'])
export const emailTemplateType = pgEnum('EmailTemplateType', [
  'TICKET_CREATED',
  'TICKET_REPLIED',
  'TICKET_CLOSED',
  'TICKET_REOPENED',
  'TICKET_ASSIGNED',
  'TICKET_STATUS_CHANGED',
  'CUSTOM',
])
export const extractionRuleType = pgEnum('ExtractionRuleType', [
  'REGEX',
  'MARKER',
  'POSITION',
  'AI_ASSISTED',
  'VISUAL_SELECTION',
])
export const fulfillmentStatus = pgEnum('FULFILLMENT_STATUS', [
  'CANCELLED',
  'ERROR',
  'FAILURE',
  'SUCCESS',
  'OPEN',
  'PENDING',
])
export const fileStatus = pgEnum('FileStatus', [
  'PENDING',
  'CONFIRMED',
  'ARCHIVED',
  'DELETED',
  'FAILED',
])
export const fileVisibility = pgEnum('FileVisibility', ['PUBLIC', 'PRIVATE', 'INTERNAL'])
export const inventoryPolicy = pgEnum('INVENTORY_POLICY', ['CONTINUE', 'DENY'])
export const identifierType = pgEnum('IdentifierType', [
  'EMAIL',
  'PHONE',
  'FACEBOOK_PSID',
  'INSTAGRAM_IGSID',
])
export const inboxStatus = pgEnum('InboxStatus', ['ACTIVE', 'ARCHIVED', 'PAUSED'])
export const indexStatus = pgEnum('IndexStatus', ['PENDING', 'INDEXED', 'ERROR'])
export const integrationAuthStatus = pgEnum('IntegrationAuthStatus', [
  'AUTHENTICATED',
  'UNAUTHENTICATED',
  'ERROR',
  'INVALID_GRANT',
  'EXPIRED_TOKEN',
  'REVOKED_ACCESS',
  'INSUFFICIENT_SCOPE',
  'RATE_LIMITED',
  'PROVIDER_ERROR',
  'NETWORK_ERROR',
  'UNKNOWN_ERROR',
])
export const integrationSyncStage = pgEnum('IntegrationSyncStage', [
  'IDLE', // Not currently syncing
  'MESSAGE_LIST_FETCH_PENDING', // Waiting for scanner to enqueue list-fetch job
  'MESSAGE_LIST_FETCH', // List-fetch job running, discovering message IDs
  'MESSAGES_IMPORT_PENDING', // IDs cached in Redis, waiting for import
  'MESSAGES_IMPORT', // Import job running, fetching content
  'FAILED', // Sync failed during execution
])
export const integrationSyncStatus = pgEnum('IntegrationSyncStatus', [
  'NOT_SYNCED', // Never synced
  'SYNCING', // Actively syncing right now
  'ACTIVE', // Last sync succeeded, idle
  'FAILED', // Last sync failed
])
export const integrationProviderType = pgEnum('IntegrationProviderType', [
  'google',
  'outlook',
  'facebook',
  'instagram',
  'openphone',
  'mailgun',
  'sms',
  'whatsapp',
  'chat',
  'email',
  'shopify',
  'imap',
])
export const invitationStatus = pgEnum('InvitationStatus', [
  'PENDING',
  'ACCEPTED',
  'EXPIRED',
  'CANCELLED',
])
export const invoiceStatus = pgEnum('InvoiceStatus', [
  'PENDING',
  'PAID',
  'VOID',
  'UNCOLLECTIBLE',
  'DRAFT',
])
export const jobStatus = pgEnum('JobStatus', [
  'PENDING',
  'PROCESSING',
  'COMPLETED_SUCCESS',
  'COMPLETED_PARTIAL',
  'COMPLETED_FAILURE',
  'FAILED',
  'RETRYING',
])
export const labelType = pgEnum('LabelType', ['system', 'user'])
export const mediaContentType = pgEnum('MEDIA_CONTENT_TYPE', [
  'EXTERNAL_VIDEO',
  'IMAGE',
  'MODEL_3D',
  'VIDEO',
])
export const meetingMessageMethod = pgEnum('MeetingMessageMethod', [
  'request',
  'reply',
  'cancel',
  'counter',
  'other',
])
export const messageType = pgEnum('MessageType', [
  'EMAIL',
  'FACEBOOK',
  'SMS',
  'WHATSAPP',
  'INSTAGRAM',
  'OPENPHONE',
  'CHAT',
])
export const modelType = pgEnum('ModelType', [
  'LLM',
  'TEXT_EMBEDDING',
  'RERANK',
  'TTS',
  'SPEECH2TEXT',
  'MODERATION',
  'VISION',
])
export const nodeExecutionStatus = pgEnum('NodeExecutionStatus', [
  'pending',
  'running',
  'succeeded',
  'failed',
  'exception',
  'skipped',
  'stopped',
  'waiting',
])
export const nodeTriggerSource = pgEnum('NodeTriggerSource', ['SINGLE_STEP', 'WORKFLOW_RUN'])
export const notificationType = pgEnum('NotificationType', [
  'COMMENT_MENTION',
  'COMMENT_REPLY',
  'COMMENT_REACTION',
  'TICKET_ASSIGNED',
  'TICKET_UPDATED',
  'TICKET_MENTIONED',
  'THREAD_ACTIVITY',
  'SYSTEM_MESSAGE',
  'WORKFLOW_APPROVAL_REQUIRED',
  'WORKFLOW_APPROVAL_REMINDER',
  'WORKFLOW_APPROVAL_COMPLETED',
])
export const orderAddressType = pgEnum('ORDER_ADDRESS_TYPE', ['SHIPPING', 'BILLING'])
export const orderCancelReason = pgEnum('ORDER_CANCEL_REASON', [
  'CUSTOMER',
  'DECLINED',
  'FRAUD',
  'INVENTORY',
  'OTHER',
  'STAFF',
])
export const orderFinancialStatus = pgEnum('ORDER_FINANCIAL_STATUS', [
  'AUTHORIZED',
  'EXPIRED',
  'PAID',
  'PARTIALLY_PAID',
  'PARTIALLY_REFUNDED',
  'PENDING',
  'REFUNDED',
  'VOIDED',
])
export const orderFulfillmentStatus = pgEnum('ORDER_FULFILLMENT_STATUS', [
  'FULFILLED',
  'IN_PROGRESS',
  'ON_HOLD',
  'OPEN',
  'PARTIALLY_FULFILLED',
  'PENDING_FULFILLMENT',
  'REQUEST_DECLINED',
  'RESTOCKED',
  'SCHEDULED',
  'UNFULFILLED',
])
export const orderReturnStatus = pgEnum('ORDER_RETURN_STATUS', [
  'INSPECTION_COMPLETED',
  'IN_PROGRESS',
  'NO_RETURN',
  'RETURNED',
  'RETURN_FAILED',
  'RETURN_REQUESTED',
])
export const organizationMemberStatus = pgEnum('OrganizationMemberStatus', ['ACTIVE', 'INACTIVE'])
export const organizationRole = pgEnum('OrganizationRole', ['OWNER', 'ADMIN', 'USER'])
export const organizationType = pgEnum('OrganizationType', ['INDIVIDUAL', 'TEAM'])
export const produdtStatus = pgEnum('PRODUDT_STATUS', ['ACTIVE', 'ARCHIVED', 'DRAFT'])
export const participantRole = pgEnum('ParticipantRole', ['FROM', 'TO', 'CC', 'BCC', 'REPLY_TO'])
export const proposedActionStatus = pgEnum('ProposedActionStatus', [
  'PENDING',
  'APPROVED',
  'REJECTED',
  'EXECUTED',
  'FAILED',
])
export const providerQuotaType = pgEnum('ProviderQuotaType', ['PAID', 'FREE', 'TRIAL'])
export const providerType = pgEnum('ProviderType', ['SYSTEM', 'CUSTOM'])
export const returnStatus = pgEnum('RETURN_STATUS', [
  'CANCELLED',
  'CLOSED',
  'DECLINED',
  'OPEN',
  'REQUESTED',
])
export const recipientRole = pgEnum('RecipientRole', ['FROM', 'TO', 'CC', 'BCC'])
export const scheduledMessageStatus = pgEnum('ScheduledMessageStatus', [
  'PENDING',
  'PROCESSING',
  'SENT',
  'FAILED',
  'CANCELLED',
])
export const responseStatus = pgEnum('ResponseStatus', [
  'DRAFT',
  'PENDING_APPROVAL',
  'APPROVED',
  'SCHEDULED',
  'SENDING',
  'SENT',
  'FAILED',
  'CANCELLED',
])
export const responseType = pgEnum('ResponseType', [
  'MANUAL',
  'TEMPLATE',
  'AI_GENERATED',
  'RULE_BASED',
  'HYBRID',
])
export const ruleGroupOperator = pgEnum('RuleGroupOperator', [
  'AND',
  'OR',
  'NOT',
  'XOR',
  'THRESHOLD',
])
export const ruleType = pgEnum('RuleType', [
  'STATIC',
  'CATEGORY',
  'AI',
  'SPAM_HANDLER',
  'RULE_GROUP',
  'SHOPIFY_AUTOMATION',
])
export const syncStatus = pgEnum('SYNC_STATUS', ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED'])
export const sendStatus = pgEnum('SendStatus', ['PENDING', 'SENT', 'FAILED'])
export const senderType = pgEnum('SenderType', [
  'INTERNAL_STAFF',
  'INTERNAL_SYSTEM',
  'PARTNER',
  'CUSTOMER',
  'VENDOR',
  'UNKNOWN_EXTERNAL',
])
export const sensitivity = pgEnum('Sensitivity', ['normal', 'private', 'personal', 'confidential'])
export const settingScope = pgEnum('SettingScope', [
  'APPEARANCE',
  'NOTIFICATION',
  'DASHBOARD',
  'COMMUNICATION',
  'SECURITY',
  'INTEGRATION',
  'GENERAL',
  'SIDEBAR',
  'RECORDING',
])
export const signatureSharingType = pgEnum('SignatureSharingType', [
  'PRIVATE',
  'ORGANIZATION_WIDE',
  'SPECIFIC_INTEGRATIONS',
])
export const snippetPermission = pgEnum('SnippetPermission', ['VIEW', 'EDIT'])
export const snippetSharingType = pgEnum('SnippetSharingType', [
  'PRIVATE',
  'ORGANIZATION',
  'GROUPS',
  'MEMBERS',
])
export const staticRuleType = pgEnum('StaticRuleType', [
  'SENDER_DOMAIN',
  'SENDER_ADDRESS',
  'RECIPIENT_PATTERN',
  'SUBJECT_MATCH',
  'BODY_KEYWORD',
  'HEADER_CHECK',
  'ATTACHMENT_TYPE',
  'COMBINED',
  'INTERNAL_EXTERNAL',
  'THREAD_BASED',
])
export const storageProvider = pgEnum('StorageProvider', [
  'S3',
  'GOOGLE_DRIVE',
  'DROPBOX',
  'ONEDRIVE',
  'BOX',
  'GENERIC_URL',
])
export const threadStatus = pgEnum('ThreadStatus', [
  'OPEN',
  'ARCHIVED',
  'ACTIVE',
  'RESOLVED',
  'PENDING',
  'CLOSED',
  'SPAM',
  'TRASH',
  'IGNORED',
])
export const threadType = pgEnum('ThreadType', ['EMAIL', 'CHAT'])
export const ticketPriority = pgEnum('TicketPriority', ['LOW', 'MEDIUM', 'HIGH', 'URGENT'])
export const ticketStatus = pgEnum('TicketStatus', [
  'OPEN',
  'IN_PROGRESS',
  'WAITING_FOR_CUSTOMER',
  'WAITING_FOR_THIRD_PARTY',
  'RESOLVED',
  'CLOSED',
  'CANCELLED',
  'MERGED',
])
export const ticketType = pgEnum('TicketType', [
  'GENERAL',
  'MISSING_ITEM',
  'RETURN',
  'REFUND',
  'PRODUCT_ISSUE',
  'SHIPPING_ISSUE',
  'BILLING',
  'TECHNICAL',
  'OTHER',
])
export const trialConversionStatus = pgEnum('TrialConversionStatus', [
  'TRIAL_ACTIVE',
  'CONVERTED_TO_PAID',
  'EXPIRED_WITHOUT_CONVERSION',
  'CANCELED_DURING_TRIAL',
  'MANUAL_CONVERSION',
])
export const userType = pgEnum('UserType', ['USER', 'SYSTEM'])
export const vectorDbType = pgEnum('VectorDbType', [
  'POSTGRESQL',
  'CHROMA',
  'QDRANT',
  'WEAVIATE',
  'PINECONE',
  'MILVUS',
])
export const workflowRunStatus = pgEnum('WorkflowRunStatus', [
  'RUNNING',
  'SUCCEEDED',
  'FAILED',
  'STOPPED',
  'WAITING',
])
export const workflowTriggerSource = pgEnum('WorkflowTriggerSource', [
  'DEBUGGING',
  'APP_RUN',
  'SINGLE_STEP',
  'PUBLIC_SHARE',
  'API_KEY',
  'WEBHOOK',
])

/**
 * Access mode for shared workflows (web access only)
 * API access is controlled separately via apiEnabled flag
 */
export const workflowShareAccessMode = pgEnum('WorkflowShareAccessMode', ['public', 'organization'])

// Import job status lifecycle
export const importJobStatus = pgEnum('ImportJobStatus', [
  'uploading', // File being uploaded (chunks in progress)
  'ingesting', // Processing uploaded data, hashing values
  'waiting', // Waiting for user to complete mappings
  'planning', // Generating import plan
  'ready', // Plan complete, awaiting confirmation
  'executing', // Import in progress
  'completed', // Import finished successfully
  'failed', // Import failed
  'canceled', // User canceled
])

// Import plan status
export const importPlanStatus = pgEnum('ImportPlanStatus', [
  'planning', // Analyzing rows
  'planned', // Analysis complete
  'executing', // Running import
  'completed', // Finished
])

// Strategy status within a plan
export const importStrategyStatus = pgEnum('ImportStrategyStatus', [
  'planning_queued',
  'planning',
  'planned',
  'executing',
  'completed',
])

// Strategy type (what to do with a row)
export const importStrategyType = pgEnum('ImportStrategyType', ['create', 'update', 'skip'])

// Resolution status for a value
export const importResolutionStatus = pgEnum('ImportResolutionStatus', [
  'pending',
  'valid',
  'error',
  'warning',
  'create', // Will create new (for select:create, relation:create)
])

// Plan row execution status
export const importPlanRowStatus = pgEnum('ImportPlanRowStatus', [
  'planned',
  'executing',
  'completed',
  'failed',
])

// Mapping property target type
export const importMappingTargetType = pgEnum('ImportMappingTargetType', [
  'particle', // Maps to a field
  'relation', // Maps to a relation
  'skip', // Skip this column
])

// Calendar / meeting platform
export const calendarProvider = pgEnum('CalendarProvider', ['google', 'outlook'])
export const meetingPlatform = pgEnum('MeetingPlatform', [
  'google_meet',
  'teams',
  'zoom',
  'unknown',
])
export const calendarEventStatus = pgEnum('CalendarEventStatus', [
  'confirmed',
  'tentative',
  'cancelled',
])
export const rsvpStatus = pgEnum('RsvpStatus', [
  'accepted',
  'declined',
  'tentative',
  'needs_action',
])

// Recording
export const recordingProvider = pgEnum('RecordingProvider', ['recall', 'babl', 'self_hosted'])
export const recordingStatus = pgEnum('RecordingStatus', [
  'created',
  'joining',
  'waiting',
  'admitted',
  'recording',
  'processing',
  'completed',
  'failed',
  'kicked',
  'denied',
  'timeout',
  'cancelled',
])

// Transcription
export const transcriptType = pgEnum('TranscriptType', ['realtime', 'async'])
export const transcriptStatus = pgEnum('TranscriptStatus', ['processing', 'completed', 'failed'])

// Insights
export const insightTemplateStatus = pgEnum('InsightTemplateStatus', [
  'enabled',
  'disabled',
  'archived',
])
export const insightStatus = pgEnum('InsightStatus', ['processing', 'completed', 'failed'])

// AI post-processing
export const aiProcessingStatus = pgEnum('AiProcessingStatus', [
  'pending',
  'processing',
  'completed',
  'failed',
])

export { sql } from 'drizzle-orm'
// Re-export builders and sql for consumers
export {
  type AnyPgColumn,
  bigint,
  bigserial,
  boolean,
  date,
  doublePrecision,
  foreignKey,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  varchar,
  vector,
} from 'drizzle-orm/pg-core'
