// packages/database/src/db/schema/account.ts
// Drizzle table: account (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, pgTable, text, timestamp, uniqueIndex } from './_shared'

import { User } from './user'

/** Drizzle table for account */
export const account = pgTable(
  'account',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    providerId: text().notNull(),
    accountId: text().notNull(),
    refreshToken: text(),
    accessToken: text(),
    accessTokenExpiresAt: timestamp({ precision: 3 }),
    refreshTokenExpiresAt: timestamp({ precision: 3 }),
    tokenType: text('token_type'),
    scope: text(),
    idToken: text(),
    sessionState: text('session_state'),
    lastHistoryId: text(),
    password: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => [
    uniqueIndex('account_providerId_accountId_key').using(
      'btree',
      table.providerId.asc().nullsLast(),
      table.accountId.asc().nullsLast()
    ),
  ]
)
