// packages/database/src/db/schema/address.ts
// Drizzle table: address (generated by scripts/split-schema.ts)

import {
  pgTable,
  index,
  text,
  bigint,
  doublePrecision,
  type AnyPgColumn,
  orderAddressType,
} from './_shared'

import { shopify_customers } from './shopify-customers'
import { ShopifyIntegration } from './shopify-integration'
import { Organization } from './organization'

/** Drizzle table for address */
export const Address = pgTable(
  'Address',
  {
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    id: bigint({ mode: 'number' }).primaryKey().notNull(),
    address1: text(),
    address2: text(),
    city: text(),
    company: text(),
    countryCode: text(),
    firstName: text(),
    lastName: text(),
    latitude: doublePrecision(),
    longitude: doublePrecision(),
    name: text(),
    phone: text(),
    provinceCode: text(),
    zip: text(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    customerId: bigint({ mode: 'number' }).references((): AnyPgColumn => shopify_customers.id, {
      onUpdate: 'cascade',
    }),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    orderId: bigint({ mode: 'number' }),
    orderType: orderAddressType(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    integrationId: text()
      .notNull()
      .references((): AnyPgColumn => ShopifyIntegration.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
  },
  (table) => [
    index('Address_customerId_idx').using('btree', table.customerId.asc().nullsLast()),
    index('Address_orderId_idx').using('btree', table.orderId.asc().nullsLast()),
  ]
)
