// packages/database/src/db/schema/ai-usage.ts
// Drizzle table: aiUsage (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  credentialSource,
  doublePrecision,
  index,
  integer,
  pgTable,
  providerType,
  text,
  timestamp,
} from './_shared'

import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for aiUsage */
export const AiUsage = pgTable(
  'AiUsage',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    provider: text().notNull(),
    model: text().notNull(),
    totalTokens: integer().default(0).notNull(),
    cost: doublePrecision(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    userId: text().references((): AnyPgColumn => User.id, { onUpdate: 'cascade' }),
    endpoint: text(),
    inputTokens: integer().default(0).notNull(),
    modelType: text().default('llm').notNull(),
    outputTokens: integer().default(0).notNull(),
    requestId: text(),
    responseTime: integer(),
    /** Credits consumed for this request (default 1 for system providers) */
    creditsUsed: integer().default(1),
    /** Which credential type was used: SYSTEM (platform-provided) or CUSTOM (user-provided API key) */
    providerType: providerType('providerType'),
    /** Detailed credential source: SYSTEM, CUSTOM, MODEL_SPECIFIC, or LOAD_BALANCED */
    credentialSource: credentialSource('credentialSource'),
    /** Source of the AI usage: compose, workflow, dataset, chat, other */
    source: text(),
    /** ID of the source entity (workflow ID, dataset ID, etc.) if applicable */
    sourceId: text(),
  },
  (table) => [
    index('AiUsage_createdAt_idx').using('btree', table.createdAt.asc().nullsLast()),
    index('AiUsage_organizationId_createdAt_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.createdAt.asc().nullsLast()
    ),
    index('AiUsage_provider_model_idx').using(
      'btree',
      table.provider.asc().nullsLast(),
      table.model.asc().nullsLast()
    ),
    index('AiUsage_source_idx').using('btree', table.source.asc().nullsLast()),
  ]
)
