// packages/database/src/db/schema/api-key.ts
// Drizzle table: apiKey (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, boolean, index, pgTable, text, timestamp, uniqueIndex } from './_shared'

import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for apiKey */
export const ApiKey = pgTable(
  'ApiKey',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    name: text(),
    hashedKey: text().notNull(),
    isActive: boolean().default(true).notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text().references((): AnyPgColumn => Organization.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    /** Type of API key: 'app' for traditional org-level, 'workflow' for workflow-scoped, 'chat' for chat-widget JWT signing */
    type: text().default('app').notNull(),
    /** Reference ID (workflowAppId when type='workflow', channelId/integrationId when type='chat', null for 'app') */
    referenceId: text(),
    /**
     * AES-256-GCM encrypted plaintext secret (via `CredentialService.encrypt`).
     * Set for `type='chat'` only — HS256 JWT verification needs the original
     * secret, which a one-way `hashedKey` cannot recover. Null for other types
     * where bearer-token comparison against `hashedKey` is sufficient.
     */
    encryptedSecret: text(),
  },
  (table) => [
    uniqueIndex('ApiKey_hashedKey_key').using('btree', table.hashedKey.asc().nullsLast()),
    index('ApiKey_userId_isActive_idx').using(
      'btree',
      table.userId.asc().nullsLast(),
      table.isActive.asc().nullsLast()
    ),
    index('ApiKey_type_referenceId_idx').using(
      'btree',
      table.type.asc().nullsLast(),
      table.referenceId.asc().nullsLast()
    ),
  ]
)
