// packages/database/src/db/schema/app-webhook-handler.ts
// Drizzle table for app webhook handlers

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  index,
  pgTable,
  sql,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'
import { AppInstallation } from './app-installation'
import { Credential } from './credential'
import { DataConnector } from './data-connector'

/** Drizzle table for AppWebhookHandler */
export const AppWebhookHandler = pgTable(
  'AppWebhookHandler',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),

    // Which app installation owns this webhook. NULL for a built-in data-connector
    // webhook (generic-rest / Shopify / Stripe) — those have no installation and are
    // bound via `dataConnectorId` instead (Step 8 — webhook ingress).
    appInstallationId: text().references((): AnyPgColumn => AppInstallation.id, {
      onDelete: 'cascade',
    }),

    // Which data connector owns this webhook (Step 8). Set for built-in connector
    // webhooks (NULL `appInstallationId`); app-connector webhooks carry both.
    dataConnectorId: text().references((): AnyPgColumn => DataConnector.id, {
      onDelete: 'cascade',
    }),

    // Connection (Credential) this webhook is scoped to
    connectionId: text().references((): AnyPgColumn => Credential.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),

    // Webhook handler identifier (e.g., "prospect-updated")
    handlerId: text().notNull(), // From filename: prospect-updated.webhook.ts

    // Public webhook URL (generated by platform)
    url: text().notNull(), // https://auxx.ai/api/webhooks/{installationId}/{handlerId}

    // External webhook ID (from third-party service)
    // Used to delete webhook when connection is removed
    externalWebhookId: text(),

    // Maps to WorkflowTrigger.id from the app definition
    // Binds this webhook handler to a specific app trigger for workflow dispatch
    triggerId: text(),

    // Additional metadata from extension
    metadata: text(), // JSON string

    // Status
    isActive: boolean().default(true).notNull(),

    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    // One webhook handler per installation + handler ID + connection
    uniqueIndex('AppWebhookHandler_unique_idx').using(
      'btree',
      table.appInstallationId.asc().nullsLast(),
      table.handlerId.asc().nullsLast(),
      table.connectionId.asc().nullsLast()
    ),
    // One handler per (connector, handlerId/topic) for built-in connector webhooks.
    // Partial — NULLs are distinct in a plain unique index, so the index above can't
    // enforce this for the connector rows (Step 8).
    uniqueIndex('AppWebhookHandler_connector_unique_idx')
      .using('btree', table.dataConnectorId.asc().nullsLast(), table.handlerId.asc().nullsLast())
      .where(sql`${table.dataConnectorId} IS NOT NULL`),
    // One handler per (connection, handlerId) for the unified connection-scoped
    // webhook ingress — the rows that have neither an installation nor a connector
    // (webhook-triggers landing on a connection). Partial so it doesn't collide
    // with the app/connector rows above (NULLs are distinct in a plain unique idx).
    uniqueIndex('AppWebhookHandler_connection_unique_idx')
      .using('btree', table.connectionId.asc().nullsLast(), table.handlerId.asc().nullsLast())
      .where(
        sql`${table.appInstallationId} IS NULL AND ${table.dataConnectorId} IS NULL AND ${table.connectionId} IS NOT NULL`
      ),
    index('AppWebhookHandler_appInstallationId_idx').using(
      'btree',
      table.appInstallationId.asc().nullsLast()
    ),
    index('AppWebhookHandler_dataConnectorId_idx').using(
      'btree',
      table.dataConnectorId.asc().nullsLast()
    ),
  ]
)
