// packages/database/src/db/schema/app-webhook-handler.ts
// Drizzle table for app webhook handlers

import {
  pgTable,
  text,
  timestamp,
  boolean,
  uniqueIndex,
  index,
  type AnyPgColumn,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'
import { AppInstallation } from './app-installation'

/** Drizzle table for AppWebhookHandler */
export const AppWebhookHandler = pgTable(
  'AppWebhookHandler',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),

    // Which app installation owns this webhook
    appInstallationId: text()
      .notNull()
      .references((): AnyPgColumn => AppInstallation.id, { onDelete: 'cascade' }),

    // Webhook handler identifier (e.g., "prospect-updated")
    handlerId: text().notNull(), // From filename: prospect-updated.webhook.ts

    // Public webhook URL (generated by platform)
    url: text().notNull(), // https://auxx.ai/api/webhooks/{installationId}/{handlerId}

    // External webhook ID (from third-party service)
    // Used to delete webhook when connection is removed
    externalWebhookId: text(),

    // Additional metadata from extension
    metadata: text(), // JSON string

    // Status
    isActive: boolean().default(true).notNull(),

    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    // One webhook handler per installation + handler ID
    uniqueIndex('AppWebhookHandler_unique_idx').using(
      'btree',
      table.appInstallationId.asc().nullsLast(),
      table.handlerId.asc().nullsLast()
    ),
    index('AppWebhookHandler_appInstallationId_idx').using(
      'btree',
      table.appInstallationId.asc().nullsLast()
    ),
  ]
)
