// packages/database/src/db/schema/approval-response.ts
// Drizzle table: approvalResponse (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  timestamp,
  type AnyPgColumn,
  approvalAction,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { ApprovalRequest } from './approval-request'
import { User } from './user'

/** Drizzle table for approvalResponse */
export const ApprovalResponse = pgTable(
  'ApprovalResponse',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    approvalRequestId: text()
      .notNull()
      .references((): AnyPgColumn => ApprovalRequest.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'restrict' }),
    action: approvalAction().notNull(),
    comment: text(),
    respondedAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    responseMethod: text().notNull(),
    ipAddress: text(),
    userAgent: text(),
  },
  (table) => [
    uniqueIndex('ApprovalResponse_approvalRequestId_userId_key').using(
      'btree',
      table.approvalRequestId.asc().nullsLast(),
      table.userId.asc().nullsLast()
    ),
    index('ApprovalResponse_userId_idx').using('btree', table.userId.asc().nullsLast()),
  ]
)
