// packages/database/src/db/schema/approval-request.ts
// Drizzle table: approvalRequest (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import type { ResourcePermission } from '../../enums'
import {
  type AnyPgColumn,
  approvalKind,
  approvalStatus,
  check,
  index,
  jsonb,
  pgTable,
  sql,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'
import { Organization } from './organization'
import { User } from './user'
import { Workflow } from './workflow'
import { WorkflowRun } from './workflow-run'

/**
 * Drizzle table for approvalRequest — the shared approval spine for TWO kinds
 * (plan 28 §1):
 *
 * - `kind: 'workflow'` — the human-confirmation node. Carries
 *   `workflowId`/`workflowRunId`/`nodeId`/`nodeName`.
 * - `kind: 'access'` — a member asking for permission. Carries
 *   `requesterId`/`targetKind`/`entityDefinitionId`/`entityInstanceId`/`area` and
 *   the requested/granted level (+ lens, for mail-sharing definitions).
 *
 * The two kinds share `status`, `assigneeUsers[]`, `assigneeGroups[]`,
 * `expiresAt`, `metadata`, `ApprovalResponse` rows, the pending list and the
 * badge count. `subjectLabel` (was `workflowName`) is the denormalized display
 * string both kinds render — for a DENIED access requester it is the only way to
 * see what they asked for, since they never got access to hydrate the target.
 */
export const ApprovalRequest = pgTable(
  'ApprovalRequest',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    /** Which lane this row belongs to. Defaults to `workflow` so existing rows backfill. */
    kind: approvalKind().default('workflow').notNull(),
    // ── workflow-only columns (nullable since plan 28 §3) ──
    workflowId: text().references((): AnyPgColumn => Workflow.id, {
      onUpdate: 'cascade',
      onDelete: 'restrict',
    }),
    workflowRunId: text().references((): AnyPgColumn => WorkflowRun.id, {
      onUpdate: 'cascade',
      onDelete: 'restrict',
    }),
    nodeId: text(),
    /**
     * Deliberately NOT generalized alongside `workflowName` (plan 28 §3.1): its
     * access-request counterpart would be the type noun, which is already
     * derivable from `entityDefinitionId`. Workflow-only.
     */
    nodeName: text(),
    status: approvalStatus().default('pending').notNull(),
    message: text(),
    assigneeUsers: text().array(),
    assigneeGroups: text().array(),
    /**
     * Denormalized display label, NOT NULL for both kinds (plan 28 §3.1).
     * Snapshot semantics: live wins when the reader can hydrate the subject, this
     * is the fallback and the durability guarantee (subject renamed, deleted, or
     * the reader has no access).
     */
    subjectLabel: text().notNull(),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    // ── access-only columns (all nullable) ──
    /**
     * Who is asking. Redundant with `createdById` for today's self-service flow,
     * but explicit: a future admin-filed-on-behalf-of request separates the two.
     */
    requesterId: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    /** `'instance' | 'area' | 'def'`. */
    targetKind: text(),
    /** instance/def kinds. For mail-sharing defs this is the entity SLUG (`thread`). */
    entityDefinitionId: text(),
    /** instance kind only. */
    entityInstanceId: text(),
    /** area kind only — an `Area` registry key. */
    area: text(),
    requestedLevel: text().$type<ResourcePermission>(),
    grantedLevel: text().$type<ResourcePermission>(),
    /**
     * Mail visibility lens asked for / written (plan 42 §2.1). Set only for a
     * mail-sharing definition; mirrors `ResourceAccess.lens`'s
     * TypeScript-over-`text` representation rather than inventing a DB enum.
     */
    requestedLens: text().$type<'metadata' | 'subject' | 'full'>(),
    grantedLens: text().$type<'metadata' | 'subject' | 'full'>(),
    metadata: jsonb(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    expiresAt: timestamp({ precision: 3 }),
  },
  (table) => [
    index('ApprovalRequest_createdById_idx').using('btree', table.createdById.asc().nullsLast()),
    index('ApprovalRequest_organizationId_assigneeGroups_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.assigneeGroups.asc().nullsLast()
    ),
    index('ApprovalRequest_organizationId_assigneeUsers_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.assigneeUsers.asc().nullsLast()
    ),
    index('ApprovalRequest_organizationId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
    index('ApprovalRequest_status_expiresAt_idx').using(
      'btree',
      table.status.asc().nullsLast(),
      table.expiresAt.asc().nullsLast()
    ),
    index('ApprovalRequest_workflowRunId_idx').using(
      'btree',
      table.workflowRunId.asc().nullsLast()
    ),
    // ── Dedup: ONE open access request per (org, requester, target) ──
    //
    // Deliberately THREE target-specific partial indexes rather than one index
    // over all three nullable target columns (plan 42 §2.2): PostgreSQL treats
    // NULLs as distinct in a unique index, and every target shape leaves at
    // least one of `area` / `entityDefinitionId` / `entityInstanceId` null — so
    // the single-index form deduplicates nothing.
    //
    // `requestedLevel` / `requestedLens` are deliberately NOT in the identity:
    // with them, "give me view" and "actually give me edit" are two rows rather
    // than an upgrade, and the dedup never fires for the case it exists to
    // catch. A re-request updates the existing row UPWARD and re-notifies.
    uniqueIndex('ApprovalRequest_access_area_pending_key')
      .on(table.organizationId, table.requesterId, table.area)
      .where(sql`kind = 'access' AND status = 'pending' AND "targetKind" = 'area'`),
    uniqueIndex('ApprovalRequest_access_def_pending_key')
      .on(table.organizationId, table.requesterId, table.entityDefinitionId)
      .where(sql`kind = 'access' AND status = 'pending' AND "targetKind" = 'def'`),
    uniqueIndex('ApprovalRequest_access_instance_pending_key')
      .on(table.organizationId, table.requesterId, table.entityDefinitionId, table.entityInstanceId)
      .where(sql`kind = 'access' AND status = 'pending' AND "targetKind" = 'instance'`),
    // The workflow columns are present iff this is a workflow row.
    check(
      'ApprovalRequest_workflow_columns_check',
      sql`(${table.kind} = 'workflow') = (${table.workflowRunId} IS NOT NULL)`
    ),
    // An access row HAS a target kind and a requester, and a workflow row has
    // neither. This is what makes the three shape checks below load-bearing.
    //
    // Without it they are all evadable, because a CHECK is violated only when its
    // expression is FALSE — NULL passes. `targetKind IS NULL` makes every
    // `${table.targetKind} <> '<shape>'` comparison NULL, so an access row with a
    // null `targetKind` satisfies all three shape checks AND matches none of the
    // three partial unique indexes (each requires an equality on `targetKind`).
    // Net: dedup silently bypassed — the exact failure the shape checks were
    // added to prevent (plan 42 §2.2). `requesterId` rides along for the same
    // reason: it is in all three index key lists, and NULLs are distinct there.
    check(
      'ApprovalRequest_access_columns_check',
      sql`(${table.kind} = 'access') = (${table.targetKind} IS NOT NULL AND ${table.requesterId} IS NOT NULL)`
    ),
    // The three access target shapes, so a malformed row cannot evade the
    // corresponding partial index above by leaving the wrong column populated.
    check(
      'ApprovalRequest_access_area_shape_check',
      sql`${table.targetKind} <> 'area' OR (${table.area} IS NOT NULL AND ${table.entityDefinitionId} IS NULL AND ${table.entityInstanceId} IS NULL)`
    ),
    check(
      'ApprovalRequest_access_def_shape_check',
      sql`${table.targetKind} <> 'def' OR (${table.entityDefinitionId} IS NOT NULL AND ${table.entityInstanceId} IS NULL AND ${table.area} IS NULL)`
    ),
    check(
      'ApprovalRequest_access_instance_shape_check',
      sql`${table.targetKind} <> 'instance' OR (${table.entityDefinitionId} IS NOT NULL AND ${table.entityInstanceId} IS NOT NULL AND ${table.area} IS NULL)`
    ),
  ]
)

export type ApprovalRequestEntity = typeof ApprovalRequest.$inferSelect
export type CreateApprovalRequestInput = typeof ApprovalRequest.$inferInsert
export type UpdateApprovalRequestInput = Partial<CreateApprovalRequestInput>
