// packages/database/src/db/schema/approval-request.ts
// Drizzle table: approvalRequest (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, approvalStatus, index, jsonb, pgTable, text, timestamp } from './_shared'
import { Organization } from './organization'
import { User } from './user'
import { Workflow } from './workflow'
import { WorkflowRun } from './workflow-run'

/** Drizzle table for approvalRequest */
export const ApprovalRequest = pgTable(
  'ApprovalRequest',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    workflowId: text()
      .notNull()
      .references((): AnyPgColumn => Workflow.id, { onUpdate: 'cascade', onDelete: 'restrict' }),
    workflowRunId: text()
      .notNull()
      .references((): AnyPgColumn => WorkflowRun.id, { onUpdate: 'cascade', onDelete: 'restrict' }),
    nodeId: text().notNull(),
    nodeName: text().notNull(),
    status: approvalStatus().default('pending').notNull(),
    message: text(),
    assigneeUsers: text().array(),
    assigneeGroups: text().array(),
    workflowName: text().notNull(),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    metadata: jsonb(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    expiresAt: timestamp({ precision: 3 }),
  },
  (table) => [
    index('ApprovalRequest_createdById_idx').using('btree', table.createdById.asc().nullsLast()),
    index('ApprovalRequest_organizationId_assigneeGroups_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.assigneeGroups.asc().nullsLast()
    ),
    index('ApprovalRequest_organizationId_assigneeUsers_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.assigneeUsers.asc().nullsLast()
    ),
    index('ApprovalRequest_organizationId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
    index('ApprovalRequest_status_expiresAt_idx').using(
      'btree',
      table.status.asc().nullsLast(),
      table.expiresAt.asc().nullsLast()
    ),
    index('ApprovalRequest_workflowRunId_idx').using(
      'btree',
      table.workflowRunId.asc().nullsLast()
    ),
  ]
)
