// packages/database/src/db/schema/article-revision.ts
// Drizzle table: articleRevision (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  index,
  integer,
  jsonb,
  pgTable,
  sql,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from './_shared'

import { Article } from './article'
import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for articleRevision */
export const ArticleRevision = pgTable(
  'ArticleRevision',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    articleId: text()
      .notNull()
      .references((): AnyPgColumn => Article.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    versionNumber: integer(),
    label: text(),
    title: varchar({ length: 255 }).notNull(),
    description: text(),
    excerpt: text(),
    emoji: text(),
    content: text().notNull(),
    contentJson: jsonb(),
    editorId: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    index('ArticleRevision_articleId_idx').using('btree', table.articleId.asc().nullsLast()),
    uniqueIndex('ArticleRevision_articleId_versionNumber_key')
      .using('btree', table.articleId.asc(), table.versionNumber.desc().nullsLast())
      .where(sql`"versionNumber" IS NOT NULL`),
  ]
)
