// packages/database/src/db/schema/article.ts
// Drizzle table: article (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  articleKind,
  articleStatus,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  sql,
  text,
  timestamp,
} from './_shared'
import { ArticleRevision } from './article-revision'
import { KnowledgeBase } from './knowledge-base'
import { KnowledgeSource } from './knowledge-source'
import { Organization } from './organization'
import { User } from './user'

/**
 * Drizzle table for article — pure content (canonical, embeds once).
 *
 * Tree placement and per-KB publish state live on {@link ArticlePlacement}, so
 * one article can appear in multiple KnowledgeBases at different positions. The
 * working draft (`draftRevisionId`) stays here — it's the single source of truth
 * for content; placements only point at the *published* revision they expose.
 */
export const Article = pgTable(
  'Article',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    articleKind: articleKind().default('page').notNull(),
    authorId: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    status: articleStatus().default('DRAFT').notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    archivedAt: timestamp('archived_at', { precision: 3, withTimezone: true }),
    lastReviewedAt: timestamp({ precision: 3 }),
    viewsCount: integer().default(0).notNull(),
    title: text(),
    excerpt: text(),
    emoji: text(),
    color: text(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    /**
     * Canonical embedding/dataset owner. Content embeds once into this KB's
     * managed Dataset; search of any KB the article is *placed* into federates
     * to this dataset. For a simple native article this equals its sole
     * placement's `knowledgeBaseId`. Provenance, not tree placement.
     */
    homeKnowledgeBaseId: text()
      .notNull()
      .references((): AnyPgColumn => KnowledgeBase.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
    draftRevisionId: text().references((): AnyPgColumn => ArticleRevision.id, {
      onUpdate: 'cascade',
    }),
    aiEnabled: boolean().default(true).notNull(),
    /**
     * Source provenance (content-level). Set when this article's *content* was
     * ingested from a KnowledgeSource. Distinct from tree placement: link-ness of a
     * *position* lives on {@link ArticlePlacement.linkedFromSourceId}.
     *   hand-authored ⇒ sourceId=null, managed=false
     *   synced        ⇒ sourceId=X,    managed=true  (Locked/read-only)
     *   detached      ⇒ sourceId=X,    managed=false (keeps provenance; re-sync skips)
     */
    sourceId: text().references((): AnyPgColumn => KnowledgeSource.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    /** Stable id at source: normalized URL / shopify GID / file checksum / manual key. */
    sourceExternalId: text(),
    /** Last-synced content hash — skip unchanged items on re-sync. */
    sourceContentHash: text(),
    /** true = Locked (source-owned, read-only); flips false on detach. */
    managed: boolean().default(false).notNull(),
    /**
     * Learned-KB audit trail: append-only capped list of
     * `{ threadId, extractedAt, suggestionId }` recording which threads taught
     * this article. Null for everything outside the learned KB. Audit only —
     * dedupe lives on `Thread.learnedExtractedAt`.
     */
    learnedProvenance: jsonb(),
    /**
     * Ranked free-text search corpus: the article's title, excerpt and the
     * plain text of its draft revision's body — tags stripped,
     * `<script>`/`<style>` blocks removed, whitespace collapsed and **bounded**.
     *
     * Maintained by `kb/article-search-text.ts`, which is the single definition
     * of the expression; `kb/sync-article-denormalized-fields.ts` (the one hook
     * every revision-write path already calls) splices it into the same UPDATE
     * that denormalizes `title`/`excerpt`/`emoji`/`color`, and migration
     * `070-backfill-article-search-text` fills in the existing rows.
     *
     * The bound is not optional: `to_tsvector` **errors** past 1 MB of input
     * ("string is too long for tsvector"), which fails the write rather than
     * degrading the search.
     */
    searchText: text(),
  },
  (table) => [
    index('Article_articleKind_idx').using('btree', table.articleKind.asc().nullsLast()),
    index('Article_homeKnowledgeBaseId_idx').using(
      'btree',
      table.homeKnowledgeBaseId.asc().nullsLast()
    ),
    index('Article_title_idx').using('btree', table.title.asc().nullsLast()),
    index('Article_archived_at_idx').using('btree', table.archivedAt.asc().nullsLast()),
    index('Article_source_idx').using(
      'btree',
      table.sourceId.asc().nullsLast(),
      table.sourceExternalId.asc().nullsLast()
    ),
    // ── Ranked free-text search ───────────────────────────────────────────────
    // Org-scoped composite GIN, the same strategy migration 0058 uses for
    // EntityInstance and 0320 for Thread. `organizationId` leads because the
    // system-resource list query always filters on it, which is what lets one
    // index serve both the scope and the match.
    //
    // ⚠️ The `to_tsvector(...)` expression must stay byte-identical to the one
    // `search/text-search-sql.ts` emits (`'english'::regconfig`, `COALESCE(x,'')`)
    // — a differing config or a dropped COALESCE silently stops matching the
    // index expression and forces a sequential scan.
    index('Article_org_searchText_gin_idx').using(
      'gin',
      table.organizationId,
      sql`to_tsvector('english'::regconfig, COALESCE("searchText", ''))`
    ),
    // Backs BOTH remaining arms of the OR block: the trigram (typo-tolerance)
    // `title % q` arm and the `title ILIKE '%q%'` fallback. `gin_trgm_ops` serves
    // `~~*` as well as `%`, never a bare `similarity(a,b) > k` call. Without it
    // the ILIKE arm has no index condition and Postgres abandons the GIN index
    // above too — an OR block is only as indexable as its worst arm.
    index('Article_org_title_trgm_idx').using(
      'gin',
      table.organizationId,
      table.title.op('gin_trgm_ops')
    ),
  ]
)
