// packages/database/src/db/schema/article.ts
// Drizzle table: article (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  articleKind,
  articleStatus,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
} from './_shared'
import { ArticleRevision } from './article-revision'
import { KnowledgeBase } from './knowledge-base'
import { KnowledgeSource } from './knowledge-source'
import { Organization } from './organization'
import { User } from './user'

/**
 * Drizzle table for article — pure content (canonical, embeds once).
 *
 * Tree placement and per-KB publish state live on {@link ArticlePlacement}, so
 * one article can appear in multiple KnowledgeBases at different positions. The
 * working draft (`draftRevisionId`) stays here — it's the single source of truth
 * for content; placements only point at the *published* revision they expose.
 */
export const Article = pgTable(
  'Article',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    articleKind: articleKind().default('page').notNull(),
    authorId: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    status: articleStatus().default('DRAFT').notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    archivedAt: timestamp('archived_at', { precision: 3, withTimezone: true }),
    lastReviewedAt: timestamp({ precision: 3 }),
    viewsCount: integer().default(0).notNull(),
    title: text(),
    excerpt: text(),
    emoji: text(),
    color: text(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    /**
     * Canonical embedding/dataset owner. Content embeds once into this KB's
     * managed Dataset; search of any KB the article is *placed* into federates
     * to this dataset. For a simple native article this equals its sole
     * placement's `knowledgeBaseId`. Provenance, not tree placement.
     */
    homeKnowledgeBaseId: text()
      .notNull()
      .references((): AnyPgColumn => KnowledgeBase.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
    draftRevisionId: text().references((): AnyPgColumn => ArticleRevision.id, {
      onUpdate: 'cascade',
    }),
    aiEnabled: boolean().default(true).notNull(),
    /**
     * Source provenance (content-level). Set when this article's *content* was
     * ingested from a KnowledgeSource. Distinct from tree placement: link-ness of a
     * *position* lives on {@link ArticlePlacement.linkedFromSourceId}.
     *   hand-authored ⇒ sourceId=null, managed=false
     *   synced        ⇒ sourceId=X,    managed=true  (Locked/read-only)
     *   detached      ⇒ sourceId=X,    managed=false (keeps provenance; re-sync skips)
     */
    sourceId: text().references((): AnyPgColumn => KnowledgeSource.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    /** Stable id at source: normalized URL / shopify GID / file checksum / manual key. */
    sourceExternalId: text(),
    /** Last-synced content hash — skip unchanged items on re-sync. */
    sourceContentHash: text(),
    /** true = Locked (source-owned, read-only); flips false on detach. */
    managed: boolean().default(false).notNull(),
    /**
     * Learned-KB audit trail: append-only capped list of
     * `{ threadId, extractedAt, suggestionId }` recording which threads taught
     * this article. Null for everything outside the learned KB. Audit only —
     * dedupe lives on `Thread.learnedExtractedAt`.
     */
    learnedProvenance: jsonb(),
  },
  (table) => [
    index('Article_articleKind_idx').using('btree', table.articleKind.asc().nullsLast()),
    index('Article_homeKnowledgeBaseId_idx').using(
      'btree',
      table.homeKnowledgeBaseId.asc().nullsLast()
    ),
    index('Article_title_idx').using('btree', table.title.asc().nullsLast()),
    index('Article_archived_at_idx').using('btree', table.archivedAt.asc().nullsLast()),
    index('Article_source_idx').using(
      'btree',
      table.sourceId.asc().nullsLast(),
      table.sourceExternalId.asc().nullsLast()
    ),
  ]
)
