// packages/database/src/db/schema/article.ts
// Drizzle table: article (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  boolean,
  timestamp,
  integer,
  jsonb,
  varchar,
  vector,
  type AnyPgColumn,
  articleStatus,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'
import { KnowledgeBase } from './knowledge-base'
import { Organization } from './organization'

/** Drizzle table for article */
export const Article = pgTable(
  'Article',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    title: varchar({ length: 255 }).notNull(),
    description: text(),
    emoji: text(),
    slug: text().notNull(),
    content: text().notNull(),
    contentJson: jsonb(),
    excerpt: text(),
    isCategory: boolean().default(false).notNull(),
    authorId: text().references((): AnyPgColumn => User.id, { onUpdate: 'cascade' }),
    status: articleStatus().default('DRAFT').notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    lastReviewedAt: timestamp({ precision: 3 }),
    viewsCount: integer().default(0).notNull(),
    knowledgeBaseId: text()
      .notNull()
      .references((): AnyPgColumn => KnowledgeBase.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    parentId: text().references((): AnyPgColumn => Article.id, { onUpdate: 'cascade' }),
    order: integer().default(0).notNull(),
    isPublished: boolean().default(false).notNull(),
    publishedAt: timestamp({ precision: 3 }),
    isHomePage: boolean().default(false).notNull(),
    embedding: vector({ dimensions: 1536 }),
  },
  (table) => [
    index('Article_isCategory_idx').using('btree', table.isCategory.asc().nullsLast()),
    index('Article_knowledgeBaseId_idx').using('btree', table.knowledgeBaseId.asc().nullsLast()),
    uniqueIndex('Article_knowledgeBaseId_slug_key').using(
      'btree',
      table.knowledgeBaseId.asc().nullsLast(),
      table.slug.asc().nullsLast()
    ),
    index('Article_parentId_idx').using('btree', table.parentId.asc().nullsLast()),
  ]
)
