// packages/database/src/db/schema/attachment.ts
// Drizzle table: attachment (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, integer, pgTable, text, timestamp, uniqueIndex } from './_shared'
import { FileVersion } from './file-version'
import { FolderFile } from './folder-file'
import { MediaAsset } from './media-asset'
import { MediaAssetVersion } from './media-asset-version'
import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for attachment */
export const Attachment = pgTable(
  'Attachment',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    entityType: text().notNull(),
    entityId: text().notNull(),
    role: text().default('ATTACHMENT').notNull(),
    title: text(),
    caption: text(),
    sort: integer().default(0).notNull(),
    fileId: text().references((): AnyPgColumn => FolderFile.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    fileVersionId: text().references((): AnyPgColumn => FileVersion.id, { onUpdate: 'cascade' }),
    assetId: text().references((): AnyPgColumn => MediaAsset.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    assetVersionId: text().references((): AnyPgColumn => MediaAssetVersion.id, {
      onUpdate: 'cascade',
    }),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'restrict' }),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    index('Attachment_assetId_idx').using('btree', table.assetId.asc().nullsLast()),
    index('Attachment_createdAt_idx').using('btree', table.createdAt.asc().nullsLast()),
    index('Attachment_entityType_entityId_idx').using(
      'btree',
      table.entityType.asc().nullsLast(),
      table.entityId.asc().nullsLast()
    ),
    index('Attachment_fileId_idx').using('btree', table.fileId.asc().nullsLast()),
    uniqueIndex('Attachment_id_organizationId_key').using(
      'btree',
      table.id.asc().nullsLast(),
      table.organizationId.asc().nullsLast()
    ),
    index('Attachment_organizationId_entityType_entityId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.entityType.asc().nullsLast(),
      table.entityId.asc().nullsLast()
    ),
  ]
)
