// packages/database/src/db/schema/chat-session.ts
// Drizzle table: chatSession (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, pgTable, text, timestamp } from './_shared'
import { ChatWidget } from './chat-widget'
import { Organization } from './organization'
import { Thread } from './thread'
import { User } from './user'

/** Drizzle table for chatSession */
export const ChatSession = pgTable(
  'ChatSession',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    widgetId: text()
      .notNull()
      .references((): AnyPgColumn => ChatWidget.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    threadId: text().references((): AnyPgColumn => Thread.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    status: text().default('ACTIVE').notNull(),
    lastActivityAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    closedAt: timestamp({ precision: 3 }),
    closedById: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    visitorId: text().notNull(),
    visitorName: text(),
    visitorEmail: text(),
    userAgent: text(),
    ipAddress: text(),
    referrer: text(),
    url: text(),
  },
  (table) => [
    index('ChatSession_lastActivityAt_idx').using('btree', table.lastActivityAt.asc().nullsLast()),
    index('ChatSession_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('ChatSession_status_idx').using('btree', table.status.asc().nullsLast()),
    index('ChatSession_visitorId_idx').using('btree', table.visitorId.asc().nullsLast()),
    index('ChatSession_widgetId_idx').using('btree', table.widgetId.asc().nullsLast()),
  ]
)
