// packages/database/src/db/schema/chat-widget.ts
// Drizzle table: chatWidget (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  chatAudience,
  identityVerification,
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { Agent } from './agent'
import { Integration } from './integration'
import { KnowledgeBase } from './knowledge-base'
import { MediaAsset } from './media-asset'
import { Organization } from './organization'

/** Drizzle table for chatWidget */
export const ChatWidget = pgTable(
  'ChatWidget',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    integrationId: text().references((): AnyPgColumn => Integration.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    name: text().notNull(),
    isActive: boolean().default(true).notNull(),
    title: text().default('Chat Support').notNull(),
    subtitle: text(),
    primaryColor: text().default('#4F46E5').notNull(),
    /** Hex color override for the Home hero band. When null, the widget
     * derives the band from the brand tint hue (see --auxx-chat-primary-band).
     * Independent of `primaryColor` so the launcher and the header can be
     * tuned separately. Text color is auto-derived client-side from luminance
     * when set; theme-based when null. */
    headerColor: text(),
    logoLight: text(),
    logoDark: text(),
    logoLightId: text().references((): AnyPgColumn => MediaAsset.id, { onUpdate: 'cascade' }),
    logoDarkId: text().references((): AnyPgColumn => MediaAsset.id, { onUpdate: 'cascade' }),
    position: text().default('BOTTOM_RIGHT').notNull(),
    autoOpen: boolean().default(false).notNull(),
    mobileFullScreen: boolean().default(true).notNull(),
    collectUserInfo: boolean().default(false).notNull(),
    offlineMessage: text().default(
      "We're currently offline. Please leave a message and we'll get back to you as soon as possible."
    ),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    allowedDomains: text().array(),
    /** Agent that auto-replies to widget messages. Null = no AI auto-reply. */
    agentId: text().references((): AnyPgColumn => Agent.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),

    // v2 Home config — Tiptap JSON doc with `visitor:*` placeholder nodes.
    homeGreetingTemplate: jsonb(),
    homeShowRecentMessage: boolean().default(true).notNull(),
    homeShowSendMessageCta: boolean().default(true).notNull(),
    brandingFooterEnabled: boolean().default(true).notNull(),

    /** v3 conversation welcome — Tiptap JSON doc (same shape as
     * `homeGreetingTemplate`) rendered as a synthetic first bubble inside the
     * conversation view when the thread has zero real Messages. Null = the
     * widget falls back to a hardcoded greeting. */
    welcomeMessageTemplate: jsonb(),

    // v2 KB linkage (one widget → at most one KB)
    knowledgeBaseId: text().references((): AnyPgColumn => KnowledgeBase.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    /** Ordered list of pinned Article.id values shown on the widget Home tab. */
    featuredArticleIds: text().array(),

    allowDownloadTranscript: boolean().default(true).notNull(),

    // Dark mode
    defaultTheme: text().default('light').notNull(), // 'light' | 'dark' | 'system'
    primaryColorDark: text(), // nullable — falls back to primaryColor
    headerColorDark: text(), // nullable — falls back to headerColor

    /** Up to 5 tap-to-send suggestions shown above the composer while the
     * conversation thread has no user messages. Null = no chips rendered. */
    suggestedReplies: text().array(),

    /** Optional URL to the operator's privacy policy. When set, the conversation
     * composer shows a one-line consent banner linking to this URL. Null = no
     * banner rendered. */
    privacyPolicyUrl: text(),

    /**
     * Per-channel JWT enforcement state. `off` accepts any visitor;
     * `in_progress` accepts both JWT-signed and anonymous traffic while the
     * customer rolls out signing on their server; `enforced` rejects any
     * write without a verified JWT.
     *
     * The `in_progress → enforced` transition is gated on the channel having
     * recorded at least one successfully verified JWT inside the success
     * counter's TTL — a safety rail against locking the channel out.
     */
    identityVerification: identityVerification().default('off').notNull(),

    /**
     * Channel audience policy: `visitors` (anonymous only), `both` (visitors
     * + logged-in users), or `users` (logged-in only). Independent of
     * `identityVerification`, which is the JWT rollout stage.
     */
    chatAudience: chatAudience().default('visitors').notNull(),
  },
  (table) => [
    uniqueIndex('ChatWidget_integrationId_key').using(
      'btree',
      table.integrationId.asc().nullsLast()
    ),
    uniqueIndex('ChatWidget_logoLightId_key').using('btree', table.logoLightId.asc().nullsLast()),
    uniqueIndex('ChatWidget_logoDarkId_key').using('btree', table.logoDarkId.asc().nullsLast()),
    index('ChatWidget_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    uniqueIndex('ChatWidget_organizationId_name_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.name.asc().nullsLast()
    ),
  ]
)
