// packages/database/src/db/schema/chat-attachment.ts
// Drizzle table: chatAttachment (generated by scripts/split-schema.ts)

import { pgTable, index, text, timestamp, integer, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { ChatMessage } from './chat-message'
import { ChatSession } from './chat-session'

/** Drizzle table for chatAttachment */
export const ChatAttachment = pgTable(
  'ChatAttachment',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    filename: text().notNull(),
    contentType: text().notNull(),
    size: integer().notNull(),
    url: text().notNull(),
    sessionId: text()
      .notNull()
      .references((): AnyPgColumn => ChatSession.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    messageId: text().references((): AnyPgColumn => ChatMessage.id, { onUpdate: 'cascade' }),
  },
  (table) => [
    index('ChatAttachment_messageId_idx').using('btree', table.messageId.asc().nullsLast()),
    index('ChatAttachment_sessionId_idx').using('btree', table.sessionId.asc().nullsLast()),
  ]
)
