// packages/database/src/db/schema/chat-widget.ts
// Drizzle table: chatWidget (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { Agent } from './agent'
import { Integration } from './integration'
import { KnowledgeBase } from './knowledge-base'
import { Organization } from './organization'

/** Drizzle table for chatWidget */
export const ChatWidget = pgTable(
  'ChatWidget',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    integrationId: text().references((): AnyPgColumn => Integration.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    name: text().notNull(),
    description: text(),
    isActive: boolean().default(true).notNull(),
    title: text().default('Chat Support').notNull(),
    subtitle: text(),
    primaryColor: text().default('#4F46E5').notNull(),
    logoUrl: text(),
    position: text().default('BOTTOM_RIGHT').notNull(),
    welcomeMessage: text(),
    autoOpen: boolean().default(false).notNull(),
    mobileFullScreen: boolean().default(true).notNull(),
    collectUserInfo: boolean().default(false).notNull(),
    offlineMessage: text().default(
      "We're currently offline. Please leave a message and we'll get back to you as soon as possible."
    ),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    allowedDomains: text().array(),
    /** Agent that auto-replies to widget messages. Null = no AI auto-reply. */
    agentId: text().references((): AnyPgColumn => Agent.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),

    // v2 Home config
    homeGreetingTemplate: text(),
    homeShowRecentMessage: boolean().default(true).notNull(),
    homeShowSendMessageCta: boolean().default(true).notNull(),
    brandingFooterEnabled: boolean().default(true).notNull(),
    expandedWidthPx: integer().default(720).notNull(),

    // v2 KB linkage (one widget → at most one KB)
    knowledgeBaseId: text().references((): AnyPgColumn => KnowledgeBase.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    /** Ordered list of pinned Article.id values shown on the widget Home tab. */
    featuredArticleIds: text().array(),

    allowDownloadTranscript: boolean().default(true).notNull(),
  },
  (table) => [
    uniqueIndex('ChatWidget_integrationId_key').using(
      'btree',
      table.integrationId.asc().nullsLast()
    ),
    index('ChatWidget_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    uniqueIndex('ChatWidget_organizationId_name_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.name.asc().nullsLast()
    ),
  ]
)
