// packages/database/src/db/schema/chat-message.ts
// Drizzle table: chatMessage (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, pgTable, text, timestamp } from './_shared'
import { ChatSession } from './chat-session'
import { Thread } from './thread'
import { User } from './user'

/** Drizzle table for chatMessage */
export const ChatMessage = pgTable(
  'ChatMessage',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    content: text().notNull(),
    sender: text().notNull(),
    status: text().default('SENT').notNull(),
    sessionId: text()
      .notNull()
      .references((): AnyPgColumn => ChatSession.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    agentId: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    threadId: text()
      .notNull()
      .references((): AnyPgColumn => Thread.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    index('ChatMessage_agentId_idx').using('btree', table.agentId.asc().nullsLast()),
    index('ChatMessage_createdAt_idx').using('btree', table.createdAt.asc().nullsLast()),
    index('ChatMessage_sessionId_idx').using('btree', table.sessionId.asc().nullsLast()),
    index('ChatMessage_threadId_idx').using('btree', table.threadId.asc().nullsLast()),
  ]
)
