// packages/database/src/db/schema/comment.ts
// Drizzle table: comment (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, boolean, index, pgTable, text, timestamp } from './_shared'
import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for comment */
export const Comment = pgTable(
  'Comment',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    content: text().notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    deletedAt: timestamp({ precision: 3 }),
    entityId: text().notNull(),
    entityDefinitionId: text().notNull(),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    parentId: text().references((): AnyPgColumn => Comment.id, { onUpdate: 'cascade' }),
    isPinned: boolean().default(false).notNull(),
    pinnedAt: timestamp({ precision: 3 }),
    pinnedById: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
  },
  (table) => [
    index('Comment_createdById_idx').using('btree', table.createdById.asc().nullsLast()),
    index('Comment_deletedAt_idx').using('btree', table.deletedAt.asc().nullsLast()),
    index('Comment_entityId_entityDefinitionId_idx').using(
      'btree',
      table.entityId.asc().nullsLast(),
      table.entityDefinitionId.asc().nullsLast()
    ),
    index('Comment_isPinned_idx').using('btree', table.isPinned.asc().nullsLast()),
    index('Comment_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Comment_parentId_idx').using('btree', table.parentId.asc().nullsLast()),
  ]
)
