// packages/database/src/db/schema/comment-mention.ts
// Drizzle table: commentMention (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, index, text, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Comment } from './comment'
import { User } from './user'

/** Drizzle table for commentMention */
export const CommentMention = pgTable(
  'CommentMention',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    commentId: text()
      .notNull()
      .references((): AnyPgColumn => Comment.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    index('CommentMention_commentId_idx').using('btree', table.commentId.asc().nullsLast()),
    uniqueIndex('CommentMention_commentId_userId_key').using(
      'btree',
      table.commentId.asc().nullsLast(),
      table.userId.asc().nullsLast()
    ),
    index('CommentMention_userId_idx').using('btree', table.userId.asc().nullsLast()),
  ]
)
