// packages/database/src/db/schema/comment-reaction.ts
// Drizzle table: commentReaction (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, index, text, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Comment } from './comment'
import { User } from './user'

/** Drizzle table for commentReaction */
export const CommentReaction = pgTable(
  'CommentReaction',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    commentId: text()
      .notNull()
      .references((): AnyPgColumn => Comment.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    type: text().notNull(),
    emoji: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    index('CommentReaction_commentId_idx').using('btree', table.commentId.asc().nullsLast()),
    uniqueIndex('CommentReaction_commentId_userId_type_emoji_key').using(
      'btree',
      table.commentId.asc().nullsLast(),
      table.userId.asc().nullsLast(),
      table.type.asc().nullsLast(),
      table.emoji.asc().nullsLast()
    ),
    index('CommentReaction_type_idx').using('btree', table.type.asc().nullsLast()),
    index('CommentReaction_userId_idx').using('btree', table.userId.asc().nullsLast()),
  ]
)
