// packages/database/src/db/schema/contact.ts
// Drizzle table: contact (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  timestamp,
  type AnyPgColumn,
  customerStatus,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'

/** Drizzle table for contact */
export const Contact = pgTable(
  'Contact',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    status: customerStatus().default('ACTIVE').notNull(),
    email: text(),
    emails: text().array(),
    name: text(),
    firstName: text(),
    lastName: text(),
    phone: text(),
    notes: text(),
    tags: text().array(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    index('Contact_emails_idx').using('gin', table.emails.asc().nullsLast()),
    uniqueIndex('Contact_organizationId_email_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.email.asc().nullsLast()
    ),
    index('Contact_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Contact_organizationId_phone_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.phone.asc().nullsLast()
    ),
    index('Contact_organizationId_status_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.status.asc().nullsLast()
    ),
  ]
)
