// packages/database/src/db/schema/customer-group-member.ts
// Drizzle table: customerGroupMember (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, pgTable, text, timestamp, uniqueIndex } from './_shared'

import { Contact } from './contact'
import { CustomerGroup } from './customer-group'

/** Drizzle table for customerGroupMember */
export const CustomerGroupMember = pgTable(
  'CustomerGroupMember',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    customerGroupId: text()
      .notNull()
      .references((): AnyPgColumn => CustomerGroup.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
    contactId: text()
      .notNull()
      .references((): AnyPgColumn => Contact.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    uniqueIndex('CustomerGroupMember_customerGroupId_contactId_key').using(
      'btree',
      table.customerGroupId.asc().nullsLast(),
      table.contactId.asc().nullsLast()
    ),
  ]
)
