// packages/database/src/db/schema/customer-group.ts
// Drizzle table: customerGroup (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, pgTable, text, timestamp, uniqueIndex } from './_shared'

import { Organization } from './organization'

/** Drizzle table for customerGroup */
export const CustomerGroup = pgTable(
  'CustomerGroup',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    name: text().notNull(),
    description: text(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    uniqueIndex('CustomerGroup_name_organizationId_key').using(
      'btree',
      table.name.asc().nullsLast(),
      table.organizationId.asc().nullsLast()
    ),
    index('CustomerGroup_organizationId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
  ]
)
