// packages/database/src/db/schema/custom-field.ts
// Drizzle table: customField (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  boolean,
  timestamp,
  integer,
  jsonb,
  type AnyPgColumn,
  contactFieldType,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'
import { EntityDefinition } from './entity-definition'

/** Drizzle table for customField */
export const CustomField = pgTable(
  'CustomField',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    name: text().notNull(),
    type: contactFieldType().notNull(),
    description: text(),
    required: boolean().default(false).notNull(),
    active: boolean().default(true).notNull(),
    position: integer().default(0).notNull(),
    defaultValue: text(),
    options: jsonb(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    /** Model type - lowercase string (contact, ticket, thread, etc.) */
    modelType: text().default('contact').notNull(),
    icon: text(),
    isCustom: boolean().default(true).notNull(),
    /** System attribute identifier (e.g., 'primary_email', 'display_name') */
    systemAttribute: text(),
    /** Reference to EntityDefinition for custom entity fields */
    entityDefinitionId: text().references((): AnyPgColumn => EntityDefinition.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    /** Whether this field must contain unique values within its scope */
    isUnique: boolean().default(false).notNull(),

    // ========================================
    // Field capability flags
    // ========================================

    /** Whether this field can be set during entity creation (default: true) */
    isCreatable: boolean().default(true).notNull(),

    /** Whether this field can be modified after creation (default: true) */
    isUpdatable: boolean().default(true).notNull(),

    /** Whether this field is computed/derived and cannot be directly set (default: false) */
    isComputed: boolean().default(false).notNull(),

    /** Whether this field can be used for sorting (default: true) */
    isSortable: boolean().default(true).notNull(),

    /** Whether this field can be used in filters (default: true) */
    isFilterable: boolean().default(true).notNull(),
  },
  (table) => [
    index('CustomField_modelType_idx').using('btree', table.modelType.asc().nullsLast()),
    // Unique constraint scoped by organization, modelType, AND entityDefinitionId
    // This allows same field name across different entities/model types
    uniqueIndex('CustomField_name_org_model_entity_key').using(
      'btree',
      table.name.asc().nullsLast(),
      table.organizationId.asc().nullsLast(),
      table.modelType.asc().nullsLast(),
      table.entityDefinitionId.asc().nullsLast()
    ),
    index('CustomField_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('CustomField_entityDefinitionId_idx').using(
      'btree',
      table.entityDefinitionId.asc().nullsLast()
    ),
  ]
)
