// packages/database/src/db/schema/custom-field-value.ts
// Drizzle table: customFieldValue (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, index, text, timestamp, jsonb, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { CustomField } from './custom-field'

/** Drizzle table for customFieldValue */
export const CustomFieldValue = pgTable(
  'CustomFieldValue',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    entityId: text().notNull(),
    fieldId: text()
      .notNull()
      .references((): AnyPgColumn => CustomField.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    value: jsonb().default({}).notNull(),
  },
  (table) => [
    uniqueIndex('CustomFieldValue_entityId_fieldId_key').using(
      'btree',
      table.entityId.asc().nullsLast(),
      table.fieldId.asc().nullsLast()
    ),
    index('CustomFieldValue_entityId_idx').using('btree', table.entityId.asc().nullsLast()),
    index('CustomFieldValue_fieldId_idx').using('btree', table.fieldId.asc().nullsLast()),
  ]
)
