// packages/database/src/db/schema/document.ts
// Drizzle table: document (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  bigint,
  boolean,
  documentStatus,
  documentType,
  index,
  integer,
  jsonb,
  pgTable,
  sql,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { Dataset } from './dataset'
import { MediaAsset } from './media-asset'
import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for document */
export const Document = pgTable(
  'Document',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    title: text().notNull(),
    filename: text().notNull(),
    originalPath: text(),
    mimeType: text().notNull(),
    type: documentType().notNull(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    size: bigint({ mode: 'number' }).notNull(),
    checksum: text().notNull(),
    status: documentStatus().default('UPLOADED').notNull(),
    content: text(),
    processedAt: timestamp({ precision: 3 }),
    errorMessage: text(),
    processingTime: integer(),
    totalChunks: integer().default(0).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    datasetId: text()
      .notNull()
      .references((): AnyPgColumn => Dataset.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    uploadedById: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    enabled: boolean().default(true).notNull(),
    metadata: jsonb(),
    /** Optional document-specific chunk settings (overrides dataset defaults when set) */
    chunkSettings: jsonb(),
    mediaAssetId: text().references((): AnyPgColumn => MediaAsset.id, { onUpdate: 'cascade' }),
  },
  (table) => [
    index('Document_checksum_idx').using('btree', table.checksum.asc().nullsLast()),
    uniqueIndex('Document_datasetId_checksum_key').using(
      'btree',
      table.datasetId.asc().nullsLast(),
      table.checksum.asc().nullsLast()
    ),
    index('Document_datasetId_idx').using('btree', table.datasetId.asc().nullsLast()),
    index('Document_enabled_idx').using('btree', table.enabled.asc().nullsLast()),
    index('Document_mediaAssetId_idx').using('btree', table.mediaAssetId.asc().nullsLast()),
    index('Document_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Document_status_idx').using('btree', table.status.asc().nullsLast()),
    index('Document_type_idx').using('btree', table.type.asc().nullsLast()),
    index('Document_uploadedById_idx').using('btree', table.uploadedById.asc().nullsLast()),

    // Partial index for enabled documents in a dataset (optimizes search joins)
    index('idx_document_dataset_enabled')
      .using('btree', table.datasetId.asc())
      .where(sql`enabled = true`),
  ]
)
