// packages/database/src/db/schema/email-attachment.ts
// Drizzle table: emailAttachment (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, boolean, index, integer, pgTable, text, timestamp } from './_shared'

import { MediaAsset } from './media-asset'
import { Message } from './message'

/** Drizzle table for emailAttachment */
export const EmailAttachment = pgTable(
  'EmailAttachment',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    name: text().notNull(),
    mimeType: text().notNull(),
    size: integer().notNull(),
    inline: boolean().notNull(),
    contentId: text(),
    content: text(),
    contentLocation: text(),
    messageId: text()
      .notNull()
      .references((): AnyPgColumn => Message.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    attachmentOrder: integer().default(0).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    mediaAssetId: text().references((): AnyPgColumn => MediaAsset.id, { onUpdate: 'cascade' }),
  },
  (table) => [
    index('EmailAttachment_mediaAssetId_idx').using('btree', table.mediaAssetId.asc().nullsLast()),
    index('EmailAttachment_messageId_idx').using('btree', table.messageId.asc().nullsLast()),
  ]
)
