// packages/database/src/db/schema/email-embedding.ts
// Drizzle table: emailEmbedding (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, pgTable, text, timestamp, vector } from './_shared'

import { Message } from './message'

/** Drizzle table for emailEmbedding */
export const EmailEmbedding = pgTable(
  'EmailEmbedding',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    messageId: text()
      .notNull()
      .references((): AnyPgColumn => Message.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    content: text().notNull(),
    embedding: vector({ dimensions: 1536 }),
    model: text().default('text-embedding-3-small').notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    index('EmailEmbedding_messageId_idx').using('btree', table.messageId.asc().nullsLast()),
  ]
)
