// packages/database/src/db/schema/email-category.ts
// Drizzle table: emailCategory (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, text, boolean, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'

/** Drizzle table for emailCategory */
export const EmailCategory = pgTable(
  'EmailCategory',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    name: text().notNull(),
    description: text(),
    examplePhrases: text().array(),
    keywordPatterns: text().array(),
    autoLabel: boolean().default(true).notNull(),
    autoAssignTo: text(),
  },
  (table) => [
    uniqueIndex('EmailCategory_organizationId_name_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.name.asc().nullsLast()
    ),
  ]
)
