// packages/database/src/db/schema/embedding-jobs.ts
// Drizzle table: embeddingJobs (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, integer, jsonb, pgTable, text, timestamp } from './_shared'

import { Organization } from './organization'

/** Drizzle table for embeddingJobs */
export const embedding_jobs = pgTable(
  'embedding_jobs',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    status: text().notNull(),
    collection: text().notNull(),
    documents: jsonb().notNull(),
    chunkingOptions: jsonb(),
    documentCount: integer().notNull(),
    processedCount: integer().default(0).notNull(),
    errorCount: integer().default(0).notNull(),
    error: text(),
    createdAt: timestamp({ precision: 3 }).notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    completedAt: timestamp({ precision: 3 }),
  },
  (table) => [
    index('embedding_jobs_collection_idx').using('btree', table.collection.asc().nullsLast()),
    index('embedding_jobs_status_idx').using('btree', table.status.asc().nullsLast()),
  ]
)
