// packages/database/src/db/schema/embeddings.ts
// Drizzle table: embeddings (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, jsonb, pgTable, text, timestamp } from './_shared'

import { embedding_jobs } from './embedding-jobs'

/** Drizzle table for embeddings */
export const embeddings = pgTable(
  'embeddings',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    jobId: text()
      .notNull()
      .references((): AnyPgColumn => embedding_jobs.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
    collection: text().notNull(),
    documentId: text().notNull(),
    content: text().notNull(),
    metadata: jsonb().notNull(),
    embedding: jsonb().notNull(),
    createdAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => [
    index('embeddings_collection_idx').using('btree', table.collection.asc().nullsLast()),
    index('embeddings_documentId_idx').using('btree', table.documentId.asc().nullsLast()),
    index('embeddings_jobId_idx').using('btree', table.jobId.asc().nullsLast()),
  ]
)
