// packages/database/src/db/schema/external-knowledge-source.ts
// Drizzle table: externalKnowledgeSource (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  boolean,
  timestamp,
  integer,
  jsonb,
  type AnyPgColumn,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'
import { Dataset } from './dataset'
import { Organization } from './organization'

/** Drizzle table for externalKnowledgeSource */
export const ExternalKnowledgeSource = pgTable(
  'ExternalKnowledgeSource',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    name: text().notNull(),
    description: text(),
    sourceType: text().notNull(),
    endpoint: text(),
    configuration: jsonb().notNull(),
    syncEnabled: boolean().default(false).notNull(),
    syncInterval: integer(),
    lastSyncAt: timestamp({ precision: 3 }),
    nextSyncAt: timestamp({ precision: 3 }),
    status: text().default('inactive').notNull(),
    errorMessage: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    datasetId: text()
      .notNull()
      .references((): AnyPgColumn => Dataset.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    index('ExternalKnowledgeSource_datasetId_idx').using(
      'btree',
      table.datasetId.asc().nullsLast()
    ),
    uniqueIndex('ExternalKnowledgeSource_datasetId_name_key').using(
      'btree',
      table.datasetId.asc().nullsLast(),
      table.name.asc().nullsLast()
    ),
    index('ExternalKnowledgeSource_nextSyncAt_idx').using(
      'btree',
      table.nextSyncAt.asc().nullsLast()
    ),
    index('ExternalKnowledgeSource_organizationId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
    index('ExternalKnowledgeSource_status_idx').using('btree', table.status.asc().nullsLast()),
  ]
)
