// packages/database/src/db/schema/file-version.ts
// Drizzle table: fileVersion (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  bigint,
  timestamp,
  integer,
  type AnyPgColumn,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { FolderFile } from './folder-file'
import { StorageLocation } from './storage-location'

/** Drizzle table for fileVersion */
export const FileVersion = pgTable(
  'FileVersion',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    fileId: text()
      .notNull()
      .references((): AnyPgColumn => FolderFile.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    versionNumber: integer().notNull(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    size: bigint({ mode: 'number' }),
    checksum: text(),
    mimeType: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    storageLocationId: text()
      .notNull()
      .references((): AnyPgColumn => StorageLocation.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
  },
  (table) => [
    index('FileVersion_fileId_createdAt_idx').using(
      'btree',
      table.fileId.asc().nullsLast(),
      table.createdAt.asc().nullsLast()
    ),
    uniqueIndex('FileVersion_fileId_versionNumber_key').using(
      'btree',
      table.fileId.asc().nullsLast(),
      table.versionNumber.asc().nullsLast()
    ),
  ]
)
