// packages/database/src/db/schema/file-attachment.ts
// Drizzle table: fileAttachment (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, jsonb, pgTable, text, timestamp, uniqueIndex } from './_shared'

import { File } from './file'

/** Drizzle table for fileAttachment */
export const FileAttachment = pgTable(
  'FileAttachment',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    fileId: text()
      .notNull()
      .references((): AnyPgColumn => File.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    attachableId: text().notNull(),
    attachableType: text().notNull(),
    context: jsonb(),
  },
  (table) => [
    index('FileAttachment_attachableId_attachableType_idx').using(
      'btree',
      table.attachableId.asc().nullsLast(),
      table.attachableType.asc().nullsLast()
    ),
    uniqueIndex('FileAttachment_fileId_attachableId_attachableType_key').using(
      'btree',
      table.fileId.asc().nullsLast(),
      table.attachableId.asc().nullsLast(),
      table.attachableType.asc().nullsLast()
    ),
  ]
)
