// packages/database/src/db/schema/folder-file.ts
// Drizzle table: folderFile (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  bigint,
  boolean,
  index,
  pgTable,
  storageProvider,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'
import { FileVersion } from './file-version'
import { Folder } from './folder'
import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for folderFile */
export const FolderFile = pgTable(
  'FolderFile',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    folderId: text().references((): AnyPgColumn => Folder.id, { onUpdate: 'cascade' }),
    name: text().notNull(),
    path: text().notNull(),
    ext: text(),
    mimeType: text(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    size: bigint({ mode: 'number' }),
    checksum: text(),
    currentVersionId: text().references((): AnyPgColumn => FileVersion.id, { onUpdate: 'cascade' }),
    isArchived: boolean().default(false).notNull(),
    deletedAt: timestamp({ precision: 3 }),
    createdById: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    provider: storageProvider(),
  },
  (table) => [
    uniqueIndex('FolderFile_currentVersionId_key').using(
      'btree',
      table.currentVersionId.asc().nullsLast()
    ),
    index('FolderFile_organizationId_checksum_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.checksum.asc().nullsLast()
    ),
    index('FolderFile_organizationId_deletedAt_isArchived_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.deletedAt.asc().nullsLast(),
      table.isArchived.asc().nullsLast()
    ),
    index('FolderFile_organizationId_ext_createdAt_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.ext.asc().nullsLast(),
      table.createdAt.asc().nullsLast()
    ),
    index('FolderFile_organizationId_folderId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.folderId.asc().nullsLast()
    ),
    index('FolderFile_organizationId_folderId_path_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.folderId.asc().nullsLast(),
      table.path.asc().nullsLast()
    ),
    index('FolderFile_organizationId_mimeType_updatedAt_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.mimeType.asc().nullsLast(),
      table.updatedAt.asc().nullsLast()
    ),
    index('FolderFile_organizationId_name_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.name.asc().nullsLast()
    ),
    index('FolderFile_organizationId_path_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.path.asc().nullsLast()
    ),
    index('FolderFile_organizationId_updatedAt_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.updatedAt.asc().nullsLast()
    ),
    index('FolderFile_path_name_idx').using(
      'btree',
      table.path.asc().nullsLast(),
      table.name.asc().nullsLast()
    ),
  ]
)
