// packages/database/src/db/schema/folder.ts
// Drizzle table: folder (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  boolean,
  timestamp,
  integer,
  type AnyPgColumn,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'
import { Organization } from './organization'

/** Drizzle table for folder */
export const Folder = pgTable(
  'Folder',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    name: text().notNull(),
    parentId: text().references((): AnyPgColumn => Folder.id, { onUpdate: 'cascade' }),
    path: text(),
    depth: integer().default(0).notNull(),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'restrict' }),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    deletedAt: timestamp({ precision: 3 }),
    isArchived: boolean().default(false).notNull(),
  },
  (table) => [
    index('Folder_organizationId_deletedAt_isArchived_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.deletedAt.asc().nullsLast(),
      table.isArchived.asc().nullsLast()
    ),
    index('Folder_organizationId_depth_path_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.depth.asc().nullsLast(),
      table.path.asc().nullsLast()
    ),
    index('Folder_organizationId_parentId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.parentId.asc().nullsLast()
    ),
    uniqueIndex('Folder_organizationId_parentId_name_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.parentId.asc().nullsLast(),
      table.name.asc().nullsLast()
    ),
    index('Folder_parentId_name_idx').using(
      'btree',
      table.parentId.asc().nullsLast(),
      table.name.asc().nullsLast()
    ),
  ]
)
