// packages/database/src/db/schema/group-member.ts
// Drizzle table: groupMember (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, index, text, boolean, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Group } from './group'
import { User } from './user'

/** Drizzle table for groupMember */
export const GroupMember = pgTable(
  'GroupMember',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    groupId: text()
      .notNull()
      .references((): AnyPgColumn => Group.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    isActive: boolean().default(true).notNull(),
    joinedAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    deactivatedAt: timestamp({ precision: 3 }),
  },
  (table) => [
    index('GroupMember_groupId_idx').using('btree', table.groupId.asc().nullsLast()),
    uniqueIndex('GroupMember_groupId_userId_key').using(
      'btree',
      table.groupId.asc().nullsLast(),
      table.userId.asc().nullsLast()
    ),
    index('GroupMember_userId_idx').using('btree', table.userId.asc().nullsLast()),
  ]
)
