// packages/database/src/db/schema/inbox-group-access.ts
// Drizzle table: inboxGroupAccess (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, index, text, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Group } from './group'
import { Inbox } from './inbox'

/** Drizzle table for inboxGroupAccess */
export const InboxGroupAccess = pgTable(
  'InboxGroupAccess',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    inboxId: text()
      .notNull()
      .references((): AnyPgColumn => Inbox.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    groupId: text()
      .notNull()
      .references((): AnyPgColumn => Group.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    index('InboxGroupAccess_groupId_idx').using('btree', table.groupId.asc().nullsLast()),
    uniqueIndex('InboxGroupAccess_inboxId_groupId_key').using(
      'btree',
      table.inboxId.asc().nullsLast(),
      table.groupId.asc().nullsLast()
    ),
    index('InboxGroupAccess_inboxId_idx').using('btree', table.inboxId.asc().nullsLast()),
  ]
)
