// packages/database/src/db/schema/inbox.ts
// Drizzle table: inbox (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  boolean,
  timestamp,
  jsonb,
  type AnyPgColumn,
  inboxStatus,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'

/** Drizzle table for inbox */
export const Inbox = pgTable(
  'Inbox',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    name: text().notNull(),
    description: text(),
    color: text().default('#4F46E5'),
    status: inboxStatus().default('ACTIVE').notNull(),
    settings: jsonb().default({}),
    allowAllMembers: boolean().default(true).notNull(),
    enableMemberAccess: boolean().default(false).notNull(),
    enableGroupAccess: boolean().default(false).notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    index('Inbox_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    uniqueIndex('Inbox_organizationId_name_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.name.asc().nullsLast()
    ),
  ]
)
