// packages/database/src/db/schema/integration.ts
// Drizzle table: integration (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  boolean,
  timestamp,
  jsonb,
  type AnyPgColumn,
  integrationAuthStatus,
  integrationProviderType,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'

/** Drizzle table for integration */
export const Integration = pgTable(
  'Integration',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    name: text(),
    refreshToken: text(),
    accessToken: text(),
    expiresAt: timestamp({ precision: 3 }),
    provider: integrationProviderType().default('google').notNull(),
    enabled: boolean().default(true).notNull(),
    email: text(),
    lastSyncedAt: timestamp({ precision: 3 }),
    lastSuccessfulSync: timestamp({ precision: 3 }),
    lastHistoryId: text(),
    authStatus: integrationAuthStatus().default('AUTHENTICATED').notNull(),
    metadata: jsonb(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex('Integration_organizationId_email_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.email.asc().nullsLast()
    ),
    index('Integration_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Integration_provider_organizationId_idx').using(
      'btree',
      table.provider.asc().nullsLast(),
      table.organizationId.asc().nullsLast()
    ),
  ]
)
