// packages/database/src/db/schema/integration.ts
// Drizzle table: integration (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  index,
  integer,
  integrationAuthStatus,
  integrationProviderType,
  integrationSyncStage,
  integrationSyncStatus,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { Organization } from './organization'
import { WorkflowCredentials } from './workflow-credentials'

/** Drizzle table for integration */
export const Integration = pgTable(
  'Integration',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    name: text(),
    credentialId: text().references((): AnyPgColumn => WorkflowCredentials.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    expiresAt: timestamp({ precision: 3 }),
    provider: integrationProviderType().default('google').notNull(),
    enabled: boolean().default(true).notNull(),
    email: text(),
    lastSyncedAt: timestamp({ precision: 3 }),
    lastSuccessfulSync: timestamp({ precision: 3 }),
    lastHistoryId: text(),
    authStatus: integrationAuthStatus().default('AUTHENTICATED').notNull(),
    requiresReauth: boolean().default(false).notNull(),
    lastAuthError: text(),
    lastAuthErrorAt: timestamp({ precision: 3 }),
    // Sync state
    syncStatus: integrationSyncStatus().default('NOT_SYNCED').notNull(),
    syncStage: integrationSyncStage().default('IDLE').notNull(),
    syncStageStartedAt: timestamp({ precision: 3 }),
    // Throttling
    throttleFailureCount: integer().default(0).notNull(),
    throttleRetryAfter: timestamp({ precision: 3 }),
    syncMode: text().default('auto').notNull(), // 'webhook' | 'polling' | 'auto'
    pollingIntervalMs: integer().default(300000), // 5 min default, per-integration configurable
    metadata: jsonb(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex('Integration_organizationId_email_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.email.asc().nullsLast()
    ),
    index('Integration_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Integration_provider_organizationId_idx').using(
      'btree',
      table.provider.asc().nullsLast(),
      table.organizationId.asc().nullsLast()
    ),
    index('Integration_credentialId_idx').using('btree', table.credentialId.asc().nullsLast()),
    index('Integration_syncStatus_idx').using('btree', table.syncStatus.asc().nullsLast()),
  ]
)
