// packages/database/src/db/schema/integration.ts
// Drizzle table: integration (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  index,
  integer,
  integrationProviderType,
  integrationSyncStage,
  integrationSyncStatus,
  jsonb,
  pgTable,
  sql,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'
import { Credential } from './credential'
import { Organization } from './organization'

/** Drizzle table for integration */
export const Integration = pgTable(
  'Integration',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    name: text(),
    credentialId: text().references((): AnyPgColumn => Credential.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    provider: integrationProviderType().default('google').notNull(),
    enabled: boolean().default(true).notNull(),
    email: text(),
    lastSyncedAt: timestamp({ precision: 3 }),
    lastSuccessfulSync: timestamp({ precision: 3 }),
    lastHistoryId: text(),
    // Sync state
    syncStatus: integrationSyncStatus().default('NOT_SYNCED').notNull(),
    syncStage: integrationSyncStage().default('IDLE').notNull(),
    syncStageStartedAt: timestamp({ precision: 3 }),
    // Throttling
    throttleFailureCount: integer().default(0).notNull(),
    throttleRetryAfter: timestamp({ precision: 3 }),
    syncMode: text().default('auto').notNull(), // 'webhook' | 'polling' | 'auto'
    /**
     * Provider-owned inbound webhook routing key — the value the provider's inbound
     * door uses to resolve a notification to its channel (Outlook: Graph subscription
     * id; written on arm/renew/adopt, cleared by removeWebhook/revoke). Unique per
     * provider among live rows so two channels can never silently claim the same key.
     */
    webhookRouteKey: text(),
    pollingIntervalMs: integer().default(300000), // 5 min default, per-integration configurable
    isExample: boolean('is_example').notNull().default(false),
    metadata: jsonb(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    deletedAt: timestamp({ precision: 3 }),
  },
  (table) => [
    uniqueIndex('Integration_organizationId_provider_email_key')
      .using(
        'btree',
        table.organizationId.asc().nullsLast(),
        table.provider.asc().nullsLast(),
        table.email.asc().nullsLast()
      )
      .where(sql`${table.deletedAt} IS NULL`),
    index('Integration_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Integration_provider_organizationId_idx').using(
      'btree',
      table.provider.asc().nullsLast(),
      table.organizationId.asc().nullsLast()
    ),
    index('Integration_credentialId_idx').using('btree', table.credentialId.asc().nullsLast()),
    index('Integration_syncStatus_idx').using('btree', table.syncStatus.asc().nullsLast()),
    uniqueIndex('Integration_provider_webhookRouteKey_key')
      .using('btree', table.provider.asc().nullsLast(), table.webhookRouteKey.asc().nullsLast())
      .where(sql`${table.webhookRouteKey} IS NOT NULL AND ${table.deletedAt} IS NULL`),
    // Meta data-deletion / deauthorize callbacks join on the app-scoped Facebook user id,
    // which is many-channels-per-value by design (one login, three Pages) — so it cannot
    // live in `webhookRouteKey`'s unique (provider, key) index. Non-unique partial
    // expression index instead; taken for exactness of the access path, not for speed.
    // See plans/channels/meta-data-deletion-callback.md §4.2.
    index('Integration_social_userId_idx')
      .using('btree', sql`(${table.metadata} ->> 'userId')`)
      .where(sql`${table.deletedAt} IS NULL AND ${table.provider} IN ('facebook','instagram')`),
  ]
)

export type IntegrationEntity = typeof Integration.$inferSelect
