// packages/database/src/db/schema/inventory.ts
// Drizzle table: inventory (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, integer, pgTable, text, timestamp, uniqueIndex } from './_shared'

import { Organization } from './organization'
import { Part } from './part'

/** Drizzle table for inventory */
export const Inventory = pgTable(
  'Inventory',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    partId: text()
      .notNull()
      .references((): AnyPgColumn => Part.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    quantity: integer().default(0).notNull(),
    location: text(),
    reorderPoint: integer(),
    reorderQty: integer(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => [uniqueIndex('Inventory_partId_key').using('btree', table.partId.asc().nullsLast())]
)

/** Selected Inventory entity type */
export type InventoryEntity = typeof Inventory.$inferSelect
