// packages/database/src/db/schema/invoice.ts
// Drizzle table: invoice (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  timestamp,
  integer,
  type AnyPgColumn,
  invoiceStatus,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'
import { PlanSubscription } from './plan-subscription'

/** Drizzle table for invoice */
export const Invoice = pgTable(
  'Invoice',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    subscriptionId: text()
      .notNull()
      .references((): AnyPgColumn => PlanSubscription.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
    invoiceNumber: text().notNull(),
    amount: integer().notNull(),
    status: invoiceStatus().default('PENDING').notNull(),
    invoiceDate: timestamp({ precision: 3 }).defaultNow().notNull(),
    dueDate: timestamp({ precision: 3 }).notNull(),
    paidDate: timestamp({ precision: 3 }),
    currency: text(),
    billingReason: text(),
    stripeInvoiceId: text(),
    pdfUrl: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => [
    index('Invoice_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    uniqueIndex('Invoice_stripeInvoiceId_key').using(
      'btree',
      table.stripeInvoiceId.asc().nullsLast()
    ),
    index('Invoice_subscriptionId_idx').using('btree', table.subscriptionId.asc().nullsLast()),
  ]
)
