// packages/database/src/db/schema/load-balancing-config.ts
// Drizzle table: loadBalancingConfig (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { Organization } from './organization'

/** Drizzle table for loadBalancingConfig */
export const LoadBalancingConfig = pgTable(
  'LoadBalancingConfig',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    provider: text().notNull(),
    model: text().notNull(),
    modelType: text().notNull(),
    name: text().notNull(),
    credentials: jsonb(),
    enabled: boolean().default(true).notNull(),
    weight: integer().default(1).notNull(),
  },
  (table) => [
    index('LoadBalancingConfig_organizationId_provider_model_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.provider.asc().nullsLast(),
      table.model.asc().nullsLast()
    ),
    uniqueIndex('LoadBalancingConfig_organizationId_provider_model_modelType_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.provider.asc().nullsLast(),
      table.model.asc().nullsLast(),
      table.modelType.asc().nullsLast(),
      table.name.asc().nullsLast()
    ),
  ]
)
