// packages/database/src/db/schema/mail-domain.ts
// Drizzle table: mailDomain (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  text,
  boolean,
  timestamp,
  type AnyPgColumn,
  domainType,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'

/** Drizzle table for mailDomain */
export const MailDomain = pgTable(
  'MailDomain',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    domain: text().notNull(),
    subdomain: text(),
    type: domainType().default('CUSTOM').notNull(),
    routingPrefix: text().default('ticket').notNull(),
    isVerified: boolean().default(false).notNull(),
    verificationToken: text().notNull(),
    verifiedAt: timestamp({ precision: 3 }),
    isActive: boolean().default(true).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    webhookKey: text(),
  },
  (table) => [
    uniqueIndex('MailDomain_organizationId_domain_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.domain.asc().nullsLast()
    ),
  ]
)
