// packages/database/src/db/schema/media-asset-version.ts
// Drizzle table: mediaAssetVersion (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  assetVersionStatus,
  bigint,
  index,
  integer,
  jsonb,
  pgTable,
  sql,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { MediaAsset } from './media-asset'
import { StorageLocation } from './storage-location'

/** Drizzle table for mediaAssetVersion */
export const MediaAssetVersion = pgTable(
  'MediaAssetVersion',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    assetId: text()
      .notNull()
      .references((): AnyPgColumn => MediaAsset.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    versionNumber: integer().notNull(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    size: bigint({ mode: 'number' }),
    mimeType: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    storageLocationId: text().references((): AnyPgColumn => StorageLocation.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    deletedAt: timestamp({ precision: 3 }),
    derivedFromVersionId: text().references((): AnyPgColumn => MediaAssetVersion.id, {
      onUpdate: 'cascade',
    }),
    preset: text(),
    metadata: jsonb().default({}),
    status: assetVersionStatus().default('PENDING').notNull(),
  },
  (table) => [
    index('MediaAssetVersion_assetId_createdAt_idx').using(
      'btree',
      table.assetId.asc().nullsLast(),
      table.createdAt.asc().nullsLast()
    ),
    uniqueIndex('MediaAssetVersion_assetId_versionNumber_key').using(
      'btree',
      table.assetId.asc().nullsLast(),
      table.versionNumber.asc().nullsLast()
    ),
    uniqueIndex('MediaAssetVersion_derivedFromVersionId_preset_key').using(
      'btree',
      table.derivedFromVersionId.asc().nullsLast(),
      table.preset.asc().nullsLast()
    ),
    index('MediaAssetVersion_derivedFromVersionId_preset_status_idx').using(
      'btree',
      table.derivedFromVersionId.asc().nullsLast(),
      table.preset.asc().nullsLast(),
      table.status.asc().nullsLast()
    ),
    index('MediaAssetVersion_status_idx').using('btree', table.status.asc().nullsLast()),
    index('idx_thumbnail_cleanup')
      .using('btree', table.derivedFromVersionId.asc().nullsLast())
      .where(sql`(("derivedFromVersionId" IS NOT NULL) AND ("deletedAt" IS NULL))`),
    index('idx_thumbnail_lookup_covering')
      .using(
        'btree',
        table.derivedFromVersionId.asc().nullsLast(),
        table.preset.asc().nullsLast(),
        table.id.asc().nullsLast()
      )
      .where(sql`(("derivedFromVersionId" IS NOT NULL) AND ("deletedAt" IS NULL))`),
    uniqueIndex('idx_unique_thumbnail')
      .using('btree', table.derivedFromVersionId.asc().nullsLast(), table.preset.asc().nullsLast())
      .where(sql`(("derivedFromVersionId" IS NOT NULL) AND ("deletedAt" IS NULL))`),
  ]
)

/** Selected MediaAssetVersion entity type */
export type MediaAssetVersionEntity = typeof MediaAssetVersion.$inferSelect
