// packages/database/src/db/schema/media-asset.ts
// Drizzle table: mediaAsset (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  bigint,
  boolean,
  index,
  pgTable,
  sql,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'
import { MediaAssetVersion } from './media-asset-version'
import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for mediaAsset */
export const MediaAsset = pgTable(
  'MediaAsset',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    kind: text().notNull(),
    name: text(),
    mimeType: text(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    size: bigint({ mode: 'number' }),
    isPrivate: boolean().default(true).notNull(),
    deletedAt: timestamp({ precision: 3 }),
    currentVersionId: text().references((): AnyPgColumn => MediaAssetVersion.id, {
      onUpdate: 'cascade',
    }),
    createdById: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    expiresAt: timestamp({ precision: 3 }),
    purpose: text().default('ORIGINAL').notNull(),
  },
  (table) => [
    uniqueIndex('MediaAsset_currentVersionId_key').using(
      'btree',
      table.currentVersionId.asc().nullsLast()
    ),
    index('MediaAsset_expiresAt_idx').using('btree', table.expiresAt.asc().nullsLast()),
    uniqueIndex('MediaAsset_id_organizationId_key').using(
      'btree',
      table.id.asc().nullsLast(),
      table.organizationId.asc().nullsLast()
    ),
    index('MediaAsset_kind_isPrivate_idx').using(
      'btree',
      table.kind.asc().nullsLast(),
      table.isPrivate.asc().nullsLast()
    ),
    index('MediaAsset_organizationId_expiresAt_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.expiresAt.asc().nullsLast()
    ),
    index('MediaAsset_organizationId_kind_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.kind.asc().nullsLast()
    ),
    index('MediaAsset_organizationId_purpose_kind_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.purpose.asc().nullsLast(),
      table.kind.asc().nullsLast()
    ),
    index('idx_thumbnail_assets')
      .using('btree', table.organizationId.asc().nullsLast(), table.kind.asc().nullsLast())
      .where(sql`((kind = 'THUMBNAIL'::text) AND ("deletedAt" IS NULL))`),
  ]
)

/** Selected MediaAsset entity type */
export type MediaAssetEntity = typeof MediaAsset.$inferSelect
