// packages/database/src/db/schema/message.ts
// Drizzle table: message (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  bigint,
  boolean,
  index,
  integer,
  jsonb,
  machineMailTier,
  pgTable,
  sendStatus,
  sql,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'
import { EntityInstance } from './entity-instance'
import { Integration } from './integration'
import { Organization } from './organization'
import { Participant } from './participant'
import { StorageLocation } from './storage-location'
import { Thread } from './thread'
import { User } from './user'

/** Drizzle table for message */
export const Message = pgTable(
  'Message',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    externalId: text(),
    externalThreadId: text(),
    threadId: text()
      .notNull()
      .references((): AnyPgColumn => Thread.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    integrationId: text()
      .notNull()
      .references((): AnyPgColumn => Integration.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    isInbound: boolean().default(true).notNull(),
    isFirstInThread: boolean().default(true).notNull(),
    subject: text(),
    textHtml: text(),
    textPlain: text(),
    internetMessageId: text(),
    snippet: text(),
    metadata: jsonb(),
    createdById: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    fromId: text()
      .notNull()
      .references((): AnyPgColumn => Participant.id, { onUpdate: 'cascade', onDelete: 'restrict' }),
    replyToId: text().references((): AnyPgColumn => Participant.id, { onUpdate: 'cascade' }),
    isReply: boolean().default(false).notNull(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    historyId: bigint({ mode: 'number' }),
    createdAt: timestamp({ precision: 3 }).notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    sentAt: timestamp({ precision: 3 }),
    receivedAt: timestamp({ precision: 3 }),
    signatureId: text().references((): AnyPgColumn => EntityInstance.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    htmlBodyStorageLocationId: text().references((): AnyPgColumn => StorageLocation.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    hasAttachments: boolean().default(false).notNull(),
    attempts: integer().default(0).notNull(),
    lastAttemptAt: timestamp({ precision: 3 }),
    providerError: text(),
    sendStatus: sendStatus().default('SENT'),
    sendToken: text(),
    // Machine-mail tier, set at ingest for inbound mail (machine-mail plan Phase 1).
    // Null = ordinary human mail. The detection reason stays in metadata.machineMail.
    machineMailTier: machineMailTier(),
    // --- Bulk-mail identity, derived once at ingest from headers already in hand
    // (mail suggestions plan §1.1). Inbound-only, set at insert, never updated.
    //
    // Normalized `list-id` (human description stripped, angle brackets stripped,
    // lowercased). THE stable bulk identity: it survives VERP and per-campaign
    // from-addresses, which fragment any grouping keyed on the sender address.
    listId: text(),
    // Registrable domain of the from-address (via `tldts`). Fallback grouping when
    // there is no list-id, and independently useful as a filter condition
    // ("all mail from acme.com"). Kept SEPARATE from listId on purpose (S7): the
    // unsubscribe safety gate must be able to tell a real list from a domain guess.
    senderDomain: text(),
    // Parsed `list-unsubscribe` + `list-unsubscribe-post`:
    // `{ httpUrl?, mailto?, oneClick: boolean }`. Parsed once here instead of
    // re-parsing `<https://…>, <mailto:…>` in the mining job. Never filtered on.
    unsubscribeMeta: jsonb().$type<unknown>(),
    // DMARC/DKIM verdict from `authentication-results`.
    // NULL MEANS UNKNOWN AND MUST READ AS "NOT AUTHENTICATED" (invariant 3) — the
    // absence of the header is not a pass, and coercing it to one is how you end up
    // POSTing to a spammer's confirmation endpoint.
    senderAuthenticated: boolean(),
    // Durable per-thread auto-reply alternation guard (message-trigger-scoping plan §6
    // fix #3). Set at send time by MessageSenderService for every automated send
    // (`!viewer || isSystemViewer(viewer)`) — mirrors the same runtime determination
    // that already drives suppression/rate-limiting, just persisted this time. Default
    // false + backfill: historical rows count as not-automated, which is the accepted
    // semantics (nothing to alternate against before this column existed).
    isAutomatedSend: boolean().default(false).notNull(),
  },
  (table) => [
    index('Message_createdById_idx').using('btree', table.createdById.asc().nullsLast()),
    // SES/SNS event ingestion (packages/lib/src/signals/email-events.ts) looks up a Message by
    // externalId alone (SES events carry no integrationId) — the composite
    // Message_integrationId_externalId_key index above can't serve that (integrationId leads).
    index('Message_externalId_idx').using('btree', table.externalId.asc().nullsLast()),
    index('Message_fromId_idx').using('btree', table.fromId.asc().nullsLast()),
    uniqueIndex('Message_integrationId_externalId_key').using(
      'btree',
      table.integrationId.asc().nullsLast(),
      table.externalId.asc().nullsLast()
    ),
    index('Message_integrationId_idx').using('btree', table.integrationId.asc().nullsLast()),
    // Flagged messages only (tiny partial index) — backs future inbox "automated" filters.
    index('Message_machineMailTier_idx')
      .using(
        'btree',
        table.organizationId.asc().nullsLast(),
        table.machineMailTier.asc().nullsLast()
      )
      .where(sql`("machineMailTier" IS NOT NULL)`),
    index('Message_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    // The mining group-by (suggestions plan §1.1). Partial — most mail has no list-id.
    index('Message_organizationId_listId_idx')
      .using('btree', table.organizationId.asc().nullsLast(), table.listId.asc().nullsLast())
      .where(sql`("listId" IS NOT NULL)`),
    // Fallback group-by when there is no list-id.
    index('Message_organizationId_senderDomain_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.senderDomain.asc().nullsLast()
    ),
    // Serves the correlated `exists(...)` that a `list is X` filter condition compiles
    // to — condition-query-builder emits subqueries against Message, so threadId must
    // be IN the index or every candidate thread degrades to a heap lookup.
    index('Message_listId_threadId_idx')
      .using('btree', table.listId.asc().nullsLast(), table.threadId.asc().nullsLast())
      .where(sql`("listId" IS NOT NULL)`),
    uniqueIndex('Message_organizationId_internetMessageId_key')
      .using(
        'btree',
        table.organizationId.asc().nullsLast(),
        table.internetMessageId.asc().nullsLast()
      )
      .where(sql`("internetMessageId" IS NOT NULL)`),
    index('Message_replyToId_idx').using('btree', table.replyToId.asc().nullsLast()),
    uniqueIndex('Message_sendToken_key')
      .using('btree', table.sendToken.asc().nullsLast())
      .where(sql`("sendToken" IS NOT NULL)`),
    index('Message_sentAt_idx').using('btree', table.sentAt.asc().nullsLast()),
    index('Message_threadId_createdById_idx').using(
      'btree',
      table.threadId.asc().nullsLast(),
      table.createdById.asc().nullsLast()
    ),
    index('Message_threadId_idx').using('btree', table.threadId.asc().nullsLast()),
    index('retry_queue_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.sendStatus.asc().nullsLast(),
      table.lastAttemptAt.asc().nullsLast()
    ),
    index('thread_messages_idx').using(
      'btree',
      table.threadId.asc().nullsLast(),
      table.sentAt.asc().nullsLast()
    ),
  ]
)

export type MessageEntity = typeof Message.$inferSelect
export type CreateMessageInput = typeof Message.$inferInsert
export type UpdateMessageInput = Partial<CreateMessageInput>
