// packages/database/src/db/schema/message-participant.ts
// Drizzle table: messageParticipant (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  timestamp,
  type AnyPgColumn,
  participantRole,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Message } from './message'
import { Participant } from './participant'

/** Drizzle table for messageParticipant */
export const MessageParticipant = pgTable(
  'MessageParticipant',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    role: participantRole().notNull(),
    messageId: text()
      .notNull()
      .references((): AnyPgColumn => Message.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    participantId: text()
      .notNull()
      .references((): AnyPgColumn => Participant.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    contactId: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    index('MessageParticipant_messageId_idx').using('btree', table.messageId.asc().nullsLast()),
    uniqueIndex('MessageParticipant_messageId_participantId_role_key').using(
      'btree',
      table.messageId.asc().nullsLast(),
      table.participantId.asc().nullsLast(),
      table.role.asc().nullsLast()
    ),
    index('MessageParticipant_participantId_idx').using(
      'btree',
      table.participantId.asc().nullsLast()
    ),
    index('MessageParticipant_role_idx').using('btree', table.role.asc().nullsLast()),
    index('contact_history_idx').using(
      'btree',
      table.contactId.asc().nullsLast(),
      table.createdAt.asc().nullsLast()
    ),
    index('participant_lookup_idx').using(
      'btree',
      table.messageId.asc().nullsLast(),
      table.contactId.asc().nullsLast()
    ),
  ]
)
