// packages/database/src/db/schema/notification.ts
// Drizzle table: notification (generated by scripts/split-schema.ts)

import {
  pgTable,
  index,
  text,
  boolean,
  timestamp,
  jsonb,
  type AnyPgColumn,
  notificationType,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'
import { Organization } from './organization'

/** Drizzle table for notification */
export const Notification = pgTable(
  'Notification',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    type: notificationType().notNull(),
    message: text().notNull(),
    isRead: boolean().default(false).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    readAt: timestamp({ precision: 3 }),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    entityId: text().notNull(),
    entityType: text().notNull(),
    actorId: text().references((): AnyPgColumn => User.id, { onUpdate: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    deliveredAt: timestamp({ precision: 3 }),
    deliveryMethod: text(),
    metadata: jsonb(),
  },
  (table) => [
    index('Notification_entityType_entityId_idx').using(
      'btree',
      table.entityType.asc().nullsLast(),
      table.entityId.asc().nullsLast()
    ),
    index('Notification_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Notification_userId_createdAt_idx').using(
      'btree',
      table.userId.asc().nullsLast(),
      table.createdAt.asc().nullsLast()
    ),
    index('Notification_userId_isRead_idx').using(
      'btree',
      table.userId.asc().nullsLast(),
      table.isRead.asc().nullsLast()
    ),
  ]
)
