// packages/database/src/db/schema/notification.ts
// Drizzle table: notification (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  index,
  jsonb,
  notificationType,
  pgTable,
  text,
  timestamp,
} from './_shared'
import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for notification */
export const Notification = pgTable(
  'Notification',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    type: notificationType().notNull(),
    /** Plain-text fallback for search and non-client delivery channels. */
    message: text().notNull(),
    /** Client destination kind; see `@auxx/lib/notifications/client`. */
    targetType: text().notNull(),
    /** Destination identifiers whose shape is determined by `targetType`. */
    targetIds: jsonb().notNull(),
    isRead: boolean().default(false).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    readAt: timestamp({ precision: 3 }),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    actorId: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    deliveredAt: timestamp({ precision: 3 }),
    deliveryMethod: text(),
    metadata: jsonb(),
  },
  (table) => [
    index('Notification_targetType_idx').using('btree', table.targetType.asc().nullsLast()),
    index('Notification_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Notification_userId_org_createdAt_idx').using(
      'btree',
      table.userId.asc().nullsLast(),
      table.organizationId.asc().nullsLast(),
      table.createdAt.desc().nullsFirst(),
      table.id.desc().nullsFirst()
    ),
    index('Notification_userId_isRead_idx').using(
      'btree',
      table.userId.asc().nullsLast(),
      table.isRead.asc().nullsLast()
    ),
  ]
)
