// packages/database/src/db/schema/order-line-item.ts
// Drizzle table: orderLineItem (generated by scripts/split-schema.ts)

import { type AnyPgColumn, bigint, index, integer, pgTable, text, timestamp } from './_shared'

import { Order } from './order'

/** Drizzle table for orderLineItem */
export const OrderLineItem = pgTable(
  'OrderLineItem',
  {
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    id: bigint({ mode: 'number' }).primaryKey().notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    name: text().notNull(),
    quantity: integer().notNull(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    productId: bigint({ mode: 'number' }),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    variantId: bigint({ mode: 'number' }),
    title: text().notNull(),
    originalTotal: integer().default(0).notNull(),
    originalUnitPrice: integer().default(0).notNull(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    orderId: bigint({ mode: 'number' })
      .notNull()
      .references((): AnyPgColumn => Order.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [index('OrderLineItem_orderId_idx').using('btree', table.orderId.asc().nullsLast())]
)
