// packages/database/src/db/schema/order-fulfillment.ts
// Drizzle table: orderFulfillment (generated by scripts/split-schema.ts)

import {
  pgTable,
  index,
  bigint,
  boolean,
  timestamp,
  type AnyPgColumn,
  fulfillmentStatus,
} from './_shared'

import { Order } from './order'

/** Drizzle table for orderFulfillment */
export const OrderFulfillment = pgTable(
  'OrderFulfillment',
  {
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    id: bigint({ mode: 'number' }).primaryKey().notNull(),
    createdAt: timestamp({ precision: 3 }).notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    deliveredAt: timestamp({ precision: 3 }),
    status: fulfillmentStatus().default('OPEN').notNull(),
    requiresShipping: boolean().default(true).notNull(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    orderId: bigint({ mode: 'number' })
      .notNull()
      .references((): AnyPgColumn => Order.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    index('OrderFulfillment_orderId_idx').using('btree', table.orderId.asc().nullsLast()),
    index('OrderFulfillment_status_idx').using('btree', table.status.asc().nullsLast()),
  ]
)
