// packages/database/src/db/schema/order.ts
// Drizzle table: order (generated by scripts/split-schema.ts)

import {
  type AnyPgColumn,
  bigint,
  boolean,
  index,
  integer,
  orderCancelReason,
  orderFinancialStatus,
  orderFulfillmentStatus,
  orderReturnStatus,
  pgTable,
  text,
  timestamp,
} from './_shared'

import { Address } from './address'
import { Organization } from './organization'
import { shopify_customers } from './shopify-customers'
import { ShopifyIntegration } from './shopify-integration'

/** Drizzle table for order */
export const Order = pgTable(
  'Order',
  {
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    id: bigint({ mode: 'number' }).primaryKey().notNull(),
    createdAt: timestamp({ precision: 3 }).notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    cancelledAt: timestamp({ precision: 3 }),
    closedAt: timestamp({ precision: 3 }),
    processedAt: timestamp({ precision: 3 }),
    cancelReason: orderCancelReason(),
    canNotifyCustomer: boolean().default(false).notNull(),
    confirmationNumber: text(),
    currencyCode: text().default('USD').notNull(),
    discountCode: text(),
    financialStatus: orderFinancialStatus().notNull(),
    fulfillmentStatus: orderFulfillmentStatus().notNull(),
    email: text(),
    name: text().notNull(),
    note: text(),
    phone: text(),
    poNumber: text(),
    returnStatus: orderReturnStatus(),
    tags: text().array(),
    taxExempt: boolean().default(false).notNull(),
    subtotalPrice: integer().default(0).notNull(),
    totalDiscounts: integer().default(0).notNull(),
    totalPrice: integer().default(0).notNull(),
    totalRefunded: integer().default(0).notNull(),
    totalShippingPrice: integer().default(0).notNull(),
    totalTax: integer().default(0).notNull(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    shippingAddressId: bigint({ mode: 'number' }).references((): AnyPgColumn => Address.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    billingAddressId: bigint({ mode: 'number' }).references((): AnyPgColumn => Address.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    customerId: bigint({ mode: 'number' })
      .notNull()
      .references((): AnyPgColumn => shopify_customers.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    integrationId: text()
      .notNull()
      .references((): AnyPgColumn => ShopifyIntegration.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
  },
  (table) => [
    index('Order_customerId_idx').using('btree', table.customerId.asc().nullsLast()),
    index('Order_name_idx').using('btree', table.name.asc().nullsLast()),
  ]
)
