// packages/database/src/db/schema/organization.ts
// Drizzle table: organization (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { sql } from 'drizzle-orm'
import {
  type AnyPgColumn,
  boolean,
  index,
  jsonb,
  organizationType,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { User } from './user'

/** Drizzle table for organization */
export const Organization = pgTable(
  'Organization',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    name: text(),
    website: text(),
    about: text(),
    domains: jsonb().$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    type: organizationType().default('TEAM').notNull(),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'restrict' }),
    systemUserId: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    handle: text(),
    disabledAt: timestamp({ precision: 3 }),
    disabledReason: text(),
    disabledBy: text(),
    completedOnboarding: boolean().default(false),
    demoExpiresAt: timestamp('demo_expires_at', { precision: 3 }),
  },
  (table) => [
    index('Organization_handle_idx').using('btree', table.handle.asc().nullsLast()),
    uniqueIndex('Organization_handle_key').using('btree', table.handle.asc().nullsLast()),
    uniqueIndex('Organization_systemUserId_key').using(
      'btree',
      table.systemUserId.asc().nullsLast()
    ),
  ]
)

/** Selected Organization entity type */
export type OrganizationEntity = typeof Organization.$inferSelect
