// packages/database/src/db/schema/organization-member.ts
// Drizzle table: organizationMember (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import type { SeatType } from '../../enums'
import {
  type AnyPgColumn,
  boolean,
  index,
  organizationMemberStatus,
  organizationRole,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for organizationMember */
export const OrganizationMember = pgTable(
  'OrganizationMember',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    status: organizationMemberStatus().default('ACTIVE').notNull(),
    role: organizationRole().default('USER').notNull(),
    /** Seat packaging/billing identity, decoupled from `role`. 'full' | 'worker'
     * (worker = UI "Field seat"). Invariant: 'worker' ⇒ role 'USER'. Service-enforced.
     * See plans/permissions/capability-layer-and-worker-seat.md §2.A / §3.1. */
    seatType: text().$type<SeatType>().default('full').notNull(),
    /** Chat duty (Phase 4c): when true, this member is opted in to receive
     * routed customer chats. Persistent, manually toggled, decoupled from
     * presence. See plans/chat/v3/phase-4c-chat-duty.md. */
    onChatDuty: boolean().default(false).notNull(),
    chatDutyUpdatedAt: timestamp({ precision: 3 }),
    chatDutyUpdatedById: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
  },
  (table) => [
    index('OrganizationMember_organizationId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
    index('OrganizationMember_userId_idx').using('btree', table.userId.asc().nullsLast()),
    uniqueIndex('OrganizationMember_userId_organizationId_key').using(
      'btree',
      table.userId.asc().nullsLast(),
      table.organizationId.asc().nullsLast()
    ),
  ]
)

export type OrganizationMemberEntity = typeof OrganizationMember.$inferSelect

/** Minimal membership info used in auth checks */
export type OrganizationMemberInfo = Pick<
  OrganizationMemberEntity,
  'id' | 'userId' | 'organizationId' | 'role' | 'seatType' | 'status' | 'onChatDuty'
>
