// packages/database/src/db/schema/organization-member.ts
// Drizzle table: organizationMember (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  index,
  organizationMemberStatus,
  organizationRole,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for organizationMember */
export const OrganizationMember = pgTable(
  'OrganizationMember',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    status: organizationMemberStatus().default('ACTIVE').notNull(),
    role: organizationRole().default('USER').notNull(),
  },
  (table) => [
    index('OrganizationMember_organizationId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
    index('OrganizationMember_userId_idx').using('btree', table.userId.asc().nullsLast()),
    uniqueIndex('OrganizationMember_userId_organizationId_key').using(
      'btree',
      table.userId.asc().nullsLast(),
      table.organizationId.asc().nullsLast()
    ),
  ]
)
