// packages/database/src/db/schema/organization.ts
// Drizzle table: organization (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  timestamp,
  type AnyPgColumn,
  organizationType,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'

/** Drizzle table for organization */
export const Organization = pgTable(
  'Organization',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    name: text(),
    website: text(),
    about: text(),
    emailDomain: text('email_domain'),
    type: organizationType().default('TEAM').notNull(),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'restrict' }),
    systemUserId: text().references((): AnyPgColumn => User.id, { onUpdate: 'cascade' }),
    handle: text(),
    disabledAt: timestamp({ precision: 3 }),
    disabledReason: text(),
    disabledBy: text(),
  },
  (table) => [
    index('Organization_handle_idx').using('btree', table.handle.asc().nullsLast()),
    uniqueIndex('Organization_handle_key').using('btree', table.handle.asc().nullsLast()),
    uniqueIndex('Organization_systemUserId_key').using(
      'btree',
      table.systemUserId.asc().nullsLast()
    ),
  ]
)
