// packages/database/src/db/schema/password-reset-token.ts
// Drizzle table: passwordResetToken (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, pgTable, text, timestamp, uniqueIndex } from './_shared'

import { User } from './user'

/** Drizzle table for passwordResetToken */
export const PasswordResetToken = pgTable(
  'PasswordResetToken',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    token: text().notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    expiresAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => [
    uniqueIndex('PasswordResetToken_token_key').using('btree', table.token.asc().nullsLast()),
    index('PasswordResetToken_userId_idx').using('btree', table.userId.asc().nullsLast()),
  ]
)
