// packages/database/src/db/schema/passkey.ts
// Drizzle table: passkey (generated by scripts/split-schema.ts)

import { pgTable, text, boolean, timestamp, integer, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'

/** Drizzle table for passkey */
export const Passkey = pgTable(
  'Passkey',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    name: text(),
    publicKey: text().notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    credentialID: text().notNull(),
    counter: integer().notNull(),
    deviceType: text().notNull(),
    backedUp: boolean().default(false).notNull(),
    transports: text().notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    aaguid: text(),
  },
  (table) => []
)
