// packages/database/src/db/schema/plan-subscription.ts
// Drizzle table: planSubscription (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  text,
  boolean,
  timestamp,
  integer,
  jsonb,
  type AnyPgColumn,
  billingCycle,
  trialConversionStatus,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'
import { Plan } from './plan'

/** Drizzle table for planSubscription */
export const PlanSubscription = pgTable(
  'PlanSubscription',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    planId: text().references((): AnyPgColumn => Plan.id, { onUpdate: 'cascade', onDelete: 'cascade' }), // Nullable - populated by better-auth lifecycle hooks
    plan: text().notNull(), // Better-auth requires plan name ("free", "starter", etc.)
    status: text().default('incomplete').notNull(), // Stripe subscription status
    seats: integer().default(1).notNull(),
    billingCycle: billingCycle().default('MONTHLY').notNull(),
    endDate: timestamp({ precision: 3 }),
    canceledAt: timestamp({ precision: 3 }),
    stripeCustomerId: text(),
    stripeSubscriptionId: text(),
    periodStart: timestamp({ precision: 3 }).defaultNow(),
    periodEnd: timestamp({ precision: 3 }),
    cancelAtPeriodEnd: boolean().default(false).notNull(),
    creditsBalance: integer().default(0).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
    trialStart: timestamp({ precision: 3 }),
    trialEnd: timestamp({ precision: 3 }),
    hasTrialEnded: boolean().default(false).notNull(),
    trialConversionStatus: trialConversionStatus(),
    isEligibleForTrial: boolean().default(true).notNull(),
    trialEligibilityReason: text(),
    scheduledPlanId: text().references((): AnyPgColumn => Plan.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    scheduledPlan: text(),
    scheduledBillingCycle: billingCycle(),
    scheduledSeats: integer(),
    scheduledChangeAt: timestamp({ precision: 3 }),
    // Account deletion notification tracking fields
    lastDeletionNotificationSent: text(), // 'WARNING' | 'FINAL'
    lastDeletionNotificationDate: timestamp({ precision: 3 }),
    deletionScheduledDate: timestamp({ precision: 3 }),
    deletionReason: text(),
    // Custom feature limits for Enterprise customers
    customFeatureLimits: jsonb(),
    customPricingMonthly: integer(),
    customPricingAnnual: integer(),
    customPricingNotes: text(),
  },
  (table) => [
    uniqueIndex('PlanSubscription_organizationId_key').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
  ]
)
