// packages/database/src/db/schema/plan.ts
// Drizzle table: plan (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { boolean, integer, jsonb, pgTable, text, timestamp } from './_shared'

/** Drizzle table for plan */
export const Plan = pgTable('Plan', {
  id: text()
    .$defaultFn(() => createId())
    .primaryKey()
    .notNull(),
  name: text().notNull(),
  description: text(),
  features: jsonb().default([]).notNull(),
  monthlyPrice: integer().notNull(),
  annualPrice: integer().notNull(),
  isCustomPricing: boolean().default(false).notNull(),
  createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  updatedAt: timestamp({ precision: 3 }).notNull(),
  trialDays: integer().default(14).notNull(),
  hasTrial: boolean().default(false).notNull(),
  minSeats: integer().default(1).notNull(),
  maxSeats: integer().default(10).notNull(),
  isLegacy: boolean().default(false).notNull(),
  selfServed: boolean().default(false).notNull(),
  isMostPopular: boolean().default(false).notNull(),
  isFree: boolean().default(false).notNull(),
  featureLimits: jsonb().default([]),
  trialFeatureLimits: jsonb(),
  stripeProductId: text(),
  stripePriceIdMonthly: text(),
  stripePriceIdAnnual: text(),
  hierarchyLevel: integer().default(0).notNull(),
})
