// packages/database/src/db/schema/product-option.ts
// Drizzle table: productOption (generated by scripts/split-schema.ts)

import { pgTable, index, text, bigint, integer, type AnyPgColumn } from './_shared'

import { Product } from './product'

/** Drizzle table for productOption */
export const ProductOption = pgTable(
  'ProductOption',
  {
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    id: bigint({ mode: 'number' }).primaryKey().notNull(),
    name: text().notNull(),
    position: integer(),
    values: text().array(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    productId: bigint({ mode: 'number' })
      .notNull()
      .references((): AnyPgColumn => Product.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    index('ProductOption_productId_idx').using('btree', table.productId.asc().nullsLast()),
  ]
)
