// packages/database/src/db/schema/product.ts
// Drizzle table: product (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  text,
  bigint,
  boolean,
  timestamp,
  integer,
  type AnyPgColumn,
  produdtStatus,
} from './_shared'

import { ShopifyIntegration } from './shopify-integration'
import { Organization } from './organization'

/** Drizzle table for product */
export const Product = pgTable(
  'Product',
  {
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    id: bigint({ mode: 'number' }).primaryKey().notNull(),
    createdAt: timestamp({ precision: 3 }).notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    publishedAt: timestamp({ precision: 3 }),
    title: text().notNull(),
    descriptionHtml: text(),
    vendor: text(),
    hasOnlyDefaultVariant: boolean().notNull(),
    productType: text(),
    handle: text().notNull(),
    status: produdtStatus().default('DRAFT').notNull(),
    tags: text().array(),
    tracksInventory: boolean().notNull(),
    totalInventory: integer().notNull(),
    integrationId: text()
      .notNull()
      .references((): AnyPgColumn => ShopifyIntegration.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [uniqueIndex('Product_handle_key').using('btree', table.handle.asc().nullsLast())]
)
