// packages/database/src/db/schema/product-media.ts
// Drizzle table: productMedia (generated by scripts/split-schema.ts)

import {
  type AnyPgColumn,
  bigint,
  index,
  integer,
  mediaContentType,
  pgTable,
  text,
  timestamp,
} from './_shared'

import { Product } from './product'

/** Drizzle table for productMedia */
export const ProductMedia = pgTable(
  'ProductMedia',
  {
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    id: bigint({ mode: 'number' }).primaryKey().notNull(),
    alt: text(),
    mediaContentType: mediaContentType().default('IMAGE').notNull(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    previewId: bigint({ mode: 'number' }).notNull(),
    previewAlt: text(),
    previewHeight: integer(),
    previewWidth: integer(),
    previewUrl: text(),
    width: integer(),
    height: integer(),
    createdAt: timestamp({ precision: 3 }),
    updatedAt: timestamp({ precision: 3 }),
    variantIds: text().array(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    productId: bigint({ mode: 'number' })
      .notNull()
      .references((): AnyPgColumn => Product.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [index('ProductMedia_productId_idx').using('btree', table.productId.asc().nullsLast())]
)
