// packages/database/src/db/schema/product-variant.ts
// Drizzle table: productVariant (generated by scripts/split-schema.ts)

import {
  type AnyPgColumn,
  bigint,
  boolean,
  index,
  integer,
  inventoryPolicy,
  jsonb,
  pgTable,
  text,
  timestamp,
} from './_shared'
import { Organization } from './organization'
import { Product } from './product'
import { ShopifyIntegration } from './shopify-integration'

/** Drizzle table for productVariant */
export const ProductVariant = pgTable(
  'ProductVariant',
  {
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    id: bigint({ mode: 'number' }).primaryKey().notNull(),
    availableForSale: boolean().notNull(),
    barcode: text(),
    createdAt: timestamp({ precision: 3 }),
    updatedAt: timestamp({ precision: 3 }),
    displayName: text().notNull(),
    position: integer().default(1).notNull(),
    price: integer().default(0).notNull(),
    compareAtPrice: integer(),
    sku: text(),
    taxable: boolean().default(true).notNull(),
    title: text().notNull(),
    selectedOptions: jsonb().array(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    imageId: bigint({ mode: 'number' }),
    imageUrl: text(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    inventoryItemId: bigint({ mode: 'number' }),
    inventoryManagement: text(),
    inventoryPolicy: inventoryPolicy().default('CONTINUE').notNull(),
    inventoryQuantity: integer(),
    weightUnit: text(),
    weight: integer(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    productId: bigint({ mode: 'number' })
      .notNull()
      .references((): AnyPgColumn => Product.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    integrationId: text()
      .notNull()
      .references((): AnyPgColumn => ShopifyIntegration.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
  },
  (table) => [
    index('ProductVariant_productId_idx').using('btree', table.productId.asc().nullsLast()),
  ]
)
