// packages/database/src/db/schema/prompt-history.ts
// Drizzle table: promptHistory (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, pgTable, text, timestamp } from './_shared'

import { User } from './user'

/** Drizzle table for promptHistory */
export const PromptHistory = pgTable(
  'PromptHistory',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    prompt: text().notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => []
)
