// packages/database/src/db/schema/provider-configuration.ts
// Drizzle table: providerConfiguration (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  sql,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { Organization } from './organization'

/** Drizzle table for providerConfiguration */
export const ProviderConfiguration = pgTable(
  'ProviderConfiguration',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    provider: text().notNull(),
    providerType: text().notNull(),
    credentials: jsonb(),
    isEnabled: boolean().default(true).notNull(),
    quotaType: text(),
    quotaLimit: integer().default(sql`'-1'`).notNull(),
    quotaPeriodEnd: timestamp({ precision: 3 }),
    quotaPeriodStart: timestamp({ precision: 3 }),
    quotaUsed: integer().default(0).notNull(),
  },
  (table) => [
    index('ProviderConfiguration_organizationId_provider_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.provider.asc().nullsLast()
    ),
    uniqueIndex('ProviderConfiguration_organizationId_provider_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.provider.asc().nullsLast()
    ),
  ]
)
