// packages/database/src/db/schema/provider-preference.ts
// Drizzle table: providerPreference (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, index, text, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'

/** Drizzle table for providerPreference */
export const ProviderPreference = pgTable(
  'ProviderPreference',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    provider: text().notNull(),
    preferredType: text().notNull(),
  },
  (table) => [
    index('ProviderPreference_organizationId_provider_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.provider.asc().nullsLast()
    ),
    uniqueIndex('ProviderPreference_organizationId_provider_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.provider.asc().nullsLast()
    ),
  ]
)
