// packages/database/src/db/schema/search-history.ts
// Drizzle table: searchHistory (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, pgTable, text, timestamp } from './_shared'

import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for searchHistory */
export const SearchHistory = pgTable(
  'SearchHistory',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    query: text().notNull(),
    searchedAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    index('SearchHistory_userId_organizationId_searchedAt_idx').using(
      'btree',
      table.userId.asc().nullsLast(),
      table.organizationId.asc().nullsLast(),
      table.searchedAt.asc().nullsLast()
    ),
  ]
)
