// packages/database/src/db/schema/session.ts
// Drizzle table: session (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, text, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'

/** Drizzle table for session */
export const session = pgTable(
  'session',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    token: text().notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    expiresAt: timestamp({ precision: 3 }).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    ipAddress: text(),
    userAgent: text(),
  },
  (table) => [uniqueIndex('session_token_key').using('btree', table.token.asc().nullsLast())]
)
