// packages/database/src/db/schema/shopify-integration.ts
// Drizzle table: shopifyIntegration (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, index, text, boolean, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'
import { Organization } from './organization'

/** Drizzle table for shopifyIntegration */
export const ShopifyIntegration = pgTable(
  'ShopifyIntegration',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    shopDomain: text().notNull(),
    accessToken: text().notNull(),
    scope: text().notNull(),
    enabled: boolean().default(true).notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'restrict' }),
  },
  (table) => [
    index('ShopifyIntegration_organizationId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
    uniqueIndex('ShopifyIntegration_organizationId_shopDomain_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.shopDomain.asc().nullsLast()
    ),
    index('ShopifyIntegration_shopDomain_idx').using('btree', table.shopDomain.asc().nullsLast()),
  ]
)
