// packages/database/src/db/schema/shopify-customers.ts
// Drizzle table: shopifyCustomers (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  bigint,
  boolean,
  timestamp,
  integer,
  type AnyPgColumn,
} from './_shared'

import { Contact } from './contact'
import { Address } from './address'
import { ShopifyIntegration } from './shopify-integration'
import { Order } from './order'
import { Organization } from './organization'

/** Drizzle table for shopifyCustomers */
export const shopify_customers = pgTable(
  'shopify_customers',
  {
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    id: bigint({ mode: 'number' }).primaryKey().notNull(),
    firstName: text(),
    lastName: text(),
    email: text(),
    phone: text(),
    createdAt: timestamp({ precision: 3 }).notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    numberOfOrders: integer(),
    state: text(),
    amountSpent: integer(),
    note: text(),
    verifiedEmail: boolean(),
    multipassIdentifier: text(),
    taxExempt: boolean(),
    tags: text().array(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    defaultAddressId: bigint({ mode: 'number' }).references((): AnyPgColumn => Address.id, {
      onUpdate: 'cascade',
    }),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    lastOrderId: bigint({ mode: 'number' }).references((): AnyPgColumn => Order.id, {
      onUpdate: 'cascade',
    }),
    lastOrderName: text(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    integrationId: text()
      .notNull()
      .references((): AnyPgColumn => ShopifyIntegration.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
    contactId: text().references((): AnyPgColumn => Contact.id, { onUpdate: 'cascade' }),
  },
  (table) => [
    index('shopify_customers_contactId_idx').using('btree', table.contactId.asc().nullsLast()),
    uniqueIndex('shopify_customers_defaultAddressId_key').using(
      'btree',
      table.defaultAddressId.asc().nullsLast()
    ),
    index('shopify_customers_email_idx').using('btree', table.email.asc().nullsLast()),
    uniqueIndex('shopify_customers_lastOrderId_key').using(
      'btree',
      table.lastOrderId.asc().nullsLast()
    ),
    index('shopify_customers_phone_idx').using('btree', table.phone.asc().nullsLast()),
  ]
)
