// packages/database/src/db/schema/signature.ts
// Drizzle table: signature (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  index,
  pgTable,
  signatureSharingType,
  text,
  timestamp,
} from './_shared'
import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for signature */
export const Signature = pgTable(
  'Signature',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    name: text().notNull(),
    body: text().notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    isDefault: boolean().default(false).notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    sharingType: signatureSharingType().default('PRIVATE').notNull(),
  },
  (table) => [
    index('Signature_createdById_idx').using('btree', table.createdById.asc().nullsLast()),
    index('Signature_isDefault_idx').using('btree', table.isDefault.asc().nullsLast()),
    index('Signature_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Signature_sharingType_idx').using('btree', table.sharingType.asc().nullsLast()),
  ]
)
