// packages/database/src/db/schema/snippet-folder.ts
// Drizzle table: snippetFolder (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, index, text, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'
import { Organization } from './organization'

/** Drizzle table for snippetFolder */
export const SnippetFolder = pgTable(
  'SnippetFolder',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    name: text().notNull(),
    description: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    parentId: text().references((): AnyPgColumn => SnippetFolder.id, { onUpdate: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    index('SnippetFolder_createdById_idx').using('btree', table.createdById.asc().nullsLast()),
    index('SnippetFolder_organizationId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
    uniqueIndex('SnippetFolder_organizationId_parentId_name_key').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.parentId.asc().nullsLast(),
      table.name.asc().nullsLast()
    ),
  ]
)
