// packages/database/src/db/schema/snippet.ts
// Drizzle table: snippet (generated by scripts/split-schema.ts)

import {
  pgTable,
  index,
  text,
  boolean,
  timestamp,
  integer,
  type AnyPgColumn,
  snippetSharingType,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'
import { SnippetFolder } from './snippet-folder'
import { Organization } from './organization'

/** Drizzle table for snippet */
export const Snippet = pgTable(
  'Snippet',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    title: text().notNull(),
    content: text().notNull(),
    contentHtml: text(),
    description: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    isDeleted: boolean().default(false).notNull(),
    folderId: text().references((): AnyPgColumn => SnippetFolder.id, { onUpdate: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    sharingType: snippetSharingType().default('PRIVATE').notNull(),
    isFavorite: boolean().default(false).notNull(),
    usageCount: integer().default(0).notNull(),
  },
  (table) => [
    index('Snippet_createdById_idx').using('btree', table.createdById.asc().nullsLast()),
    index('Snippet_folderId_idx').using('btree', table.folderId.asc().nullsLast()),
    index('Snippet_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Snippet_sharingType_idx').using('btree', table.sharingType.asc().nullsLast()),
  ]
)
