// packages/database/src/db/schema/snippet-share.ts
// Drizzle table: snippetShare (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  timestamp,
  type AnyPgColumn,
  snippetPermission,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Group } from './group'
import { OrganizationMember } from './organization-member'
import { Snippet } from './snippet'

/** Drizzle table for snippetShare */
export const SnippetShare = pgTable(
  'SnippetShare',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    snippetId: text()
      .notNull()
      .references((): AnyPgColumn => Snippet.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    groupId: text().references((): AnyPgColumn => Group.id, { onUpdate: 'cascade' }),
    memberId: text().references((): AnyPgColumn => OrganizationMember.id, { onUpdate: 'cascade' }),
    permission: snippetPermission().default('VIEW').notNull(),
  },
  (table) => [
    index('SnippetShare_groupId_idx').using('btree', table.groupId.asc().nullsLast()),
    index('SnippetShare_memberId_idx').using('btree', table.memberId.asc().nullsLast()),
    uniqueIndex('SnippetShare_snippetId_groupId_memberId_key').using(
      'btree',
      table.snippetId.asc().nullsLast(),
      table.groupId.asc().nullsLast(),
      table.memberId.asc().nullsLast()
    ),
    index('SnippetShare_snippetId_idx').using('btree', table.snippetId.asc().nullsLast()),
  ]
)
