// packages/database/src/db/schema/storage-location.ts
// Drizzle table: storageLocation (generated by scripts/split-schema.ts)

import {
  pgTable,
  index,
  text,
  bigint,
  timestamp,
  jsonb,
  type AnyPgColumn,
  storageProvider,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { WorkflowCredentials } from './workflow-credentials'

/** Drizzle table for storageLocation */
export const StorageLocation = pgTable(
  'StorageLocation',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    provider: storageProvider().notNull(),
    externalId: text().notNull(),
    externalUrl: text().notNull(),
    externalRev: text().notNull(),
    credentialId: text().references((): AnyPgColumn => WorkflowCredentials.id, {
      onUpdate: 'cascade',
    }),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    size: bigint({ mode: 'number' }).default(0),
    mimeType: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    metadata: jsonb().default({}).notNull(),
  },
  (table) => [
    index('StorageLocation_credentialId_idx').using('btree', table.credentialId.asc().nullsLast()),
    index('StorageLocation_provider_externalId_idx').using(
      'btree',
      table.provider.asc().nullsLast(),
      table.externalId.asc().nullsLast()
    ),
  ]
)
