// packages/database/src/db/schema/storage-location.ts
// Drizzle table: storageLocation (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  bigint,
  index,
  jsonb,
  pgTable,
  sql,
  storageProvider,
  text,
  timestamp,
} from './_shared'

import { Organization } from './organization'
import { WorkflowCredentials } from './workflow-credentials'

/** Drizzle table for storageLocation */
export const StorageLocation = pgTable(
  'StorageLocation',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    provider: storageProvider().notNull(),
    externalId: text().notNull(),
    externalUrl: text().notNull(),
    externalRev: text().notNull(),
    organizationId: text().references((): AnyPgColumn => Organization.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    credentialId: text().references((): AnyPgColumn => WorkflowCredentials.id, {
      onUpdate: 'cascade',
    }),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    size: bigint({ mode: 'number' }).default(0),
    mimeType: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    deletedAt: timestamp({ precision: 3 }),
    metadata: jsonb().default({}).notNull(),
  },
  (table) => [
    index('StorageLocation_credentialId_idx').using('btree', table.credentialId.asc().nullsLast()),
    index('StorageLocation_provider_externalId_idx').using(
      'btree',
      table.provider.asc().nullsLast(),
      table.externalId.asc().nullsLast()
    ),
    index('StorageLocation_organizationId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
    index('StorageLocation_deletedAt_idx')
      .using('btree', table.deletedAt.asc().nullsLast())
      .where(sql`${table.deletedAt} IS NOT NULL`),
  ]
)

/** Selected StorageLocation entity type */
export type StorageLocationEntity = typeof StorageLocation.$inferSelect
/** Insertable StorageLocation input type */
export type CreateStorageLocationInput = typeof StorageLocation.$inferInsert
