// packages/database/src/db/schema/table-view.ts
// Drizzle table: tableView (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  index,
  jsonb,
  pgTable,
  sql,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for tableView */
export const TableView = pgTable(
  'TableView',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    tableId: text().notNull(),
    name: text().notNull(),
    config: jsonb().notNull(),
    /** Context type: 'table' | 'kanban' | 'panel' | 'dialog_create' | 'dialog_edit' */
    contextType: text().default('table').notNull(),
    isDefault: boolean().default(false).notNull(),
    isShared: boolean().default(false).notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => [
    index('TableView_tableId_organizationId_idx').using(
      'btree',
      table.tableId.asc().nullsLast(),
      table.organizationId.asc().nullsLast()
    ),
    // Partial unique index: only one default view per table per organization per context type
    // Uses SQL expression to only enforce uniqueness WHERE isDefault = true
    uniqueIndex('TableView_tableId_organizationId_contextType_isDefault_key')
      .on(table.tableId, table.organizationId, table.contextType)
      .where(sql`${table.isDefault} = true`),
    index('TableView_tableId_userId_idx').using(
      'btree',
      table.tableId.asc().nullsLast(),
      table.userId.asc().nullsLast()
    ),
    uniqueIndex('TableView_tableId_userId_name_contextType_key').using(
      'btree',
      table.tableId.asc().nullsLast(),
      table.userId.asc().nullsLast(),
      table.name.asc().nullsLast(),
      table.contextType.asc().nullsLast()
    ),
  ]
)

/** Selected TableView entity type */
export type TableViewEntity = typeof TableView.$inferSelect
