// packages/database/src/db/schema/tag.ts
// Drizzle table: tag (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, index, text, boolean, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'

/** Drizzle table for tag */
export const Tag = pgTable(
  'Tag',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    title: text().notNull(),
    description: text(),
    emoji: text(),
    color: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    parentId: text().references((): AnyPgColumn => Tag.id, { onUpdate: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    isSystemTag: boolean().default(false).notNull(),
  },
  (table) => [
    index('Tag_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Tag_parentId_idx').using('btree', table.parentId.asc().nullsLast()),
    uniqueIndex('Tag_title_organizationId_parentId_key').using(
      'btree',
      table.title.asc().nullsLast(),
      table.organizationId.asc().nullsLast(),
      table.parentId.asc().nullsLast()
    ),
  ]
)
