// packages/database/src/db/schema/tags-on-article.ts
// Drizzle table: tagsOnArticle (generated by scripts/split-schema.ts)

import { pgTable, text, primaryKey, type AnyPgColumn } from './_shared'

import { Article } from './article'
import { ArticleTag } from './article-tag'

/** Drizzle table for tagsOnArticle */
export const TagsOnArticle = pgTable(
  'TagsOnArticle',
  {
    articleId: text()
      .notNull()
      .references((): AnyPgColumn => Article.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    tagId: text()
      .notNull()
      .references((): AnyPgColumn => ArticleTag.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [primaryKey({ columns: [table.articleId, table.tagId], name: 'TagsOnArticle_pkey' })]
)
