// packages/database/src/db/schema/tags-on-thread.ts
// Drizzle table: tagsOnThread (generated by scripts/split-schema.ts)

import { pgTable, text, timestamp, primaryKey, type AnyPgColumn } from './_shared'

import { Tag } from './tag'
import { Thread } from './thread'

/** Drizzle table for tagsOnThread */
export const TagsOnThread = pgTable(
  'TagsOnThread',
  {
    tagId: text()
      .notNull()
      .references((): AnyPgColumn => Tag.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    threadId: text()
      .notNull()
      .references((): AnyPgColumn => Thread.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    createdBy: text(),
  },
  (table) => [primaryKey({ columns: [table.tagId, table.threadId], name: 'TagsOnThread_pkey' })]
)
