// packages/database/src/db/schema/test-case.ts
// Drizzle table: testCase (generated by scripts/split-schema.ts)

import {
  pgTable,
  index,
  text,
  timestamp,
  integer,
  jsonb,
  type AnyPgColumn,
  testCaseStatus,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'
import { Organization } from './organization'

/** Drizzle table for testCase */
export const TestCase = pgTable(
  'TestCase',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    name: text().notNull(),
    description: text(),
    email: jsonb().notNull(),
    expectedRules: jsonb().notNull(),
    expectedActions: jsonb().notNull(),
    tags: text().array(),
    version: integer().default(1).notNull(),
    status: testCaseStatus().default('ACTIVE').notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    index('TestCase_createdById_idx').using('btree', table.createdById.asc().nullsLast()),
    index('TestCase_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('TestCase_status_idx').using('btree', table.status.asc().nullsLast()),
  ]
)
