// packages/database/src/db/schema/test-case-in-suite.ts
// Drizzle table: testCaseInSuite (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, index, text, timestamp, integer, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { TestSuite } from './test-suite'
import { TestCase } from './test-case'

/** Drizzle table for testCaseInSuite */
export const TestCaseInSuite = pgTable(
  'TestCaseInSuite',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    suiteId: text()
      .notNull()
      .references((): AnyPgColumn => TestSuite.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    testCaseId: text()
      .notNull()
      .references((): AnyPgColumn => TestCase.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    order: integer().default(0).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  },
  (table) => [
    index('TestCaseInSuite_suiteId_idx').using('btree', table.suiteId.asc().nullsLast()),
    uniqueIndex('TestCaseInSuite_suiteId_testCaseId_key').using(
      'btree',
      table.suiteId.asc().nullsLast(),
      table.testCaseId.asc().nullsLast()
    ),
    index('TestCaseInSuite_testCaseId_idx').using('btree', table.testCaseId.asc().nullsLast()),
  ]
)
