// packages/database/src/db/schema/test-suite.ts
// Drizzle table: testSuite (generated by scripts/split-schema.ts)

import { pgTable, index, text, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'
import { Organization } from './organization'

/** Drizzle table for testSuite */
export const TestSuite = pgTable(
  'TestSuite',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    name: text().notNull(),
    description: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    createdById: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
  },
  (table) => [
    index('TestSuite_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
  ]
)
