// packages/database/src/db/schema/thread-participant.ts
// Drizzle table: threadParticipant (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from './_shared'

import { Thread } from './thread'

/** Drizzle table for threadParticipant */
export const ThreadParticipant = pgTable(
  'ThreadParticipant',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    threadId: text()
      .notNull()
      .references((): AnyPgColumn => Thread.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    email: text().notNull(),
    name: text(),
    isInternal: boolean().default(false).notNull(),
    messageCount: integer().default(1).notNull(),
    firstMessageAt: timestamp({ precision: 3 }).notNull(),
    lastMessageAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => [
    uniqueIndex('ThreadParticipant_threadId_email_key').using(
      'btree',
      table.threadId.asc().nullsLast(),
      table.email.asc().nullsLast()
    ),
  ]
)
