// packages/database/src/db/schema/thread.ts
// Drizzle table: thread (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  timestamp,
  integer,
  jsonb,
  type AnyPgColumn,
  threadStatus,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'
import { Integration } from './integration'
import { Organization } from './organization'

/** Drizzle table for thread */
export const Thread = pgTable(
  'Thread',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    externalId: text(),
    subject: text().notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    integrationId: text()
      .notNull()
      .references((): AnyPgColumn => Integration.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    assigneeId: text().references((): AnyPgColumn => User.id, { onUpdate: 'cascade' }),
    status: threadStatus().default('OPEN').notNull(),
    messageCount: integer().default(0).notNull(),
    participantCount: integer().default(0).notNull(),
    firstMessageAt: timestamp({ precision: 3 }),
    lastMessageAt: timestamp({ precision: 3 }),
    closedAt: timestamp({ precision: 3 }),
    repliedAt: timestamp({ precision: 3 }),
    waitingSince: timestamp({ precision: 3 }),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    metadata: jsonb(),
  },
  (table) => [
    uniqueIndex('Thread_integrationId_externalId_key').using(
      'btree',
      table.integrationId.asc().nullsLast(),
      table.externalId.asc().nullsLast()
    ),
    index('Thread_integrationId_idx').using('btree', table.integrationId.asc().nullsLast()),
    index('Thread_lastMessageAt_idx').using('btree', table.lastMessageAt.asc().nullsLast()),
    index('Thread_organizationId_assigneeId_status_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.assigneeId.asc().nullsLast(),
      table.status.asc().nullsLast()
    ),
    index('Thread_organizationId_createdAt_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.createdAt.asc().nullsLast()
    ),
    index('Thread_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Thread_organizationId_status_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.status.asc().nullsLast()
    ),
    index('Thread_status_idx').using('btree', table.status.asc().nullsLast()),
    index('thread_pagination_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.lastMessageAt.desc().nullsFirst(),
      table.id.desc().nullsFirst()
    ),
  ]
)
