// packages/database/src/db/schema/thread-read-status.ts
// Drizzle table: threadReadStatus (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, index, text, boolean, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'
import { Thread } from './thread'
import { User } from './user'

/** Drizzle table for threadReadStatus */
export const ThreadReadStatus = pgTable(
  'ThreadReadStatus',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    threadId: text()
      .notNull()
      .references((): AnyPgColumn => Thread.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    isRead: boolean().default(false).notNull(),
    lastReadAt: timestamp({ precision: 3 }),
    lastSeenMessageId: text(),
  },
  (table) => [
    index('ThreadReadStatus_isRead_idx').using('btree', table.isRead.asc().nullsLast()),
    index('ThreadReadStatus_organizationId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
    index('ThreadReadStatus_organizationId_userId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.userId.asc().nullsLast()
    ),
    index('ThreadReadStatus_threadId_idx').using('btree', table.threadId.asc().nullsLast()),
    uniqueIndex('ThreadReadStatus_threadId_userId_key').using(
      'btree',
      table.threadId.asc().nullsLast(),
      table.userId.asc().nullsLast()
    ),
    index('ThreadReadStatus_userId_idx').using('btree', table.userId.asc().nullsLast()),
    index('ThreadReadStatus_userId_isRead_idx').using(
      'btree',
      table.userId.asc().nullsLast(),
      table.isRead.asc().nullsLast()
    ),
  ]
)
