// packages/database/src/db/schema/ticket-reply.ts
// Drizzle table: ticketReply (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, boolean, index, pgTable, text, timestamp, uniqueIndex } from './_shared'
import { Ticket } from './ticket'
import { User } from './user'

/** Drizzle table for ticketReply */
export const TicketReply = pgTable(
  'TicketReply',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    content: text().notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    messageId: text(),
    senderEmail: text(),
    isFromCustomer: boolean().default(false).notNull(),
    ticketId: text()
      .notNull()
      .references((): AnyPgColumn => Ticket.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    recipientEmail: text(),
    ccEmails: text().array().default(['RAY']),
    createdById: text().references((): AnyPgColumn => User.id, { onUpdate: 'cascade' }),
    mailgunMessageId: text(),
    inReplyTo: text(),
    references: text(),
  },
  (table) => [
    uniqueIndex('TicketReply_mailgunMessageId_key').using(
      'btree',
      table.mailgunMessageId.asc().nullsLast()
    ),
    index('TicketReply_messageId_idx').using('btree', table.messageId.asc().nullsLast()),
    uniqueIndex('TicketReply_messageId_key').using('btree', table.messageId.asc().nullsLast()),
    index('TicketReply_ticketId_idx').using('btree', table.ticketId.asc().nullsLast()),
  ]
)
