// packages/database/src/db/schema/ticket-view.ts
// Drizzle table: ticketView (generated by scripts/split-schema.ts)

import { pgTable, text, boolean, timestamp, jsonb, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for ticketView */
export const TicketView = pgTable(
  'TicketView',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    name: text().notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    isPublic: boolean().default(false).notNull(),
    filters: jsonb().notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => []
)
