// packages/database/src/db/schema/ticket-assignment.ts
// Drizzle table: ticketAssignment (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, boolean, pgTable, text, timestamp, uniqueIndex } from './_shared'
import { Ticket } from './ticket'
import { User } from './user'

/** Drizzle table for ticketAssignment */
export const TicketAssignment = pgTable(
  'TicketAssignment',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    ticketId: text()
      .notNull()
      .references((): AnyPgColumn => Ticket.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    agentId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    isActive: boolean().default(true).notNull(),
    assignedAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => [
    uniqueIndex('TicketAssignment_ticketId_agentId_isActive_key').using(
      'btree',
      table.ticketId.asc().nullsLast(),
      table.agentId.asc().nullsLast(),
      table.isActive.asc().nullsLast()
    ),
  ]
)
