// packages/database/src/db/schema/ticket.ts
// Drizzle table: ticket (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  index,
  text,
  bigint,
  timestamp,
  jsonb,
  type AnyPgColumn,
  ticketPriority,
  ticketStatus,
  ticketType,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { Contact } from './contact'
import { User } from './user'
import { Order } from './order'
import { Organization } from './organization'
import { shopify_customers } from './shopify-customers'

/** Drizzle table for ticket */
export const Ticket = pgTable(
  'Ticket',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    number: text().notNull(),
    title: text().notNull(),
    description: text(),
    type: ticketType().notNull(),
    priority: ticketPriority().default('MEDIUM').notNull(),
    status: ticketStatus().default('OPEN').notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    dueDate: timestamp({ precision: 3 }),
    resolvedAt: timestamp({ precision: 3 }),
    closedAt: timestamp({ precision: 3 }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    emailThreadId: text(),
    createdById: text().references((): AnyPgColumn => User.id, { onUpdate: 'cascade' }),
    parentTicketId: text().references((): AnyPgColumn => Ticket.id, { onUpdate: 'cascade' }),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    orderId: bigint({ mode: 'number' }).references((): AnyPgColumn => Order.id, {
      onUpdate: 'cascade',
    }),
    mailgunMessageId: text(),
    internalReference: text(),
    contactId: text()
      .notNull()
      .references((): AnyPgColumn => Contact.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    shopifyCustomerId: bigint({ mode: 'number' }).references(
      (): AnyPgColumn => shopify_customers.id,
      { onUpdate: 'cascade' }
    ),
    typeData: jsonb().default({}),
    typeStatus: text(),
  },
  (table) => [
    index('Ticket_contactId_idx').using('btree', table.contactId.asc().nullsLast()),
    index('Ticket_emailThreadId_idx').using('btree', table.emailThreadId.asc().nullsLast()),
    uniqueIndex('Ticket_mailgunMessageId_key').using(
      'btree',
      table.mailgunMessageId.asc().nullsLast()
    ),
    index('Ticket_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('Ticket_status_idx').using('btree', table.status.asc().nullsLast()),
    index('Ticket_type_idx').using('btree', table.type.asc().nullsLast()),
  ]
)
