// packages/database/src/db/schema/ticket-note.ts
// Drizzle table: ticketNote (generated by scripts/split-schema.ts)

import { pgTable, index, text, boolean, timestamp, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'
import { Ticket } from './ticket'

/** Drizzle table for ticketNote */
export const TicketNote = pgTable(
  'TicketNote',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    ticketId: text()
      .notNull()
      .references((): AnyPgColumn => Ticket.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    content: text().notNull(),
    authorId: text().references((): AnyPgColumn => User.id, { onUpdate: 'cascade' }),
    isInternal: boolean().default(true).notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => [
    index('TicketNote_authorId_idx').using('btree', table.authorId.asc().nullsLast()),
    index('TicketNote_ticketId_idx').using('btree', table.ticketId.asc().nullsLast()),
  ]
)
