// packages/database/src/db/schema/two-factor.ts
// Drizzle table: twoFactor (generated by scripts/split-schema.ts)

import { pgTable, uniqueIndex, text, type AnyPgColumn } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { User } from './user'

/** Drizzle table for twoFactor */
export const TwoFactor = pgTable(
  'TwoFactor',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    secret: text(),
    backupCodes: text(),
  },
  (table) => [uniqueIndex('TwoFactor_userId_key').using('btree', table.userId.asc().nullsLast())]
)
