// packages/database/src/db/schema/user-setting.ts
// Drizzle table: userSetting (generated by scripts/split-schema.ts)
//
// Settings v2 re-key (plans/settings/v2/README.md §Service refactor): unique
// `(userId, organizationId, key)` with jsonb `value`, replacing the old
// `organizationSettingId` FK to `OrganizationSetting`. Round 1 added
// `organizationId`/`key` nullable alongside the old FK so the ledgered
// DataMigration (`035-usersetting-rekey-backfill`) could backfill them; this
// round tightens both to NOT NULL, adds the composite unique index, and drops
// `organizationSettingId` + its index/unique index now that the backfill has
// run.

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, jsonb, pgTable, text, timestamp, uniqueIndex } from './_shared'

import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for userSetting */
export const UserSetting = pgTable(
  'UserSetting',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    userId: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    key: text().notNull(),
    value: jsonb().notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => [
    index('UserSetting_userId_idx').using('btree', table.userId.asc().nullsLast()),
    index('UserSetting_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
    index('UserSetting_key_idx').using('btree', table.key.asc().nullsLast()),
    uniqueIndex('UserSetting_userId_organizationId_key_key').using(
      'btree',
      table.userId.asc().nullsLast(),
      table.organizationId.asc().nullsLast(),
      table.key.asc().nullsLast()
    ),
  ]
)
