// packages/database/src/db/schema/user.ts
// Drizzle table: user (generated by scripts/split-schema.ts)

import {
  pgTable,
  uniqueIndex,
  text,
  boolean,
  timestamp,
  jsonb,
  type AnyPgColumn,
  userType,
} from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { MediaAsset } from './media-asset'

/** Drizzle table for user */
export const User = pgTable(
  'User',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    name: text(),
    email: text(),
    lastActiveAt: timestamp({ precision: 3 }),
    lastLoginAt: timestamp({ precision: 3, mode: 'date' }),
    preferredTimezone: text(),
    completedOnboarding: boolean().default(false),
    twoFactorEnabled: boolean().default(false),
    hashedPassword: text(),
    watchEmailsExpirationDate: timestamp({ precision: 3 }),
    image: text(),
    about: text(),
    isSuperAdmin: boolean().default(false).notNull(),
    defaultOrganizationId: text(),
    settings: jsonb().default({}).notNull(),
    webhookSecret: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    phoneNumber: text(),
    phoneNumberVerified: boolean().default(false),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    emailVerified: boolean().default(false).notNull(),
    avatarAssetId: text().references((): AnyPgColumn => MediaAsset.id, { onUpdate: 'cascade' }),
    userType: userType().default('USER').notNull(),
    firstName: text(),
    lastName: text(),
  },
  (table) => [
    uniqueIndex('User_avatarAssetId_key').using('btree', table.avatarAssetId.asc().nullsLast()),
    uniqueIndex('User_email_key').using('btree', table.email.asc().nullsLast()),
  ]
)
