// packages/database/src/db/schema/user.ts
// Drizzle table: user (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  userType,
} from './_shared'

import { MediaAsset } from './media-asset'

/** Drizzle table for user */
export const User = pgTable(
  'User',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    name: text(),
    email: text(),
    lastActiveAt: timestamp({ precision: 3 }),
    lastLoginAt: timestamp({ precision: 3, mode: 'date' }),
    preferredTimezone: text(),
    completedOnboarding: boolean().default(false),
    twoFactorEnabled: boolean().default(false),
    hashedPassword: text(),
    watchEmailsExpirationDate: timestamp({ precision: 3 }),
    image: text(),
    about: text(),
    isSuperAdmin: boolean().default(false).notNull(),
    defaultOrganizationId: text(),
    // `settings` (legacy jsonb blob) dropped — settings v2 deletes the
    // `UserSettingsService`/`User.settings` store entirely. See
    // plans/settings/v2/README.md §Deletions.
    webhookSecret: text(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    phoneNumber: text(),
    phoneNumberVerified: boolean().default(false),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    emailVerified: boolean().default(false).notNull(),
    // `onDelete: 'set null'` is load-bearing: `MediaAsset` is org-scoped and cascade-deleted
    // with its Organization, but `User` is not — a user outlives the orgs they belong to. With
    // the default NO ACTION, deleting an org whose member had ever set an avatar aborted the
    // whole cascade with a 23503 on this constraint, so org deletion succeeded or failed purely
    // on whether anyone had uploaded a profile picture. Losing the asset means losing the
    // avatar, which is exactly what null here means.
    avatarAssetId: text().references((): AnyPgColumn => MediaAsset.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
    userType: userType().default('USER').notNull(),
    firstName: text(),
    lastName: text(),
    banned: boolean().default(false).notNull(),
    bannedReason: text(),
    bannedAt: timestamp({ precision: 3 }),
    forcePasswordChange: boolean().default(false).notNull(),
    signupSource: text().default('web').notNull(),
  },
  (table) => [
    uniqueIndex('User_avatarAssetId_key').using('btree', table.avatarAssetId.asc().nullsLast()),
    uniqueIndex('User_email_key').using('btree', table.email.asc().nullsLast()),
  ]
)

export type UserEntity = typeof User.$inferSelect
