// packages/database/src/db/schema/verification.ts
// Drizzle table: verification (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { pgTable, text, timestamp } from './_shared'

/** Drizzle table for verification */
export const verification = pgTable('verification', {
  id: text()
    .$defaultFn(() => createId())
    .primaryKey()
    .notNull(),
  identifier: text().notNull(),
  value: text().notNull(),
  expiresAt: timestamp({ precision: 3 }).notNull(),
  createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
  updatedAt: timestamp({ precision: 3 }).notNull(),
})
