// packages/database/src/db/schema/webhook.ts
// Drizzle table: webhook (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, boolean, index, pgTable, text, timestamp } from './_shared'

import { Organization } from './organization'

/** Drizzle table for webhook */
export const Webhook = pgTable(
  'Webhook',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    name: text().notNull(),
    url: text().notNull(),
    secret: text().notNull(),
    isActive: boolean().default(true).notNull(),
    eventTypes: text().array(),
    lastTriggeredAt: timestamp({ precision: 3 }),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
  },
  (table) => [
    index('Webhook_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
  ]
)
