// packages/database/src/db/schema/webhook-event.ts
// Drizzle table: webhookEvent (generated by scripts/split-schema.ts)

import { pgTable, index, text, timestamp, integer, type AnyPgColumn, syncStatus } from './_shared'
import { createId } from '@paralleldrive/cuid2'

import { ShopifyIntegration } from './shopify-integration'
import { Organization } from './organization'
import { Subscription } from './subscription'

/** Drizzle table for webhookEvent */
export const WebhookEvent = pgTable(
  'WebhookEvent',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    retryCount: integer().default(0).notNull(),
    payload: text().notNull(),
    headers: text(),
    subscriptionId: text()
      .notNull()
      .references((): AnyPgColumn => Subscription.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    integrationId: text()
      .notNull()
      .references((): AnyPgColumn => ShopifyIntegration.id, {
        onUpdate: 'cascade',
        onDelete: 'cascade',
      }),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    topic: text().notNull(),
    eventId: text().notNull(),
    status: syncStatus().default('PENDING').notNull(),
    startTime: timestamp({ precision: 3 }),
    endTime: timestamp({ precision: 3 }),
    error: text(),
  },
  (table) => [
    index('WebhookEvent_integrationId_idx').using('btree', table.integrationId.asc().nullsLast()),
    index('WebhookEvent_organizationId_idx').using('btree', table.organizationId.asc().nullsLast()),
  ]
)
