// packages/database/src/db/schema/workflow.ts
// Drizzle table: workflow (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
} from './_shared'
import { Organization } from './organization'
import { User } from './user'
import { WorkflowApp } from './workflow-app'

/** Drizzle table for workflow */
export const Workflow = pgTable(
  'Workflow',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    name: text().notNull(),
    description: text(),
    enabled: boolean().default(true).notNull(),
    version: integer().default(1).notNull(),
    triggerType: text(), // 'form', 'manual', 'created', 'updated', 'deleted', 'scheduled', 'message-received'
    entityDefinitionId: text(), // Entity identifier (system or custom) - nullable for form/scheduled/message-received triggers
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),
    createdById: text().references((): AnyPgColumn => User.id, { onUpdate: 'cascade' }),
    envVars: jsonb('env_vars'),
    graph: jsonb(),
    workflowAppId: text()
      .notNull()
      .references((): AnyPgColumn => WorkflowApp.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    variables: jsonb(),
  },
  (table) => [
    index('Workflow_organizationId_enabled_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.enabled.asc().nullsLast()
    ),
    index('Workflow_orgId_triggerType_entityDefId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.triggerType.asc().nullsLast(),
      table.entityDefinitionId.asc().nullsLast()
    ),
  ]
)
