// packages/database/src/db/schema/workflow-credentials.ts
// Drizzle table: workflowCredentials (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import { type AnyPgColumn, index, integer, pgTable, text, timestamp } from './_shared'
import { App } from './app'
import { AppInstallation } from './app-installation'
import { Organization } from './organization'
import { User } from './user'

/** Drizzle table for workflowCredentials */
export const WorkflowCredentials = pgTable(
  'WorkflowCredentials',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    createdById: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),

    // App connection fields
    userId: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    appId: text().references((): AnyPgColumn => App.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    appInstallationId: text().references((): AnyPgColumn => AppInstallation.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),

    name: text().notNull(),
    type: text().notNull(),
    encryptedData: text().notNull(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    updatedAt: timestamp({ precision: 3 }).notNull(),

    // OAuth2 token expiration and refresh tracking
    expiresAt: timestamp({ precision: 3 }), // Duplicated from encrypted data for querying
    lastTokenRefreshAt: timestamp({ precision: 3 }), // Last successful token refresh
    lastRefreshFailureAt: timestamp({ precision: 3 }), // Last failed refresh attempt
    consecutiveRefreshFailures: integer().default(0).notNull(), // Circuit breaker counter
  },
  (table) => [
    index('WorkflowCredentials_createdById_idx').using(
      'btree',
      table.createdById.asc().nullsLast()
    ),
    index('WorkflowCredentials_organizationId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast()
    ),
    index('WorkflowCredentials_organizationId_type_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.type.asc().nullsLast()
    ),
    // App connection indexes
    index('WorkflowCredentials_appId_organizationId_idx').using(
      'btree',
      table.appId.asc().nullsLast(),
      table.organizationId.asc().nullsLast()
    ),
    index('WorkflowCredentials_userId_appId_idx').using(
      'btree',
      table.userId.asc().nullsLast(),
      table.appId.asc().nullsLast()
    ),
    index('WorkflowCredentials_appInstallationId_idx').using(
      'btree',
      table.appInstallationId.asc().nullsLast()
    ),
    // OAuth2 refresh indexes
    index('WorkflowCredentials_expiresAt_idx').using('btree', table.expiresAt.asc().nullsLast()),
    index('WorkflowCredentials_lastTokenRefreshAt_idx').using(
      'btree',
      table.lastTokenRefreshAt.asc().nullsLast()
    ),
  ]
)
