// packages/database/src/db/schema/workflow-node-execution.ts
// Drizzle table: workflowNodeExecution (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  doublePrecision,
  index,
  integer,
  jsonb,
  nodeExecutionStatus,
  nodeTriggerSource,
  pgTable,
  text,
  timestamp,
} from './_shared'
import { Organization } from './organization'
import { User } from './user'
import { Workflow } from './workflow'
import { WorkflowApp } from './workflow-app'
import { WorkflowRun } from './workflow-run'

/** Drizzle table for workflowNodeExecution */
export const WorkflowNodeExecution = pgTable(
  'WorkflowNodeExecution',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    workflowAppId: text()
      .notNull()
      .references((): AnyPgColumn => WorkflowApp.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    workflowId: text()
      .notNull()
      .references((): AnyPgColumn => Workflow.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    triggeredFrom: nodeTriggerSource().notNull(),
    workflowRunId: text().references((): AnyPgColumn => WorkflowRun.id, {
      onUpdate: 'cascade',
      onDelete: 'cascade',
    }),
    index: integer().notNull(),
    predecessorNodeId: text(),
    nodeId: text().notNull(),
    nodeType: text().notNull(),
    title: text().notNull(),
    inputs: jsonb(),
    processData: jsonb(),
    outputs: jsonb(),
    status: nodeExecutionStatus().notNull(),
    error: text(),
    elapsedTime: doublePrecision(),
    executionMetadata: jsonb(),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    finishedAt: timestamp({ precision: 3 }),
    createdById: text().references((): AnyPgColumn => User.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
  },
  (table) => [
    index('WorkflowNodeExecution_nodeId_idx').using('btree', table.nodeId.asc().nullsLast()),
    index('WorkflowNodeExecution_status_idx').using('btree', table.status.asc().nullsLast()),
    index('WorkflowNodeExecution_workflowRunId_idx').using(
      'btree',
      table.workflowRunId.asc().nullsLast()
    ),
  ]
)
