// packages/database/src/db/schema/workflow-run.ts
// Drizzle table: workflowRun (generated by scripts/split-schema.ts)

import { createId } from '@paralleldrive/cuid2'
import {
  type AnyPgColumn,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  workflowRunStatus,
  workflowTriggerSource,
} from './_shared'
import { EndUser } from './end-user'
import { Organization } from './organization'
import { User } from './user'
import { Workflow } from './workflow'
import { WorkflowApp } from './workflow-app'

/** Drizzle table for workflowRun */
export const WorkflowRun = pgTable(
  'WorkflowRun',
  {
    id: text()
      .$defaultFn(() => createId())
      .primaryKey()
      .notNull(),
    organizationId: text()
      .notNull()
      .references((): AnyPgColumn => Organization.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    workflowAppId: text()
      .notNull()
      .references((): AnyPgColumn => WorkflowApp.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    sequenceNumber: integer().notNull(),
    workflowId: text()
      .notNull()
      .references((): AnyPgColumn => Workflow.id, { onUpdate: 'cascade', onDelete: 'cascade' }),
    type: text().notNull(),
    triggeredFrom: workflowTriggerSource().notNull(),
    version: text().notNull(),
    graph: jsonb().notNull(),
    inputs: jsonb().notNull(),
    outputs: jsonb(),
    status: workflowRunStatus().notNull(),
    error: text(),
    elapsedTime: doublePrecision(),
    totalTokens: integer().default(0).notNull(),
    totalSteps: integer().default(0).notNull(),
    createdBy: text()
      .notNull()
      .references((): AnyPgColumn => User.id, { onUpdate: 'cascade', onDelete: 'restrict' }),
    createdAt: timestamp({ precision: 3 }).defaultNow().notNull(),
    finishedAt: timestamp({ precision: 3 }),
    pausedAt: timestamp({ precision: 3 }),
    pausedNodeId: text(),
    resumeAt: timestamp({ precision: 3 }),
    serializedState: jsonb(),
    /** End user who triggered this run (for public workflow runs) */
    endUserId: text().references((): AnyPgColumn => EndUser.id, {
      onUpdate: 'cascade',
      onDelete: 'set null',
    }),
  },
  (table) => [
    index('WorkflowRun_createdAt_idx').using('btree', table.createdAt.asc().nullsLast()),
    index('WorkflowRun_organizationId_workflowAppId_idx').using(
      'btree',
      table.organizationId.asc().nullsLast(),
      table.workflowAppId.asc().nullsLast()
    ),
    index('WorkflowRun_resumeAt_idx').using('btree', table.resumeAt.asc().nullsLast()),
    index('WorkflowRun_status_idx').using('btree', table.status.asc().nullsLast()),
    index('WorkflowRun_workflowId_idx').using('btree', table.workflowId.asc().nullsLast()),
  ]
)
