// apps/web/scripts/copy-pdfjs-assets.ts

/**
 * Copy pdf.js's runtime assets into `public/pdfjs/<version>/`.
 *
 * pdf.js does not bundle these. It fetches them **at runtime, by URL**, and in
 * `pdfjs-dist@6.3.289` every one of the options that names them defaults to
 * `null` (verified in `build/pdf.mjs`). Skip this step and the failures are
 * silent and type-specific:
 *
 * - `cmaps/`         , CJK text with non-embedded fonts renders as blank boxes.
 *                       Not hypothetical: our vendor quotes come from Chinese
 *                       suppliers.
 * - `standard_fonts/`, the 14 standard PDF fonts, when a document does not
 *                       embed them.
 * - `wasm/`          , JPEG 2000 and JBIG2 image decoding, i.e. scanned bills.
 * - `iccs/`          , ICC colour profiles.
 *
 * The worker is copied here too rather than resolved through the bundler. We
 * need a copy step for the four directories above regardless, and `apps/web`
 * builds two different ways (`build` uses `--turbopack`, `build:prod` does not),
 * so one mechanism that is identical in both beats saving four lines.
 *
 * The version is in the path so a `pdfjs-dist` bump is self-busting, the client
 * builds the URL from `pdfjs.version` at runtime, so old and new never collide
 * in a CDN or a service worker.
 *
 * Runs from `predev` and `prebuild`, so a fresh clone needs no manual step.
 * `apps/web`'s `build` script already does `cp -r public .next/standalone/...`,
 * which picks these up with no further change.
 */

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const appRoot = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Directories pdf.js fetches from at runtime, copied verbatim. */
const ASSET_DIRS = ['cmaps', 'standard_fonts', 'wasm', 'iccs'] as const

/** The worker entry. Its filename is also what `pdf-viewer.tsx` hardcodes. */
const WORKER_FILE = 'pdf.worker.min.mjs'

const GITIGNORE = `# Generated by apps/web/scripts/copy-pdfjs-assets.ts (predev / prebuild).
# Source of truth is the \`pdfjs-dist\` package; never edit anything in here.
*/
`

function main() {
  const pkgPath = require.resolve('pdfjs-dist/package.json')
  const pkgDir = dirname(pkgPath)
  const { version } = JSON.parse(readFileSync(pkgPath, 'utf8')) as { version: string }

  const outRoot = join(appRoot, 'public', 'pdfjs')
  const outDir = join(outRoot, version)

  mkdirSync(outRoot, { recursive: true })
  writeFileSync(join(outRoot, '.gitignore'), GITIGNORE)

  // Already current. The version is in the path, so a stale copy is impossible
  // for a version that exists, only a half-written one, which the rm covers.
  if (existsSync(join(outDir, WORKER_FILE))) {
    console.log(`pdfjs assets already present for ${version}`)
    return
  }

  rmSync(outDir, { recursive: true, force: true })
  mkdirSync(outDir, { recursive: true })

  cpSync(join(pkgDir, 'build', WORKER_FILE), join(outDir, WORKER_FILE))
  for (const dir of ASSET_DIRS) {
    const from = join(pkgDir, dir)
    if (!existsSync(from)) {
      // A future pdfjs-dist could drop or rename one of these. Loud, but not
      // fatal, a missing cmaps directory degrades CJK rendering, it does not
      // break the build.
      console.warn(`pdfjs: expected directory "${dir}" not found in ${pkgDir}`)
      continue
    }
    cpSync(from, join(outDir, dir), { recursive: true })
  }

  console.log(`pdfjs assets copied to public/pdfjs/${version}/`)
}

main()
