// packages/ui/src/components/emojis.ts

import type { LucideIcon } from 'lucide-react'
import { Coffee, Flag, Gamepad2, Hash, MapPin, Package, Smile, TreePine } from 'lucide-react'

/** Emoji item definition */
export interface EmojiItem {
  /** Unique identifier (e.g., ':grinning_face:') */
  id: string
  /** Display name */
  label: string
  /** Emoji character */
  emoji: string
  /** Whether this emoji supports skin tone modifiers */
  supportsSkinTone?: boolean
}

/** Available skin tone modifiers */
export const SKIN_TONES = ['', '🏻', '🏼', '🏽', '🏾', '🏿'] as const

/** Skin tone type */
export type SkinTone = (typeof SKIN_TONES)[number]

/** Skin tone color mapping for UI display */
export const SKIN_TONE_COLORS: Record<SkinTone, string> = {
  '': 'bg-yellow-400',
  '🏻': 'bg-[#FFDBB4]',
  '🏼': 'bg-[#EDB98A]',
  '🏽': 'bg-[#C68642]',
  '🏾': 'bg-[#8D5524]',
  '🏿': 'bg-[#5C3317]',
}

/** Zero Width Joiner character used in emoji sequences */
const ZWJ = '\u200D'

/** Variation Selector 16 - forces emoji presentation */
const VS16 = '\uFE0F'

/**
 * Applies a skin tone modifier to an emoji.
 * Inserts skin tone after the base emoji but before any ZWJ or FE0F.
 * For simple emojis, appends the skin tone at the end.
 */
export function applyEmojiSkinTone(emoji: string, skinTone: SkinTone): string {
  if (!skinTone) return emoji

  // Find the first occurrence of ZWJ or VS16 (variation selector)
  const zwjIndex = emoji.indexOf(ZWJ)
  const vs16Index = emoji.indexOf(VS16)

  // Get the earliest modifier position (ignoring -1 values)
  let insertIndex = -1
  if (zwjIndex !== -1 && vs16Index !== -1) {
    insertIndex = Math.min(zwjIndex, vs16Index)
  } else if (zwjIndex !== -1) {
    insertIndex = zwjIndex
  } else if (vs16Index !== -1) {
    insertIndex = vs16Index
  }

  if (insertIndex !== -1) {
    return emoji.slice(0, insertIndex) + skinTone + emoji.slice(insertIndex)
  }

  return emoji + skinTone
}

/** Emoji group/category definition */
export interface EmojiGroup {
  /** Unique identifier (e.g., 'smileys') */
  id: string
  /** Display name */
  label: string
  /** Lucide icon for the group tab */
  icon: LucideIcon
}

/** Emoji category groups */
export const EMOJI_GROUPS: EmojiGroup[] = [
  { id: 'smileys', label: 'Smileys and People', icon: Smile },
  { id: 'animals', label: 'Animals and Nature', icon: TreePine },
  { id: 'food', label: 'Food and Drink', icon: Coffee },
  { id: 'activity', label: 'Activity', icon: Gamepad2 },
  { id: 'travel', label: 'Travel and Places', icon: MapPin },
  { id: 'objects', label: 'Objects', icon: Package },
  { id: 'symbols', label: 'Symbols', icon: Hash },
  { id: 'flags', label: 'Flags', icon: Flag },
]

/** Emoji data organized by category */
export const EMOJI_DATA: Record<string, EmojiItem[]> = {
  smileys: [
    { id: ':grinning_face:', label: 'Grinning face', emoji: '😀' },
    { id: ':grinning_face_with_big_eyes:', label: 'Grinning face with big eyes', emoji: '😃' },
    {
      id: ':grinning_face_with_smiling_eyes:',
      label: 'Grinning face with smiling eyes',
      emoji: '😄',
    },
    {
      id: ':beaming_face_with_smiling_eyes:',
      label: 'Beaming face with smiling eyes',
      emoji: '😁',
    },
    { id: ':grinning_squinting_face:', label: 'Grinning squinting face', emoji: '😆' },
    { id: ':grinning_face_with_sweat:', label: 'Grinning face with sweat', emoji: '😅' },
    { id: ':rolling_on_the_floor_laughing:', label: 'Rolling on the floor laughing', emoji: '🤣' },
    { id: ':face_with_tears_of_joy:', label: 'Face with tears of joy', emoji: '😂' },
    { id: ':slightly_smiling_face:', label: 'Slightly smiling face', emoji: '🙂' },
    { id: ':upside_down_face:', label: 'Upside down face', emoji: '🙃' },
    { id: ':winking_face:', label: 'Winking face', emoji: '😉' },
    {
      id: ':smiling_face_with_smiling_eyes:',
      label: 'Smiling face with smiling eyes',
      emoji: '😊',
    },
    { id: ':smiling_face_with_halo:', label: 'Smiling face with halo', emoji: '😇' },
    { id: ':smiling_face_with_hearts:', label: 'Smiling face with hearts', emoji: '🥰' },
    { id: ':smiling_face_with_heart-eyes:', label: 'Smiling face with heart-eyes', emoji: '😍' },
    { id: ':star-struck:', label: 'Star-struck', emoji: '🤩' },
    { id: ':face_blowing_a_kiss:', label: 'Face blowing a kiss', emoji: '😘' },
    { id: ':kissing_face:', label: 'Kissing face', emoji: '😗' },
    { id: ':smiling_face:', label: 'Smiling face', emoji: '☺️' },
    { id: ':kissing_face_with_closed_eyes:', label: 'Kissing face with closed eyes', emoji: '😚' },
    {
      id: ':kissing_face_with_smiling_eyes:',
      label: 'Kissing face with smiling eyes',
      emoji: '😙',
    },
    { id: ':face_savoring_food:', label: 'Face savoring food', emoji: '😋' },
    { id: ':face_with_tongue:', label: 'Face with tongue', emoji: '😛' },
    { id: ':winking_face_with_tongue:', label: 'Winking face with tongue', emoji: '😜' },
    { id: ':zany_face:', label: 'Zany face', emoji: '🤪' },
    { id: ':squinting_face_with_tongue:', label: 'Squinting face with tongue', emoji: '😝' },
    { id: ':money-mouth_face:', label: 'Money-mouth face', emoji: '🤑' },
    { id: ':smiling_face_with_open_hands:', label: 'Smiling face with open hands', emoji: '🤗' },
    { id: ':face_with_hand_over_mouth:', label: 'Face with hand over mouth', emoji: '🤭' },
    { id: ':shushing_face:', label: 'Shushing face', emoji: '🤫' },
    { id: ':thinking_face:', label: 'Thinking face', emoji: '🤔' },
    { id: ':zipper-mouth_face:', label: 'Zipper-mouth face', emoji: '🤐' },
    { id: ':face_with_raised_eyebrow:', label: 'Face with raised eyebrow', emoji: '🤨' },
    { id: ':neutral_face:', label: 'Neutral face', emoji: '😐' },
    { id: ':expressionless_face:', label: 'Expressionless face', emoji: '😑' },
    { id: ':face_without_mouth:', label: 'Face without mouth', emoji: '😶' },
    { id: ':smirking_face:', label: 'Smirking face', emoji: '😏' },
    { id: ':unamused_face:', label: 'Unamused face', emoji: '😒' },
    { id: ':face_with_rolling_eyes:', label: 'Face with rolling eyes', emoji: '🙄' },
    { id: ':grimacing_face:', label: 'Grimacing face', emoji: '😬' },
    { id: ':lying_face:', label: 'Lying face', emoji: '🤥' },
    { id: ':pensive_face:', label: 'Pensive face', emoji: '😔' },
    { id: ':sleepy_face:', label: 'Sleepy face', emoji: '😪' },
    { id: ':drooling_face:', label: 'Drooling face', emoji: '🤤' },
    { id: ':sleeping_face:', label: 'Sleeping face', emoji: '😴' },
    { id: ':face_with_medical_mask:', label: 'Face with medical mask', emoji: '😷' },
    { id: ':face_with_thermometer:', label: 'Face with thermometer', emoji: '🤒' },
    { id: ':face_with_head-bandage:', label: 'Face with head-bandage', emoji: '🤕' },
    { id: ':nauseated_face:', label: 'Nauseated face', emoji: '🤢' },
    { id: ':face_vomiting:', label: 'Face vomiting', emoji: '🤮' },
    { id: ':sneezing_face:', label: 'Sneezing face', emoji: '🤧' },
    { id: ':hot_face:', label: 'Hot face', emoji: '🥵' },
    { id: ':cold_face:', label: 'Cold face', emoji: '🥶' },
    { id: ':woozy_face:', label: 'Woozy face', emoji: '🥴' },
    { id: ':face_with_crossed-out_eyes:', label: 'Face with crossed-out eyes', emoji: '😵' },
    { id: ':exploding_head:', label: 'Exploding head', emoji: '🤯' },
    { id: ':cowboy_hat_face:', label: 'Cowboy hat face', emoji: '🤠' },
    { id: ':partying_face:', label: 'Partying face', emoji: '🥳' },
    { id: ':smiling_face_with_sunglasses:', label: 'Smiling face with sunglasses', emoji: '😎' },
    { id: ':nerd_face:', label: 'Nerd face', emoji: '🤓' },
    { id: ':face_with_monocle:', label: 'Face with monocle', emoji: '🧐' },
    // Negative emotions
    { id: ':confused_face:', label: 'Confused face', emoji: '😕' },
    { id: ':worried_face:', label: 'Worried face', emoji: '😟' },
    { id: ':slightly_frowning_face:', label: 'Slightly frowning face', emoji: '🙁' },
    { id: ':frowning_face:', label: 'Frowning face', emoji: '☹️' },
    { id: ':face_with_open_mouth:', label: 'Face with open mouth', emoji: '😮' },
    { id: ':hushed_face:', label: 'Hushed face', emoji: '😯' },
    { id: ':astonished_face:', label: 'Astonished face', emoji: '😲' },
    { id: ':flushed_face:', label: 'Flushed face', emoji: '😳' },
    { id: ':pleading_face:', label: 'Pleading face', emoji: '🥺' },
    { id: ':smiling_face_with_tear:', label: 'Smiling face with tear', emoji: '🥲' },
    { id: ':face_holding_back_tears:', label: 'Face holding back tears', emoji: '🥹' },
    { id: ':frowning_face_with_open_mouth:', label: 'Frowning face with open mouth', emoji: '😦' },
    { id: ':anguished_face:', label: 'Anguished face', emoji: '😧' },
    { id: ':fearful_face:', label: 'Fearful face', emoji: '😨' },
    { id: ':anxious_face_with_sweat:', label: 'Anxious face with sweat', emoji: '😰' },
    { id: ':sad_but_relieved_face:', label: 'Sad but relieved face', emoji: '😥' },
    { id: ':crying_face:', label: 'Crying face', emoji: '😢' },
    { id: ':loudly_crying_face:', label: 'Loudly crying face', emoji: '😭' },
    { id: ':face_screaming_in_fear:', label: 'Face screaming in fear', emoji: '😱' },
    { id: ':confounded_face:', label: 'Confounded face', emoji: '😖' },
    { id: ':persevering_face:', label: 'Persevering face', emoji: '😣' },
    { id: ':disappointed_face:', label: 'Disappointed face', emoji: '😞' },
    { id: ':downcast_face_with_sweat:', label: 'Downcast face with sweat', emoji: '😓' },
    { id: ':weary_face:', label: 'Weary face', emoji: '😩' },
    { id: ':tired_face:', label: 'Tired face', emoji: '😫' },
    { id: ':yawning_face:', label: 'Yawning face', emoji: '🥱' },
    { id: ':face_with_steam_from_nose:', label: 'Face with steam from nose', emoji: '😤' },
    { id: ':pouting_face:', label: 'Pouting face', emoji: '😡' },
    { id: ':angry_face:', label: 'Angry face', emoji: '😠' },
    { id: ':face_with_symbols_on_mouth:', label: 'Face with symbols on mouth', emoji: '🤬' },
    { id: ':smiling_face_with_horns:', label: 'Smiling face with horns', emoji: '😈' },
    { id: ':angry_face_with_horns:', label: 'Angry face with horns', emoji: '👿' },
    // Newer face emojis (2020+)
    { id: ':melting_face:', label: 'Melting face', emoji: '🫠' },
    {
      id: ':face_with_open_eyes_and_hand_over_mouth:',
      label: 'Face with open eyes and hand over mouth',
      emoji: '🫢',
    },
    { id: ':face_with_peeking_eye:', label: 'Face with peeking eye', emoji: '🫣' },
    { id: ':saluting_face:', label: 'Saluting face', emoji: '🫡' },
    { id: ':face_with_diagonal_mouth:', label: 'Face with diagonal mouth', emoji: '🫤' },
    { id: ':dotted_line_face:', label: 'Dotted line face', emoji: '🫥' },
    { id: ':face_in_clouds:', label: 'Face in clouds', emoji: '😶‍🌫️' },
    { id: ':face_exhaling:', label: 'Face exhaling', emoji: '😮‍💨' },
    { id: ':face_with_spiral_eyes:', label: 'Face with spiral eyes', emoji: '😵‍💫' },
    { id: ':shaking_face:', label: 'Shaking face', emoji: '🫨' },
    // Fantasy and creature faces
    { id: ':skull:', label: 'Skull', emoji: '💀' },
    { id: ':skull_and_crossbones:', label: 'Skull and crossbones', emoji: '☠️' },
    { id: ':pile_of_poo:', label: 'Pile of poo', emoji: '💩' },
    { id: ':clown_face:', label: 'Clown face', emoji: '🤡' },
    { id: ':ogre:', label: 'Ogre', emoji: '👹' },
    { id: ':goblin:', label: 'Goblin', emoji: '👺' },
    { id: ':ghost:', label: 'Ghost', emoji: '👻' },
    { id: ':alien:', label: 'Alien', emoji: '👽' },
    { id: ':alien_monster:', label: 'Alien monster', emoji: '👾' },
    { id: ':robot:', label: 'Robot', emoji: '🤖' },
    { id: ':jack-o-lantern:', label: 'Jack-o-lantern', emoji: '🎃' },
    // Cat faces
    { id: ':grinning_cat:', label: 'Grinning cat', emoji: '😺' },
    {
      id: ':grinning_cat_with_smiling_eyes:',
      label: 'Grinning cat with smiling eyes',
      emoji: '😸',
    },
    { id: ':cat_with_tears_of_joy:', label: 'Cat with tears of joy', emoji: '😹' },
    { id: ':smiling_cat_with_heart-eyes:', label: 'Smiling cat with heart-eyes', emoji: '😻' },
    { id: ':cat_with_wry_smile:', label: 'Cat with wry smile', emoji: '😼' },
    { id: ':kissing_cat:', label: 'Kissing cat', emoji: '😽' },
    { id: ':weary_cat:', label: 'Weary cat', emoji: '🙀' },
    { id: ':crying_cat:', label: 'Crying cat', emoji: '😿' },
    { id: ':pouting_cat:', label: 'Pouting cat', emoji: '😾' },
    // Body parts
    { id: ':kiss_mark:', label: 'Kiss mark', emoji: '💋' },
    { id: ':mouth:', label: 'Mouth', emoji: '👄' },
    { id: ':biting_lip:', label: 'Biting lip', emoji: '🫦' },
    { id: ':tongue:', label: 'Tongue', emoji: '👅' },
    { id: ':eye:', label: 'Eye', emoji: '👁️' },
    { id: ':eyes:', label: 'Eyes', emoji: '👀' },
    { id: ':nose:', label: 'Nose', emoji: '👃', supportsSkinTone: true },
    { id: ':ear:', label: 'Ear', emoji: '👂', supportsSkinTone: true },
    {
      id: ':ear_with_hearing_aid:',
      label: 'Ear with hearing aid',
      emoji: '🦻',
      supportsSkinTone: true,
    },
    { id: ':brain:', label: 'Brain', emoji: '🧠' },
    { id: ':anatomical_heart:', label: 'Anatomical heart', emoji: '🫀' },
    { id: ':lungs:', label: 'Lungs', emoji: '🫁' },
    { id: ':tooth:', label: 'Tooth', emoji: '🦷' },
    { id: ':bone:', label: 'Bone', emoji: '🦴' },
    // Hand gestures
    { id: ':waving_hand:', label: 'Waving hand', emoji: '👋', supportsSkinTone: true },
    {
      id: ':raised_back_of_hand:',
      label: 'Raised back of hand',
      emoji: '🤚',
      supportsSkinTone: true,
    },
    {
      id: ':hand_with_fingers_splayed:',
      label: 'Hand with fingers splayed',
      emoji: '🖐️',
      supportsSkinTone: true,
    },
    { id: ':raised_hand:', label: 'Raised hand', emoji: '✋', supportsSkinTone: true },
    { id: ':vulcan_salute:', label: 'Vulcan salute', emoji: '🖖', supportsSkinTone: true },
    { id: ':ok_hand:', label: 'OK hand', emoji: '👌', supportsSkinTone: true },
    { id: ':pinched_fingers:', label: 'Pinched fingers', emoji: '🤌', supportsSkinTone: true },
    { id: ':pinching_hand:', label: 'Pinching hand', emoji: '🤏', supportsSkinTone: true },
    { id: ':victory_hand:', label: 'Victory hand', emoji: '✌️', supportsSkinTone: true },
    { id: ':crossed_fingers:', label: 'Crossed fingers', emoji: '🤞', supportsSkinTone: true },
    { id: ':love-you_gesture:', label: 'Love-you gesture', emoji: '🤟', supportsSkinTone: true },
    { id: ':sign_of_the_horns:', label: 'Sign of the horns', emoji: '🤘', supportsSkinTone: true },
    { id: ':call_me_hand:', label: 'Call me hand', emoji: '🤙', supportsSkinTone: true },
    {
      id: ':backhand_index_pointing_left:',
      label: 'Backhand index pointing left',
      emoji: '👈',
      supportsSkinTone: true,
    },
    {
      id: ':backhand_index_pointing_right:',
      label: 'Backhand index pointing right',
      emoji: '👉',
      supportsSkinTone: true,
    },
    {
      id: ':backhand_index_pointing_up:',
      label: 'Backhand index pointing up',
      emoji: '👆',
      supportsSkinTone: true,
    },
    {
      id: ':backhand_index_pointing_down:',
      label: 'Backhand index pointing down',
      emoji: '👇',
      supportsSkinTone: true,
    },
    { id: ':index_pointing_up:', label: 'Index pointing up', emoji: '☝️', supportsSkinTone: true },
    { id: ':thumbs_up:', label: 'Thumbs up', emoji: '👍', supportsSkinTone: true },
    { id: ':thumbs_down:', label: 'Thumbs down', emoji: '👎', supportsSkinTone: true },
    { id: ':raised_fist:', label: 'Raised fist', emoji: '✊', supportsSkinTone: true },
    { id: ':oncoming_fist:', label: 'Oncoming fist', emoji: '👊', supportsSkinTone: true },
    { id: ':left-facing_fist:', label: 'Left-facing fist', emoji: '🤛', supportsSkinTone: true },
    { id: ':right-facing_fist:', label: 'Right-facing fist', emoji: '🤜', supportsSkinTone: true },
    { id: ':clapping_hands:', label: 'Clapping hands', emoji: '👏', supportsSkinTone: true },
    { id: ':raising_hands:', label: 'Raising hands', emoji: '🙌', supportsSkinTone: true },
    { id: ':open_hands:', label: 'Open hands', emoji: '👐', supportsSkinTone: true },
    { id: ':palms_up_together:', label: 'Palms up together', emoji: '🤲', supportsSkinTone: true },
    { id: ':handshake:', label: 'Handshake', emoji: '🤝', supportsSkinTone: true },
    { id: ':folded_hands:', label: 'Folded hands', emoji: '🙏', supportsSkinTone: true },
    { id: ':writing_hand:', label: 'Writing hand', emoji: '✍️', supportsSkinTone: true },
    { id: ':nail_polish:', label: 'Nail polish', emoji: '💅', supportsSkinTone: true },
    { id: ':selfie:', label: 'Selfie', emoji: '🤳', supportsSkinTone: true },
    { id: ':flexed_biceps:', label: 'Flexed biceps', emoji: '💪', supportsSkinTone: true },
    { id: ':mechanical_arm:', label: 'Mechanical arm', emoji: '🦾' },
    { id: ':mechanical_leg:', label: 'Mechanical leg', emoji: '🦿' },
    { id: ':leg:', label: 'Leg', emoji: '🦵', supportsSkinTone: true },
    { id: ':foot:', label: 'Foot', emoji: '🦶', supportsSkinTone: true },
    // Newer hand gestures (2020+)
    { id: ':rightwards_hand:', label: 'Rightwards hand', emoji: '🫱', supportsSkinTone: true },
    { id: ':leftwards_hand:', label: 'Leftwards hand', emoji: '🫲', supportsSkinTone: true },
    { id: ':palm_down_hand:', label: 'Palm down hand', emoji: '🫳', supportsSkinTone: true },
    { id: ':palm_up_hand:', label: 'Palm up hand', emoji: '🫴', supportsSkinTone: true },
    {
      id: ':index_pointing_at_the_viewer:',
      label: 'Index pointing at the viewer',
      emoji: '🫵',
      supportsSkinTone: true,
    },
    { id: ':heart_hands:', label: 'Heart hands', emoji: '🫶', supportsSkinTone: true },
    {
      id: ':hand_with_index_finger_and_thumb_crossed:',
      label: 'Hand with index finger and thumb crossed',
      emoji: '🫰',
      supportsSkinTone: true,
    },
    {
      id: ':leftwards_pushing_hand:',
      label: 'Leftwards pushing hand',
      emoji: '🫷',
      supportsSkinTone: true,
    },
    {
      id: ':rightwards_pushing_hand:',
      label: 'Rightwards pushing hand',
      emoji: '🫸',
      supportsSkinTone: true,
    },
    // People
    { id: ':baby:', label: 'Baby', emoji: '👶', supportsSkinTone: true },
    { id: ':child:', label: 'Child', emoji: '🧒', supportsSkinTone: true },
    { id: ':boy:', label: 'Boy', emoji: '👦', supportsSkinTone: true },
    { id: ':girl:', label: 'Girl', emoji: '👧', supportsSkinTone: true },
    { id: ':person:', label: 'Person', emoji: '🧑', supportsSkinTone: true },
    { id: ':man:', label: 'Man', emoji: '👨', supportsSkinTone: true },
    { id: ':woman:', label: 'Woman', emoji: '👩', supportsSkinTone: true },
    { id: ':older_person:', label: 'Older person', emoji: '🧓', supportsSkinTone: true },
    { id: ':old_man:', label: 'Old man', emoji: '👴', supportsSkinTone: true },
    { id: ':old_woman:', label: 'Old woman', emoji: '👵', supportsSkinTone: true },
    // Person with hair/appearance variations
    { id: ':person_blond_hair:', label: 'Person: blond hair', emoji: '👱', supportsSkinTone: true },
    { id: ':man_blond_hair:', label: 'Man: blond hair', emoji: '👱‍♂️', supportsSkinTone: true },
    { id: ':woman_blond_hair:', label: 'Woman: blond hair', emoji: '👱‍♀️', supportsSkinTone: true },
    { id: ':person_red_hair:', label: 'Person: red hair', emoji: '🧑‍🦰', supportsSkinTone: true },
    { id: ':man_red_hair:', label: 'Man: red hair', emoji: '👨‍🦰', supportsSkinTone: true },
    { id: ':woman_red_hair:', label: 'Woman: red hair', emoji: '👩‍🦰', supportsSkinTone: true },
    {
      id: ':person_curly_hair:',
      label: 'Person: curly hair',
      emoji: '🧑‍🦱',
      supportsSkinTone: true,
    },
    { id: ':man_curly_hair:', label: 'Man: curly hair', emoji: '👨‍🦱', supportsSkinTone: true },
    { id: ':woman_curly_hair:', label: 'Woman: curly hair', emoji: '👩‍🦱', supportsSkinTone: true },
    {
      id: ':person_white_hair:',
      label: 'Person: white hair',
      emoji: '🧑‍🦳',
      supportsSkinTone: true,
    },
    { id: ':man_white_hair:', label: 'Man: white hair', emoji: '👨‍🦳', supportsSkinTone: true },
    { id: ':woman_white_hair:', label: 'Woman: white hair', emoji: '👩‍🦳', supportsSkinTone: true },
    { id: ':person_bald:', label: 'Person: bald', emoji: '🧑‍🦲', supportsSkinTone: true },
    { id: ':man_bald:', label: 'Man: bald', emoji: '👨‍🦲', supportsSkinTone: true },
    { id: ':woman_bald:', label: 'Woman: bald', emoji: '👩‍🦲', supportsSkinTone: true },
    { id: ':person_beard:', label: 'Person: beard', emoji: '🧔', supportsSkinTone: true },
    { id: ':man_beard:', label: 'Man: beard', emoji: '🧔‍♂️', supportsSkinTone: true },
    { id: ':woman_beard:', label: 'Woman: beard', emoji: '🧔‍♀️', supportsSkinTone: true },
    // Professions
    { id: ':health_worker:', label: 'Health worker', emoji: '🧑‍⚕️', supportsSkinTone: true },
    { id: ':man_health_worker:', label: 'Man health worker', emoji: '👨‍⚕️', supportsSkinTone: true },
    {
      id: ':woman_health_worker:',
      label: 'Woman health worker',
      emoji: '👩‍⚕️',
      supportsSkinTone: true,
    },
    { id: ':student:', label: 'Student', emoji: '🧑‍🎓', supportsSkinTone: true },
    { id: ':man_student:', label: 'Man student', emoji: '👨‍🎓', supportsSkinTone: true },
    { id: ':woman_student:', label: 'Woman student', emoji: '👩‍🎓', supportsSkinTone: true },
    { id: ':teacher:', label: 'Teacher', emoji: '🧑‍🏫', supportsSkinTone: true },
    { id: ':man_teacher:', label: 'Man teacher', emoji: '👨‍🏫', supportsSkinTone: true },
    { id: ':woman_teacher:', label: 'Woman teacher', emoji: '👩‍🏫', supportsSkinTone: true },
    { id: ':judge:', label: 'Judge', emoji: '🧑‍⚖️', supportsSkinTone: true },
    { id: ':man_judge:', label: 'Man judge', emoji: '👨‍⚖️', supportsSkinTone: true },
    { id: ':woman_judge:', label: 'Woman judge', emoji: '👩‍⚖️', supportsSkinTone: true },
    { id: ':farmer:', label: 'Farmer', emoji: '🧑‍🌾', supportsSkinTone: true },
    { id: ':man_farmer:', label: 'Man farmer', emoji: '👨‍🌾', supportsSkinTone: true },
    { id: ':woman_farmer:', label: 'Woman farmer', emoji: '👩‍🌾', supportsSkinTone: true },
    { id: ':cook:', label: 'Cook', emoji: '🧑‍🍳', supportsSkinTone: true },
    { id: ':man_cook:', label: 'Man cook', emoji: '👨‍🍳', supportsSkinTone: true },
    { id: ':woman_cook:', label: 'Woman cook', emoji: '👩‍🍳', supportsSkinTone: true },
    { id: ':mechanic:', label: 'Mechanic', emoji: '🧑‍🔧', supportsSkinTone: true },
    { id: ':man_mechanic:', label: 'Man mechanic', emoji: '👨‍🔧', supportsSkinTone: true },
    { id: ':woman_mechanic:', label: 'Woman mechanic', emoji: '👩‍🔧', supportsSkinTone: true },
    { id: ':factory_worker:', label: 'Factory worker', emoji: '🧑‍🏭', supportsSkinTone: true },
    {
      id: ':man_factory_worker:',
      label: 'Man factory worker',
      emoji: '👨‍🏭',
      supportsSkinTone: true,
    },
    {
      id: ':woman_factory_worker:',
      label: 'Woman factory worker',
      emoji: '👩‍🏭',
      supportsSkinTone: true,
    },
    { id: ':office_worker:', label: 'Office worker', emoji: '🧑‍💼', supportsSkinTone: true },
    {
      id: ':man_office_worker:',
      label: 'Man office worker',
      emoji: '👨‍💼',
      supportsSkinTone: true,
    },
    {
      id: ':woman_office_worker:',
      label: 'Woman office worker',
      emoji: '👩‍💼',
      supportsSkinTone: true,
    },
    { id: ':scientist:', label: 'Scientist', emoji: '🧑‍🔬', supportsSkinTone: true },
    { id: ':man_scientist:', label: 'Man scientist', emoji: '👨‍🔬', supportsSkinTone: true },
    { id: ':woman_scientist:', label: 'Woman scientist', emoji: '👩‍🔬', supportsSkinTone: true },
    { id: ':technologist:', label: 'Technologist', emoji: '🧑‍💻', supportsSkinTone: true },
    { id: ':man_technologist:', label: 'Man technologist', emoji: '👨‍💻', supportsSkinTone: true },
    {
      id: ':woman_technologist:',
      label: 'Woman technologist',
      emoji: '👩‍💻',
      supportsSkinTone: true,
    },
    { id: ':singer:', label: 'Singer', emoji: '🧑‍🎤', supportsSkinTone: true },
    { id: ':man_singer:', label: 'Man singer', emoji: '👨‍🎤', supportsSkinTone: true },
    { id: ':woman_singer:', label: 'Woman singer', emoji: '👩‍🎤', supportsSkinTone: true },
    { id: ':artist:', label: 'Artist', emoji: '🧑‍🎨', supportsSkinTone: true },
    { id: ':man_artist:', label: 'Man artist', emoji: '👨‍🎨', supportsSkinTone: true },
    { id: ':woman_artist:', label: 'Woman artist', emoji: '👩‍🎨', supportsSkinTone: true },
    { id: ':pilot:', label: 'Pilot', emoji: '🧑‍✈️', supportsSkinTone: true },
    { id: ':man_pilot:', label: 'Man pilot', emoji: '👨‍✈️', supportsSkinTone: true },
    { id: ':woman_pilot:', label: 'Woman pilot', emoji: '👩‍✈️', supportsSkinTone: true },
    { id: ':astronaut:', label: 'Astronaut', emoji: '🧑‍🚀', supportsSkinTone: true },
    { id: ':man_astronaut:', label: 'Man astronaut', emoji: '👨‍🚀', supportsSkinTone: true },
    { id: ':woman_astronaut:', label: 'Woman astronaut', emoji: '👩‍🚀', supportsSkinTone: true },
    { id: ':firefighter:', label: 'Firefighter', emoji: '🧑‍🚒', supportsSkinTone: true },
    { id: ':man_firefighter:', label: 'Man firefighter', emoji: '👨‍🚒', supportsSkinTone: true },
    {
      id: ':woman_firefighter:',
      label: 'Woman firefighter',
      emoji: '👩‍🚒',
      supportsSkinTone: true,
    },
    { id: ':police_officer:', label: 'Police officer', emoji: '👮', supportsSkinTone: true },
    {
      id: ':man_police_officer:',
      label: 'Man police officer',
      emoji: '👮‍♂️',
      supportsSkinTone: true,
    },
    {
      id: ':woman_police_officer:',
      label: 'Woman police officer',
      emoji: '👮‍♀️',
      supportsSkinTone: true,
    },
    { id: ':ninja:', label: 'Ninja', emoji: '🥷', supportsSkinTone: true },
    {
      id: ':construction_worker:',
      label: 'Construction worker',
      emoji: '👷',
      supportsSkinTone: true,
    },
    {
      id: ':man_construction_worker:',
      label: 'Man construction worker',
      emoji: '👷‍♂️',
      supportsSkinTone: true,
    },
    {
      id: ':woman_construction_worker:',
      label: 'Woman construction worker',
      emoji: '👷‍♀️',
      supportsSkinTone: true,
    },
    // Royalty and fantasy
    { id: ':prince:', label: 'Prince', emoji: '🤴', supportsSkinTone: true },
    { id: ':princess:', label: 'Princess', emoji: '👸', supportsSkinTone: true },
    {
      id: ':person_wearing_turban:',
      label: 'Person wearing turban',
      emoji: '👳',
      supportsSkinTone: true,
    },
    {
      id: ':man_wearing_turban:',
      label: 'Man wearing turban',
      emoji: '👳‍♂️',
      supportsSkinTone: true,
    },
    {
      id: ':woman_wearing_turban:',
      label: 'Woman wearing turban',
      emoji: '👳‍♀️',
      supportsSkinTone: true,
    },
    {
      id: ':person_with_skullcap:',
      label: 'Person with skullcap',
      emoji: '👲',
      supportsSkinTone: true,
    },
    {
      id: ':woman_with_headscarf:',
      label: 'Woman with headscarf',
      emoji: '🧕',
      supportsSkinTone: true,
    },
    { id: ':person_in_tuxedo:', label: 'Person in tuxedo', emoji: '🤵', supportsSkinTone: true },
    { id: ':man_in_tuxedo:', label: 'Man in tuxedo', emoji: '🤵‍♂️', supportsSkinTone: true },
    { id: ':woman_in_tuxedo:', label: 'Woman in tuxedo', emoji: '🤵‍♀️', supportsSkinTone: true },
    { id: ':person_with_veil:', label: 'Person with veil', emoji: '👰', supportsSkinTone: true },
    { id: ':man_with_veil:', label: 'Man with veil', emoji: '👰‍♂️', supportsSkinTone: true },
    { id: ':woman_with_veil:', label: 'Woman with veil', emoji: '👰‍♀️', supportsSkinTone: true },
    { id: ':pregnant_woman:', label: 'Pregnant woman', emoji: '🤰', supportsSkinTone: true },
    { id: ':pregnant_man:', label: 'Pregnant man', emoji: '🫃', supportsSkinTone: true },
    { id: ':pregnant_person:', label: 'Pregnant person', emoji: '🫄', supportsSkinTone: true },
    { id: ':breast-feeding:', label: 'Breast-feeding', emoji: '🤱', supportsSkinTone: true },
    {
      id: ':person_feeding_baby:',
      label: 'Person feeding baby',
      emoji: '🧑‍🍼',
      supportsSkinTone: true,
    },
    { id: ':man_feeding_baby:', label: 'Man feeding baby', emoji: '👨‍🍼', supportsSkinTone: true },
    {
      id: ':woman_feeding_baby:',
      label: 'Woman feeding baby',
      emoji: '👩‍🍼',
      supportsSkinTone: true,
    },
    { id: ':baby_angel:', label: 'Baby angel', emoji: '👼', supportsSkinTone: true },
    { id: ':santa_claus:', label: 'Santa Claus', emoji: '🎅', supportsSkinTone: true },
    { id: ':mrs_claus:', label: 'Mrs. Claus', emoji: '🤶', supportsSkinTone: true },
    { id: ':mx_claus:', label: 'Mx Claus', emoji: '🧑‍🎄', supportsSkinTone: true },
    { id: ':superhero:', label: 'Superhero', emoji: '🦸', supportsSkinTone: true },
    { id: ':man_superhero:', label: 'Man superhero', emoji: '🦸‍♂️', supportsSkinTone: true },
    { id: ':woman_superhero:', label: 'Woman superhero', emoji: '🦸‍♀️', supportsSkinTone: true },
    { id: ':supervillain:', label: 'Supervillain', emoji: '🦹', supportsSkinTone: true },
    { id: ':man_supervillain:', label: 'Man supervillain', emoji: '🦹‍♂️', supportsSkinTone: true },
    {
      id: ':woman_supervillain:',
      label: 'Woman supervillain',
      emoji: '🦹‍♀️',
      supportsSkinTone: true,
    },
    { id: ':mage:', label: 'Mage', emoji: '🧙', supportsSkinTone: true },
    { id: ':man_mage:', label: 'Man mage', emoji: '🧙‍♂️', supportsSkinTone: true },
    { id: ':woman_mage:', label: 'Woman mage', emoji: '🧙‍♀️', supportsSkinTone: true },
    { id: ':fairy:', label: 'Fairy', emoji: '🧚', supportsSkinTone: true },
    { id: ':man_fairy:', label: 'Man fairy', emoji: '🧚‍♂️', supportsSkinTone: true },
    { id: ':woman_fairy:', label: 'Woman fairy', emoji: '🧚‍♀️', supportsSkinTone: true },
    { id: ':vampire:', label: 'Vampire', emoji: '🧛', supportsSkinTone: true },
    { id: ':man_vampire:', label: 'Man vampire', emoji: '🧛‍♂️', supportsSkinTone: true },
    { id: ':woman_vampire:', label: 'Woman vampire', emoji: '🧛‍♀️', supportsSkinTone: true },
    { id: ':merperson:', label: 'Merperson', emoji: '🧜', supportsSkinTone: true },
    { id: ':merman:', label: 'Merman', emoji: '🧜‍♂️', supportsSkinTone: true },
    { id: ':mermaid:', label: 'Mermaid', emoji: '🧜‍♀️', supportsSkinTone: true },
    { id: ':elf:', label: 'Elf', emoji: '🧝', supportsSkinTone: true },
    { id: ':man_elf:', label: 'Man elf', emoji: '🧝‍♂️', supportsSkinTone: true },
    { id: ':woman_elf:', label: 'Woman elf', emoji: '🧝‍♀️', supportsSkinTone: true },
    { id: ':genie:', label: 'Genie', emoji: '🧞' },
    { id: ':man_genie:', label: 'Man genie', emoji: '🧞‍♂️' },
    { id: ':woman_genie:', label: 'Woman genie', emoji: '🧞‍♀️' },
    { id: ':zombie:', label: 'Zombie', emoji: '🧟' },
    { id: ':man_zombie:', label: 'Man zombie', emoji: '🧟‍♂️' },
    { id: ':woman_zombie:', label: 'Woman zombie', emoji: '🧟‍♀️' },
    { id: ':troll:', label: 'Troll', emoji: '🧌' },
    // Person gestures and activities
    { id: ':person_frowning:', label: 'Person frowning', emoji: '🙍', supportsSkinTone: true },
    { id: ':man_frowning:', label: 'Man frowning', emoji: '🙍‍♂️', supportsSkinTone: true },
    { id: ':woman_frowning:', label: 'Woman frowning', emoji: '🙍‍♀️', supportsSkinTone: true },
    { id: ':person_pouting:', label: 'Person pouting', emoji: '🙎', supportsSkinTone: true },
    { id: ':man_pouting:', label: 'Man pouting', emoji: '🙎‍♂️', supportsSkinTone: true },
    { id: ':woman_pouting:', label: 'Woman pouting', emoji: '🙎‍♀️', supportsSkinTone: true },
    {
      id: ':person_gesturing_no:',
      label: 'Person gesturing no',
      emoji: '🙅',
      supportsSkinTone: true,
    },
    { id: ':man_gesturing_no:', label: 'Man gesturing no', emoji: '🙅‍♂️', supportsSkinTone: true },
    {
      id: ':woman_gesturing_no:',
      label: 'Woman gesturing no',
      emoji: '🙅‍♀️',
      supportsSkinTone: true,
    },
    {
      id: ':person_gesturing_ok:',
      label: 'Person gesturing OK',
      emoji: '🙆',
      supportsSkinTone: true,
    },
    { id: ':man_gesturing_ok:', label: 'Man gesturing OK', emoji: '🙆‍♂️', supportsSkinTone: true },
    {
      id: ':woman_gesturing_ok:',
      label: 'Woman gesturing OK',
      emoji: '🙆‍♀️',
      supportsSkinTone: true,
    },
    {
      id: ':person_tipping_hand:',
      label: 'Person tipping hand',
      emoji: '💁',
      supportsSkinTone: true,
    },
    { id: ':man_tipping_hand:', label: 'Man tipping hand', emoji: '💁‍♂️', supportsSkinTone: true },
    {
      id: ':woman_tipping_hand:',
      label: 'Woman tipping hand',
      emoji: '💁‍♀️',
      supportsSkinTone: true,
    },
    {
      id: ':person_raising_hand:',
      label: 'Person raising hand',
      emoji: '🙋',
      supportsSkinTone: true,
    },
    { id: ':man_raising_hand:', label: 'Man raising hand', emoji: '🙋‍♂️', supportsSkinTone: true },
    {
      id: ':woman_raising_hand:',
      label: 'Woman raising hand',
      emoji: '🙋‍♀️',
      supportsSkinTone: true,
    },
    { id: ':deaf_person:', label: 'Deaf person', emoji: '🧏', supportsSkinTone: true },
    { id: ':deaf_man:', label: 'Deaf man', emoji: '🧏‍♂️', supportsSkinTone: true },
    { id: ':deaf_woman:', label: 'Deaf woman', emoji: '🧏‍♀️', supportsSkinTone: true },
    { id: ':person_bowing:', label: 'Person bowing', emoji: '🙇', supportsSkinTone: true },
    { id: ':man_bowing:', label: 'Man bowing', emoji: '🙇‍♂️', supportsSkinTone: true },
    { id: ':woman_bowing:', label: 'Woman bowing', emoji: '🙇‍♀️', supportsSkinTone: true },
    {
      id: ':person_facepalming:',
      label: 'Person facepalming',
      emoji: '🤦',
      supportsSkinTone: true,
    },
    { id: ':man_facepalming:', label: 'Man facepalming', emoji: '🤦‍♂️', supportsSkinTone: true },
    { id: ':woman_facepalming:', label: 'Woman facepalming', emoji: '🤦‍♀️', supportsSkinTone: true },
    { id: ':person_shrugging:', label: 'Person shrugging', emoji: '🤷', supportsSkinTone: true },
    { id: ':man_shrugging:', label: 'Man shrugging', emoji: '🤷‍♂️', supportsSkinTone: true },
    { id: ':woman_shrugging:', label: 'Woman shrugging', emoji: '🤷‍♀️', supportsSkinTone: true },
    {
      id: ':person_getting_massage:',
      label: 'Person getting massage',
      emoji: '💆',
      supportsSkinTone: true,
    },
    {
      id: ':man_getting_massage:',
      label: 'Man getting massage',
      emoji: '💆‍♂️',
      supportsSkinTone: true,
    },
    {
      id: ':woman_getting_massage:',
      label: 'Woman getting massage',
      emoji: '💆‍♀️',
      supportsSkinTone: true,
    },
    {
      id: ':person_getting_haircut:',
      label: 'Person getting haircut',
      emoji: '💇',
      supportsSkinTone: true,
    },
    {
      id: ':man_getting_haircut:',
      label: 'Man getting haircut',
      emoji: '💇‍♂️',
      supportsSkinTone: true,
    },
    {
      id: ':woman_getting_haircut:',
      label: 'Woman getting haircut',
      emoji: '💇‍♀️',
      supportsSkinTone: true,
    },
    { id: ':person_walking:', label: 'Person walking', emoji: '🚶', supportsSkinTone: true },
    { id: ':man_walking:', label: 'Man walking', emoji: '🚶‍♂️', supportsSkinTone: true },
    { id: ':woman_walking:', label: 'Woman walking', emoji: '🚶‍♀️', supportsSkinTone: true },
    { id: ':person_standing:', label: 'Person standing', emoji: '🧍', supportsSkinTone: true },
    { id: ':man_standing:', label: 'Man standing', emoji: '🧍‍♂️', supportsSkinTone: true },
    { id: ':woman_standing:', label: 'Woman standing', emoji: '🧍‍♀️', supportsSkinTone: true },
    { id: ':person_kneeling:', label: 'Person kneeling', emoji: '🧎', supportsSkinTone: true },
    { id: ':man_kneeling:', label: 'Man kneeling', emoji: '🧎‍♂️', supportsSkinTone: true },
    { id: ':woman_kneeling:', label: 'Woman kneeling', emoji: '🧎‍♀️', supportsSkinTone: true },
    {
      id: ':person_with_probing_cane:',
      label: 'Person with probing cane',
      emoji: '🧑‍🦯',
      supportsSkinTone: true,
    },
    {
      id: ':man_with_probing_cane:',
      label: 'Man with probing cane',
      emoji: '👨‍🦯',
      supportsSkinTone: true,
    },
    {
      id: ':woman_with_probing_cane:',
      label: 'Woman with probing cane',
      emoji: '👩‍🦯',
      supportsSkinTone: true,
    },
    {
      id: ':person_in_motorized_wheelchair:',
      label: 'Person in motorized wheelchair',
      emoji: '🧑‍🦼',
      supportsSkinTone: true,
    },
    {
      id: ':man_in_motorized_wheelchair:',
      label: 'Man in motorized wheelchair',
      emoji: '👨‍🦼',
      supportsSkinTone: true,
    },
    {
      id: ':woman_in_motorized_wheelchair:',
      label: 'Woman in motorized wheelchair',
      emoji: '👩‍🦼',
      supportsSkinTone: true,
    },
    {
      id: ':person_in_manual_wheelchair:',
      label: 'Person in manual wheelchair',
      emoji: '🧑‍🦽',
      supportsSkinTone: true,
    },
    {
      id: ':man_in_manual_wheelchair:',
      label: 'Man in manual wheelchair',
      emoji: '👨‍🦽',
      supportsSkinTone: true,
    },
    {
      id: ':woman_in_manual_wheelchair:',
      label: 'Woman in manual wheelchair',
      emoji: '👩‍🦽',
      supportsSkinTone: true,
    },
    { id: ':person_running:', label: 'Person running', emoji: '🏃', supportsSkinTone: true },
    { id: ':man_running:', label: 'Man running', emoji: '🏃‍♂️', supportsSkinTone: true },
    { id: ':woman_running:', label: 'Woman running', emoji: '🏃‍♀️', supportsSkinTone: true },
    { id: ':woman_dancing:', label: 'Woman dancing', emoji: '💃', supportsSkinTone: true },
    { id: ':man_dancing:', label: 'Man dancing', emoji: '🕺', supportsSkinTone: true },
    { id: ':people_with_bunny_ears:', label: 'People with bunny ears', emoji: '👯' },
    { id: ':men_with_bunny_ears:', label: 'Men with bunny ears', emoji: '👯‍♂️' },
    { id: ':women_with_bunny_ears:', label: 'Women with bunny ears', emoji: '👯‍♀️' },
    // Family and groups
    {
      id: ':women_holding_hands:',
      label: 'Women holding hands',
      emoji: '👭',
      supportsSkinTone: true,
    },
    {
      id: ':woman_and_man_holding_hands:',
      label: 'Woman and man holding hands',
      emoji: '👫',
      supportsSkinTone: true,
    },
    { id: ':men_holding_hands:', label: 'Men holding hands', emoji: '👬', supportsSkinTone: true },
    { id: ':kiss:', label: 'Kiss', emoji: '💏', supportsSkinTone: true },
    { id: ':couple_with_heart:', label: 'Couple with heart', emoji: '💑', supportsSkinTone: true },
    { id: ':family:', label: 'Family', emoji: '👪' },
    { id: ':family_man_woman_boy:', label: 'Family: man, woman, boy', emoji: '👨‍👩‍👦' },
    { id: ':family_man_woman_girl:', label: 'Family: man, woman, girl', emoji: '👨‍👩‍👧' },
    {
      id: ':family_man_woman_girl_boy:',
      label: 'Family: man, woman, girl, boy',
      emoji: '👨‍👩‍👧‍👦',
    },
    { id: ':family_man_woman_boy_boy:', label: 'Family: man, woman, boy, boy', emoji: '👨‍👩‍👦‍👦' },
    {
      id: ':family_man_woman_girl_girl:',
      label: 'Family: man, woman, girl, girl',
      emoji: '👨‍👩‍👧‍👧',
    },
    { id: ':family_man_man_boy:', label: 'Family: man, man, boy', emoji: '👨‍👨‍👦' },
    { id: ':family_man_man_girl:', label: 'Family: man, man, girl', emoji: '👨‍👨‍👧' },
    { id: ':family_woman_woman_boy:', label: 'Family: woman, woman, boy', emoji: '👩‍👩‍👦' },
    { id: ':family_woman_woman_girl:', label: 'Family: woman, woman, girl', emoji: '👩‍👩‍👧' },
    { id: ':family_man_boy:', label: 'Family: man, boy', emoji: '👨‍👦' },
    { id: ':family_man_girl:', label: 'Family: man, girl', emoji: '👨‍👧' },
    { id: ':family_woman_boy:', label: 'Family: woman, boy', emoji: '👩‍👦' },
    { id: ':family_woman_girl:', label: 'Family: woman, girl', emoji: '👩‍👧' },
    { id: ':speaking_head:', label: 'Speaking head', emoji: '🗣️' },
    { id: ':bust_in_silhouette:', label: 'Bust in silhouette', emoji: '👤' },
    { id: ':busts_in_silhouette:', label: 'Busts in silhouette', emoji: '👥' },
    { id: ':footprints:', label: 'Footprints', emoji: '👣' },
  ],

  animals: [
    { id: ':dog_face:', label: 'Dog face', emoji: '🐶' },
    { id: ':cat_face:', label: 'Cat face', emoji: '🐱' },
    { id: ':mouse_face:', label: 'Mouse face', emoji: '🐭' },
    { id: ':hamster:', label: 'Hamster', emoji: '🐹' },
    { id: ':rabbit_face:', label: 'Rabbit face', emoji: '🐰' },
    { id: ':fox:', label: 'Fox', emoji: '🦊' },
    { id: ':bear:', label: 'Bear', emoji: '🐻' },
    { id: ':panda:', label: 'Panda', emoji: '🐼' },
    { id: ':koala:', label: 'Koala', emoji: '🐨' },
    { id: ':tiger_face:', label: 'Tiger face', emoji: '🐯' },
    { id: ':lion:', label: 'Lion', emoji: '🦁' },
    { id: ':cow_face:', label: 'Cow face', emoji: '🐮' },
    { id: ':pig_face:', label: 'Pig face', emoji: '🐷' },
    { id: ':frog:', label: 'Frog', emoji: '🐸' },
    { id: ':monkey_face:', label: 'Monkey face', emoji: '🐵' },
    { id: ':see-no-evil_monkey:', label: 'See-no-evil monkey', emoji: '🙈' },
    { id: ':hear-no-evil_monkey:', label: 'Hear-no-evil monkey', emoji: '🙉' },
    { id: ':speak-no-evil_monkey:', label: 'Speak-no-evil monkey', emoji: '🙊' },
    { id: ':monkey:', label: 'Monkey', emoji: '🐒' },
    { id: ':chicken:', label: 'Chicken', emoji: '🐔' },
    { id: ':penguin:', label: 'Penguin', emoji: '🐧' },
    { id: ':bird:', label: 'Bird', emoji: '🐦' },
    { id: ':baby_chick:', label: 'Baby chick', emoji: '🐤' },
    { id: ':hatching_chick:', label: 'Hatching chick', emoji: '🐣' },
    { id: ':front-facing_baby_chick:', label: 'Front-facing baby chick', emoji: '🐥' },
    { id: ':duck:', label: 'Duck', emoji: '🦆' },
    { id: ':eagle:', label: 'Eagle', emoji: '🦅' },
    { id: ':owl:', label: 'Owl', emoji: '🦉' },
    { id: ':bat:', label: 'Bat', emoji: '🦇' },
    { id: ':wolf:', label: 'Wolf', emoji: '🐺' },
    { id: ':boar:', label: 'Boar', emoji: '🐗' },
    { id: ':horse_face:', label: 'Horse face', emoji: '🐴' },
    { id: ':unicorn:', label: 'Unicorn', emoji: '🦄' },
    { id: ':honeybee:', label: 'Honeybee', emoji: '🐝' },
    { id: ':bug:', label: 'Bug', emoji: '🐛' },
    { id: ':butterfly:', label: 'Butterfly', emoji: '🦋' },
    { id: ':snail:', label: 'Snail', emoji: '🐌' },
    { id: ':lady_beetle:', label: 'Lady beetle', emoji: '🐞' },
    { id: ':ant:', label: 'Ant', emoji: '🐜' },
    { id: ':spider:', label: 'Spider', emoji: '🕷️' },
    { id: ':spider_web:', label: 'Spider web', emoji: '🕸️' },
    { id: ':scorpion:', label: 'Scorpion', emoji: '🦂' },
    { id: ':turtle:', label: 'Turtle', emoji: '🐢' },
    { id: ':snake:', label: 'Snake', emoji: '🐍' },
    { id: ':lizard:', label: 'Lizard', emoji: '🦎' },
    { id: ':t-rex:', label: 'T-Rex', emoji: '🦖' },
    { id: ':sauropod:', label: 'Sauropod', emoji: '🦕' },
    { id: ':octopus:', label: 'Octopus', emoji: '🐙' },
    { id: ':squid:', label: 'Squid', emoji: '🦑' },
    { id: ':shrimp:', label: 'Shrimp', emoji: '🦐' },
    { id: ':lobster:', label: 'Lobster', emoji: '🦞' },
    { id: ':crab:', label: 'Crab', emoji: '🦀' },
    { id: ':blowfish:', label: 'Blowfish', emoji: '🐡' },
    { id: ':tropical_fish:', label: 'Tropical fish', emoji: '🐠' },
    { id: ':fish:', label: 'Fish', emoji: '🐟' },
    { id: ':dolphin:', label: 'Dolphin', emoji: '🐬' },
    { id: ':spouting_whale:', label: 'Spouting whale', emoji: '🐳' },
    { id: ':whale:', label: 'Whale', emoji: '🐋' },
    { id: ':shark:', label: 'Shark', emoji: '🦈' },
    { id: ':crocodile:', label: 'Crocodile', emoji: '🐊' },
    { id: ':tiger:', label: 'Tiger', emoji: '🐅' },
    { id: ':leopard:', label: 'Leopard', emoji: '🐆' },
    { id: ':zebra:', label: 'Zebra', emoji: '🦓' },
    { id: ':gorilla:', label: 'Gorilla', emoji: '🦍' },
    { id: ':orangutan:', label: 'Orangutan', emoji: '🦧' },
    { id: ':elephant:', label: 'Elephant', emoji: '🐘' },
    { id: ':rhinoceros:', label: 'Rhinoceros', emoji: '🦏' },
    { id: ':hippopotamus:', label: 'Hippopotamus', emoji: '🦛' },
    { id: ':camel:', label: 'Camel', emoji: '🐪' },
    { id: ':two-hump_camel:', label: 'Two-hump camel', emoji: '🐫' },
    { id: ':giraffe:', label: 'Giraffe', emoji: '🦒' },
    { id: ':kangaroo:', label: 'Kangaroo', emoji: '🦘' },
    { id: ':water_buffalo:', label: 'Water buffalo', emoji: '🐃' },
    { id: ':ox:', label: 'Ox', emoji: '🐂' },
    { id: ':cow:', label: 'Cow', emoji: '🐄' },
    { id: ':horse:', label: 'Horse', emoji: '🐎' },
    { id: ':pig:', label: 'Pig', emoji: '🐖' },
    { id: ':ram:', label: 'Ram', emoji: '🐏' },
    { id: ':ewe:', label: 'Ewe', emoji: '🐑' },
    { id: ':llama:', label: 'Llama', emoji: '🦙' },
    { id: ':goat:', label: 'Goat', emoji: '🐐' },
    { id: ':deer:', label: 'Deer', emoji: '🦌' },
    { id: ':dog:', label: 'Dog', emoji: '🐕' },
    { id: ':poodle:', label: 'Poodle', emoji: '🐩' },
    { id: ':cat:', label: 'Cat', emoji: '🐈' },
    { id: ':paw_prints:', label: 'Paw prints', emoji: '🐾' },
    // Additional animals
    { id: ':raccoon:', label: 'Raccoon', emoji: '🦝' },
    { id: ':badger:', label: 'Badger', emoji: '🦡' },
    { id: ':hedgehog:', label: 'Hedgehog', emoji: '🦔' },
    { id: ':otter:', label: 'Otter', emoji: '🦦' },
    { id: ':skunk:', label: 'Skunk', emoji: '🦨' },
    { id: ':beaver:', label: 'Beaver', emoji: '🦫' },
    { id: ':bison:', label: 'Bison', emoji: '🦬' },
    { id: ':mammoth:', label: 'Mammoth', emoji: '🦣' },
    { id: ':sloth:', label: 'Sloth', emoji: '🦥' },
    { id: ':polar_bear:', label: 'Polar bear', emoji: '🐻‍❄️' },
    { id: ':black_cat:', label: 'Black cat', emoji: '🐈‍⬛' },
    { id: ':guide_dog:', label: 'Guide dog', emoji: '🦮' },
    { id: ':service_dog:', label: 'Service dog', emoji: '🐕‍🦺' },
    { id: ':rooster:', label: 'Rooster', emoji: '🐓' },
    { id: ':turkey:', label: 'Turkey', emoji: '🦃' },
    { id: ':dodo:', label: 'Dodo', emoji: '🦤' },
    { id: ':feather:', label: 'Feather', emoji: '🪶' },
    { id: ':flamingo:', label: 'Flamingo', emoji: '🦩' },
    { id: ':peacock:', label: 'Peacock', emoji: '🦚' },
    { id: ':parrot:', label: 'Parrot', emoji: '🦜' },
    { id: ':swan:', label: 'Swan', emoji: '🦢' },
    { id: ':goose:', label: 'Goose', emoji: '🪿' },
    { id: ':seal:', label: 'Seal', emoji: '🦭' },
    { id: ':jellyfish:', label: 'Jellyfish', emoji: '🪼' },
    { id: ':coral:', label: 'Coral', emoji: '🪸' },
    { id: ':fly:', label: 'Fly', emoji: '🪰' },
    { id: ':mosquito:', label: 'Mosquito', emoji: '🦟' },
    { id: ':cockroach:', label: 'Cockroach', emoji: '🪳' },
    { id: ':beetle:', label: 'Beetle', emoji: '🪲' },
    { id: ':cricket:', label: 'Cricket', emoji: '🦗' },
    { id: ':worm:', label: 'Worm', emoji: '🪱' },
    { id: ':microbe:', label: 'Microbe', emoji: '🦠' },
    { id: ':nest_with_eggs:', label: 'Nest with eggs', emoji: '🪺' },
    { id: ':empty_nest:', label: 'Empty nest', emoji: '🪹' },
    { id: ':wing:', label: 'Wing', emoji: '🪽' },
    // Plants and nature
    { id: ':seedling:', label: 'Seedling', emoji: '🌱' },
    { id: ':herb:', label: 'Herb', emoji: '🌿' },
    { id: ':shamrock:', label: 'Shamrock', emoji: '☘️' },
    { id: ':four_leaf_clover:', label: 'Four leaf clover', emoji: '🍀' },
    { id: ':evergreen_tree:', label: 'Evergreen tree', emoji: '🌲' },
    { id: ':deciduous_tree:', label: 'Deciduous tree', emoji: '🌳' },
    { id: ':palm_tree:', label: 'Palm tree', emoji: '🌴' },
    { id: ':cactus:', label: 'Cactus', emoji: '🌵' },
    { id: ':tulip:', label: 'Tulip', emoji: '🌷' },
    { id: ':cherry_blossom:', label: 'Cherry blossom', emoji: '🌸' },
    { id: ':rose:', label: 'Rose', emoji: '🌹' },
    { id: ':hibiscus:', label: 'Hibiscus', emoji: '🌺' },
    { id: ':sunflower:', label: 'Sunflower', emoji: '🌻' },
    { id: ':blossom:', label: 'Blossom', emoji: '🌼' },
    { id: ':bouquet:', label: 'Bouquet', emoji: '💐' },
    { id: ':mushroom:', label: 'Mushroom', emoji: '🍄' },
    { id: ':maple_leaf:', label: 'Maple leaf', emoji: '🍁' },
    { id: ':fallen_leaves:', label: 'Fallen leaves', emoji: '🍂' },
    { id: ':leaf_fluttering_in_wind:', label: 'Leaf fluttering in wind', emoji: '🍃' },
  ],

  food: [
    { id: ':grapes:', label: 'Grapes', emoji: '🍇' },
    { id: ':melon:', label: 'Melon', emoji: '🍈' },
    { id: ':watermelon:', label: 'Watermelon', emoji: '🍉' },
    { id: ':tangerine:', label: 'Tangerine', emoji: '🍊' },
    { id: ':lemon:', label: 'Lemon', emoji: '🍋' },
    { id: ':banana:', label: 'Banana', emoji: '🍌' },
    { id: ':pineapple:', label: 'Pineapple', emoji: '🍍' },
    { id: ':mango:', label: 'Mango', emoji: '🥭' },
    { id: ':red_apple:', label: 'Red apple', emoji: '🍎' },
    { id: ':green_apple:', label: 'Green apple', emoji: '🍏' },
    { id: ':pear:', label: 'Pear', emoji: '🍐' },
    { id: ':peach:', label: 'Peach', emoji: '🍑' },
    { id: ':cherries:', label: 'Cherries', emoji: '🍒' },
    { id: ':strawberry:', label: 'Strawberry', emoji: '🍓' },
    { id: ':blueberries:', label: 'Blueberries', emoji: '🫐' },
    { id: ':kiwi_fruit:', label: 'Kiwi fruit', emoji: '🥝' },
    { id: ':coconut:', label: 'Coconut', emoji: '🥥' },
    { id: ':tomato:', label: 'Tomato', emoji: '🍅' },
    { id: ':avocado:', label: 'Avocado', emoji: '🥑' },
    { id: ':eggplant:', label: 'Eggplant', emoji: '🍆' },
    { id: ':potato:', label: 'Potato', emoji: '🥔' },
    { id: ':carrot:', label: 'Carrot', emoji: '🥕' },
    { id: ':corn:', label: 'Corn', emoji: '🌽' },
    { id: ':hot_pepper:', label: 'Hot pepper', emoji: '🌶️' },
    { id: ':cucumber:', label: 'Cucumber', emoji: '🥒' },
    { id: ':leafy_greens:', label: 'Leafy greens', emoji: '🥬' },
    { id: ':broccoli:', label: 'Broccoli', emoji: '🥦' },
    { id: ':garlic:', label: 'Garlic', emoji: '🧄' },
    { id: ':onion:', label: 'Onion', emoji: '🧅' },
    { id: ':bell_pepper:', label: 'Bell pepper', emoji: '🫑' },
    { id: ':olive:', label: 'Olive', emoji: '🫒' },
    { id: ':ginger_root:', label: 'Ginger root', emoji: '🫚' },
    { id: ':pea_pod:', label: 'Pea pod', emoji: '🫛' },
    { id: ':beans:', label: 'Beans', emoji: '🫘' },
    { id: ':peanuts:', label: 'Peanuts', emoji: '🥜' },
    { id: ':chestnut:', label: 'Chestnut', emoji: '🌰' },
    { id: ':bread:', label: 'Bread', emoji: '🍞' },
    { id: ':croissant:', label: 'Croissant', emoji: '🥐' },
    { id: ':baguette_bread:', label: 'Baguette bread', emoji: '🥖' },
    { id: ':pretzel:', label: 'Pretzel', emoji: '🥨' },
    { id: ':bagel:', label: 'Bagel', emoji: '🥯' },
    { id: ':flatbread:', label: 'Flatbread', emoji: '🫓' },
    { id: ':pancakes:', label: 'Pancakes', emoji: '🥞' },
    { id: ':waffle:', label: 'Waffle', emoji: '🧇' },
    { id: ':cheese_wedge:', label: 'Cheese wedge', emoji: '🧀' },
    { id: ':meat_on_bone:', label: 'Meat on bone', emoji: '🍖' },
    { id: ':poultry_leg:', label: 'Poultry leg', emoji: '🍗' },
    { id: ':cut_of_meat:', label: 'Cut of meat', emoji: '🥩' },
    { id: ':bacon:', label: 'Bacon', emoji: '🥓' },
    { id: ':hamburger:', label: 'Hamburger', emoji: '🍔' },
    { id: ':french_fries:', label: 'French fries', emoji: '🍟' },
    { id: ':pizza:', label: 'Pizza', emoji: '🍕' },
    { id: ':hot_dog:', label: 'Hot dog', emoji: '🌭' },
    { id: ':sandwich:', label: 'Sandwich', emoji: '🥪' },
    { id: ':taco:', label: 'Taco', emoji: '🌮' },
    { id: ':burrito:', label: 'Burrito', emoji: '🌯' },
    { id: ':tamale:', label: 'Tamale', emoji: '🫔' },
    { id: ':stuffed_flatbread:', label: 'Stuffed flatbread', emoji: '🥙' },
    { id: ':falafel:', label: 'Falafel', emoji: '🧆' },
    { id: ':egg:', label: 'Egg', emoji: '🥚' },
    { id: ':cooking:', label: 'Cooking', emoji: '🍳' },
    { id: ':shallow_pan_of_food:', label: 'Shallow pan of food', emoji: '🥘' },
    { id: ':pot_of_food:', label: 'Pot of food', emoji: '🍲' },
    { id: ':fondue:', label: 'Fondue', emoji: '🫕' },
    { id: ':bowl_with_spoon:', label: 'Bowl with spoon', emoji: '🥣' },
    { id: ':green_salad:', label: 'Green salad', emoji: '🥗' },
    { id: ':popcorn:', label: 'Popcorn', emoji: '🍿' },
    { id: ':butter:', label: 'Butter', emoji: '🧈' },
    { id: ':salt:', label: 'Salt', emoji: '🧂' },
    { id: ':canned_food:', label: 'Canned food', emoji: '🥫' },
    { id: ':bento_box:', label: 'Bento box', emoji: '🍱' },
    { id: ':rice_cracker:', label: 'Rice cracker', emoji: '🍘' },
    { id: ':rice_ball:', label: 'Rice ball', emoji: '🍙' },
    { id: ':cooked_rice:', label: 'Cooked rice', emoji: '🍚' },
    { id: ':curry_rice:', label: 'Curry rice', emoji: '🍛' },
    { id: ':steaming_bowl:', label: 'Steaming bowl', emoji: '🍜' },
    { id: ':spaghetti:', label: 'Spaghetti', emoji: '🍝' },
    { id: ':roasted_sweet_potato:', label: 'Roasted sweet potato', emoji: '🍠' },
    { id: ':oden:', label: 'Oden', emoji: '🍢' },
    { id: ':sushi:', label: 'Sushi', emoji: '🍣' },
    { id: ':fried_shrimp:', label: 'Fried shrimp', emoji: '🍤' },
    { id: ':fish_cake_with_swirl:', label: 'Fish cake with swirl', emoji: '🍥' },
    { id: ':dumpling:', label: 'Dumpling', emoji: '🥟' },
    { id: ':fortune_cookie:', label: 'Fortune cookie', emoji: '🥠' },
    { id: ':takeout_box:', label: 'Takeout box', emoji: '🥡' },
    // Desserts and sweets
    { id: ':soft_ice_cream:', label: 'Soft ice cream', emoji: '🍦' },
    { id: ':shaved_ice:', label: 'Shaved ice', emoji: '🍧' },
    { id: ':ice_cream:', label: 'Ice cream', emoji: '🍨' },
    { id: ':doughnut:', label: 'Doughnut', emoji: '🍩' },
    { id: ':cookie:', label: 'Cookie', emoji: '🍪' },
    { id: ':birthday_cake:', label: 'Birthday cake', emoji: '🎂' },
    { id: ':shortcake:', label: 'Shortcake', emoji: '🍰' },
    { id: ':cupcake:', label: 'Cupcake', emoji: '🧁' },
    { id: ':pie:', label: 'Pie', emoji: '🥧' },
    { id: ':chocolate_bar:', label: 'Chocolate bar', emoji: '🍫' },
    { id: ':candy:', label: 'Candy', emoji: '🍬' },
    { id: ':lollipop:', label: 'Lollipop', emoji: '🍭' },
    { id: ':custard:', label: 'Custard', emoji: '🍮' },
    { id: ':honey_pot:', label: 'Honey pot', emoji: '🍯' },
    // Drinks
    { id: ':baby_bottle:', label: 'Baby bottle', emoji: '🍼' },
    { id: ':glass_of_milk:', label: 'Glass of milk', emoji: '🥛' },
    { id: ':hot_beverage:', label: 'Hot beverage', emoji: '☕' },
    { id: ':teacup_without_handle:', label: 'Teacup without handle', emoji: '🍵' },
    { id: ':sake:', label: 'Sake', emoji: '🍶' },
    { id: ':bottle_with_popping_cork:', label: 'Bottle with popping cork', emoji: '🍾' },
    { id: ':wine_glass:', label: 'Wine glass', emoji: '🍷' },
    { id: ':cocktail_glass:', label: 'Cocktail glass', emoji: '🍸' },
    { id: ':tropical_drink:', label: 'Tropical drink', emoji: '🍹' },
    { id: ':beer_mug:', label: 'Beer mug', emoji: '🍺' },
    { id: ':clinking_beer_mugs:', label: 'Clinking beer mugs', emoji: '🍻' },
    { id: ':clinking_glasses:', label: 'Clinking glasses', emoji: '🥂' },
    { id: ':tumbler_glass:', label: 'Tumbler glass', emoji: '🥃' },
    { id: ':cup_with_straw:', label: 'Cup with straw', emoji: '🥤' },
    { id: ':bubble_tea:', label: 'Bubble tea', emoji: '🧋' },
    { id: ':beverage_box:', label: 'Beverage box', emoji: '🧃' },
    { id: ':mate:', label: 'Mate', emoji: '🧉' },
    { id: ':ice:', label: 'Ice', emoji: '🧊' },
  ],

  activity: [
    { id: ':soccer_ball:', label: 'Soccer ball', emoji: '⚽' },
    { id: ':basketball:', label: 'Basketball', emoji: '🏀' },
    { id: ':american_football:', label: 'American football', emoji: '🏈' },
    { id: ':baseball:', label: 'Baseball', emoji: '⚾' },
    { id: ':softball:', label: 'Softball', emoji: '🥎' },
    { id: ':tennis:', label: 'Tennis', emoji: '🎾' },
    { id: ':volleyball:', label: 'Volleyball', emoji: '🏐' },
    { id: ':rugby_football:', label: 'Rugby football', emoji: '🏉' },
    { id: ':flying_disc:', label: 'Flying disc', emoji: '🥏' },
    { id: ':8_ball:', label: '8 ball', emoji: '🎱' },
    { id: ':ping_pong:', label: 'Ping pong', emoji: '🏓' },
    { id: ':badminton:', label: 'Badminton', emoji: '🏸' },
    { id: ':ice_hockey:', label: 'Ice hockey', emoji: '🏒' },
    { id: ':field_hockey:', label: 'Field hockey', emoji: '🏑' },
    { id: ':lacrosse:', label: 'Lacrosse', emoji: '🥍' },
    { id: ':cricket_game:', label: 'Cricket game', emoji: '🏏' },
    { id: ':goal_net:', label: 'Goal net', emoji: '🥅' },
    { id: ':flag_in_hole:', label: 'Flag in hole', emoji: '⛳' },
    { id: ':bow_and_arrow:', label: 'Bow and arrow', emoji: '🏹' },
    { id: ':fishing_pole:', label: 'Fishing pole', emoji: '🎣' },
    { id: ':diving_mask:', label: 'Diving mask', emoji: '🤿' },
    { id: ':boxing_glove:', label: 'Boxing glove', emoji: '🥊' },
    { id: ':martial_arts_uniform:', label: 'Martial arts uniform', emoji: '🥋' },
    { id: ':running_shirt:', label: 'Running shirt', emoji: '🎽' },
    { id: ':skateboard:', label: 'Skateboard', emoji: '🛹' },
    { id: ':sled:', label: 'Sled', emoji: '🛷' },
    { id: ':ice_skate:', label: 'Ice skate', emoji: '⛸️' },
    { id: ':curling_stone:', label: 'Curling stone', emoji: '🥌' },
    { id: ':skis:', label: 'Skis', emoji: '🎿' },
    { id: ':skier:', label: 'Skier', emoji: '⛷️' },
    { id: ':snowboarder:', label: 'Snowboarder', emoji: '🏂' },
    { id: ':person_lifting_weights:', label: 'Person lifting weights', emoji: '🏋️' },
    { id: ':people_wrestling:', label: 'People wrestling', emoji: '🤼' },
    { id: ':person_cartwheeling:', label: 'Person cartwheeling', emoji: '🤸' },
    { id: ':person_bouncing_ball:', label: 'Person bouncing ball', emoji: '⛹️' },
    { id: ':person_fencing:', label: 'Person fencing', emoji: '🤺' },
    { id: ':person_playing_handball:', label: 'Person playing handball', emoji: '🤾' },
    { id: ':person_golfing:', label: 'Person golfing', emoji: '🏌️' },
    { id: ':horse_racing:', label: 'Horse racing', emoji: '🏇' },
    { id: ':person_in_lotus_position:', label: 'Person in lotus position', emoji: '🧘' },
    { id: ':person_surfing:', label: 'Person surfing', emoji: '🏄' },
    { id: ':person_swimming:', label: 'Person swimming', emoji: '🏊' },
    { id: ':person_playing_water_polo:', label: 'Person playing water polo', emoji: '🤽' },
    { id: ':person_rowing_boat:', label: 'Person rowing boat', emoji: '🚣' },
    { id: ':person_climbing:', label: 'Person climbing', emoji: '🧗' },
    { id: ':person_mountain_biking:', label: 'Person mountain biking', emoji: '🚵' },
    { id: ':person_biking:', label: 'Person biking', emoji: '🚴' },
    { id: ':trophy:', label: 'Trophy', emoji: '🏆' },
    { id: ':1st_place_medal:', label: '1st place medal', emoji: '🥇' },
    { id: ':2nd_place_medal:', label: '2nd place medal', emoji: '🥈' },
    { id: ':3rd_place_medal:', label: '3rd place medal', emoji: '🥉' },
    { id: ':sports_medal:', label: 'Sports medal', emoji: '🏅' },
    { id: ':military_medal:', label: 'Military medal', emoji: '🎖️' },
    { id: ':rosette:', label: 'Rosette', emoji: '🏵️' },
    { id: ':reminder_ribbon:', label: 'Reminder ribbon', emoji: '🎗️' },
    { id: ':ticket:', label: 'Ticket', emoji: '🎫' },
    { id: ':admission_tickets:', label: 'Admission tickets', emoji: '🎟️' },
    { id: ':circus_tent:', label: 'Circus tent', emoji: '🎪' },
    { id: ':person_juggling:', label: 'Person juggling', emoji: '🤹' },
    { id: ':performing_arts:', label: 'Performing arts', emoji: '🎭' },
    { id: ':artist_palette:', label: 'Artist palette', emoji: '🎨' },
    { id: ':clapper_board:', label: 'Clapper board', emoji: '🎬' },
    { id: ':microphone:', label: 'Microphone', emoji: '🎤' },
    { id: ':headphone:', label: 'Headphone', emoji: '🎧' },
    { id: ':musical_score:', label: 'Musical score', emoji: '🎼' },
    { id: ':musical_note:', label: 'Musical note', emoji: '🎵' },
    { id: ':musical_notes:', label: 'Musical notes', emoji: '🎶' },
    { id: ':drum:', label: 'Drum', emoji: '🥁' },
    { id: ':musical_keyboard:', label: 'Musical keyboard', emoji: '🎹' },
    { id: ':saxophone:', label: 'Saxophone', emoji: '🎷' },
    { id: ':trumpet:', label: 'Trumpet', emoji: '🎺' },
    { id: ':guitar:', label: 'Guitar', emoji: '🎸' },
    { id: ':violin:', label: 'Violin', emoji: '🎻' },
    { id: ':game_die:', label: 'Game die', emoji: '🎲' },
    { id: ':direct_hit:', label: 'Direct hit', emoji: '🎯' },
    { id: ':bowling:', label: 'Bowling', emoji: '🎳' },
    { id: ':video_game:', label: 'Video game', emoji: '🎮' },
    { id: ':joystick:', label: 'Joystick', emoji: '🕹️' },
    { id: ':slot_machine:', label: 'Slot machine', emoji: '🎰' },
    { id: ':flower_playing_cards:', label: 'Flower playing cards', emoji: '🎴' },
    { id: ':joker:', label: 'Joker', emoji: '🃏' },
    { id: ':mahjong_red_dragon:', label: 'Mahjong red dragon', emoji: '🀄' },
  ],

  travel: [
    { id: ':globe_showing_europe-africa:', label: 'Globe showing Europe-Africa', emoji: '🌍' },
    { id: ':globe_showing_americas:', label: 'Globe showing Americas', emoji: '🌎' },
    { id: ':globe_showing_asia-australia:', label: 'Globe showing Asia-Australia', emoji: '🌏' },
    { id: ':globe_with_meridians:', label: 'Globe with meridians', emoji: '🌐' },
    { id: ':world_map:', label: 'World map', emoji: '🗺️' },
    { id: ':compass:', label: 'Compass', emoji: '🧭' },
    { id: ':snow-capped_mountain:', label: 'Snow-capped mountain', emoji: '🏔️' },
    { id: ':mountain:', label: 'Mountain', emoji: '⛰️' },
    { id: ':volcano:', label: 'Volcano', emoji: '🌋' },
    { id: ':mount_fuji:', label: 'Mount Fuji', emoji: '🗻' },
    { id: ':camping:', label: 'Camping', emoji: '🏕️' },
    { id: ':beach_with_umbrella:', label: 'Beach with umbrella', emoji: '🏖️' },
    { id: ':desert:', label: 'Desert', emoji: '🏜️' },
    { id: ':desert_island:', label: 'Desert island', emoji: '🏝️' },
    { id: ':national_park:', label: 'National park', emoji: '🏞️' },
    { id: ':stadium:', label: 'Stadium', emoji: '🏟️' },
    { id: ':classical_building:', label: 'Classical building', emoji: '🏛️' },
    { id: ':building_construction:', label: 'Building construction', emoji: '🏗️' },
    { id: ':houses:', label: 'Houses', emoji: '🏘️' },
    { id: ':derelict_house:', label: 'Derelict house', emoji: '🏚️' },
    { id: ':house:', label: 'House', emoji: '🏠' },
    { id: ':house_with_garden:', label: 'House with garden', emoji: '🏡' },
    { id: ':office_building:', label: 'Office building', emoji: '🏢' },
    { id: ':japanese_post_office:', label: 'Japanese post office', emoji: '🏣' },
    { id: ':post_office:', label: 'Post office', emoji: '🏤' },
    { id: ':hospital:', label: 'Hospital', emoji: '🏥' },
    { id: ':bank:', label: 'Bank', emoji: '🏦' },
    { id: ':hotel:', label: 'Hotel', emoji: '🏨' },
    { id: ':love_hotel:', label: 'Love hotel', emoji: '🏩' },
    { id: ':convenience_store:', label: 'Convenience store', emoji: '🏪' },
    { id: ':school:', label: 'School', emoji: '🏫' },
    { id: ':department_store:', label: 'Department store', emoji: '🏬' },
    { id: ':factory:', label: 'Factory', emoji: '🏭' },
    { id: ':japanese_castle:', label: 'Japanese castle', emoji: '🏯' },
    { id: ':castle:', label: 'Castle', emoji: '🏰' },
    { id: ':wedding:', label: 'Wedding', emoji: '💒' },
    { id: ':tokyo_tower:', label: 'Tokyo tower', emoji: '🗼' },
    { id: ':statue_of_liberty:', label: 'Statue of Liberty', emoji: '🗽' },
    { id: ':church:', label: 'Church', emoji: '⛪' },
    { id: ':mosque:', label: 'Mosque', emoji: '🕌' },
    { id: ':hindu_temple:', label: 'Hindu temple', emoji: '🛕' },
    { id: ':synagogue:', label: 'Synagogue', emoji: '🕍' },
    { id: ':shinto_shrine:', label: 'Shinto shrine', emoji: '⛩️' },
    { id: ':kaaba:', label: 'Kaaba', emoji: '🕋' },
    { id: ':fountain:', label: 'Fountain', emoji: '⛲' },
    { id: ':tent:', label: 'Tent', emoji: '⛺' },
    { id: ':foggy:', label: 'Foggy', emoji: '🌁' },
    { id: ':night_with_stars:', label: 'Night with stars', emoji: '🌃' },
    { id: ':cityscape:', label: 'Cityscape', emoji: '🏙️' },
    { id: ':sunrise_over_mountains:', label: 'Sunrise over mountains', emoji: '🌄' },
    { id: ':sunrise:', label: 'Sunrise', emoji: '🌅' },
    { id: ':cityscape_at_dusk:', label: 'Cityscape at dusk', emoji: '🌆' },
    { id: ':sunset:', label: 'Sunset', emoji: '🌇' },
    { id: ':bridge_at_night:', label: 'Bridge at night', emoji: '🌉' },
    { id: ':hot_springs:', label: 'Hot springs', emoji: '♨️' },
    { id: ':carousel_horse:', label: 'Carousel horse', emoji: '🎠' },
    { id: ':ferris_wheel:', label: 'Ferris wheel', emoji: '🎡' },
    { id: ':roller_coaster:', label: 'Roller coaster', emoji: '🎢' },
    { id: ':barber_pole:', label: 'Barber pole', emoji: '💈' },
    { id: ':circus_tent_travel:', label: 'Circus tent', emoji: '🎪' },
    // Transportation
    { id: ':locomotive:', label: 'Locomotive', emoji: '🚂' },
    { id: ':railway_car:', label: 'Railway car', emoji: '🚃' },
    { id: ':high-speed_train:', label: 'High-speed train', emoji: '🚄' },
    { id: ':bullet_train:', label: 'Bullet train', emoji: '🚅' },
    { id: ':train:', label: 'Train', emoji: '🚆' },
    { id: ':metro:', label: 'Metro', emoji: '🚇' },
    { id: ':light_rail:', label: 'Light rail', emoji: '🚈' },
    { id: ':station:', label: 'Station', emoji: '🚉' },
    { id: ':tram:', label: 'Tram', emoji: '🚊' },
    { id: ':monorail:', label: 'Monorail', emoji: '🚝' },
    { id: ':mountain_railway:', label: 'Mountain railway', emoji: '🚞' },
    { id: ':tram_car:', label: 'Tram car', emoji: '🚋' },
    { id: ':bus:', label: 'Bus', emoji: '🚌' },
    { id: ':oncoming_bus:', label: 'Oncoming bus', emoji: '🚍' },
    { id: ':trolleybus:', label: 'Trolleybus', emoji: '🚎' },
    { id: ':minibus:', label: 'Minibus', emoji: '🚐' },
    { id: ':ambulance:', label: 'Ambulance', emoji: '🚑' },
    { id: ':fire_engine:', label: 'Fire engine', emoji: '🚒' },
    { id: ':police_car:', label: 'Police car', emoji: '🚓' },
    { id: ':oncoming_police_car:', label: 'Oncoming police car', emoji: '🚔' },
    { id: ':taxi:', label: 'Taxi', emoji: '🚕' },
    { id: ':oncoming_taxi:', label: 'Oncoming taxi', emoji: '🚖' },
    { id: ':automobile:', label: 'Automobile', emoji: '🚗' },
    { id: ':oncoming_automobile:', label: 'Oncoming automobile', emoji: '🚘' },
    { id: ':sport_utility_vehicle:', label: 'Sport utility vehicle', emoji: '🚙' },
    { id: ':delivery_truck:', label: 'Delivery truck', emoji: '🚚' },
    { id: ':articulated_lorry:', label: 'Articulated lorry', emoji: '🚛' },
    { id: ':tractor:', label: 'Tractor', emoji: '🚜' },
    { id: ':racing_car:', label: 'Racing car', emoji: '🏎️' },
    { id: ':motorcycle:', label: 'Motorcycle', emoji: '🏍️' },
    { id: ':kick_scooter:', label: 'Kick scooter', emoji: '🛴' },
    { id: ':bicycle:', label: 'Bicycle', emoji: '🚲' },
    { id: ':auto_rickshaw:', label: 'Auto rickshaw', emoji: '🛺' },
    { id: ':helicopter:', label: 'Helicopter', emoji: '🚁' },
    { id: ':satellite:', label: 'Satellite', emoji: '🛰️' },
    { id: ':rocket:', label: 'Rocket', emoji: '🚀' },
    { id: ':flying_saucer:', label: 'Flying saucer', emoji: '🛸' },
    { id: ':canoe:', label: 'Canoe', emoji: '🛶' },
    { id: ':sailboat:', label: 'Sailboat', emoji: '⛵' },
    { id: ':speedboat:', label: 'Speedboat', emoji: '🚤' },
    { id: ':ship:', label: 'Ship', emoji: '🚢' },
    { id: ':airplane:', label: 'Airplane', emoji: '✈️' },
    { id: ':small_airplane:', label: 'Small airplane', emoji: '🛩️' },
    { id: ':airplane_departure:', label: 'Airplane departure', emoji: '🛫' },
    { id: ':airplane_arrival:', label: 'Airplane arrival', emoji: '🛬' },
    { id: ':seat:', label: 'Seat', emoji: '💺' },
    { id: ':police_car_light:', label: 'Police car light', emoji: '🚨' },
    { id: ':horizontal_traffic_light:', label: 'Horizontal traffic light', emoji: '🚥' },
    { id: ':vertical_traffic_light:', label: 'Vertical traffic light', emoji: '🚦' },
    { id: ':stop_sign:', label: 'Stop sign', emoji: '🛑' },
    { id: ':construction:', label: 'Construction', emoji: '🚧' },
  ],

  objects: [
    { id: ':watch:', label: 'Watch', emoji: '⌚' },
    { id: ':mobile_phone:', label: 'Mobile phone', emoji: '📱' },
    { id: ':mobile_phone_with_arrow:', label: 'Mobile phone with arrow', emoji: '📲' },
    { id: ':laptop:', label: 'Laptop', emoji: '💻' },
    { id: ':keyboard:', label: 'Keyboard', emoji: '⌨️' },
    { id: ':desktop_computer:', label: 'Desktop computer', emoji: '🖥️' },
    { id: ':printer:', label: 'Printer', emoji: '🖨️' },
    { id: ':computer_mouse:', label: 'Computer mouse', emoji: '🖱️' },
    { id: ':trackball:', label: 'Trackball', emoji: '🖲️' },
    { id: ':joystick_obj:', label: 'Joystick', emoji: '🕹️' },
    { id: ':computer_disk:', label: 'Computer disk', emoji: '💽' },
    { id: ':floppy_disk:', label: 'Floppy disk', emoji: '💾' },
    { id: ':optical_disk:', label: 'Optical disk', emoji: '💿' },
    { id: ':dvd:', label: 'DVD', emoji: '📀' },
    { id: ':videocassette:', label: 'Videocassette', emoji: '📼' },
    { id: ':camera:', label: 'Camera', emoji: '📷' },
    { id: ':camera_with_flash:', label: 'Camera with flash', emoji: '📸' },
    { id: ':video_camera:', label: 'Video camera', emoji: '📹' },
    { id: ':movie_camera:', label: 'Movie camera', emoji: '🎥' },
    { id: ':film_projector:', label: 'Film projector', emoji: '📽️' },
    { id: ':film_strip:', label: 'Film strip', emoji: '🎞️' },
    { id: ':telephone_receiver:', label: 'Telephone receiver', emoji: '📞' },
    { id: ':telephone:', label: 'Telephone', emoji: '☎️' },
    { id: ':pager:', label: 'Pager', emoji: '📟' },
    { id: ':fax_machine:', label: 'Fax machine', emoji: '📠' },
    { id: ':television:', label: 'Television', emoji: '📺' },
    { id: ':radio:', label: 'Radio', emoji: '📻' },
    { id: ':studio_microphone:', label: 'Studio microphone', emoji: '🎙️' },
    { id: ':level_slider:', label: 'Level slider', emoji: '🎚️' },
    { id: ':control_knobs:', label: 'Control knobs', emoji: '🎛️' },
    { id: ':stopwatch:', label: 'Stopwatch', emoji: '⏱️' },
    { id: ':timer_clock:', label: 'Timer clock', emoji: '⏲️' },
    { id: ':alarm_clock:', label: 'Alarm clock', emoji: '⏰' },
    { id: ':mantelpiece_clock:', label: 'Mantelpiece clock', emoji: '🕰️' },
    { id: ':hourglass_done:', label: 'Hourglass done', emoji: '⌛' },
    { id: ':hourglass_not_done:', label: 'Hourglass not done', emoji: '⏳' },
    { id: ':satellite_antenna:', label: 'Satellite antenna', emoji: '📡' },
    { id: ':battery:', label: 'Battery', emoji: '🔋' },
    { id: ':electric_plug:', label: 'Electric plug', emoji: '🔌' },
    { id: ':light_bulb:', label: 'Light bulb', emoji: '💡' },
    { id: ':flashlight:', label: 'Flashlight', emoji: '🔦' },
    { id: ':candle:', label: 'Candle', emoji: '🕯️' },
    { id: ':fire_extinguisher:', label: 'Fire extinguisher', emoji: '🧯' },
    { id: ':oil_drum:', label: 'Oil drum', emoji: '🛢️' },
    { id: ':money_with_wings:', label: 'Money with wings', emoji: '💸' },
    { id: ':dollar_banknote:', label: 'Dollar banknote', emoji: '💵' },
    { id: ':yen_banknote:', label: 'Yen banknote', emoji: '💴' },
    { id: ':euro_banknote:', label: 'Euro banknote', emoji: '💶' },
    { id: ':pound_banknote:', label: 'Pound banknote', emoji: '💷' },
    { id: ':money_bag:', label: 'Money bag', emoji: '💰' },
    { id: ':credit_card:', label: 'Credit card', emoji: '💳' },
    { id: ':gem_stone:', label: 'Gem stone', emoji: '💎' },
    { id: ':balance_scale:', label: 'Balance scale', emoji: '⚖️' },
    { id: ':toolbox:', label: 'Toolbox', emoji: '🧰' },
    { id: ':wrench:', label: 'Wrench', emoji: '🔧' },
    { id: ':hammer:', label: 'Hammer', emoji: '🔨' },
    { id: ':hammer_and_pick:', label: 'Hammer and pick', emoji: '⚒️' },
    { id: ':hammer_and_wrench:', label: 'Hammer and wrench', emoji: '🛠️' },
    { id: ':pick:', label: 'Pick', emoji: '⛏️' },
    { id: ':nut_and_bolt:', label: 'Nut and bolt', emoji: '🔩' },
    { id: ':gear:', label: 'Gear', emoji: '⚙️' },
    { id: ':brick:', label: 'Brick', emoji: '🧱' },
    { id: ':chains:', label: 'Chains', emoji: '⛓️' },
    { id: ':magnet:', label: 'Magnet', emoji: '🧲' },
    { id: ':water_pistol:', label: 'Water pistol', emoji: '🔫' },
    { id: ':bomb:', label: 'Bomb', emoji: '💣' },
    { id: ':firecracker:', label: 'Firecracker', emoji: '🧨' },
    { id: ':kitchen_knife:', label: 'Kitchen knife', emoji: '🔪' },
    { id: ':dagger:', label: 'Dagger', emoji: '🗡️' },
    { id: ':crossed_swords:', label: 'Crossed swords', emoji: '⚔️' },
    { id: ':shield:', label: 'Shield', emoji: '🛡️' },
    { id: ':cigarette:', label: 'Cigarette', emoji: '🚬' },
    { id: ':coffin:', label: 'Coffin', emoji: '⚰️' },
    { id: ':funeral_urn:', label: 'Funeral urn', emoji: '⚱️' },
    { id: ':amphora:', label: 'Amphora', emoji: '🏺' },
    { id: ':crystal_ball:', label: 'Crystal ball', emoji: '🔮' },
    { id: ':prayer_beads:', label: 'Prayer beads', emoji: '📿' },
    { id: ':nazar_amulet:', label: 'Nazar amulet', emoji: '🧿' },
    { id: ':barber_pole_obj:', label: 'Barber pole', emoji: '💈' },
    { id: ':alembic:', label: 'Alembic', emoji: '⚗️' },
    { id: ':telescope:', label: 'Telescope', emoji: '🔭' },
    { id: ':microscope:', label: 'Microscope', emoji: '🔬' },
    { id: ':hole:', label: 'Hole', emoji: '🕳️' },
    { id: ':pill:', label: 'Pill', emoji: '💊' },
    { id: ':syringe:', label: 'Syringe', emoji: '💉' },
    { id: ':thermometer:', label: 'Thermometer', emoji: '🌡️' },
    { id: ':broom:', label: 'Broom', emoji: '🧹' },
    { id: ':basket:', label: 'Basket', emoji: '🧺' },
    { id: ':roll_of_paper:', label: 'Roll of paper', emoji: '🧻' },
    { id: ':toilet:', label: 'Toilet', emoji: '🚽' },
    { id: ':shower:', label: 'Shower', emoji: '🚿' },
    { id: ':bathtub:', label: 'Bathtub', emoji: '🛁' },
    { id: ':lotion_bottle:', label: 'Lotion bottle', emoji: '🧴' },
    { id: ':safety_pin:', label: 'Safety pin', emoji: '🧷' },
    { id: ':teddy_bear:', label: 'Teddy bear', emoji: '🧸' },
    { id: ':framed_picture:', label: 'Framed picture', emoji: '🖼️' },
    { id: ':bed:', label: 'Bed', emoji: '🛏️' },
    { id: ':couch_and_lamp:', label: 'Couch and lamp', emoji: '🛋️' },
    { id: ':door:', label: 'Door', emoji: '🚪' },
    { id: ':luggage:', label: 'Luggage', emoji: '🧳' },
    { id: ':umbrella_on_ground:', label: 'Umbrella on ground', emoji: '⛱️' },
    { id: ':backpack:', label: 'Backpack', emoji: '🎒' },
    { id: ':clutch_bag:', label: 'Clutch bag', emoji: '👝' },
    { id: ':purse:', label: 'Purse', emoji: '👛' },
    { id: ':handbag:', label: 'Handbag', emoji: '👜' },
    { id: ':briefcase:', label: 'Briefcase', emoji: '💼' },
    { id: ':coat:', label: 'Coat', emoji: '🧥' },
    { id: ':necktie:', label: 'Necktie', emoji: '👔' },
    { id: ':t-shirt:', label: 'T-shirt', emoji: '👕' },
    { id: ':jeans:', label: 'Jeans', emoji: '👖' },
    { id: ':scarf:', label: 'Scarf', emoji: '🧣' },
    { id: ':gloves:', label: 'Gloves', emoji: '🧤' },
    { id: ':socks:', label: 'Socks', emoji: '🧦' },
    { id: ':dress:', label: 'Dress', emoji: '👗' },
    { id: ':kimono:', label: 'Kimono', emoji: '👘' },
    { id: ':bikini:', label: 'Bikini', emoji: '👙' },
    { id: ':womans_clothes:', label: 'Womans clothes', emoji: '👚' },
    { id: ':mans_shoe:', label: 'Mans shoe', emoji: '👞' },
    { id: ':running_shoe:', label: 'Running shoe', emoji: '👟' },
    { id: ':high-heeled_shoe:', label: 'High-heeled shoe', emoji: '👠' },
    { id: ':sandal:', label: 'Sandal', emoji: '👡' },
    { id: ':boot:', label: 'Boot', emoji: '👢' },
    { id: ':crown:', label: 'Crown', emoji: '👑' },
    { id: ':hat:', label: 'Hat', emoji: '👒' },
    { id: ':top_hat:', label: 'Top hat', emoji: '🎩' },
    { id: ':graduation_cap:', label: 'Graduation cap', emoji: '🎓' },
    { id: ':baseball_cap:', label: 'Baseball cap', emoji: '🧢' },
    { id: ':rescue_workers_helmet:', label: 'Rescue workers helmet', emoji: '⛑️' },
    { id: ':lipstick:', label: 'Lipstick', emoji: '💄' },
    { id: ':ring:', label: 'Ring', emoji: '💍' },
    // Stationery and office
    { id: ':pencil:', label: 'Pencil', emoji: '✏️' },
    { id: ':black_nib:', label: 'Black nib', emoji: '✒️' },
    { id: ':fountain_pen:', label: 'Fountain pen', emoji: '🖋️' },
    { id: ':pen:', label: 'Pen', emoji: '🖊️' },
    { id: ':paintbrush:', label: 'Paintbrush', emoji: '🖌️' },
    { id: ':crayon:', label: 'Crayon', emoji: '🖍️' },
    { id: ':memo:', label: 'Memo', emoji: '📝' },
    { id: ':file_folder:', label: 'File folder', emoji: '📁' },
    { id: ':open_file_folder:', label: 'Open file folder', emoji: '📂' },
    { id: ':card_index_dividers:', label: 'Card index dividers', emoji: '🗂️' },
    { id: ':calendar:', label: 'Calendar', emoji: '📅' },
    { id: ':tear-off_calendar:', label: 'Tear-off calendar', emoji: '📆' },
    { id: ':spiral_notepad:', label: 'Spiral notepad', emoji: '🗒️' },
    { id: ':spiral_calendar:', label: 'Spiral calendar', emoji: '🗓️' },
    { id: ':card_index:', label: 'Card index', emoji: '📇' },
    { id: ':chart_increasing:', label: 'Chart increasing', emoji: '📈' },
    { id: ':chart_decreasing:', label: 'Chart decreasing', emoji: '📉' },
    { id: ':bar_chart:', label: 'Bar chart', emoji: '📊' },
    { id: ':clipboard:', label: 'Clipboard', emoji: '📋' },
    { id: ':pushpin:', label: 'Pushpin', emoji: '📌' },
    { id: ':round_pushpin:', label: 'Round pushpin', emoji: '📍' },
    { id: ':paperclip:', label: 'Paperclip', emoji: '📎' },
    { id: ':linked_paperclips:', label: 'Linked paperclips', emoji: '🖇️' },
    { id: ':straight_ruler:', label: 'Straight ruler', emoji: '📏' },
    { id: ':triangular_ruler:', label: 'Triangular ruler', emoji: '📐' },
    { id: ':scissors:', label: 'Scissors', emoji: '✂️' },
    { id: ':card_file_box:', label: 'Card file box', emoji: '🗃️' },
    { id: ':file_cabinet:', label: 'File cabinet', emoji: '🗄️' },
    { id: ':wastebasket:', label: 'Wastebasket', emoji: '🗑️' },
    // Books and documents
    { id: ':closed_book:', label: 'Closed book', emoji: '📕' },
    { id: ':open_book:', label: 'Open book', emoji: '📖' },
    { id: ':green_book:', label: 'Green book', emoji: '📗' },
    { id: ':blue_book:', label: 'Blue book', emoji: '📘' },
    { id: ':orange_book:', label: 'Orange book', emoji: '📙' },
    { id: ':books:', label: 'Books', emoji: '📚' },
    { id: ':notebook:', label: 'Notebook', emoji: '📓' },
    { id: ':ledger:', label: 'Ledger', emoji: '📒' },
    {
      id: ':notebook_with_decorative_cover:',
      label: 'Notebook with decorative cover',
      emoji: '📔',
    },
    { id: ':page_with_curl:', label: 'Page with curl', emoji: '📃' },
    { id: ':scroll:', label: 'Scroll', emoji: '📜' },
    { id: ':page_facing_up:', label: 'Page facing up', emoji: '📄' },
    { id: ':newspaper:', label: 'Newspaper', emoji: '📰' },
    { id: ':rolled-up_newspaper:', label: 'Rolled-up newspaper', emoji: '🗞️' },
    { id: ':bookmark_tabs:', label: 'Bookmark tabs', emoji: '📑' },
    { id: ':bookmark:', label: 'Bookmark', emoji: '🔖' },
    { id: ':label:', label: 'Label', emoji: '🏷️' },
    // Mail and communication
    { id: ':envelope:', label: 'Envelope', emoji: '✉️' },
    { id: ':e-mail:', label: 'E-mail', emoji: '📧' },
    { id: ':incoming_envelope:', label: 'Incoming envelope', emoji: '📨' },
    { id: ':envelope_with_arrow:', label: 'Envelope with arrow', emoji: '📩' },
    { id: ':outbox_tray:', label: 'Outbox tray', emoji: '📤' },
    { id: ':inbox_tray:', label: 'Inbox tray', emoji: '📥' },
    { id: ':package:', label: 'Package', emoji: '📦' },
    { id: ':mailbox_closed:', label: 'Closed mailbox with raised flag', emoji: '📫' },
    { id: ':mailbox:', label: 'Closed mailbox with lowered flag', emoji: '📪' },
    { id: ':mailbox_with_mail:', label: 'Open mailbox with raised flag', emoji: '📬' },
    { id: ':mailbox_with_no_mail:', label: 'Open mailbox with lowered flag', emoji: '📭' },
    { id: ':postbox:', label: 'Postbox', emoji: '📮' },
    { id: ':ballot_box_with_ballot:', label: 'Ballot box with ballot', emoji: '🗳️' },
    // Locks and keys
    { id: ':locked:', label: 'Locked', emoji: '🔒' },
    { id: ':unlocked:', label: 'Unlocked', emoji: '🔓' },
    { id: ':locked_with_pen:', label: 'Locked with pen', emoji: '🔏' },
    { id: ':locked_with_key:', label: 'Locked with key', emoji: '🔐' },
    { id: ':key:', label: 'Key', emoji: '🔑' },
    { id: ':old_key:', label: 'Old key', emoji: '🗝️' },
    // Search and magnifying
    { id: ':magnifying_glass_tilted_left:', label: 'Magnifying glass tilted left', emoji: '🔍' },
    { id: ':magnifying_glass_tilted_right:', label: 'Magnifying glass tilted right', emoji: '🔎' },
    // Links
    { id: ':link:', label: 'Link', emoji: '🔗' },
  ],

  symbols: [
    // Weather and sky
    { id: ':sun:', label: 'Sun', emoji: '☀️' },
    { id: ':sun_with_face:', label: 'Sun with face', emoji: '🌞' },
    { id: ':full_moon:', label: 'Full moon', emoji: '🌕' },
    { id: ':waning_gibbous_moon:', label: 'Waning gibbous moon', emoji: '🌖' },
    { id: ':last_quarter_moon:', label: 'Last quarter moon', emoji: '🌗' },
    { id: ':waning_crescent_moon:', label: 'Waning crescent moon', emoji: '🌘' },
    { id: ':new_moon:', label: 'New moon', emoji: '🌑' },
    { id: ':waxing_crescent_moon:', label: 'Waxing crescent moon', emoji: '🌒' },
    { id: ':first_quarter_moon:', label: 'First quarter moon', emoji: '🌓' },
    { id: ':waxing_gibbous_moon:', label: 'Waxing gibbous moon', emoji: '🌔' },
    { id: ':crescent_moon:', label: 'Crescent moon', emoji: '🌙' },
    { id: ':new_moon_face:', label: 'New moon face', emoji: '🌚' },
    { id: ':first_quarter_moon_face:', label: 'First quarter moon face', emoji: '🌛' },
    { id: ':last_quarter_moon_face:', label: 'Last quarter moon face', emoji: '🌜' },
    { id: ':full_moon_face:', label: 'Full moon face', emoji: '🌝' },
    { id: ':ringed_planet:', label: 'Ringed planet', emoji: '🪐' },
    { id: ':fire:', label: 'Fire', emoji: '🔥' },
    { id: ':droplet:', label: 'Droplet', emoji: '💧' },
    { id: ':water_wave:', label: 'Water wave', emoji: '🌊' },
    { id: ':sparkles:', label: 'Sparkles', emoji: '✨' },
    { id: ':rainbow:', label: 'Rainbow', emoji: '🌈' },
    { id: ':high_voltage:', label: 'High voltage', emoji: '⚡' },
    { id: ':snowflake:', label: 'Snowflake', emoji: '❄️' },
    { id: ':snowman:', label: 'Snowman', emoji: '☃️' },
    { id: ':snowman_without_snow:', label: 'Snowman without snow', emoji: '⛄' },
    { id: ':cloud:', label: 'Cloud', emoji: '☁️' },
    { id: ':sun_behind_cloud:', label: 'Sun behind cloud', emoji: '⛅' },
    { id: ':sun_behind_small_cloud:', label: 'Sun behind small cloud', emoji: '🌤️' },
    { id: ':sun_behind_large_cloud:', label: 'Sun behind large cloud', emoji: '🌥️' },
    { id: ':sun_behind_rain_cloud:', label: 'Sun behind rain cloud', emoji: '🌦️' },
    { id: ':cloud_with_rain:', label: 'Cloud with rain', emoji: '🌧️' },
    { id: ':cloud_with_snow:', label: 'Cloud with snow', emoji: '🌨️' },
    { id: ':cloud_with_lightning:', label: 'Cloud with lightning', emoji: '🌩️' },
    { id: ':cloud_with_lightning_and_rain:', label: 'Cloud with lightning and rain', emoji: '⛈️' },
    { id: ':tornado:', label: 'Tornado', emoji: '🌪️' },
    { id: ':fog:', label: 'Fog', emoji: '🌫️' },
    { id: ':wind_face:', label: 'Wind face', emoji: '🌬️' },
    { id: ':cyclone:', label: 'Cyclone', emoji: '🌀' },
    { id: ':umbrella:', label: 'Umbrella', emoji: '☂️' },
    { id: ':umbrella_with_rain_drops:', label: 'Umbrella with rain drops', emoji: '☔' },
    { id: ':closed_umbrella:', label: 'Closed umbrella', emoji: '🌂' },
    // Hearts
    { id: ':red_heart:', label: 'Red heart', emoji: '❤️' },
    { id: ':orange_heart:', label: 'Orange heart', emoji: '🧡' },
    { id: ':yellow_heart:', label: 'Yellow heart', emoji: '💛' },
    { id: ':green_heart:', label: 'Green heart', emoji: '💚' },
    { id: ':blue_heart:', label: 'Blue heart', emoji: '💙' },
    { id: ':purple_heart:', label: 'Purple heart', emoji: '💜' },
    { id: ':black_heart:', label: 'Black heart', emoji: '🖤' },
    { id: ':white_heart:', label: 'White heart', emoji: '🤍' },
    { id: ':brown_heart:', label: 'Brown heart', emoji: '🤎' },
    { id: ':pink_heart:', label: 'Pink heart', emoji: '🩷' },
    { id: ':light_blue_heart:', label: 'Light blue heart', emoji: '🩵' },
    { id: ':grey_heart:', label: 'Grey heart', emoji: '🩶' },
    { id: ':heart_on_fire:', label: 'Heart on fire', emoji: '❤️‍🔥' },
    { id: ':mending_heart:', label: 'Mending heart', emoji: '❤️‍🩹' },
    { id: ':broken_heart:', label: 'Broken heart', emoji: '💔' },
    { id: ':heart_exclamation:', label: 'Heart exclamation', emoji: '❣️' },
    { id: ':two_hearts:', label: 'Two hearts', emoji: '💕' },
    { id: ':revolving_hearts:', label: 'Revolving hearts', emoji: '💞' },
    { id: ':beating_heart:', label: 'Beating heart', emoji: '💓' },
    { id: ':growing_heart:', label: 'Growing heart', emoji: '💗' },
    { id: ':sparkling_heart:', label: 'Sparkling heart', emoji: '💖' },
    { id: ':heart_with_arrow:', label: 'Heart with arrow', emoji: '💘' },
    { id: ':heart_with_ribbon:', label: 'Heart with ribbon', emoji: '💝' },
    { id: ':heart_decoration:', label: 'Heart decoration', emoji: '💟' },
    { id: ':peace_symbol:', label: 'Peace symbol', emoji: '☮️' },
    { id: ':latin_cross:', label: 'Latin cross', emoji: '✝️' },
    { id: ':star_and_crescent:', label: 'Star and crescent', emoji: '☪️' },
    { id: ':om:', label: 'Om', emoji: '🕉️' },
    { id: ':wheel_of_dharma:', label: 'Wheel of dharma', emoji: '☸️' },
    { id: ':star_of_david:', label: 'Star of David', emoji: '✡️' },
    { id: ':dotted_six-pointed_star:', label: 'Dotted six-pointed star', emoji: '🔯' },
    { id: ':menorah:', label: 'Menorah', emoji: '🕎' },
    { id: ':yin_yang:', label: 'Yin yang', emoji: '☯️' },
    { id: ':orthodox_cross:', label: 'Orthodox cross', emoji: '☦️' },
    { id: ':place_of_worship:', label: 'Place of worship', emoji: '🛐' },
    { id: ':atom_symbol:', label: 'Atom symbol', emoji: '⚛️' },
    { id: ':hundred_points:', label: 'Hundred points', emoji: '💯' },
    { id: ':red_circle:', label: 'Red circle', emoji: '🔴' },
    { id: ':orange_circle:', label: 'Orange circle', emoji: '🟠' },
    { id: ':yellow_circle:', label: 'Yellow circle', emoji: '🟡' },
    { id: ':green_circle:', label: 'Green circle', emoji: '🟢' },
    { id: ':blue_circle:', label: 'Blue circle', emoji: '🔵' },
    { id: ':purple_circle:', label: 'Purple circle', emoji: '🟣' },
    { id: ':black_circle:', label: 'Black circle', emoji: '⚫' },
    { id: ':white_circle:', label: 'White circle', emoji: '⚪' },
    { id: ':brown_circle:', label: 'Brown circle', emoji: '🟤' },
    { id: ':red_triangle_pointed_up:', label: 'Red triangle pointed up', emoji: '🔺' },
    { id: ':red_triangle_pointed_down:', label: 'Red triangle pointed down', emoji: '🔻' },
    { id: ':small_orange_diamond:', label: 'Small orange diamond', emoji: '🔸' },
    { id: ':small_blue_diamond:', label: 'Small blue diamond', emoji: '🔹' },
    { id: ':large_orange_diamond:', label: 'Large orange diamond', emoji: '🔶' },
    { id: ':large_blue_diamond:', label: 'Large blue diamond', emoji: '🔷' },
    { id: ':white_square_button:', label: 'White square button', emoji: '🔳' },
    { id: ':black_square_button:', label: 'Black square button', emoji: '🔲' },
    { id: ':black_small_square:', label: 'Black small square', emoji: '▪️' },
    { id: ':white_small_square:', label: 'White small square', emoji: '▫️' },
    { id: ':black_medium-small_square:', label: 'Black medium-small square', emoji: '◾' },
    { id: ':white_medium-small_square:', label: 'White medium-small square', emoji: '◽' },
    { id: ':black_medium_square:', label: 'Black medium square', emoji: '◼️' },
    { id: ':white_medium_square:', label: 'White medium square', emoji: '◻️' },
    { id: ':black_large_square:', label: 'Black large square', emoji: '⬛' },
    { id: ':white_large_square:', label: 'White large square', emoji: '⬜' },
    { id: ':red_square:', label: 'Red square', emoji: '🟥' },
    { id: ':orange_square:', label: 'Orange square', emoji: '🟧' },
    { id: ':yellow_square:', label: 'Yellow square', emoji: '🟨' },
    { id: ':green_square:', label: 'Green square', emoji: '🟩' },
    { id: ':blue_square:', label: 'Blue square', emoji: '🟦' },
    { id: ':purple_square:', label: 'Purple square', emoji: '🟪' },
    { id: ':brown_square:', label: 'Brown square', emoji: '🟫' },
    { id: ':star:', label: 'Star', emoji: '⭐' },
    { id: ':glowing_star:', label: 'Glowing star', emoji: '🌟' },
    { id: ':dizzy:', label: 'Dizzy', emoji: '💫' },
    { id: ':shooting_star:', label: 'Shooting star', emoji: '🌠' },
    { id: ':milky_way:', label: 'Milky Way', emoji: '🌌' },
    { id: ':comet:', label: 'Comet', emoji: '☄️' },
    { id: ':collision:', label: 'Collision', emoji: '💥' },
    { id: ':anger_symbol:', label: 'Anger symbol', emoji: '💢' },
    { id: ':sweat_droplets:', label: 'Sweat droplets', emoji: '💦' },
    { id: ':dashing_away:', label: 'Dashing away', emoji: '💨' },
    { id: ':speech_balloon:', label: 'Speech balloon', emoji: '💬' },
    { id: ':left_speech_bubble:', label: 'Left speech bubble', emoji: '🗨️' },
    { id: ':right_anger_bubble:', label: 'Right anger bubble', emoji: '🗯️' },
    { id: ':thought_balloon:', label: 'Thought balloon', emoji: '💭' },
    { id: ':zzz:', label: 'Zzz', emoji: '💤' },
    // Arrows
    { id: ':up_arrow:', label: 'Up arrow', emoji: '⬆️' },
    { id: ':up-right_arrow:', label: 'Up-right arrow', emoji: '↗️' },
    { id: ':right_arrow:', label: 'Right arrow', emoji: '➡️' },
    { id: ':down-right_arrow:', label: 'Down-right arrow', emoji: '↘️' },
    { id: ':down_arrow:', label: 'Down arrow', emoji: '⬇️' },
    { id: ':down-left_arrow:', label: 'Down-left arrow', emoji: '↙️' },
    { id: ':left_arrow:', label: 'Left arrow', emoji: '⬅️' },
    { id: ':up-left_arrow:', label: 'Up-left arrow', emoji: '↖️' },
    { id: ':up-down_arrow:', label: 'Up-down arrow', emoji: '↕️' },
    { id: ':left-right_arrow:', label: 'Left-right arrow', emoji: '↔️' },
    { id: ':right_arrow_curving_left:', label: 'Right arrow curving left', emoji: '↩️' },
    { id: ':left_arrow_curving_right:', label: 'Left arrow curving right', emoji: '↪️' },
    { id: ':right_arrow_curving_up:', label: 'Right arrow curving up', emoji: '⤴️' },
    { id: ':right_arrow_curving_down:', label: 'Right arrow curving down', emoji: '⤵️' },
    { id: ':clockwise_vertical_arrows:', label: 'Clockwise vertical arrows', emoji: '🔃' },
    {
      id: ':counterclockwise_arrows_button:',
      label: 'Counterclockwise arrows button',
      emoji: '🔄',
    },
    { id: ':back_arrow:', label: 'Back arrow', emoji: '🔙' },
    { id: ':end_arrow:', label: 'End arrow', emoji: '🔚' },
    { id: ':on!_arrow:', label: 'On! arrow', emoji: '🔛' },
    { id: ':soon_arrow:', label: 'Soon arrow', emoji: '🔜' },
    { id: ':top_arrow:', label: 'Top arrow', emoji: '🔝' },
    { id: ':medical_symbol:', label: 'Medical symbol', emoji: '⚕️' },
    { id: ':recycling_symbol:', label: 'Recycling symbol', emoji: '♻️' },
    { id: ':fleur-de-lis:', label: 'Fleur-de-lis', emoji: '⚜️' },
    { id: ':trident_emblem:', label: 'Trident emblem', emoji: '🔱' },
    { id: ':name_badge:', label: 'Name badge', emoji: '📛' },
    { id: ':japanese_symbol_for_beginner:', label: 'Japanese symbol for beginner', emoji: '🔰' },
    { id: ':heavy_large_circle:', label: 'Heavy large circle', emoji: '⭕' },
    { id: ':check_mark_button:', label: 'Check mark button', emoji: '✅' },
    { id: ':check_box_with_check:', label: 'Check box with check', emoji: '☑️' },
    { id: ':check_mark:', label: 'Check mark', emoji: '✔️' },
    { id: ':cross_mark:', label: 'Cross mark', emoji: '❌' },
    { id: ':cross_mark_button:', label: 'Cross mark button', emoji: '❎' },
    { id: ':plus:', label: 'Plus', emoji: '➕' },
    { id: ':minus:', label: 'Minus', emoji: '➖' },
    { id: ':divide:', label: 'Divide', emoji: '➗' },
    { id: ':curly_loop:', label: 'Curly loop', emoji: '➰' },
    { id: ':double_curly_loop:', label: 'Double curly loop', emoji: '➿' },
    { id: ':part_alternation_mark:', label: 'Part alternation mark', emoji: '〽️' },
    { id: ':eight-spoked_asterisk:', label: 'Eight-spoked asterisk', emoji: '✳️' },
    { id: ':eight-pointed_star:', label: 'Eight-pointed star', emoji: '✴️' },
    { id: ':sparkle:', label: 'Sparkle', emoji: '❇️' },
    { id: ':double_exclamation_mark:', label: 'Double exclamation mark', emoji: '‼️' },
    { id: ':exclamation_question_mark:', label: 'Exclamation question mark', emoji: '⁉️' },
    { id: ':question_mark:', label: 'Question mark', emoji: '❓' },
    { id: ':white_question_mark:', label: 'White question mark', emoji: '❔' },
    { id: ':white_exclamation_mark:', label: 'White exclamation mark', emoji: '❕' },
    { id: ':exclamation_mark:', label: 'Exclamation mark', emoji: '❗' },
    { id: ':wavy_dash:', label: 'Wavy dash', emoji: '〰️' },
    { id: ':copyright:', label: 'Copyright', emoji: '©️' },
    { id: ':registered:', label: 'Registered', emoji: '®️' },
    { id: ':trade_mark:', label: 'Trade mark', emoji: '™️' },
    { id: ':keycap_hash:', label: 'Keycap: #', emoji: '#️⃣' },
    { id: ':keycap_asterisk:', label: 'Keycap: *', emoji: '*️⃣' },
    { id: ':keycap_0:', label: 'Keycap: 0', emoji: '0️⃣' },
    { id: ':keycap_1:', label: 'Keycap: 1', emoji: '1️⃣' },
    { id: ':keycap_2:', label: 'Keycap: 2', emoji: '2️⃣' },
    { id: ':keycap_3:', label: 'Keycap: 3', emoji: '3️⃣' },
    { id: ':keycap_4:', label: 'Keycap: 4', emoji: '4️⃣' },
    { id: ':keycap_5:', label: 'Keycap: 5', emoji: '5️⃣' },
    { id: ':keycap_6:', label: 'Keycap: 6', emoji: '6️⃣' },
    { id: ':keycap_7:', label: 'Keycap: 7', emoji: '7️⃣' },
    { id: ':keycap_8:', label: 'Keycap: 8', emoji: '8️⃣' },
    { id: ':keycap_9:', label: 'Keycap: 9', emoji: '9️⃣' },
    { id: ':keycap_10:', label: 'Keycap: 10', emoji: '🔟' },
  ],

  flags: [
    { id: ':chequered_flag:', label: 'Chequered flag', emoji: '🏁' },
    { id: ':triangular_flag:', label: 'Triangular flag', emoji: '🚩' },
    { id: ':crossed_flags:', label: 'Crossed flags', emoji: '🎌' },
    { id: ':black_flag:', label: 'Black flag', emoji: '🏴' },
    { id: ':white_flag:', label: 'White flag', emoji: '🏳️' },
    { id: ':rainbow_flag:', label: 'Rainbow flag', emoji: '🏳️‍🌈' },
    { id: ':transgender_flag:', label: 'Transgender flag', emoji: '🏳️‍⚧️' },
    { id: ':pirate_flag:', label: 'Pirate flag', emoji: '🏴‍☠️' },
    // Country flags
    { id: ':united_states:', label: 'United States', emoji: '🇺🇸' },
    { id: ':canada:', label: 'Canada', emoji: '🇨🇦' },
    { id: ':mexico:', label: 'Mexico', emoji: '🇲🇽' },
    { id: ':brazil:', label: 'Brazil', emoji: '🇧🇷' },
    { id: ':argentina:', label: 'Argentina', emoji: '🇦🇷' },
    { id: ':chile:', label: 'Chile', emoji: '🇨🇱' },
    { id: ':france:', label: 'France', emoji: '🇫🇷' },
    { id: ':germany:', label: 'Germany', emoji: '🇩🇪' },
    { id: ':italy:', label: 'Italy', emoji: '🇮🇹' },
    { id: ':spain:', label: 'Spain', emoji: '🇪🇸' },
    { id: ':portugal:', label: 'Portugal', emoji: '🇵🇹' },
    { id: ':netherlands:', label: 'Netherlands', emoji: '🇳🇱' },
    { id: ':belgium:', label: 'Belgium', emoji: '🇧🇪' },
    { id: ':switzerland:', label: 'Switzerland', emoji: '🇨🇭' },
    { id: ':austria:', label: 'Austria', emoji: '🇦🇹' },
    { id: ':sweden:', label: 'Sweden', emoji: '🇸🇪' },
    { id: ':norway:', label: 'Norway', emoji: '🇳🇴' },
    { id: ':denmark:', label: 'Denmark', emoji: '🇩🇰' },
    { id: ':finland:', label: 'Finland', emoji: '🇫🇮' },
    { id: ':iceland:', label: 'Iceland', emoji: '🇮🇸' },
    { id: ':ireland:', label: 'Ireland', emoji: '🇮🇪' },
    { id: ':united_kingdom:', label: 'United Kingdom', emoji: '🇬🇧' },
    { id: ':russia:', label: 'Russia', emoji: '🇷🇺' },
    { id: ':ukraine:', label: 'Ukraine', emoji: '🇺🇦' },
    { id: ':poland:', label: 'Poland', emoji: '🇵🇱' },
    { id: ':japan:', label: 'Japan', emoji: '🇯🇵' },
    { id: ':south_korea:', label: 'South Korea', emoji: '🇰🇷' },
    { id: ':china:', label: 'China', emoji: '🇨🇳' },
    { id: ':india:', label: 'India', emoji: '🇮🇳' },
    { id: ':australia:', label: 'Australia', emoji: '🇦🇺' },
    { id: ':new_zealand:', label: 'New Zealand', emoji: '🇳🇿' },
    { id: ':south_africa:', label: 'South Africa', emoji: '🇿🇦' },
    { id: ':egypt:', label: 'Egypt', emoji: '🇪🇬' },
    { id: ':saudi_arabia:', label: 'Saudi Arabia', emoji: '🇸🇦' },
    { id: ':united_arab_emirates:', label: 'United Arab Emirates', emoji: '🇦🇪' },
    { id: ':kenya:', label: 'Kenya', emoji: '🇰🇪' },
    { id: ':nigeria:', label: 'Nigeria', emoji: '🇳🇬' },
    { id: ':ghana:', label: 'Ghana', emoji: '🇬🇭' },
    { id: ':thailand:', label: 'Thailand', emoji: '🇹🇭' },
    { id: ':vietnam:', label: 'Vietnam', emoji: '🇻🇳' },
    { id: ':singapore:', label: 'Singapore', emoji: '🇸🇬' },
    { id: ':malaysia:', label: 'Malaysia', emoji: '🇲🇾' },
    { id: ':indonesia:', label: 'Indonesia', emoji: '🇮🇩' },
    { id: ':philippines:', label: 'Philippines', emoji: '🇵🇭' },
  ],
}

/** Get emoji item by ID */
export const getEmoji = (emojiId: string): EmojiItem | undefined => {
  for (const emojis of Object.values(EMOJI_DATA)) {
    const found = emojis.find((item) => item.id === emojiId)
    if (found) return found
  }
  return undefined
}
