// 🤖 AUTO-GENERATED by packages/workflow-nodes/scripts/generate-frontend.ts - DO NOT EDIT
// This file is automatically updated when running: pnpm --filter @auxx/workflow-nodes run generate

import { ComponentType } from 'react'
import { NodeProps } from '@xyflow/react'
import { NodeDefinition, NodeType } from '~/components/workflow/types'

// Generated node component imports
import { ProfessionalNetworkNode } from './professionalNetwork/node'

// Generated node definition imports  
import { professionalNetworkDefinition } from './professionalNetwork'

/**
 * Auto-generated node definitions
 * Updated automatically when running: pnpm --filter @auxx/workflow-nodes run generate
 */
export const AUTO_GENERATED_NODE_DEFINITIONS: NodeDefinition[] = [
  professionalNetworkDefinition,
]

/**
 * Auto-generated node component types  
 * Updated automatically when running: pnpm --filter @auxx/workflow-nodes run generate
 */
export const AUTO_GENERATED_NODE_TYPES: Record<string, ComponentType<NodeProps>> = {
  [NodeType.PROFESSIONAL_NETWORK]: ProfessionalNetworkNode as ComponentType<NodeProps>,
}
