// packages/lib/src/data-migrations/migrations/148-recurring-journal-entries.ts

import { type Database, schema } from '@auxx/database'
import { createScopedLogger } from '@auxx/logger'
import { eq } from 'drizzle-orm'
import { getOrgCache } from '../../cache'
import { JOURNAL_ENTRY_FIELDS } from '../../resources/registry/resources/journal-entry-fields'
import { ensureCustomFields, loadExistingState } from '../../seed/entity-helpers'
import type { PerOrgMigration, PerOrgMigrationResult } from '../per-org'

const logger = createScopedLogger('entity-migrations:148')

const JOURNAL_ENTRY_ENTITY_TYPE = 'journal_entry'
const JOURNAL_ENTRY_KIND_ATTRIBUTE = 'journal_entry_kind'

/**
 * The option this migration adds, as a LITERAL.
 *
 * A migration must still make sense years after the enum it might have
 * imported has changed - `132-card-clearing-rename.ts` and
 * `144-gl-account-code-optional-and-subtype.ts` hold their stored strings the
 * same way, for the same reason. This is the VALUE this migration writes, not
 * a reference to whatever `JournalEntryKind` currently says.
 */
const RECURRING_KIND_OPTION = { value: 'recurring', label: 'Recurring', color: 'indigo' }

/** A new field is invisible to every read path that serves it until these drop. */
const CACHE_KEYS = ['customFields', 'resources'] as const

/**
 * Migration 148: `journal_entry` learns what a GENERATED entry is
 * (`plans/accounting/tasks/21-the-books-stand-alone.md` §1).
 *
 * ## Why a migration and not just the registry edit
 *
 * Registry edits reach no existing org on their own. `ensureCustomFields` is
 * INSERT-only, so the two new fields do not exist on any org that already has
 * a `journal_entry` def; and it never UPDATES a stored field, so the
 * `journal_entry_kind` SINGLE_SELECT keeps the three options migration 125
 * gave it. A fresh org gets all of it from the registry; every existing one
 * needs this.
 *
 * ## What it does, per org
 *
 * 1. **`recurring` on `journal_entry_kind`.** The value the sweep stamps on an
 *    entry it copies out of a template. It is a fourth option rather than a
 *    reuse of `manual` because the kind is the single authority for the
 *    posting type: `recurring` posts as `recurring_journal`, whose `periodKey`
 *    is a fold of `<ruleId>:<occurrenceDate>` rather than the record's own
 *    number. Two drafts of one occurrence then contend on one claim tuple and
 *    the second converges to `already_posted`; two `manual` drafts would key
 *    on their own numbers and post the month twice.
 * 2. **`journal_entry_recurrence_rule_id` and
 *    `journal_entry_occurrence_date`.** Both TEXT, both set once. Together
 *    they ARE the idempotency key above, which is why the occurrence date is
 *    text and separate from `journal_entry_date`: the accounting date may be
 *    re-dated by a person, and the slot identity may never move.
 *
 * ## No backfill, and there is nothing to backfill
 *
 * No entry in any org was generated by a scheduler, because there was no
 * scheduler. Both fields are correctly null everywhere, and a null pair is
 * what `assertRecurrenceIdentity` reads as "hand-authored".
 *
 * ## Idempotent
 *
 * A re-run finds the option already present and both fields already created -
 * `alreadyUpToDate: true`, nothing written. Safe to re-apply with
 * `packages/lib/scripts/run-entity-migration.ts --id 148-recurring-journal-entries`.
 */
export const migration148RecurringJournalEntries: PerOrgMigration = {
  id: '148-recurring-journal-entries',
  description:
    "Adds the 'recurring' journal_entry_kind option and the recurrence rule / occurrence date " +
    'fields a generated entry keys its posting on (task 21 §1.4)',

  async up(db: Database, organizationId: string): Promise<PerOrgMigrationResult> {
    const state = { entityDefsCreated: 0, fieldsCreated: 0, relationshipsLinked: 0 }
    const existing = await loadExistingState(db, organizationId)

    const journalEntryDef = existing.entityDefs.get(JOURNAL_ENTRY_ENTITY_TYPE)
    if (!journalEntryDef) {
      // The org never got migration 125's `journal_entry` def. Fresh installs
      // bring the whole shape along from the registry.
      return { ...state, alreadyUpToDate: true }
    }

    // (a) The fourth kind.
    const kindField = [...existing.fields.values()].find(
      (field) =>
        field.entityDefinitionId === journalEntryDef.id &&
        field.systemAttribute === JOURNAL_ENTRY_KIND_ATTRIBUTE
    )
    let optionAdded = false
    if (kindField) {
      const stored = kindField.options as { options?: { value: string }[] } | null
      const currentOptions = stored?.options ?? []
      if (!currentOptions.some((option) => option.value === RECURRING_KIND_OPTION.value)) {
        await db
          .update(schema.CustomField)
          .set({
            options: { ...(stored ?? {}), options: [...currentOptions, RECURRING_KIND_OPTION] },
            updatedAt: new Date(),
          })
          .where(eq(schema.CustomField.id, kindField.id))
        optionAdded = true
      }
    }

    // (b) The two pointer fields, created when missing.
    const ruleFieldDef = JOURNAL_ENTRY_FIELDS.recurrenceRuleId
    const slotFieldDef = JOURNAL_ENTRY_FIELDS.occurrenceDate
    if (!ruleFieldDef || !slotFieldDef) {
      throw new Error(
        "journal-entry-fields registry is missing 'recurrenceRuleId' or 'occurrenceDate' " +
          '(migration 148)'
      )
    }
    await ensureCustomFields(
      db,
      organizationId,
      JOURNAL_ENTRY_ENTITY_TYPE,
      journalEntryDef.id,
      { recurrenceRuleId: ruleFieldDef, occurrenceDate: slotFieldDef },
      existing,
      state
    )

    const changed = optionAdded || state.fieldsCreated > 0

    if (changed) {
      // `ensureCustomFields` and the direct `CustomField` write both bypass the
      // org cache, and `UnifiedCrudHandler` resolves a field's shape from it -
      // a stale entry would keep refusing the `recurring` option and hiding
      // both pointers until something else evicted it. `perOrgMigration`
      // does this after the whole batch, but `up()` is also called directly by
      // `scripts/run-entity-migration.ts`, so do it here too (as 137, 139 and
      // 144 do).
      await getOrgCache().invalidateAndRecompute(organizationId, [...CACHE_KEYS])
      logger.info('Migration 148 applied', {
        organizationId,
        kindOptionAdded: optionAdded,
        fieldsCreated: state.fieldsCreated,
      })
    }

    return { ...state, alreadyUpToDate: !changed }
  },
}
