// Application constants used across the monorepo
import { HOMEPAGE_URL, WEBAPP_URL } from './url'

export const constants = {
  app: { name: 'Auxx.ai', description: 'AI-powered email support ticket answer service' },

  pagination: { defaultPageSize: 25, maxPageSize: 100 },

  limits: {
    maxFileSize: 10 * 1024 * 1024, // 10MB
    maxAttachments: 5,
  },

  timing: {
    sessionTimeout: 30 * 60 * 1000, // 30 minutes
    refreshTokenExpiry: 7 * 24 * 60 * 60, // 7 days
  },

  /** App categories for marketplace */
  appCategories: [
    { value: 'analytics', label: 'Analytics', icon: 'BarChart3' },
    { value: 'autonomous', label: 'Autonomous', icon: 'Bot' },
    { value: 'billing', label: 'Billing', icon: 'CreditCard' },
    { value: 'calling', label: 'Calling', icon: 'Phone' },
    { value: 'customer-support', label: 'Customer Support', icon: 'Headphones' },
    { value: 'communication', label: 'Communication', icon: 'MessageSquare' },
    { value: 'forms-survey', label: 'Forms & Survey', icon: 'ClipboardList' },
    { value: 'product-management', label: 'Product Management', icon: 'Package' },
  ] as const,

  /** Workflow template categories */
  workflowCategories: [
    { value: 'all', label: 'All Templates', icon: 'LayoutGrid' },
    { value: 'customer-service', label: 'Customer Service', icon: 'Headphones' },
    { value: 'shopify', label: 'Shopify', icon: 'ShoppingBag' },
    { value: 'automation', label: 'Automation', icon: 'Zap' },
    { value: 'routing', label: 'Routing & Assignment', icon: 'GitBranch' },
    { value: 'ai', label: 'AI-Powered', icon: 'Sparkles' },
    { value: 'sales', label: 'Sales & Marketing', icon: 'TrendingUp' },
  ] as const,

  PRIVACY_URL: `${HOMEPAGE_URL}/privacy-policy`,
  IMPRINT_URL: `${HOMEPAGE_URL}/imprint`,
  TOS_URL: `${HOMEPAGE_URL}/terms-of-service`,
  IMPRINT_ADDRESS: '8811 S Test Drive, Inglewood, CA 90305',
} as const

/**
 * Reserved API slugs that cannot be used for custom entity definitions
 * These are system entity types and would conflict with built-in functionality
 */
export const RESERVED_API_SLUGS = [
  'thread',
  'message',
  'contact',
  'workflow',
  'ticket',
  'dataset',
  'user',
  'inbox',
  'participant',
  'file',
  'shopify',
  'kb',
  'auxx',
  'auxxai',
  'threads',
  'messages',
  'contacts',
  'workflows',
  'tickets',
  'datasets',
  'users',
  'inboxes',
  'participants',
  'files',
  'kbs',
] as const

export type ReservedApiSlug = (typeof RESERVED_API_SLUGS)[number]

/**
 * Reserved handles that cannot be used for organization URLs
 * These conflict with system routes, auth paths, and reserved namespaces
 */
export const RESERVED_ORGANIZATION_HANDLES = [
  'api',
  'auxx',
  'auxxai',
  'welcome',
  'integrations',
  'auth',
  'admin',
  'awac',
  'atac',
  'redirect',
  'workspaces',
  'authorize',
  'app-invites',
  '2fa-recovery',
  '2fa',
  'account-lock',
  'account-recover',
  'account-recovery',
  'account-unlock',
  'account-verify',
  'account',
  'activate',
  'auth-callback',
  'auth-login',
  'auth-logout',
  'auth-register',
  'auth-reset-password',
  'auth-signup',
  'auth-token',
  'auth-verify',
  'change-password',
  'confirm-email',
  'consent',
  'email-confirm',
  'email-verification',
  'forgot-password',
  'jwks-json',
  'jwks',
  'login',
  'logout',
  'oauth-access-token',
  'oauth-authorize',
  'oauth-callback',
  'oauth-consent',
  'oauth-error',
  'oauth-introspect',
  'oauth-login',
  'oauth-redirect',
  'oauth-refresh-token',
  'oauth-revoke',
  'oauth-token',
  'oauth-userinfo',
  'oauth',
  'openid-authorize',
  'openid-callback',
  'openid-config',
  'openid-configuration',
  'openid-connect',
  'openid-introspect',
  'openid-jwks',
  'openid-logout',
  'openid-redirect',
  'openid-revoke',
  'openid-token',
  'openid-userinfo',
  'openid',
  'password-change',
  'password-recovery',
  'password-reset',
  'profile',
  'recover-password',
  'refresh-token',
  'register',
  'reset-password',
  'saml-acs',
  'saml-idp',
  'saml-login',
  'saml-metadata',
  'saml-slo',
  'saml-sp',
  'saml-sso-login',
  'saml-sso',
  'saml',
  'session',
  'sessions',
  'signin',
  'signout',
  'signup',
  'token',
  'tokens',
  'two-factor-recovery',
  'two-factor',
  'user-2fa',
  'user-account',
  'user-activate',
  'user-change-password',
  'user-forgot-password',
  'user-lock',
  'user-login',
  'user-logout',
  'user-profile',
  'user-recover-account',
  'user-recover-password',
  'user-recover',
  'user-register',
  'user-reset-password',
  'user-signin',
  'user-signout',
  'user-signup',
  'user-unlock',
  'user-verify-email',
  'user-verify',
  'verify-2fa',
  'verify-email',
  'verify',
  'well-known',
  'admin-dashboard',
  'administrator',
  'api-v1',
  'api-v2',
  'backend',
  'backup',
  'backups',
  'bin',
  'cgi-bin',
  'cmd',
  'config',
  'configuration',
  'control-panel',
  'controlpanel',
  'dashboard',
  'database',
  'db',
  'debug',
  'env',
  'graphql',
  'hidden',
  'internal-api',
  'log',
  'logs',
  'manage',
  'management',
  'private-api',
  'private',
  'script',
  'scripts',
  'secret',
  'secure',
  'service',
  'services',
  'settings',
  'super-user',
  'superuser',
  'system-config',
  'system',
  '404',
  '500',
  'error',
  'download',
  'downloads',
  'faq',
  'help',
  'privacy',
  'security',
  'terms',
  'uploads',
  'ds-store',
  'git',
  'hg',
  'htaccess',
  'htpasswd',
  'svn',
] as const

export type ReservedOrganizationHandle = (typeof RESERVED_ORGANIZATION_HANDLES)[number]
