// apps/web/src/components/workflow/ui/output-variables/output-variables-display.tsx

'use client'

import React, { useMemo } from 'react'
// import Section from '../section'
import { VarItem } from '../structured-output-generator/output-vars'
import { type UnifiedVariable, BaseType } from '../../types/variable-types'
import type { OutputVariablesDisplayProps, DisplayVariable } from '../../types/output-variables'
import Section from '../section'
import { parseVariable } from '~/components/workflow/utils/variable-utils'

/**
 * Converts a UnifiedVariable to a DisplayVariable structure for the VarItem component
 * Recursively processes nested objects and arrays to any depth
 */
function unifiedVariableToDisplayVariable(variable: UnifiedVariable): DisplayVariable {
  const parsed = parseVariable(variable)
  const displayVar: DisplayVariable = {
    name: variable.label,
    type: parsed.displayType,
    description: variable.description,
  }

  // Handle object types with properties - recursively process each property
  if (variable.type === BaseType.OBJECT && variable.properties) {
    displayVar.subItems = Object.entries(variable.properties).map(([key, prop]) => {
      // Create a child variable with proper label and recursively convert it
      const childVariable: UnifiedVariable = { ...prop, label: key }
      return unifiedVariableToDisplayVariable(childVariable)
    })
  }

  // Handle array types with items - recursively process the items structure
  if (variable.type === BaseType.ARRAY && variable.items) {
    // Create a child variable for the array item and recursively convert it
    // Preserve the original label if it exists (for entity types like "Product")
    const childVariable: UnifiedVariable = {
      ...variable.items,
      label: variable.items.label || '[item]',
    }
    displayVar.subItems = [unifiedVariableToDisplayVariable(childVariable)]
  }

  return displayVar
}

/**
 * Component to display output variables from a node in a read-only format
 */
export const OutputVariablesDisplay: React.FC<OutputVariablesDisplayProps> = ({
  outputVariables = [],
  outputs,
  nodeId,
  title = 'Output Variables',
  description = 'Output variables generated by this node',
  initialOpen = false,
  className,
}) => {
  const variables = outputVariables
  // Convert outputs to outputVariables if needed
  // const variables = useMemo(() => {
  //   // If outputVariables provided, use them (for built-in nodes)
  //   if (outputVariables) {
  //     return outputVariables
  //   }

  //   // If outputs provided, convert them to UnifiedVariables (for app blocks)
  //   if (outputs && nodeId) {
  //     return convertOutputFieldsToVariables(outputs, nodeId)
  //   }

  //   return []
  // }, [outputVariables, outputs, nodeId])

  // Transform UnifiedVariables to DisplayVariables
  const displayVariables = useMemo(() => {
    return variables.map(unifiedVariableToDisplayVariable)
  }, [variables])
  if (!variables || variables.length === 0) {
    return null
  }

  return (
    <Section
      title={title}
      initialOpen={initialOpen}
      description={description}
      className={className}>
      {displayVariables.map((variable, index) => (
        <VarItem
          key={index}
          name={variable.name}
          type={variable.type}
          description={variable.description}
          subItems={variable.subItems}
        />
      ))}
    </Section>
  )
}
