// packages/lib/src/sequences/crud.ts
// Sequence CRUD (Sequences plan §3.4/Phase 2). `createSequence` also
// provisions the hidden system-owned `WorkflowApp`/`Workflow` pair a sequence
// compiles onto at publish time (plan §3.2 gap 4) — mirrors
// `workflows/workflow-service.ts`'s `create()` WorkflowApp+Workflow insert
// shape, but skips the draft-workflow half entirely: a sequence's graph is
// always generated by `publishSequence`, never hand-drafted, so only the
// published `workflowId` slot is ever used.

import { type Database, schema } from '@auxx/database'
import { generateId } from '@auxx/utils'
import { and, count, eq } from 'drizzle-orm'
import { err, ok, type Result } from 'neverthrow'
import { ConflictError, NotFoundError } from '../errors'
import { grantSequenceCreatorAccess } from './access'
import type { CreateSequenceInput, SequenceEntity, UpdateSequenceFields } from './types'

/**
 * Create a draft sequence. Provisions its hidden `WorkflowApp`
 * (`ownerType: 'sequence'`) + an empty-graph `Workflow` in the same
 * transaction, then grants the creator `admin` `ResourceAccess`.
 */
export async function createSequence(
  db: Database,
  input: CreateSequenceInput
): Promise<Result<SequenceEntity, Error>> {
  const {
    organizationId,
    name,
    description,
    integrationId,
    signatureEntityInstanceId,
    deliveryStartTime,
    deliveryEndTime,
    deliveryTimezone,
    deliveryBusinessDaysOnly,
    createdById,
  } = input

  // Pre-generated so the WorkflowApp row can carry `ownerId` (Sequence.id)
  // before the Sequence row itself exists — the two rows reference each
  // other, so one side's id must be minted client-side.
  const sequenceId = generateId()
  const now = new Date()

  const sequence = await db.transaction(async (tx) => {
    const [workflowApp] = await tx
      .insert(schema.WorkflowApp)
      .values({
        organizationId,
        name: `[Sequence] ${name}`,
        enabled: true,
        createdById,
        ownerType: 'sequence',
        ownerId: sequenceId,
        updatedAt: now,
      })
      .returning()

    const [workflow] = await tx
      .insert(schema.Workflow)
      .values({
        organizationId,
        name: `${name} (sequence)`,
        enabled: true,
        version: 1,
        triggerType: 'manual',
        workflowAppId: workflowApp!.id,
        graph: { nodes: [], edges: [] },
        createdById,
        updatedAt: now,
      })
      .returning()

    await tx
      .update(schema.WorkflowApp)
      .set({ workflowId: workflow!.id, updatedAt: now })
      .where(eq(schema.WorkflowApp.id, workflowApp!.id))

    const [created] = await tx
      .insert(schema.Sequence)
      .values({
        id: sequenceId,
        organizationId,
        name,
        description: description ?? null,
        status: 'draft',
        workflowAppId: workflowApp!.id,
        integrationId: integrationId ?? null,
        signatureEntityInstanceId: signatureEntityInstanceId ?? null,
        deliveryStartTime: deliveryStartTime ?? null,
        deliveryEndTime: deliveryEndTime ?? null,
        deliveryTimezone: deliveryTimezone ?? null,
        deliveryBusinessDaysOnly: deliveryBusinessDaysOnly ?? false,
        createdById,
      })
      .returning()

    return created!
  })

  await grantSequenceCreatorAccess({ db, organizationId, userId: createdById }, sequenceId)

  return ok(sequence)
}

export interface UpdateSequenceInput {
  sequenceId: string
  organizationId: string
  fields: UpdateSequenceFields
}

/**
 * Patch a sequence's draft fields. Any field edit after publish marks
 * `hasUnpublishedChanges: true` — an explicit `status` change (pause/resume)
 * bypasses that (status isn't part of the compiled graph).
 */
export async function updateSequence(
  db: Database,
  input: UpdateSequenceInput
): Promise<Result<SequenceEntity, Error>> {
  const { sequenceId, organizationId, fields } = input
  const existing = await db.query.Sequence.findFirst({
    where: and(
      eq(schema.Sequence.id, sequenceId),
      eq(schema.Sequence.organizationId, organizationId)
    ),
  })
  if (!existing) return err(new NotFoundError('Sequence not found'))

  const { status, ...draftFields } = fields
  const hasDraftEdits = Object.keys(draftFields).length > 0

  const [updated] = await db
    .update(schema.Sequence)
    .set({
      ...draftFields,
      ...(status !== undefined ? { status } : {}),
      ...(hasDraftEdits && existing.publishedAt ? { hasUnpublishedChanges: true } : {}),
    })
    .where(eq(schema.Sequence.id, sequenceId))
    .returning()

  return ok(updated!)
}

/** List all sequences for an org, newest first. */
export async function listSequences(
  db: Database,
  params: { organizationId: string }
): Promise<Result<SequenceEntity[], Error>> {
  const rows = await db.query.Sequence.findMany({
    where: eq(schema.Sequence.organizationId, params.organizationId),
    orderBy: (t, { desc }) => desc(t.createdAt),
  })
  return ok(rows)
}

/** Fetch a single sequence, org-scoped. */
export async function getSequence(
  db: Database,
  params: { sequenceId: string; organizationId: string }
): Promise<Result<SequenceEntity, Error>> {
  const row = await db.query.Sequence.findFirst({
    where: and(
      eq(schema.Sequence.id, params.sequenceId),
      eq(schema.Sequence.organizationId, params.organizationId)
    ),
  })
  if (!row) return err(new NotFoundError('Sequence not found'))
  return ok(row)
}

/**
 * Delete a sequence and everything under it. Forbidden while any run is
 * still active (in-flight enrollments must exit/complete first). Deleting
 * the hidden `WorkflowApp` cascades onto its `Workflow` row (FK) AND onto the
 * `Sequence` row itself (`Sequence.workflowAppId` FK is `onDelete: 'cascade'`),
 * which in turn cascades onto `SequenceStep`/`SequenceRun` — one delete call
 * unwinds the whole tree.
 */
export async function deleteSequence(
  db: Database,
  params: { sequenceId: string; organizationId: string }
): Promise<Result<void, Error>> {
  const { sequenceId, organizationId } = params
  const sequence = await db.query.Sequence.findFirst({
    where: and(
      eq(schema.Sequence.id, sequenceId),
      eq(schema.Sequence.organizationId, organizationId)
    ),
  })
  if (!sequence) return err(new NotFoundError('Sequence not found'))

  const [{ activeCount }] = await db
    .select({ activeCount: count() })
    .from(schema.SequenceRun)
    .where(
      and(eq(schema.SequenceRun.sequenceId, sequenceId), eq(schema.SequenceRun.status, 'active'))
    )

  if (activeCount > 0) {
    return err(new ConflictError('Cannot delete a sequence with active runs — exit them first'))
  }

  await db.delete(schema.WorkflowApp).where(eq(schema.WorkflowApp.id, sequence.workflowAppId))

  return ok(undefined)
}
