// apps/web/src/components/fields/ai-overlay/sparkle-badge.tsx

'use client'

import type { AiValueMetadata } from '@auxx/lib/realtime/client'
import { cn } from '@auxx/ui/lib/utils'
import { formatRelativeTime } from '@auxx/utils'
import { Tooltip } from '~/components/global/tooltip'
import { SparkleIcon, type SparkleIconVariant } from '~/components/kopilot/ui/sparkle-icon'

/**
 * - `'cell'`: absolute-positioned overlay anchored to the top-left of a table
 *   cell; only visible when the row has the `.cell-selected` class.
 * - `'inline'`: flows in-line next to other badges (property row, detail view).
 */
export type SparkleBadgeVariant = 'cell' | 'inline'

interface SparkleBadgeProps {
  metadata?: AiValueMetadata
  /** Click regenerates the AI value. */
  onClick: () => void
  /** Stale = input-hash drift. Switches the sparkle icon to the `stale` variant. */
  stale?: boolean
  /** Generation in flight — switches the icon to the floating `generating` variant. */
  isGenerating?: boolean
  /** Last generation failed. Switches the icon to `error` and surfaces the message. */
  errorMessage?: string
  /** Layout variant. Defaults to `'cell'` for the existing table-cell mount. */
  variant?: SparkleBadgeVariant
}

/**
 * Circular sparkle badge carrying AI value state. In `'cell'` variant it's
 * anchored to the top-left corner of a cell and only appears on selection;
 * in `'inline'` variant it flows with surrounding content. Click
 * regenerates (or generates, if the cell has no prior AI value).
 */
export function SparkleBadge({
  metadata,
  onClick,
  stale,
  isGenerating,
  errorMessage,
  variant = 'cell',
}: SparkleBadgeProps) {
  // Metadata is populated the first time the worker writes an AI value, so its
  // presence is the regenerate-vs-generate signal: no metadata → nothing to
  // regenerate yet.
  const isRegenerate = metadata?.generatedAt != null
  const rel = metadata?.generatedAt ? formatRelativeTime(metadata.generatedAt) : null
  const model = metadata?.model

  const iconVariant: SparkleIconVariant = isGenerating
    ? 'generating'
    : errorMessage
      ? 'error'
      : !isRegenerate
        ? 'empty'
        : stale
          ? 'stale'
          : 'generated'

  const tooltipContent = (
    <div className='text-xs'>
      {isGenerating ? (
        <span>Generating AI value…</span>
      ) : errorMessage ? (
        <span>{errorMessage} · Click to retry</span>
      ) : !isRegenerate ? (
        <span>Click to generate AI value</span>
      ) : stale ? (
        <span>AI value may be out of date · Click to regenerate</span>
      ) : (
        <span>
          {model ? `Generated by ${model}` : 'AI generated'}
          {rel ? ` · ${rel}` : ''} · Click to regenerate
        </span>
      )}
    </div>
  )

  return (
    <Tooltip contentComponent={tooltipContent} side='top' delayDuration={200}>
      <button
        type='button'
        onPointerDown={(e) => e.stopPropagation()}
        onClick={(e) => {
          e.stopPropagation()
          if (isGenerating) return
          onClick()
        }}
        className={cn(
          'size-4 items-center justify-center pointer-events-auto',
          variant === 'cell'
            ? // Overflows half a button-height into the row above and a bit
              // to the left. Only visible when the cell is selected
              // (including while editing); `visible` overrides the
              // `visibility: hidden` that the cell's inline-edit wrapper
              // applies via the `invisible` utility — without it, the
              // ancestor's hidden visibility cascades and the badge
              // disappears in edit mode even though its display rule still
              // matches.
              'absolute -top-2 -left-2 z-16 hidden visible [.cell-selected_&]:flex'
            : 'relative inline-flex'
        )}>
        <SparkleIcon variant={iconVariant} />
      </button>
    </Tooltip>
  )
}
