// apps/web/src/components/fields/ai-overlay/sparkle-badge.tsx

'use client'

import type { AiValueMetadata } from '@auxx/lib/realtime/client'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@auxx/ui/components/tooltip'
import { cn } from '@auxx/ui/lib/utils'
import { Sparkles } from 'lucide-react'

interface SparkleBadgeProps {
  metadata?: AiValueMetadata
  /** Click regenerates the AI value. */
  onClick: () => void
  /** Stale = input-hash drift. Renders an amber ring hint. */
  stale?: boolean
}

function formatRelative(iso?: string): string | null {
  if (!iso) return null
  const then = new Date(iso).getTime()
  if (Number.isNaN(then)) return null
  const diffMs = Date.now() - then
  const mins = Math.round(diffMs / 60_000)
  if (mins < 1) return 'just now'
  if (mins < 60) return `${mins}m ago`
  const hrs = Math.round(mins / 60)
  if (hrs < 24) return `${hrs}h ago`
  const days = Math.round(hrs / 24)
  return `${days}d ago`
}

/**
 * Circular sparkle badge anchored to the top-left corner of an AI-generated
 * cell. Overflows half a button-height into the row above and a bit to the
 * left. Click regenerates.
 */
export function SparkleBadge({ metadata, onClick, stale }: SparkleBadgeProps) {
  const rel = formatRelative(metadata?.generatedAt)
  const model = metadata?.model

  return (
    <TooltipProvider>
      <Tooltip delayDuration={200}>
        <TooltipTrigger asChild>
          <button
            type='button'
            onPointerDown={(e) => e.stopPropagation()}
            onClick={(e) => {
              e.stopPropagation()
              onClick()
            }}
            className={cn(
              'absolute -top-2 -left-2 z-16 size-4 items-center justify-center rounded-full',
              // Only visible when the cell is selected (but not editing) —
              // matches the ExpandableCell self-overlay visibility pattern.
              'hidden [.cell-selected:not(.cell-editing)_&]:flex',
              'ring-1 bg-background shadow-sm transition-colors',
              'text-purple-500 hover:text-purple-600',
              'hover:bg-purple-50 dark:hover:bg-purple-500/10',
              'pointer-events-auto',
              stale
                ? 'ring-amber-500/60 hover:ring-amber-500'
                : 'ring-purple-500/40 hover:ring-purple-500'
            )}>
            <Sparkles className='size-3' />
          </button>
        </TooltipTrigger>
        <TooltipContent side='top'>
          <div className='text-xs'>
            {stale ? (
              <span>AI value may be out of date · Click to regenerate</span>
            ) : (
              <span>
                {model ? `Generated by ${model}` : 'AI generated'}
                {rel ? ` · ${rel}` : ''} · Click to regenerate
              </span>
            )}
          </div>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}
