// packages/lib/scripts/generate-inter-font.ts
//
// One-off generator for `src/documents/fonts/inter.ts` — downloads the official Inter
// v4.1 release (pinned, MIT-licensed: https://github.com/rsms/inter), extracts the
// static Regular + Bold TTFs, and emits base64 TS constants. react-pdf documents embed
// fonts as in-memory Buffers via `Font.register` — no bundler in this repo copies loose
// asset files into `dist` (money MQ2 build spec §B.3), so the font ships as a committed
// TS module instead of a binary blob in the repo.
//
// Re-run only if the embedded font needs to change — the generated `inter.ts` is
// committed and imported directly at runtime; this script is not part of any build step.
//
// Run (from repo root):
//   npx tsx packages/lib/scripts/generate-inter-font.ts

import { execSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const RELEASE_ZIP_URL = 'https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip'
const OUTPUT_PATH = join(import.meta.dirname, '../src/documents/fonts/inter.ts')

async function main() {
  const workDir = mkdtempSync(join(tmpdir(), 'inter-font-'))
  const zipPath = join(workDir, 'inter.zip')

  console.log(`Downloading ${RELEASE_ZIP_URL} ...`)
  execSync(`curl -sL -o "${zipPath}" "${RELEASE_ZIP_URL}"`, { stdio: 'inherit' })

  console.log('Extracting Regular + Bold static TTFs ...')
  execSync(
    `unzip -o -j "${zipPath}" "extras/ttf/Inter-Regular.ttf" "extras/ttf/Inter-Bold.ttf" -d "${workDir}"`,
    { stdio: 'inherit' }
  )

  const regularB64 = readFileSync(join(workDir, 'Inter-Regular.ttf')).toString('base64')
  const boldB64 = readFileSync(join(workDir, 'Inter-Bold.ttf')).toString('base64')

  const output = `// packages/lib/src/documents/fonts/inter.ts
// GENERATED by packages/lib/scripts/generate-inter-font.ts — do not hand-edit.
// Inter v4.1 (SIL Open Font License 1.1, https://github.com/rsms/inter) Regular + Bold,
// base64-embedded so react-pdf's Font.register can load them as in-memory Buffers — no
// bundler in this repo copies loose asset files into dist (money MQ2 build spec §B.3).

/** Inter Regular (400) TTF, base64-encoded. */
export const INTER_REGULAR_BASE64 = '${regularB64}'

/** Inter Bold (700) TTF, base64-encoded. */
export const INTER_BOLD_BASE64 = '${boldB64}'
`

  writeFileSync(OUTPUT_PATH, output)
  rmSync(workDir, { recursive: true, force: true })

  console.log(`Wrote ${OUTPUT_PATH} (${(output.length / 1024).toFixed(0)} KB)`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
