// packages/lib/src/accounting/ledger/client.ts
//
// Client-safe entry point for the ledger module. Pure re-exports only: types,
// account codes, the entry builders and the period helpers. Nothing here touches
// a database, a logger, or a provider.
//
// NOTE: no 'use client' directive - this file is imported by server code too
// (the builders run in a worker), and the directive would turn every export into
// a client-reference proxy there. See docs/lib-module-guide.md section 7.

export {
  GL_ACCOUNT_TYPE_META,
  type GlAccountTypeMeta,
  glAccountTypeMeta,
} from '../../resources/registry/gl-account-type-meta'
export {
  ACCOUNT_ROLE_LABELS,
  ACCOUNT_ROLES,
  type AccountRole,
  type BuildCreditMemoEntitlementEntryInput,
  type BuildCreditMemoEntryInput,
  type BuildEntryInput,
  type BuildFulfillmentEntryInput,
  type BuildInvoiceEntryInput,
  type BuildManualEntryInput,
  type BuildOpeningBalanceEntryInput,
  type BuildPayoutEntryInput,
  type BuiltCreditMemoEntitlementEntry,
  type BuiltCreditMemoEntry,
  type BuiltFulfillmentEntry,
  type BuiltInventoryMovementEntry,
  type BuiltInvoiceEntry,
  type BuiltManualEntry,
  type BuiltOpeningBalanceEntry,
  type BuiltPayoutEntry,
  type BuiltVendorBillEntry,
  buildCreditMemoEntitlementEntry,
  buildCreditMemoEntry,
  buildDocNumber,
  buildEntry,
  buildFulfillmentEntry,
  buildInventoryMovementEntry,
  buildInvoiceEntry,
  buildManualEntry,
  buildOpeningBalanceEntry,
  buildPayoutEntry,
  buildVendorBillEntry,
  CHANNEL_KEYS,
  CREDIT_MEMO_POSTING_TYPE,
  CREDIT_MEMO_SOURCE_TYPE,
  type CreditMemoAmountsInput,
  type CreditMemoEntitlementComponent,
  computeCreditMemoAmounts,
  computeShipmentTotals,
  cutoverDateFor,
  DOC_NUMBER_KIND,
  DOC_NUMBER_MAX_LENGTH,
  DOC_NUMBER_PREFIX,
  DOCUMENT_KEY_MAX_LENGTH,
  type DocNumberInput,
  type DocNumberKind,
  extendRateToAmount,
  FULFILLMENT_SOURCE_TYPE,
  type FulfillmentShippedLine,
  fulfillmentPeriodKey,
  INVOICE_ISSUED_POSTING_TYPE,
  INVOICE_SOURCE_TYPE,
  type InventoryDocumentKind,
  type InventoryMovementEntryInput,
  type InventoryMovementLine,
  MANUAL_ENTRY_SOURCE_TYPE,
  type ManualEntryLine,
  type ManualPostingType,
  OPENING_ENTRY_SOURCE_TYPE,
  type OpeningBalanceLine,
  type OrderChannelKey,
  PAYOUT_SOURCE_TYPE,
  ROLE_ACCOUNT_SUBTYPES,
  ROLE_ACCOUNT_TYPES,
  roleAcceptsManualSource,
  roleScopeAxis,
  SCOPABLE_ROLES,
  type ScopeAxis,
  type ShipmentTotals,
  type ShipmentTotalsInput,
  type ShipmentTotalsLine,
  toAmountMinor,
  toChannelKey,
  toMinorUnits,
  VENDOR_BILL_POSTING_TYPE,
  VENDOR_BILL_SOURCE_TYPE,
  type VendorBillEntryInput,
  type VendorBillLineInput,
} from './builders/client'
export {
  type AccountCodeBand,
  type AccountNode,
  accountDepth,
  accountLabel,
  accountPath,
  accountPathLabel,
  accountSubtypeLabel,
  buildAccountTree,
  CHART_PACK_KEYS,
  CHART_PACKS,
  type ChartPack,
  type ChartPackKey,
  CLEARING_ACCOUNT_CODE_BAND,
  type CodedAccount,
  compareAccountsByCodeThenName,
  DEFAULT_CHART_OF_ACCOUNTS,
  type DefaultChartAccount,
  descendantIds,
  GL_ACCOUNT_SUBTYPES,
  GL_ACCOUNT_TYPES,
  type GlAccountSubtypeValue,
  type GlAccountTypeValue,
  isManualSource,
  MERCHANT_FEE_ACCOUNT_CODE_BAND,
  type NamedAccount,
  nextAccountCode,
  PROVIDER_ACCOUNT_TYPE_SUBTYPE,
  packForRole,
  packState,
  planChartImport,
  ROLE_IMPORT_MATCH,
  type SourceAccountSubject,
  sortChartTree,
  sourceAccountLabel,
  sourceAccountTooltip,
  sourceProviderLabel,
} from './chart/client'
export {
  assertDocumentKey,
  assertPeriodOpen,
  type CloseBlockerItem,
  type CloseBlockerItemKey,
  closeBlockerMessage,
  compareMonths,
  describeIncompleteRevenue,
  describeUnmappedRoles,
  hashedPeriodKey,
  type IncompleteRevenueCounts,
  incompleteRevenueLead,
  isPeriodLocked,
  MAX_COMPACT_PERIOD_KEY,
  monthBounds,
  monthDateRange,
  monthLabel,
  type ParsedPeriodKey,
  type PeriodGranularity,
  type PeriodLock,
  parsePeriodKey,
  periodKeyForDate,
  periodMonth,
} from './periods/client'
export {
  type DuplicateMovementEntry,
  type DuplicateMovementFinding,
  didLedgerAccept,
  LEDGER_WIDE_SETTING_KEYS,
  type MonthEndInventorySnapshot,
  POSTING_DRAFT_VERSION,
  POSTING_POLICIES,
  POSTING_POLICY,
  type PostingAssertions,
  type PostingDraftV1,
  type PostingParameter,
  type PostingPolicy,
  type PostingRecordLink,
  type PostingSettingCopy,
  type PostingTemplateLine,
  type PostingTrigger,
  reverseAssertions,
} from './post/client'
export {
  type PostingExportState,
  type PostingExportStateFilter,
  type PostingListRow,
  summaryGrainKey,
} from './reads/client'
export {
  ENABLED_POSTING_TYPES,
  EXPORT_ROUTE_BY_POSTING_TYPE,
  type ExportRoute,
  INVENTORY_ROLES,
  SINGLE_WRITER_ROLES,
  SINGLE_WRITER_ROLES_BY_POSTING_TYPE,
} from './roles/client'
export {
  ABSORPTION_RATE_SETTING_KEYS,
  avenueOfPostingType,
  describeUnscopedSources,
  EXPORT_AVENUES,
  type ExportAvenue,
  type ExportSettings,
  FINALIZED_SETUP_STATE,
  isSummaryGrainAvenue,
  isValidTimeZone,
  isWholeMinorUnits,
  LEDGER_CURRENCY,
  minorUnitError,
  OPENING_BASELINE_SETTING_KEYS,
  OPENING_FROM_NOTHING_SETTING_KEY,
  type OpeningTrialBalanceSummary,
  openingDifference,
  openingDifferenceRows,
  openingTrialBalanceDifference,
  type ReadinessRequirement,
  readOpeningFromNothing,
  readSettingMinorUnits,
  readSettingText,
  resolveSetupReadiness,
  SETUP_READINESS_SETTING_KEYS,
  type SettingsRecord,
  type SetupReadiness,
  type SetupReadinessContext,
  SUMMARY_GRAIN_AVENUES,
  SUMMARY_GRAINS,
  type SummaryGrain,
  type SummaryGrainAvenue,
  summariseOpeningTrialBalance,
  type UnscopedSourceConnection,
  type UnscopedSourceRole,
  type UnscopedSourceWarning,
} from './setup/client'
// The manual bucket's identity, for screens that render a source account and
// have to tell the sentinel row apart from a connected one (`source-scope.ts`).
export {
  type AccountIdentityRow,
  type AccountIdentityState,
  type AccountSuggestionReason,
  type BooksBalanceDiscrepancy,
  type BooksBalanceReport,
  type BuiltEntry,
  type ChartAccountRow,
  type ChartImportPlan,
  type ChartImportResult,
  type ClosePeriod,
  type CounterpartyType,
  type EntryPreview,
  type GlPostingLineInput,
  type GlPostingSourceInput,
  MANUAL_SOURCE_EXTERNAL_ID,
  MANUAL_SOURCE_LABEL,
  MANUAL_SOURCE_PROVIDER_KEY,
  NON_FAILURE_REFUSALS,
  POSTED_STATUSES,
  POSTING_LINK_ROLES,
  POSTING_STATUSES,
  POSTING_TYPES,
  type PostFailureClass,
  type PostingDetail,
  type PostingDetailLine,
  type PostingDirection,
  type PostingLinkRole,
  type PostingStatus,
  type PostingType,
  type PostResult,
  type PostResultStatus,
  type ProviderAccount,
  type ProviderBalanceRow,
  type ProviderBalanceSheet,
  ProviderPostError,
  type ResolvedPostingLine,
  type RoleAssignmentRow,
  type RoleAssignmentState,
  type RoleRailAssignmentRow,
  type RoleSourceAssignmentRow,
  type RoleSourceRow,
  type RoleSourceScope,
} from './types'
