// packages/lib/src/accounting/ledger/index.ts
//
// Server entry point for the postings module - our own double-entry ledger
// (plans/purchasing/README.md decisions P1/P2, build plan section 7).
//
// The accounting system is an exporter. Postings are built here, balanced here,
// keyed on account CODES here, and only then handed to whichever
// `AccountingProvider` an organization has connected - possibly none.
//
// Client code must import `@auxx/lib/accounting/ledger/client`, never this barrel.

export {
  GL_ACCOUNT_TYPE_META,
  type GlAccountTypeMeta,
  glAccountTypeMeta,
} from '../../resources/registry/gl-account-type-meta'
export {
  ACCOUNT_ROLE_LABELS,
  ACCOUNT_ROLES,
  type AccountingBasisDimension,
  type AccountRole,
  type BuildCreditMemoEntitlementEntryInput,
  type BuildCreditMemoEntryInput,
  type BuildDepositApplicationEntryInput,
  type BuildEntryInput,
  type BuildFulfillmentEntryInput,
  type BuildInvoiceEntryInput,
  type BuildManualEntryInput,
  type BuildOpeningBalanceEntryInput,
  type BuildPayoutEntryInput,
  type BuildWriteOffEntryInput,
  type BuiltCreditMemoEntitlementEntry,
  type BuiltCreditMemoEntry,
  type BuiltDepositApplicationEntry,
  type BuiltFulfillmentEntry,
  type BuiltInventoryMovementEntry,
  type BuiltInvoiceEntry,
  type BuiltManualEntry,
  type BuiltOpeningBalanceEntry,
  type BuiltPayoutEntry,
  type BuiltVendorBillEntry,
  buildCreditMemoEntitlementEntry,
  buildCreditMemoEntry,
  buildDepositApplicationEntry,
  buildDocNumber,
  buildEntry,
  buildFulfillmentEntry,
  buildInventoryMovementEntry,
  buildInvoiceEntry,
  buildManualEntry,
  buildOpeningBalanceEntry,
  buildPayoutEntry,
  buildVendorBillEntry,
  buildWriteOffEntry,
  CHANNEL_KEYS,
  CREDIT_MEMO_POSTING_TYPE,
  CREDIT_MEMO_SOURCE_TYPE,
  type CreditMemoAmountsInput,
  type CreditMemoEntitlementComponent,
  computeCreditMemoAmounts,
  computeShipmentTotals,
  cutoverDateFor,
  DEPOSIT_APPLICATION_PERIOD_KEY_PREFIX,
  DEPOSIT_APPLICATION_POSTING_TYPE,
  DEPOSIT_APPLICATION_SOURCE_TYPE,
  DOC_NUMBER_MAX_LENGTH,
  DOC_NUMBER_PREFIX,
  type DocNumberInput,
  depositApplicationPeriodKey,
  extendRateToAmount,
  FULFILLMENT_SOURCE_TYPE,
  type FulfillmentShippedLine,
  fulfillmentPeriodKey,
  INVOICE_ISSUED_POSTING_TYPE,
  INVOICE_SOURCE_TYPE,
  type InventoryDocumentKind,
  type InventoryMovementEntryInput,
  type InventoryMovementLine,
  MANUAL_ENTRY_SOURCE_TYPE,
  MAX_WRITE_OFF_ATTEMPT,
  type ManualEntryLine,
  type ManualPostingType,
  OPENING_ENTRY_SOURCE_TYPE,
  type OpeningBalanceLine,
  type OrderChannelKey,
  PAYOUT_SOURCE_TYPE,
  ROLE_ACCOUNT_TYPES,
  reservedAccountingBasis,
  roleAcceptsManualSource,
  roleScopeAxis,
  SCOPABLE_ROLES,
  type ScopeAxis,
  type ShipmentTotals,
  type ShipmentTotalsInput,
  type ShipmentTotalsLine,
  toAmountMinor,
  toChannelKey,
  toMinorUnits,
  VENDOR_BILL_POSTING_TYPE,
  VENDOR_BILL_SOURCE_TYPE,
  type VendorBillEntryInput,
  type VendorBillLineInput,
  WRITE_OFF_SOURCE_TYPE,
  writeOffPeriodKey,
} from './builders'
export {
  type AccountCodeBand,
  type AccountNode,
  accountDepth,
  accountLabel,
  accountPath,
  accountPathLabel,
  accountSubtypeLabel,
  buildAccountTree,
  CHART_PACK_KEYS,
  CHART_PACKS,
  type ChartPack,
  type ChartPackKey,
  CLEARING_ACCOUNT_CODE_BAND,
  type CodedAccount,
  type CreateChartAccountOptions,
  compareAccountsByCodeThenName,
  createChartAccount,
  DEFAULT_CHART_OF_ACCOUNTS,
  type DefaultChartAccount,
  descendantIds,
  GL_ACCOUNT_SUBTYPES,
  GL_ACCOUNT_TYPES,
  type GlAccountSubtypeValue,
  type GlAccountTypeValue,
  type ImportChartOptions,
  importChartFromProvider,
  MERCHANT_FEE_ACCOUNT_CODE_BAND,
  type NamedAccount,
  nextAccountCode,
  PROVIDER_ACCOUNT_TYPE_SUBTYPE,
  packForRole,
  packState,
  planChartImport,
  type RemoveChartAccountOptions,
  ROLE_IMPORT_MATCH,
  removeChartAccount,
  restoreChartAccount,
  sortChartTree,
  type UpdateChartAccountOptions,
  updateChartAccount,
} from './chart'
export {
  assertAccountingSetupUnfrozen,
  assertCompactablePeriodKey,
  assertPeriodOpen,
  type CloseBlockersResult,
  compareMonths,
  FROZEN_SETUP_SETTING_KEYS,
  hashedPeriodKey,
  isPeriodLocked,
  listClosePeriods,
  MAX_COMPACT_PERIOD_KEY,
  type MonthActivity,
  type ParsedPeriodKey,
  PERIOD_LOCK_SETTING_KEY,
  type PeriodGranularity,
  type PeriodLock,
  type PostingTypeActivity,
  parsePeriodKey,
  periodKeyForDate,
  periodMonth,
  type ReadMonthActivityOptions,
  readCloseBlockers,
  readMonthActivity,
  resolvePeriodLock,
  type SetLockedThroughInput,
  setLockedThrough,
} from './periods'
export {
  type BooksBalanceDiscrepancy,
  type BooksBalanceReport,
  buildPostingDraft,
  type DuplicateMovementEntry,
  type DuplicateMovementFinding,
  didLedgerAccept,
  discardDraftPosting,
  type EntryPreview,
  exportInventoryMovement,
  type FindDuplicateBankMovementsOptions,
  findDuplicateBankMovements,
  type InventoryDocumentSubject,
  inventoryTxnDate,
  isExpectedPostOutcome,
  LEDGER_CURRENCY,
  LEDGER_WIDE_SETTING_KEYS,
  linkMovementsToPosting,
  type MonthEndInventorySnapshot,
  POSTING_DRAFT_VERSION,
  POSTING_POLICIES,
  POSTING_POLICY,
  type PostDraftOptions,
  type PostEntryOptions,
  type PostingAssertions,
  type PostingDraftV1,
  type PostingParameter,
  type PostingPolicy,
  type PostingRecordLink,
  type PostingSettingCopy,
  type PostingTemplateLine,
  type PostingTrigger,
  type PostPayoutEntryOptions,
  type PreviewEntryOptions,
  parsePostingDraft,
  postDraft,
  postEntry,
  postInventoryMovementInTx,
  postPayoutEntry,
  previewEntry,
  type ReverseEntriesOptions,
  type ReverseEntryOptions,
  reverseAssertions,
  reverseEntries,
  reverseEntry,
  reverseInventoryMovementPosting,
  reversePostingForMovement,
  type UpdateDraftLinesInput,
  updateDraftLines,
  verifyBooksBalance,
  withAccountingCommitLock,
} from './post'
export {
  getPosting,
  type LatestPostingByType,
  type LedgerSummaryLine,
  type LedgerSummaryRow,
  listPostings,
  listPostingsForSource,
  type ReadLedgerSummaryOptions,
  readLatestPostingsByType,
  readLedgerSummary,
  readPostingLineSourceIds,
  type SourcePosting,
  summaryGrainKey,
} from './reads'
export {
  ENABLED_POSTING_TYPES,
  EXPORT_ROUTE_BY_POSTING_TYPE,
  type ExportRoute,
  ensureManualSourceAccount,
  findInventoryWriterConflicts,
  findWriterConflicts,
  INVENTORY_ROLES,
  type InventoryWriterConflict,
  listChartAccounts,
  listChartAccountUsage,
  listRoleMap,
  listRoleSources,
  loadRoleAccountCodes,
  MANUAL_SOURCE_EXTERNAL_ID,
  MANUAL_SOURCE_LABEL,
  MANUAL_SOURCE_PROVIDER_KEY,
  type ResolvedAccount,
  type RoleSourceRow,
  type RoleSourceScope,
  readManualSourceAccountId,
  resolveAccountLines,
  resolveRoles,
  type SaveMappingRow,
  type SetRoleAssignmentOptions,
  SINGLE_WRITER_ROLES,
  SINGLE_WRITER_ROLES_BY_POSTING_TYPE,
  saveRoleAssignments,
  setRoleAssignment,
  type WriterConflict,
} from './roles'
export {
  avenueOfPostingType,
  EXPORT_AVENUES,
  type ExportAvenue,
  type ExportSettings,
  type OpeningTrialBalanceSummary,
  openingTrialBalanceDifference,
  readBookTimeZone,
  readBookTimeZoneOrUtc,
  readExportSettings,
  resolveSetupReadiness,
  type SetupReadiness,
  type SetupReadinessContext,
  SUMMARY_GRAIN_AVENUES,
  type SummaryGrain,
  type SummaryGrainAvenue,
  summariseOpeningTrialBalance,
  todayInBookTimeZone,
} from './setup'
export {
  type AccountIdentityRow,
  type AccountIdentityState,
  type AccountSuggestionReason,
  type BuiltEntry,
  type ChartAccountRow,
  type ChartImportPlan,
  type ChartImportResult,
  type ClosePeriod,
  type CounterpartyType,
  type GlPostingLineInput,
  NON_FAILURE_REFUSALS,
  POSTING_STATUSES,
  POSTING_TYPES,
  type PostFailureClass,
  type PostingDetail,
  type PostingDetailLine,
  type PostingDirection,
  type PostingType,
  type PostResult,
  type PostResultStatus,
  type ProviderAccount,
  type ProviderBalanceRow,
  type ProviderBalanceSheet,
  ProviderPostError,
  type ResolvedPostingLine,
  type ReverseManyResult,
  type ReverseOutcome,
  type RoleAssignmentRow,
  type RoleAssignmentState,
  type RoleRailAssignmentRow,
  type WithdrawResult,
} from './types'
