// packages/lib/tsdown.config.ts
import { readFileSync } from 'node:fs'
import { builtinModules } from 'node:module'
import { defineConfig } from 'tsdown'

// Derive entry points from package.json exports (generated by generate-exports.ts)
const pkg = JSON.parse(readFileSync('package.json', 'utf8'))
const entries = Object.values(pkg.exports as Record<string, Record<string, string>>)
  .map((exp) => exp.types ?? exp.default)
  .filter((p): p is string => typeof p === 'string' && p.startsWith('./src/'))
  .map((p) => p.slice(2)) // remove './' prefix

export default defineConfig({
  entry: entries,
  format: 'esm',
  target: 'es2022',
  // `neutral`, not `node`: with `node`, rolldown emits its shared runtime chunk
  // (`dist/_virtual/_rolldown/runtime.mjs`) with a top-level
  // `import { createRequire } from 'node:module'`. Nothing here ever calls
  // `__require`, so that import is dead — but it is inherited by every chunk
  // needing a runtime helper, `errors.mjs` among them. A client component
  // importing any `@auxx/lib/<feature>/client` whose graph reaches `errors.mjs`
  // then drags `node:module` into a browser chunk, and Turbopack does not fail
  // gracefully on that — it panics the dev server with "the chunking context
  // (unknown) does not support external modules".
  platform: 'neutral',
  // Both of these were implied by `platform: 'node'`. Keep them explicitly, or
  // the output silently becomes `.js` (package.json `exports` point at
  // `./dist/**/*.mjs`) and every Node builtin warns as unresolved — the bare
  // specifiers (`crypto`, `path`, `child_process`) as well as the `node:` ones,
  // since `neutral` carries no builtin list of its own.
  fixedExtension: true,
  external: [/^node:/, ...builtinModules],
  unbundle: true,
  dts: false,
  loader: { '.md': 'text' },
  tsconfig: 'tsconfig.build.json',
})
