// packages/lib/tsdown.config.ts
import { readFileSync } from 'node:fs'
import { defineConfig } from 'tsdown'

// Derive entry points from package.json exports (generated by generate-exports.ts)
const pkg = JSON.parse(readFileSync('package.json', 'utf8'))
const entries = Object.values(pkg.exports as Record<string, Record<string, string>>)
  .map((exp) => exp.types ?? exp.default)
  .filter((p): p is string => typeof p === 'string' && p.startsWith('./src/'))
  .map((p) => p.slice(2)) // remove './' prefix

export default defineConfig({
  entry: entries,
  format: 'esm',
  target: 'es2022',
  platform: 'node',
  unbundle: true,
  dts: false,
  tsconfig: 'tsconfig.build.json',
})
