// packages/lib/src/mrp/__tests__/support/plan-item.ts

import type { MrpPlanItemRow } from '../../reads/runs'

/** A stored item with neutral defaults; tests override what they assert on. */
export function item(overrides: Partial<MrpPlanItemRow> & { partId: string }): MrpPlanItemRow {
  return {
    mrpPlanRunId: 'run1',
    organizationId: 'org1',
    supplyType: 'bought',
    buffered: false,
    proposedBuffered: false,
    proposalReasons: [],
    adu: null,
    sigma: null,
    cv: null,
    stockoutDaysExcluded: null,
    onHand: 0,
    onOrder: 0,
    openDemand: 0,
    netFlow: 0,
    leadTimeDays: null,
    leadTimeSource: 'none',
    decoupledLeadTimeDays: null,
    observedLeadTimeDays: null,
    observedReceipts: null,
    leadTimeFactor: null,
    leadTimeFactorSource: null,
    variabilityFactor: null,
    variabilityFactorSource: null,
    orderCycleDays: null,
    orderMode: 'when_needed',
    nextOrderDate: null,
    nextArrivalDate: null,
    followingArrivalDate: null,
    pullsOrderForward: null,
    seasonalIndex: null,
    baseAdu: null,
    topOfRed: null,
    topOfYellow: null,
    topOfGreen: null,
    stockoutDate: null,
    orderByDate: null,
    priority: null,
    suggestionKind: null,
    suggestedQty: null,
    suggestedPurchaseUnits: null,
    suggestedVendorPartId: null,
    suggestedSupplierId: null,
    flags: [],
    runAsOf: new Date('2026-09-24T07:00:00Z'),
    isLatest: true,
    isOverdue: false,
    ...overrides,
  }
}
