// apps/web/src/components/calls/ui/recordings/recordings-mocks.ts

import type { Recording } from './recordings-types'

/** TODO: Remove once real recordings exist. */
export const MOCK_RECORDINGS: Recording[] = [
  {
    id: 'rec_001',
    organizationId: 'org_1',
    meetingId: null,
    calendarEventId: null,
    externalBotId: 'bot_abc',
    provider: 'recall',
    meetingPlatform: 'google_meet',
    status: 'completed',
    botName: 'Auxx Recorder',
    consentMessage: null,
    durationSeconds: 2340,
    startedAt: new Date('2026-04-14T14:00:00Z'),
    endedAt: new Date('2026-04-14T14:39:00Z'),
    failureReason: null,
    videoAssetId: null,
    audioAssetId: null,
    videoPreviewAssetId: null,
    videoStoryboardAssetId: null,
    createdById: 'user_1',
    createdAt: new Date('2026-04-14T13:58:00Z'),
    updatedAt: new Date('2026-04-14T14:39:00Z'),
    calendarEvent: { title: 'Q2 Product Roadmap Review' } as never,
  },
  {
    id: 'rec_002',
    organizationId: 'org_1',
    meetingId: null,
    calendarEventId: null,
    externalBotId: 'bot_def',
    provider: 'recall',
    meetingPlatform: 'zoom',
    status: 'recording',
    botName: 'Auxx Recorder',
    consentMessage: null,
    durationSeconds: null,
    startedAt: new Date('2026-04-15T10:00:00Z'),
    endedAt: null,
    failureReason: null,
    videoAssetId: null,
    audioAssetId: null,
    videoPreviewAssetId: null,
    videoStoryboardAssetId: null,
    createdById: 'user_1',
    createdAt: new Date('2026-04-15T09:58:00Z'),
    updatedAt: new Date('2026-04-15T10:00:00Z'),
    calendarEvent: { title: 'Weekly Customer Success Sync' } as never,
  },
  {
    id: 'rec_003',
    organizationId: 'org_1',
    meetingId: null,
    calendarEventId: null,
    externalBotId: 'bot_ghi',
    provider: 'recall',
    meetingPlatform: 'teams',
    status: 'completed',
    botName: 'Auxx Recorder',
    consentMessage: null,
    durationSeconds: 1800,
    startedAt: new Date('2026-04-13T16:00:00Z'),
    endedAt: new Date('2026-04-13T16:30:00Z'),
    failureReason: null,
    videoAssetId: 'asset_video_1',
    audioAssetId: null,
    videoPreviewAssetId: null,
    videoStoryboardAssetId: null,
    createdById: 'user_1',
    createdAt: new Date('2026-04-13T15:58:00Z'),
    updatedAt: new Date('2026-04-13T16:30:00Z'),
    calendarEvent: { title: 'Sprint Retrospective' } as never,
  },
  {
    id: 'rec_004',
    organizationId: 'org_1',
    meetingId: null,
    calendarEventId: null,
    externalBotId: 'bot_jkl',
    provider: 'recall',
    meetingPlatform: 'google_meet',
    status: 'failed',
    botName: 'Auxx Recorder',
    consentMessage: null,
    durationSeconds: null,
    startedAt: null,
    endedAt: null,
    failureReason: 'Bot was denied entry to the meeting',
    videoAssetId: null,
    audioAssetId: null,
    videoPreviewAssetId: null,
    videoStoryboardAssetId: null,
    createdById: 'user_1',
    createdAt: new Date('2026-04-12T11:00:00Z'),
    updatedAt: new Date('2026-04-12T11:02:00Z'),
    calendarEvent: { title: 'Investor Update Call' } as never,
  },
  {
    id: 'rec_005',
    organizationId: 'org_1',
    meetingId: null,
    calendarEventId: null,
    externalBotId: null,
    provider: 'recall',
    meetingPlatform: 'google_meet',
    status: 'created',
    botName: 'Auxx Recorder',
    consentMessage: null,
    durationSeconds: null,
    startedAt: null,
    endedAt: null,
    failureReason: null,
    videoAssetId: null,
    audioAssetId: null,
    videoPreviewAssetId: null,
    videoStoryboardAssetId: null,
    createdById: 'user_1',
    createdAt: new Date('2026-04-15T15:00:00Z'),
    updatedAt: new Date('2026-04-15T15:00:00Z'),
    calendarEvent: { title: 'Design Review — Calls Page' } as never,
  },
]
