// packages/lib/src/ai/providers/google/google-defaults.ts

import { FetchFrom, type ModelCapabilities, ModelType, type ProviderCapabilities } from '../types'

export const GOOGLE_CAPABILITIES: ProviderCapabilities = {
  id: 'google',
  displayName: 'Google',
  icon: 'google',
  color: '#4285F4',
  supportedModelTypes: [ModelType.LLM, ModelType.VISION, ModelType.TEXT_EMBEDDING],
  defaultModel: 'gemini-1.5-pro-latest',
  requiresApiKey: true,
  toolFormat: 'google',
  configurateMethods: ['predefined-model', 'customizable-model'],

  // NEW: Unified credential schema with scope-based filtering
  credentialSchema: [
    {
      variable: 'google_api_key',
      type: 'secret-input',
      label: 'API Key',
      placeholder: 'Enter your Google AI API Key',
      required: true,
      scope: 'both', // Available for both provider and model config
      priority: 'model-override', // Model-level key overrides provider key
      helpText: 'Your Google AI API key from Google AI Studio',
      validation: {
        pattern: '^AIza[0-9A-Za-z-_]{35}$',
        message: 'Google AI API key must start with AIza and be 39 characters long',
      },
    },
  ],

  rateLimits: {
    requestsPerMinute: 60,
    tokensPerMinute: 30000,
    cacheTtl: 300, // 5 minutes
  },
  description: "Google's advanced multimodal AI models with large context windows",
  documentationUrl: 'https://ai.google.dev/docs',
  setupInstructions:
    'Get your API key from Google AI Studio at https://aistudio.google.com/app/apikey',
}

export const GOOGLE_MODELS: Record<string, ModelCapabilities> = {
  'gemini-1.5-pro-latest': {
    provider: 'google',
    modelId: 'gemini-1.5-pro-latest',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Gemini 1.5 Pro',
    icon: 'google',
    color: '#4285F4',
    contextLength: 1000000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'multimodal'],
    supports: {
      streaming: true,
      structured: false,
      vision: true,
      toolCalling: false,
      systemMessages: false,
    },
    description: "Google's most capable multimodal model with huge context",
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls the randomness of the generated text.',
        default: 0.9,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'maxOutputTokens',
        type: 'int',
        label: 'Max Output Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 8192,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'gemini-1.5-flash-latest': {
    provider: 'google',
    modelId: 'gemini-1.5-flash-latest',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Gemini 1.5 Flash',
    icon: 'google',
    color: '#4285F4',
    contextLength: 1000000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'multimodal'],
    supports: {
      streaming: true,
      structured: false,
      vision: true,
      toolCalling: false,
      systemMessages: false,
    },
    description: 'Fast and efficient Gemini model with multimodal support',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls the randomness of the generated text.',
        default: 0.9,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
    ],
  },
  'gemini-2.0-flash': {
    provider: 'google',
    modelId: 'gemini-2.0-flash',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Gemini 2.0 Flash',
    icon: 'google',
    color: '#4285F4',
    contextLength: 1000000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'multimodal'],
    supports: {
      streaming: true,
      structured: false,
      vision: true,
      toolCalling: false,
      systemMessages: false,
    },
    description: 'Latest Gemini model with improved performance',
    parameterRules: [],
  },
  'gemini-2.0-flash-lite': {
    provider: 'google',
    modelId: 'gemini-2.0-flash-lite',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Gemini 2.0 Flash Lite',
    icon: 'google',
    color: '#4285F4',
    contextLength: 1000000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'multimodal'],
    supports: {
      streaming: true,
      structured: false,
      vision: true,
      toolCalling: false,
      systemMessages: false,
    },
    description: 'Lightweight version of Gemini 2.0 Flash',
    parameterRules: [],
  },

  // Embedding Models
  'text-embedding-004': {
    provider: 'google',
    modelId: 'text-embedding-004',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Text Embedding 004',
    icon: 'google',
    color: '#4285F4',
    contextLength: 2048,
    maxTokens: 2048,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00002, output: 0 },
    description: 'Latest Google text embedding model',
    parameterRules: [],
  },

  'textembedding-gecko@003': {
    provider: 'google',
    modelId: 'textembedding-gecko@003',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Gecko Embedding 003',
    icon: 'google',
    color: '#4285F4',
    contextLength: 3072,
    maxTokens: 3072,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.000025, output: 0 },
    description: 'Gecko text embedding model with extended context',
    parameterRules: [],
  },

  'gemini-embedding-001': {
    provider: 'google',
    modelId: 'gemini-embedding-001',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Gemini Embedding 001',
    icon: 'google',
    color: '#4285F4',
    contextLength: 2048,
    maxTokens: 2048,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00002, output: 0 },
    description: 'Gemini Embedding with configurable dimensions',
    parameterRules: [
      {
        name: 'dimensions',
        type: 'int',
        label: 'Dimensions',
        help: 'Number of dimensions for the embedding vector',
        default: 3072,
        required: false,
        template: 'dimensions',
        options: ['256', '512', '768', '1536', '3072'],
      },
    ],
  },
}
