// packages/sdk/src/util/generate-app-fields-types.ts

import fs from 'fs/promises'
import path from 'path'
import { APP_FIELDS_TYPES_FILENAME } from '../constants/app-fields-files.js'
import { HIDDEN_AUXX_DIRECTORY } from '../constants/hidden-auxx-directory.js'
import { complete, errored, type Result } from '../errors.js'

/**
 * Marker identifying field-type files that are safe for the CLI to overwrite.
 */
const GENERATED_MARKER = '// Auto-generated by auxx CLI. Do not edit.'

/**
 * Canonical content for the generated app-fields augmentation.
 *
 * It reads the app's `fields[]` straight off the entry's `app` export and feeds
 * it into the {@link AppOwnedFieldRegistry} seam (declared in
 * `@auxx/sdk/server`). TypeScript resolves the app-specific types from the app's
 * own source, so the emitted file is **identical for every app** — the literal
 * `key`/`type`/`options` survive on `typeof app['fields']` as long as the
 * `app` export is not annotated `: App`. The registry is keyed by each field's
 * `key` (`AppFieldValues<F>` in `root/fields/define-field.ts`).
 *
 * The `'../src/app'` specifier is extensionless on purpose: under the app
 * template's `moduleResolution: bundler` it resolves to `app.ts` or `app.tsx`
 * without hardcoding the extension. An app with no `fields` resolves `__AppFields`
 * to `[]`, which the seam treats as unregistered → permissive signatures.
 */
const APP_FIELDS_TYPES_FILE_CONTENT = `// .auxx/${APP_FIELDS_TYPES_FILENAME}
${GENERATED_MARKER}
import '@auxx/sdk/server'
import type { app } from '../src/app'

type __AppFields = typeof app extends { fields: infer F } ? F : []

declare module '@auxx/sdk/server' {
  export interface AppOwnedFieldRegistry {
    fields: __AppFields
  }
}
`

/**
 * Error type for failures while generating the app-fields augmentation.
 */
export type GenerateAppFieldsTypesError =
  | { code: 'FAILED_TO_READ_APP_FIELDS_TYPES_FILE'; path: string }
  | { code: 'FAILED_TO_WRITE_APP_FIELDS_TYPES_FILE'; path: string }
  | { code: 'FAILED_TO_CREATE_HIDDEN_DIRECTORY'; path: string }

/**
 * Status describing the generator outcome.
 */
export type GenerateAppFieldsTypesStatus = 'created' | 'updated' | 'unchanged' | 'skipped_unmanaged'

/**
 * Ensures `.auxx/app-fields.d.ts` exists and stays synchronized with the SDK.
 * Existing unmanaged (hand-edited) files are preserved and reported as
 * `skipped_unmanaged`. The file is emitted unconditionally — apps with no
 * `fields` degrade to permissive value-I/O signatures via the seam fallback.
 *
 * @param rootDirAbsolute Absolute path to the app root. Defaults to cwd.
 * @returns Result containing a generation status or a filesystem error.
 */
export async function generateAppFieldsTypes(
  rootDirAbsolute: string = path.resolve('.')
): Promise<Result<GenerateAppFieldsTypesStatus, GenerateAppFieldsTypesError>> {
  const hiddenDirAbsolute = path.join(rootDirAbsolute, HIDDEN_AUXX_DIRECTORY)
  const typesFilePath = path.join(hiddenDirAbsolute, APP_FIELDS_TYPES_FILENAME)

  try {
    await fs.mkdir(hiddenDirAbsolute, { recursive: true })
  } catch {
    return errored({ code: 'FAILED_TO_CREATE_HIDDEN_DIRECTORY', path: hiddenDirAbsolute })
  }

  let existingContent: string | null = null
  try {
    existingContent = await fs.readFile(typesFilePath, 'utf8')
  } catch (error) {
    if (typeof error === 'object' && error !== null && 'code' in error && error.code === 'ENOENT') {
      existingContent = null
    } else {
      return errored({ code: 'FAILED_TO_READ_APP_FIELDS_TYPES_FILE', path: typesFilePath })
    }
  }

  if (existingContent === null) {
    try {
      await fs.writeFile(typesFilePath, APP_FIELDS_TYPES_FILE_CONTENT, 'utf8')
      return complete('created')
    } catch {
      return errored({ code: 'FAILED_TO_WRITE_APP_FIELDS_TYPES_FILE', path: typesFilePath })
    }
  }

  if (existingContent === APP_FIELDS_TYPES_FILE_CONTENT) {
    return complete('unchanged')
  }

  if (!existingContent.includes(GENERATED_MARKER)) {
    return complete('skipped_unmanaged')
  }

  try {
    await fs.writeFile(typesFilePath, APP_FIELDS_TYPES_FILE_CONTENT, 'utf8')
    return complete('updated')
  } catch {
    return errored({ code: 'FAILED_TO_WRITE_APP_FIELDS_TYPES_FILE', path: typesFilePath })
  }
}
