// packages/credentials/src/config/config-registry.ts
// Single source of truth for all known config variables.
// Adding a new variable = adding an entry here.

import { ConfigVariableGroup, ConfigVariableType } from '@auxx/types/config'
import type { ConfigVariableDefinition } from './types'

/**
 * Registry of all known config variables.
 * Each entry defines metadata, type, default, and constraints.
 *
 * To add a new config variable:
 * 1. Add an entry to CONFIG_VARIABLES below
 * 2. That's it — the UI, API, and service layer pick it up automatically
 */
export const CONFIG_VARIABLES = {
  // ── SERVER ──────────────────────────────────────────────
  API_PORT: {
    key: 'API_PORT',
    description: 'The port the API server (apps/api) listens on',
    type: ConfigVariableType.NUMBER,
    group: ConfigVariableGroup.SERVER,
    defaultValue: 3007,
    isSensitive: false,
    isEnvOnly: true,
    min: 1,
    max: 65535,
  },
  NODE_ENV: {
    key: 'NODE_ENV',
    description: 'Node environment (development, production, test)',
    type: ConfigVariableType.ENUM,
    group: ConfigVariableGroup.SERVER,
    defaultValue: 'production',
    isSensitive: false,
    isEnvOnly: true,
    options: ['development', 'production', 'test'],
  },
  APP_URL: {
    key: 'APP_URL',
    description: 'Main application URL (used for OAuth callbacks, webhooks, etc.)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SERVER,
    isSensitive: false,
    isEnvOnly: true,
  },
  DEPLOYMENT_MODE: {
    key: 'DEPLOYMENT_MODE',
    description: 'Deployment mode: cloud (SaaS) or self-hosted',
    type: ConfigVariableType.ENUM,
    group: ConfigVariableGroup.SERVER,
    defaultValue: 'cloud',
    isSensitive: false,
    isEnvOnly: true,
    options: ['cloud', 'self-hosted'],
  },
  DOMAIN: {
    key: 'DOMAIN',
    description: 'Primary domain (self-hosted: subdomains app.DOMAIN, api.DOMAIN)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SERVER,
    isSensitive: false,
    isEnvOnly: true,
  },
  EXTRA_ALLOWED_ORIGINS: {
    key: 'EXTRA_ALLOWED_ORIGINS',
    description: 'Additional comma-separated origins for CORS (preview deploys, staging, etc.)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SERVER,
    isSensitive: false,
    isEnvOnly: true,
  },
  IS_CONFIG_VARIABLES_IN_DB_ENABLED: {
    key: 'IS_CONFIG_VARIABLES_IN_DB_ENABLED',
    description: 'Enable DB-based config overrides (must be env var)',
    type: ConfigVariableType.BOOLEAN,
    group: ConfigVariableGroup.SERVER,
    defaultValue: false,
    isSensitive: false,
    isEnvOnly: true,
  },
  DEMO_ENABLED: {
    key: 'DEMO_ENABLED',
    description: 'Enable the demo system (anonymous demo sessions, demo CTA on login page)',
    type: ConfigVariableType.BOOLEAN,
    group: ConfigVariableGroup.SERVER,
    defaultValue: false,
    isSensitive: false,
    isEnvOnly: true,
  },
  DEMO_EMAIL_DOMAIN: {
    key: 'DEMO_EMAIL_DOMAIN',
    description: 'Email domain used for demo user accounts (e.g. demo-abc123@<domain>)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SERVER,
    defaultValue: 'demo.auxx.ai',
    isSensitive: false,
    isEnvOnly: true,
  },

  // ── DATABASE ────────────────────────────────────────────
  DATABASE_URL: {
    key: 'DATABASE_URL',
    description: 'PostgreSQL connection string',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.DATABASE,
    isSensitive: true,
    isEnvOnly: true,
    infraManaged: true,
  },
  DATABASE_PASSWORD: {
    key: 'DATABASE_PASSWORD',
    description: 'PostgreSQL password (used by setup.sh to build DATABASE_URL)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.DATABASE,
    isSensitive: true,
    isEnvOnly: true,
    infraManaged: true,
  },

  // ── REDIS ───────────────────────────────────────────────
  REDIS_HOST: {
    key: 'REDIS_HOST',
    description: 'Redis server hostname',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.REDIS,
    defaultValue: 'localhost',
    isSensitive: false,
    isEnvOnly: true,
    infraManaged: true,
  },
  REDIS_PORT: {
    key: 'REDIS_PORT',
    description: 'Redis server port',
    type: ConfigVariableType.NUMBER,
    group: ConfigVariableGroup.REDIS,
    defaultValue: 6379,
    isSensitive: false,
    isEnvOnly: true,
    infraManaged: true,
    min: 1,
    max: 65535,
  },
  REDIS_PASSWORD: {
    key: 'REDIS_PASSWORD',
    description: 'Redis authentication password',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.REDIS,
    isSensitive: true,
    isEnvOnly: true,
    infraManaged: true,
  },

  // ── AUTH ─────────────────────────────────────────────────
  BETTER_AUTH_SECRET: {
    key: 'BETTER_AUTH_SECRET',
    description: 'Secret key for Better Auth session signing',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: true,
    isEnvOnly: true,
  },
  API_KEY_SALT: {
    key: 'API_KEY_SALT',
    description: 'Salt for hashing API keys',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: true,
    isEnvOnly: true,
  },
  LAMBDA_INVOKE_SECRET: {
    key: 'LAMBDA_INVOKE_SECRET',
    description: 'Shared secret for authenticating lambda invocations',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: true,
    isEnvOnly: true,
  },
  WORKFLOW_CREDENTIAL_ENCRYPTION_KEY: {
    key: 'WORKFLOW_CREDENTIAL_ENCRYPTION_KEY',
    description: 'Encryption key for workflow credential storage',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: true,
    isEnvOnly: true,
  },
  PUBLIC_WORKFLOW_JWT_SECRET: {
    key: 'PUBLIC_WORKFLOW_JWT_SECRET',
    description: 'JWT secret for public workflow passports',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: true,
    isEnvOnly: true,
  },
  SDK_CLIENT_SECRET: {
    key: 'SDK_CLIENT_SECRET',
    description: 'SDK client secret for OIDC/JWT signing',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: true,
    isEnvOnly: true,
  },
  LOGIN_TOKEN_PRIVATE_KEY: {
    key: 'LOGIN_TOKEN_PRIVATE_KEY',
    description:
      'Ed25519 private key (PEM) for signing cross-app login tokens. Only needed on the central auth app (apps/web).',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: true,
    isEnvOnly: true,
  },
  LOGIN_TOKEN_PUBLIC_KEY: {
    key: 'LOGIN_TOKEN_PUBLIC_KEY',
    description:
      'Ed25519 public key (PEM) for verifying cross-app login tokens. Deployed to all satellite apps.',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: false,
    isEnvOnly: true,
  },
  BUILD_SESSION_SECRET: {
    key: 'BUILD_SESSION_SECRET',
    description: 'HMAC secret for signing apps/build local session cookies.',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: true,
    isEnvOnly: true,
  },
  SUPER_ADMIN_EMAIL: {
    key: 'SUPER_ADMIN_EMAIL',
    description: 'Email of the super admin user',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: false,
    isEnvOnly: true,
  },
  AUTH_GITHUB_ID: {
    key: 'AUTH_GITHUB_ID',
    description: 'GitHub OAuth provider client ID (login)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: false,
    isEnvOnly: false,
  },
  AUTH_GITHUB_SECRET: {
    key: 'AUTH_GITHUB_SECRET',
    description: 'GitHub OAuth provider client secret (login)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: true,
    isEnvOnly: false,
  },
  AUTH_GOOGLE_ID: {
    key: 'AUTH_GOOGLE_ID',
    description: 'Google OAuth provider client ID (login)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: false,
    isEnvOnly: false,
  },
  AUTH_GOOGLE_SECRET: {
    key: 'AUTH_GOOGLE_SECRET',
    description: 'Google OAuth provider client secret (login)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: true,
    isEnvOnly: false,
  },
  GRAVATAR_API_KEY: {
    key: 'GRAVATAR_API_KEY',
    description: 'Gravatar API key for avatar fetching',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AUTH,
    isSensitive: true,
    isEnvOnly: false,
  },

  // ── GOOGLE WORKSPACE ──────────────────────────────────────
  GOOGLE_CLIENT_ID: {
    key: 'GOOGLE_CLIENT_ID',
    description: 'Google Workspace OAuth2 client ID (email integration)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.GOOGLE_WORKSPACE,
    isSensitive: false,
    isEnvOnly: false,
  },
  GOOGLE_CLIENT_SECRET: {
    key: 'GOOGLE_CLIENT_SECRET',
    description: 'Google Workspace OAuth2 client secret',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.GOOGLE_WORKSPACE,
    isSensitive: true,
    isEnvOnly: false,
  },
  GOOGLE_PROJECT_ID: {
    key: 'GOOGLE_PROJECT_ID',
    description: 'Google Cloud project ID',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.GOOGLE_WORKSPACE,
    isSensitive: false,
    isEnvOnly: false,
  },
  GOOGLE_PUBSUB_TOPIC: {
    key: 'GOOGLE_PUBSUB_TOPIC',
    description: 'Google PubSub topic for email notifications',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.GOOGLE_WORKSPACE,
    defaultValue: 'email-notifications',
    isSensitive: false,
    isEnvOnly: false,
  },
  GOOGLE_PUBSUB_SUBSCRIPTION: {
    key: 'GOOGLE_PUBSUB_SUBSCRIPTION',
    description: 'Google PubSub subscription name',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.GOOGLE_WORKSPACE,
    defaultValue: 'email-notifications-sub',
    isSensitive: false,
    isEnvOnly: false,
  },
  GOOGLE_PUBSUB_VERIFICATION_TOKEN: {
    key: 'GOOGLE_PUBSUB_VERIFICATION_TOKEN',
    description: 'Token for verifying PubSub push messages',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.GOOGLE_WORKSPACE,
    isSensitive: true,
    isEnvOnly: false,
  },
  GOOGLE_PUBSUB_SERVICE_ACCOUNT_EMAIL: {
    key: 'GOOGLE_PUBSUB_SERVICE_ACCOUNT_EMAIL',
    description: 'Service account email used as JWT audience for PubSub push verification',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.GOOGLE_WORKSPACE,
    isSensitive: false,
    isEnvOnly: false,
  },
  GOOGLE_CLIENT_EMAIL: {
    key: 'GOOGLE_CLIENT_EMAIL',
    description: 'Service account email for Google APIs',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.GOOGLE_WORKSPACE,
    isSensitive: false,
    isEnvOnly: false,
  },
  GOOGLE_PRIVATE_KEY: {
    key: 'GOOGLE_PRIVATE_KEY',
    description: 'Service account private key for Google APIs',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.GOOGLE_WORKSPACE,
    isSensitive: true,
    isEnvOnly: false,
  },
  GOOGLE_PLATFORM_CREDENTIALS_APPROVED: {
    key: 'GOOGLE_PLATFORM_CREDENTIALS_APPROVED',
    description: 'Whether platform Google OAuth credentials are approved for Gmail scopes',
    type: ConfigVariableType.BOOLEAN,
    group: ConfigVariableGroup.GOOGLE_WORKSPACE,
    isSensitive: false,
    isEnvOnly: false,
    defaultValue: false,
  },

  // ── OUTLOOK ───────────────────────────────────────────────
  OUTLOOK_CLIENT_ID: {
    key: 'OUTLOOK_CLIENT_ID',
    description: 'Microsoft Outlook OAuth client ID',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.OUTLOOK,
    isSensitive: false,
    isEnvOnly: false,
  },
  OUTLOOK_CLIENT_SECRET: {
    key: 'OUTLOOK_CLIENT_SECRET',
    description: 'Microsoft Outlook OAuth client secret',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.OUTLOOK,
    isSensitive: true,
    isEnvOnly: false,
  },
  OUTLOOK_WEBHOOK_SECRET: {
    key: 'OUTLOOK_WEBHOOK_SECRET',
    description: 'Outlook webhook signing secret',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.OUTLOOK,
    isSensitive: true,
    isEnvOnly: false,
  },
  OUTLOOK_PLATFORM_CREDENTIALS_APPROVED: {
    key: 'OUTLOOK_PLATFORM_CREDENTIALS_APPROVED',
    description: 'Whether platform Outlook OAuth credentials are approved for Mail scopes',
    type: ConfigVariableType.BOOLEAN,
    group: ConfigVariableGroup.OUTLOOK,
    isSensitive: false,
    isEnvOnly: false,
    defaultValue: false,
  },

  // ── DROPBOX ──────────────────────────────────────────────
  DROPBOX_CLIENT_ID: {
    key: 'DROPBOX_CLIENT_ID',
    description: 'Dropbox OAuth2 client ID',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.DROPBOX,
    isSensitive: false,
    isEnvOnly: false,
  },
  DROPBOX_CLIENT_SECRET: {
    key: 'DROPBOX_CLIENT_SECRET',
    description: 'Dropbox OAuth2 client secret',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.DROPBOX,
    isSensitive: true,
    isEnvOnly: false,
  },

  // ── FACEBOOK ──────────────────────────────────────────────
  FACEBOOK_APP_ID: {
    key: 'FACEBOOK_APP_ID',
    description: 'Facebook App ID',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.FACEBOOK,
    isSensitive: false,
    isEnvOnly: false,
  },
  FACEBOOK_APP_SECRET: {
    key: 'FACEBOOK_APP_SECRET',
    description: 'Facebook App secret',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.FACEBOOK,
    isSensitive: true,
    isEnvOnly: false,
  },
  FACEBOOK_GRAPH_API_VERSION: {
    key: 'FACEBOOK_GRAPH_API_VERSION',
    description: 'Facebook Graph API version',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.FACEBOOK,
    defaultValue: 'v19.0',
    isSensitive: false,
    isEnvOnly: false,
  },
  FACEBOOK_WEBHOOK_VERIFY_TOKEN: {
    key: 'FACEBOOK_WEBHOOK_VERIFY_TOKEN',
    description: 'Facebook webhook verification token',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.FACEBOOK,
    isSensitive: true,
    isEnvOnly: false,
  },

  // ── EMAIL ────────────────────────────────────────────────
  EMAIL_PROVIDER: {
    key: 'EMAIL_PROVIDER',
    description: 'Email sending provider',
    type: ConfigVariableType.ENUM,
    group: ConfigVariableGroup.EMAIL,
    defaultValue: 'smtp',
    isSensitive: false,
    isEnvOnly: false,
    options: ['mailgun', 'ses', 'smtp', 'sendmail'],
  },
  MAILGUN_API_KEY: {
    key: 'MAILGUN_API_KEY',
    description: 'Mailgun API key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    isSensitive: true,
    isEnvOnly: false,
  },
  MAILGUN_DOMAIN: {
    key: 'MAILGUN_DOMAIN',
    description: 'Mailgun sending domain',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    isSensitive: false,
    isEnvOnly: false,
  },
  MAILGUN_REGION: {
    key: 'MAILGUN_REGION',
    description: 'Mailgun region (us or eu)',
    type: ConfigVariableType.ENUM,
    group: ConfigVariableGroup.EMAIL,
    defaultValue: 'us',
    isSensitive: false,
    isEnvOnly: false,
    options: ['us', 'eu'],
  },
  AWS_SES_ACCESS_KEY_ID: {
    key: 'AWS_SES_ACCESS_KEY_ID',
    description: 'AWS SES access key ID',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    isSensitive: true,
    isEnvOnly: false,
  },
  AWS_SES_SECRET_ACCESS_KEY: {
    key: 'AWS_SES_SECRET_ACCESS_KEY',
    description: 'AWS SES secret access key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    isSensitive: true,
    isEnvOnly: false,
  },
  SMTP_HOST: {
    key: 'SMTP_HOST',
    description: 'SMTP server hostname',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    isSensitive: false,
    isEnvOnly: false,
  },
  SMTP_PORT: {
    key: 'SMTP_PORT',
    description: 'SMTP server port',
    type: ConfigVariableType.NUMBER,
    group: ConfigVariableGroup.EMAIL,
    defaultValue: 587,
    isSensitive: false,
    isEnvOnly: false,
    min: 1,
    max: 65535,
  },
  SMTP_SECURE: {
    key: 'SMTP_SECURE',
    description: 'Use TLS for SMTP connection',
    type: ConfigVariableType.BOOLEAN,
    group: ConfigVariableGroup.EMAIL,
    defaultValue: false,
    isSensitive: false,
    isEnvOnly: false,
  },
  SMTP_USER: {
    key: 'SMTP_USER',
    description: 'SMTP authentication username',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    isSensitive: false,
    isEnvOnly: false,
  },
  SMTP_PASS: {
    key: 'SMTP_PASS',
    description: 'SMTP authentication password',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    isSensitive: true,
    isEnvOnly: false,
  },
  SYSTEM_FROM_EMAIL: {
    key: 'SYSTEM_FROM_EMAIL',
    description: 'Default "from" email for system emails',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    defaultValue: 'noreply@m.auxx.ai',
    isSensitive: false,
    isEnvOnly: false,
  },
  SYSTEM_FROM_NAME: {
    key: 'SYSTEM_FROM_NAME',
    description: 'Default "from" name for system emails',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    defaultValue: 'System',
    isSensitive: false,
    isEnvOnly: false,
  },
  SUPPORT_EMAIL: {
    key: 'SUPPORT_EMAIL',
    description: 'Support team email address',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    defaultValue: 'support@m.auxx.ai',
    isSensitive: false,
    isEnvOnly: false,
  },
  SUPPORT_NAME: {
    key: 'SUPPORT_NAME',
    description: 'Support team display name',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    defaultValue: 'Support Team',
    isSensitive: false,
    isEnvOnly: false,
  },
  EMAIL_REPLY_TO: {
    key: 'EMAIL_REPLY_TO',
    description: 'Reply-to address for system emails',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.EMAIL,
    isSensitive: false,
    isEnvOnly: false,
  },

  // ── STORAGE ──────────────────────────────────────────────
  FILE_STORAGE_TYPE: {
    key: 'FILE_STORAGE_TYPE',
    description: 'File storage backend (local or s3)',
    type: ConfigVariableType.ENUM,
    group: ConfigVariableGroup.STORAGE,
    defaultValue: 's3',
    isSensitive: false,
    isEnvOnly: false,
    options: ['local', 's3'],
  },
  LOCAL_STORAGE_PUBLIC_PATH: {
    key: 'LOCAL_STORAGE_PUBLIC_PATH',
    description: 'Local filesystem path for public file storage',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.STORAGE,
    isSensitive: false,
    isEnvOnly: true,
  },
  S3_ENDPOINT: {
    key: 'S3_ENDPOINT',
    description: 'S3 endpoint URL (for R2, DigitalOcean Spaces, etc. Leave empty for AWS)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.STORAGE,
    isSensitive: false,
    isEnvOnly: false,
  },
  S3_REGION: {
    key: 'S3_REGION',
    description: 'S3 bucket region',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.STORAGE,
    defaultValue: 'us-east-1',
    isSensitive: false,
    isEnvOnly: false,
  },
  S3_PUBLIC_BUCKET: {
    key: 'S3_PUBLIC_BUCKET',
    description: 'S3 bucket for public assets (avatars, logos — CDN cached)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.STORAGE,
    defaultValue: 'auxx-public',
    isSensitive: false,
    isEnvOnly: false,
  },
  S3_PRIVATE_BUCKET: {
    key: 'S3_PRIVATE_BUCKET',
    description: 'S3 bucket for private files (attachments — presigned URLs)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.STORAGE,
    defaultValue: 'auxx-private',
    isSensitive: false,
    isEnvOnly: false,
  },
  CDN_URL: {
    key: 'CDN_URL',
    description: 'CDN URL for serving public assets',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.STORAGE,
    isSensitive: false,
    isEnvOnly: false,
  },
  S3_ACCESS_KEY_ID: {
    key: 'S3_ACCESS_KEY_ID',
    description: 'S3 access key ID',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.STORAGE,
    isSensitive: true,
    isEnvOnly: false,
  },
  S3_SECRET_ACCESS_KEY: {
    key: 'S3_SECRET_ACCESS_KEY',
    description: 'S3 secret access key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.STORAGE,
    isSensitive: true,
    isEnvOnly: false,
  },
  AWS_REGION: {
    key: 'AWS_REGION',
    description: 'AWS region (used by SST/infra stacks)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.STORAGE,
    defaultValue: 'us-west-1',
    isSensitive: false,
    isEnvOnly: true,
  },
  AWS_ACCESS_KEY_ID: {
    key: 'AWS_ACCESS_KEY_ID',
    description: 'Generic AWS access key (fallback for SES/S3)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.STORAGE,
    isSensitive: true,
    isEnvOnly: true,
  },
  AWS_SECRET_ACCESS_KEY: {
    key: 'AWS_SECRET_ACCESS_KEY',
    description: 'Generic AWS secret key (fallback for SES/S3)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.STORAGE,
    isSensitive: true,
    isEnvOnly: true,
  },

  // ── AI ───────────────────────────────────────────────────
  OPENAI_API_KEY: {
    key: 'OPENAI_API_KEY',
    description: 'OpenAI API key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AI,
    isSensitive: true,
    isEnvOnly: false,
  },
  OPENAI_MODEL: {
    key: 'OPENAI_MODEL',
    description: 'Default OpenAI model',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AI,
    defaultValue: 'gpt-4o',
    isSensitive: false,
    isEnvOnly: false,
  },
  OPENAI_ORGANIZATION: {
    key: 'OPENAI_ORGANIZATION',
    description: 'OpenAI organization ID',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AI,
    isSensitive: false,
    isEnvOnly: false,
  },
  ANTHROPIC_API_KEY: {
    key: 'ANTHROPIC_API_KEY',
    description: 'Anthropic API key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AI,
    isSensitive: true,
    isEnvOnly: false,
  },
  ANTHROPIC_MODEL: {
    key: 'ANTHROPIC_MODEL',
    description: 'Default Anthropic model',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AI,
    isSensitive: false,
    isEnvOnly: false,
  },
  BEDROCK_ACCESS_KEY: {
    key: 'BEDROCK_ACCESS_KEY',
    description: 'AWS Bedrock access key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AI,
    isSensitive: true,
    isEnvOnly: false,
  },
  BEDROCK_SECRET_KEY: {
    key: 'BEDROCK_SECRET_KEY',
    description: 'AWS Bedrock secret key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AI,
    isSensitive: true,
    isEnvOnly: false,
  },
  GOOGLE_API_KEY: {
    key: 'GOOGLE_API_KEY',
    description: 'Google AI (Gemini) API key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AI,
    isSensitive: true,
    isEnvOnly: false,
  },
  GROQ_API_KEY: {
    key: 'GROQ_API_KEY',
    description: 'Groq API key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.AI,
    isSensitive: true,
    isEnvOnly: false,
  },
  USE_BACKUP_MODEL: {
    key: 'USE_BACKUP_MODEL',
    description: 'Enable fallback to backup AI model',
    type: ConfigVariableType.BOOLEAN,
    group: ConfigVariableGroup.AI,
    defaultValue: false,
    isSensitive: false,
    isEnvOnly: false,
  },

  // ── SHOPIFY ──────────────────────────────────────────────
  SHOPIFY_API_KEY: {
    key: 'SHOPIFY_API_KEY',
    description: 'Shopify API key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SHOPIFY,
    isSensitive: true,
    isEnvOnly: false,
  },
  SHOPIFY_API_SECRET: {
    key: 'SHOPIFY_API_SECRET',
    description: 'Shopify API secret',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SHOPIFY,
    isSensitive: true,
    isEnvOnly: false,
  },

  // ── BILLING ──────────────────────────────────────────────
  STRIPE_SECRET_KEY: {
    key: 'STRIPE_SECRET_KEY',
    description: 'Stripe secret API key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.BILLING,
    isSensitive: true,
    isEnvOnly: false,
  },
  STRIPE_PUBLISHABLE_KEY: {
    key: 'STRIPE_PUBLISHABLE_KEY',
    description: 'Stripe publishable key (public, safe for client)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.BILLING,
    isSensitive: false,
    isEnvOnly: false,
  },
  STRIPE_WEBHOOK_SECRET: {
    key: 'STRIPE_WEBHOOK_SECRET',
    description: 'Stripe webhook signing secret',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.BILLING,
    isSensitive: true,
    isEnvOnly: false,
  },
  ENABLE_AUTO_TRIAL: {
    key: 'ENABLE_AUTO_TRIAL',
    description: 'Enable automatic trial subscription creation',
    type: ConfigVariableType.BOOLEAN,
    group: ConfigVariableGroup.BILLING,
    defaultValue: true,
    isSensitive: false,
    isEnvOnly: false,
  },
  TRIAL_PLAN_NAME: {
    key: 'TRIAL_PLAN_NAME',
    description: 'Plan name for trial subscriptions (must match DB)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.BILLING,
    defaultValue: 'Growth',
    isSensitive: false,
    isEnvOnly: false,
  },
  TRIAL_DAYS: {
    key: 'TRIAL_DAYS',
    description: 'Number of days for trial period',
    type: ConfigVariableType.NUMBER,
    group: ConfigVariableGroup.BILLING,
    defaultValue: 14,
    isSensitive: false,
    isEnvOnly: false,
    min: 1,
    max: 365,
  },

  // ── REALTIME (Pusher) ─────────────────────────────────────
  PUSHER_APP_ID: {
    key: 'PUSHER_APP_ID',
    description: 'Pusher app ID (server-side)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.REALTIME,
    isSensitive: false,
    isEnvOnly: false,
  },
  PUSHER_KEY: {
    key: 'PUSHER_KEY',
    description: 'Pusher app key (server-side)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.REALTIME,
    isSensitive: false,
    isEnvOnly: false,
  },
  PUSHER_SECRET: {
    key: 'PUSHER_SECRET',
    description: 'Pusher app secret (server-side)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.REALTIME,
    isSensitive: true,
    isEnvOnly: false,
  },
  PUSHER_CLUSTER: {
    key: 'PUSHER_CLUSTER',
    description: 'Pusher cluster region (server-side)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.REALTIME,
    defaultValue: 'us3',
    isSensitive: false,
    isEnvOnly: false,
  },
  SKIP_CHAT_SESSION_VERIFICATION: {
    key: 'SKIP_CHAT_SESSION_VERIFICATION',
    description: 'Skip chat session verification (dev only)',
    type: ConfigVariableType.BOOLEAN,
    group: ConfigVariableGroup.REALTIME,
    defaultValue: false,
    isSensitive: false,
    isEnvOnly: true,
  },

  // ── ANALYTICS ────────────────────────────────────────────
  POSTHOG_KEY: {
    key: 'POSTHOG_KEY',
    description: 'PostHog analytics project API key',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.ANALYTICS,
    isSensitive: false,
    isEnvOnly: false,
  },
  POSTHOG_HOST: {
    key: 'POSTHOG_HOST',
    description: 'PostHog analytics host URL',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.ANALYTICS,
    defaultValue: 'https://app.posthog.com',
    isSensitive: false,
    isEnvOnly: false,
  },

  // ── CACHE ─────────────────────────────────────────────────
  CACHE_PROVIDER: {
    key: 'CACHE_PROVIDER',
    description: 'Cache provider (hosted, upstash, aws)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.CACHE,
    isSensitive: false,
    isEnvOnly: true,
    defaultValue: 'hosted',
  },
  KV_URL: {
    key: 'KV_URL',
    description: 'Vercel KV connection URL',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.CACHE,
    isSensitive: true,
    isEnvOnly: true,
  },
  KV_REST_API_URL: {
    key: 'KV_REST_API_URL',
    description: 'Vercel KV REST API URL',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.CACHE,
    isSensitive: false,
    isEnvOnly: true,
  },
  KV_REST_API_TOKEN: {
    key: 'KV_REST_API_TOKEN',
    description: 'Vercel KV REST API token',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.CACHE,
    isSensitive: true,
    isEnvOnly: true,
  },
  ELASTICACHE_URL: {
    key: 'ELASTICACHE_URL',
    description: 'AWS ElastiCache connection URL',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.CACHE,
    isSensitive: true,
    isEnvOnly: true,
  },
  ELASTICACHE_TLS: {
    key: 'ELASTICACHE_TLS',
    description: 'Enable TLS for ElastiCache connection',
    type: ConfigVariableType.BOOLEAN,
    group: ConfigVariableGroup.CACHE,
    isSensitive: false,
    isEnvOnly: true,
  },

  // ── WORKER ───────────────────────────────────────────────
  WORKER_PORT: {
    key: 'WORKER_PORT',
    description: 'Port for the worker admin UI',
    type: ConfigVariableType.NUMBER,
    group: ConfigVariableGroup.WORKER,
    defaultValue: 3005,
    isSensitive: false,
    isEnvOnly: true,
    min: 1,
    max: 65535,
  },
  // ── URL vars (deploy-time constants, resolved by @auxx/config) ──
  API_URL: {
    key: 'API_URL',
    description: 'API service URL',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SERVER,
    isSensitive: false,
    isEnvOnly: true,
  },
  HOMEPAGE_URL: {
    key: 'HOMEPAGE_URL',
    description: 'Homepage/marketing site URL',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SERVER,
    isSensitive: false,
    isEnvOnly: true,
  },
  DEV_PORTAL_URL: {
    key: 'DEV_PORTAL_URL',
    description: 'Developer portal URL',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SERVER,
    isSensitive: false,
    isEnvOnly: true,
  },
  DOCS_URL: {
    key: 'DOCS_URL',
    description: 'Documentation site URL',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SERVER,
    isSensitive: false,
    isEnvOnly: true,
  },
  KB_URL: {
    key: 'KB_URL',
    description: 'Knowledge base URL',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SERVER,
    isSensitive: false,
    isEnvOnly: true,
  },
  LAMBDA_URL: {
    key: 'LAMBDA_URL',
    description: 'Lambda executor URL',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SERVER,
    isSensitive: false,
    isEnvOnly: true,
  },
  LAMBDA_INTERNAL_URL: {
    key: 'LAMBDA_INTERNAL_URL',
    description: 'Internal Lambda executor URL for server-to-server calls',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.SERVER,
    isSensitive: false,
    isEnvOnly: true,
  },

  // ── FRONTEND (Group B — build info, truly build-time) ─────
  GIT_SHA: {
    key: 'GIT_SHA',
    description: 'Git commit SHA (set at build time)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.FRONTEND,
    isSensitive: false,
    isEnvOnly: true,
  },
  BUILD_TIME: {
    key: 'BUILD_TIME',
    description: 'Build timestamp (set at build time)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.FRONTEND,
    isSensitive: false,
    isEnvOnly: true,
  },
  APP_VERSION: {
    key: 'APP_VERSION',
    description: 'Application version (set at build time)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.FRONTEND,
    isSensitive: false,
    isEnvOnly: true,
  },

  // ── CAPTCHA ──────────────────────────────────────────────
  TURNSTILE_SECRET_KEY: {
    key: 'TURNSTILE_SECRET_KEY',
    description: 'Cloudflare Turnstile secret key for captcha verification',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.CAPTCHA,
    isSensitive: true,
    isEnvOnly: false,
  },
  TURNSTILE_SITE_KEY: {
    key: 'TURNSTILE_SITE_KEY',
    description: 'Cloudflare Turnstile site key (public, sent to client for widget rendering)',
    type: ConfigVariableType.STRING,
    group: ConfigVariableGroup.CAPTCHA,
    isSensitive: false,
    isEnvOnly: false,
  },
} satisfies Record<string, ConfigVariableDefinition>

/** Union of all known config variable keys. */
export type ConfigKey = keyof typeof CONFIG_VARIABLES

/**
 * Group metadata for UI display
 */
export const CONFIG_GROUP_META: Record<
  string,
  { label: string; description: string; iconId: string }
> = {
  SERVER: { label: 'Server', description: 'Core server and deployment settings', iconId: 'server' },
  DATABASE: {
    label: 'Database',
    description: 'PostgreSQL connection settings',
    iconId: 'database',
  },
  REDIS: { label: 'Redis', description: 'Redis connection settings', iconId: 'database' },
  AUTH: {
    label: 'Authentication',
    description: 'Auth secrets, OAuth login providers, and security keys',
    iconId: 'shield',
  },
  GOOGLE_WORKSPACE: {
    label: 'Google Workspace',
    description: 'Gmail integration, PubSub, and service account settings',
    iconId: 'mail',
  },
  OUTLOOK: { label: 'Outlook', description: 'Microsoft Outlook email integration', iconId: 'mail' },
  FACEBOOK: { label: 'Facebook', description: 'Facebook/Instagram integration', iconId: 'globe' },
  DROPBOX: { label: 'Dropbox', description: 'Dropbox OAuth2 integration', iconId: 'cloud' },
  EMAIL: {
    label: 'Email Sending',
    description: 'Outbound email provider and system email settings',
    iconId: 'send',
  },
  STORAGE: {
    label: 'Storage',
    description: 'File storage (S3 / local) and AWS settings',
    iconId: 'cloud',
  },
  AI: {
    label: 'AI Providers',
    description: 'AI model API keys, model selection, and fallbacks',
    iconId: 'brain',
  },
  SHOPIFY: {
    label: 'Shopify',
    description: 'Shopify integration settings',
    iconId: 'shopping-cart',
  },
  BILLING: {
    label: 'Billing',
    description: 'Stripe payments and trial configuration',
    iconId: 'credit-card',
  },
  REALTIME: {
    label: 'Realtime',
    description: 'Pusher real-time notifications (server-side)',
    iconId: 'zap',
  },
  ANALYTICS: {
    label: 'Analytics',
    description: 'PostHog analytics and tracking configuration',
    iconId: 'bar-chart',
  },
  CACHE: {
    label: 'Cache',
    description: 'Cache provider settings (Redis, KV, ElastiCache)',
    iconId: 'layers',
  },
  WORKER: {
    label: 'Worker',
    description: 'Background job processing and Bull admin',
    iconId: 'activity',
  },
  FRONTEND: {
    label: 'Frontend',
    description: 'URL constants and build info (NEXT_PUBLIC_ vars)',
    iconId: 'layout',
  },
  CAPTCHA: {
    label: 'Captcha',
    description: 'Cloudflare Turnstile bot protection for auth endpoints',
    iconId: 'shield',
  },
}

/**
 * Get all variable definitions as an array
 */
export function getAllConfigDefinitions(): ConfigVariableDefinition[] {
  return Object.values(CONFIG_VARIABLES)
}

/**
 * Get a single variable definition by key
 */
export function getConfigDefinition(key: string): ConfigVariableDefinition | undefined {
  return (CONFIG_VARIABLES as Record<string, ConfigVariableDefinition>)[key]
}

/**
 * Get all variable definitions for a specific group
 */
export function getConfigDefinitionsByGroup(group: string): ConfigVariableDefinition[] {
  return Object.values(CONFIG_VARIABLES).filter((v) => v.group === group)
}
