// packages/lib/src/ai/providers/anthropic/anthropic-defaults.ts

import { FetchFrom, type ModelCapabilities, ModelType, type ProviderCapabilities } from '../types'

export const ANTHROPIC_CAPABILITIES: ProviderCapabilities = {
  id: 'anthropic',
  displayName: 'Anthropic',
  icon: 'anthropic',
  color: '#D97706',
  supportedModelTypes: [ModelType.LLM, ModelType.TEXT_EMBEDDING],
  defaultModel: 'claude-sonnet-4-6',
  requiresApiKey: true,
  toolFormat: 'anthropic',
  configurateMethods: ['predefined-model', 'customizable-model'],

  // NEW: Unified credential schema with scope-based filtering
  credentialSchema: [
    {
      variable: 'anthropic_api_key',
      type: 'secret-input',
      label: 'API Key',
      placeholder: 'Enter your Anthropic API Key',
      required: true,
      scope: 'both', // Available for both provider and model config
      priority: 'model-override', // Model-level key overrides provider key
      helpText: 'Your Anthropic API key from the Anthropic console',
      validation: {
        pattern: '^sk-ant-[a-zA-Z0-9-_]{20,}$',
        message: 'Anthropic API key must start with sk-ant- and be at least 24 characters',
      },
    },
  ],

  rateLimits: {
    requestsPerMinute: 100,
    tokensPerMinute: 40000,
    cacheTtl: 300, // 5 minutes
  },
  description: 'Advanced AI assistant by Anthropic with strong reasoning capabilities',
  documentationUrl: 'https://docs.anthropic.com/claude/reference',
  setupInstructions:
    'Get your API key from the Anthropic console at https://console.anthropic.com/',
}

/**
 * Fable 5 / Opus 4.8 / Opus 4.7 remove sampling parameters — sending
 * `temperature`, `top_p`, or `top_k` returns a 400 (`invalid_request_error`).
 * Sampling is steered by prompting + effort on these models. The Anthropic
 * client reads `unsupportedParams` and strips these at the wire boundary.
 */
const CLAUDE_NO_SAMPLING_PARAMS: ModelCapabilities['parameterRestrictions'] = {
  isReasoningModel: false, // thinking is off-by-default; we don't send a thinking block
  supportedParams: ['max_tokens'],
  unsupportedParams: ['temperature', 'top_p', 'top_k'],
}

/** Max-tokens-only rules for sampling-restricted Claude models (hides temp/top_p in the UI). */
const CLAUDE_MAXTOKENS_ONLY_RULES = [
  {
    name: 'max_tokens',
    type: 'int' as const,
    label: 'Max Tokens',
    help: 'Maximum number of tokens to generate in the response.',
    default: 16384,
    min: 1,
    max: 128000,
    precision: 0,
    required: false,
    template: 'max_tokens',
  },
]

export const ANTHROPIC_MODELS: Record<string, ModelCapabilities> = {
  'claude-fable-5': {
    provider: 'anthropic',
    modelId: 'claude-fable-5',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude Fable 5',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 128000,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.01, output: 0.05, cachedInput: 0.001, cacheWrite: 0.0125 },
    description:
      'Claude Fable 5 — most powerful Anthropic model, tier above Opus. Sampling parameters (temperature, top_p) are fixed by the model.',
    parameterRestrictions: CLAUDE_NO_SAMPLING_PARAMS,
    parameterRules: CLAUDE_MAXTOKENS_ONLY_RULES,
  },
  'claude-opus-4-8': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-8',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude Opus 4.8',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 128000,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.005, output: 0.025, cachedInput: 0.0005, cacheWrite: 0.00625 },
    description:
      'Claude Opus 4.8 — most capable Opus: autonomous long-horizon agentic work. Sampling parameters (temperature, top_p) are fixed by the model.',
    parameterRestrictions: CLAUDE_NO_SAMPLING_PARAMS,
    parameterRules: CLAUDE_MAXTOKENS_ONLY_RULES,
  },
  'claude-opus-4-7': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-7',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude Opus 4.7',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 128000,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.005, output: 0.025, cachedInput: 0.0005, cacheWrite: 0.00625 },
    description:
      'Claude Opus 4.7 — previous-generation Opus; strong long-horizon agentic and vision work. Sampling parameters (temperature, top_p) are fixed by the model.',
    parameterRestrictions: CLAUDE_NO_SAMPLING_PARAMS,
    parameterRules: CLAUDE_MAXTOKENS_ONLY_RULES,
  },
  'claude-opus-4-6': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-6',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude Opus 4.6',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 16384,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.005, output: 0.025, cachedInput: 0.0005, cacheWrite: 0.00625 },
    description: 'Claude Opus 4.6 - most powerful model with advanced reasoning',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 16384,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-sonnet-4-6': {
    provider: 'anthropic',
    modelId: 'claude-sonnet-4-6',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude Sonnet 4.6',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 64000,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.003, output: 0.015, cachedInput: 0.0003, cacheWrite: 0.00375 },
    description: 'Claude Sonnet 4.6 - latest generation with enhanced capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 32000,
        min: 1,
        max: 64000,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-sonnet-4-5-20250929': {
    provider: 'anthropic',
    modelId: 'claude-sonnet-4-5-20250929',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude Sonnet 4.5',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 16384,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.003, output: 0.015, cachedInput: 0.0003, cacheWrite: 0.00375 },
    description: 'Claude Sonnet 4.5 - balanced performance and capability',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 16384,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-haiku-4-5-20251001': {
    provider: 'anthropic',
    modelId: 'claude-haiku-4-5-20251001',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude Haiku 4.5',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.001, output: 0.005, cachedInput: 0.0001, cacheWrite: 0.00125 },
    description: 'Claude Haiku 4.5 - fastest model with strong capability',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 8192,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-sonnet-4-20250514': {
    provider: 'anthropic',
    modelId: 'claude-sonnet-4-20250514',
    deprecated: true,
    replacement: 'claude-sonnet-4-6',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude Sonnet 4',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.003, output: 0.015, cachedInput: 0.0003, cacheWrite: 0.00375 },
    description: 'Claude Sonnet 4 - latest generation with enhanced capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 8192,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-opus-4-20250514': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-20250514',
    deprecated: true,
    replacement: 'claude-opus-4-6',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude Opus 4',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.015, output: 0.075, cachedInput: 0.0015, cacheWrite: 0.01875 },
    description: 'Claude Opus 4 - most powerful model with advanced reasoning',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 8192,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-3-7-sonnet-20250219': {
    provider: 'anthropic',
    modelId: 'claude-3-7-sonnet-20250219',
    retired: true,
    replacement: 'claude-sonnet-4-6',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude 3.7 Sonnet',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: false,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.003, output: 0.015, cachedInput: 0.0003, cacheWrite: 0.00375 },
    description: 'Latest Claude model with enhanced reasoning capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 8192,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'claude-3-5-sonnet-20241022': {
    provider: 'anthropic',
    modelId: 'claude-3-5-sonnet-20241022',
    retired: true,
    replacement: 'claude-sonnet-4-6',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude 3.5 Sonnet (Oct 2024)',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.003, output: 0.015, cachedInput: 0.0003, cacheWrite: 0.00375 },
    description: 'Claude 3.5 Sonnet with computer use and vision capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 8192,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-3-5-haiku-20241022': {
    provider: 'anthropic',
    modelId: 'claude-3-5-haiku-20241022',
    retired: true,
    replacement: 'claude-haiku-4-5-20251001',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude 3.5 Haiku',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: true,
    },
    costPer1kTokens: { input: 0.0008, output: 0.004, cachedInput: 0.00008, cacheWrite: 0.001 },
    description: 'Claude 3.5 Haiku - enhanced speed and capability',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 8192,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },

  // Voyage AI Embedding Models (via Anthropic provider)
  'voyage-2': {
    provider: 'anthropic',
    modelId: 'voyage-2',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage 2',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 4000,
    maxTokens: 4000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0001, output: 0 },
    description: 'Voyage AI general-purpose embedding model',
    parameterRules: [],
  },

  'voyage-large-2': {
    provider: 'anthropic',
    modelId: 'voyage-large-2',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage Large 2',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 16000,
    maxTokens: 16000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.00012, output: 0 },
    description: 'Voyage AI large context embedding model',
    parameterRules: [],
  },

  // Voyage 3.x Embedding Models
  'voyage-3-large': {
    provider: 'anthropic',
    modelId: 'voyage-3-large',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage 3 Large',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.00018, output: 0 },
    description: 'Voyage 3 Large - high-performance embedding with configurable dimensions',
    parameterRules: [
      {
        name: 'dimensions',
        type: 'int',
        label: 'Dimensions',
        help: 'Number of dimensions for the embedding vector',
        default: 1024,
        required: false,
        template: 'dimensions',
        options: ['256', '512', '1024', '2048'],
      },
    ],
  },

  'voyage-3.5': {
    provider: 'anthropic',
    modelId: 'voyage-3.5',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage 3.5',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.00006, output: 0 },
    description: 'Voyage 3.5 - latest generation embedding model',
    parameterRules: [
      {
        name: 'dimensions',
        type: 'int',
        label: 'Dimensions',
        help: 'Number of dimensions for the embedding vector',
        default: 1024,
        required: false,
        template: 'dimensions',
        options: ['256', '512', '1024', '2048'],
      },
    ],
  },

  'voyage-3.5-lite': {
    provider: 'anthropic',
    modelId: 'voyage-3.5-lite',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage 3.5 Lite',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.00002, output: 0 },
    description: 'Voyage 3.5 Lite - fast and efficient embedding model',
    parameterRules: [
      {
        name: 'dimensions',
        type: 'int',
        label: 'Dimensions',
        help: 'Number of dimensions for the embedding vector',
        default: 1024,
        required: false,
        template: 'dimensions',
        options: ['256', '512', '1024', '2048'],
      },
    ],
  },

  'voyage-code-3': {
    provider: 'anthropic',
    modelId: 'voyage-code-3',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage Code 3',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.00018, output: 0 },
    description: 'Voyage Code 3 - optimized for code and technical content',
    parameterRules: [
      {
        name: 'dimensions',
        type: 'int',
        label: 'Dimensions',
        help: 'Number of dimensions for the embedding vector',
        default: 1024,
        required: false,
        template: 'dimensions',
        options: ['256', '512', '1024', '2048'],
      },
    ],
  },

  'voyage-finance-2': {
    provider: 'anthropic',
    modelId: 'voyage-finance-2',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage Finance 2',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.00012, output: 0 },
    description: 'Voyage Finance 2 - optimized for financial documents (fixed 1024 dimensions)',
    parameterRules: [],
  },

  'voyage-law-2': {
    provider: 'anthropic',
    modelId: 'voyage-law-2',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage Law 2',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.00012, output: 0 },
    description: 'Voyage Law 2 - optimized for legal documents (fixed 1024 dimensions)',
    parameterRules: [],
  },
}
