// packages/lib/src/ai/providers/anthropic/anthropic-defaults.ts

import { FetchFrom, type ModelCapabilities, ModelType, type ProviderCapabilities } from '../types'

export const ANTHROPIC_CAPABILITIES: ProviderCapabilities = {
  id: 'anthropic',
  displayName: 'Anthropic',
  icon: 'anthropic',
  color: '#D97706',
  supportedModelTypes: [ModelType.LLM, ModelType.TEXT_EMBEDDING],
  defaultModel: 'claude-3-5-sonnet-20240620',
  requiresApiKey: true,
  toolFormat: 'anthropic',
  configurateMethods: ['predefined-model', 'customizable-model'],

  // NEW: Unified credential schema with scope-based filtering
  credentialSchema: [
    {
      variable: 'anthropic_api_key',
      type: 'secret-input',
      label: 'API Key',
      placeholder: 'Enter your Anthropic API Key',
      required: true,
      scope: 'both', // Available for both provider and model config
      priority: 'model-override', // Model-level key overrides provider key
      helpText: 'Your Anthropic API key from the Anthropic console',
      validation: {
        pattern: '^sk-ant-[a-zA-Z0-9-_]{20,}$',
        message: 'Anthropic API key must start with sk-ant- and be at least 24 characters',
      },
    },
  ],

  rateLimits: {
    requestsPerMinute: 100,
    tokensPerMinute: 40000,
    cacheTtl: 300, // 5 minutes
  },
  description: 'Advanced AI assistant by Anthropic with strong reasoning capabilities',
  documentationUrl: 'https://docs.anthropic.com/claude/reference',
  setupInstructions:
    'Get your API key from the Anthropic console at https://console.anthropic.com/',
}

export const ANTHROPIC_MODELS: Record<string, ModelCapabilities> = {
  'claude-sonnet-4-20250514': {
    provider: 'anthropic',
    modelId: 'claude-sonnet-4-20250514',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude Sonnet 4',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.003, output: 0.015 },
    description: 'Claude Sonnet 4 - latest generation with enhanced capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 1024,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-opus-4-20250514': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-20250514',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude Opus 4',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.015, output: 0.075 },
    description: 'Claude Opus 4 - most powerful model with advanced reasoning',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 1024,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-3-7-sonnet-20250219': {
    provider: 'anthropic',
    modelId: 'claude-3-7-sonnet-20250219',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude 3.7 Sonnet',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: false,
      vision: false,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.003, output: 0.015 },
    description: 'Latest Claude model with enhanced reasoning capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 1024,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'claude-3-5-sonnet-20241022': {
    provider: 'anthropic',
    modelId: 'claude-3-5-sonnet-20241022',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude 3.5 Sonnet (Oct 2024)',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools', 'computer_use'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.003, output: 0.015 },
    description: 'Claude 3.5 Sonnet with computer use and vision capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 1024,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-3-5-sonnet-20240620': {
    provider: 'anthropic',
    modelId: 'claude-3-5-sonnet-20240620',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude 3.5 Sonnet',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: false, // JSON mode via prompt
      vision: false,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.003, output: 0.015 },
    description: "Anthropic's most capable model for complex reasoning",
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 1024,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-3-5-haiku-20241022': {
    provider: 'anthropic',
    modelId: 'claude-3-5-haiku-20241022',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude 3.5 Haiku',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.001, output: 0.005 },
    description: 'Claude 3.5 Haiku - enhanced speed and capability',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 1024,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },

  'claude-3-sonnet-20240229': {
    provider: 'anthropic',
    modelId: 'claude-3-sonnet-20240229',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude 3 Sonnet',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: false,
      vision: false,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.003, output: 0.015 },
    description: 'Claude 3 Sonnet model with strong reasoning capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 1024,
        min: 1,
        max: 4096,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-3-opus-20240229': {
    provider: 'anthropic',
    modelId: 'claude-3-opus-20240229',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude 3 Opus',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: false,
      vision: false,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.015, output: 0.075 },
    description: 'Claude 3 Opus - most capable model for complex reasoning and analysis',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 1024,
        min: 1,
        max: 4096,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },
  'claude-3-haiku-20240307': {
    provider: 'anthropic',
    modelId: 'claude-3-haiku-20240307',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Claude 3 Haiku',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 200000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: false,
      vision: false,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.00025, output: 0.00125 },
    description: 'Claude 3 Haiku - fastest and most cost-effective model',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: "Controls randomness in Claude's responses. Lower values make the output more focused and deterministic.",
        default: 0.7,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate in the response.',
        default: 1024,
        min: 1,
        max: 4096,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity by considering only the top P probability mass.',
        default: 0.95,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
    ],
  },

  // Voyage AI Embedding Models (via Anthropic provider)
  'voyage-2': {
    provider: 'anthropic',
    modelId: 'voyage-2',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage 2',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 4000,
    maxTokens: 4000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.0001, output: 0 },
    description: 'Voyage AI general-purpose embedding model',
    parameterRules: [],
  },

  'voyage-large-2': {
    provider: 'anthropic',
    modelId: 'voyage-large-2',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage Large 2',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 16000,
    maxTokens: 16000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00015, output: 0 },
    description: 'Voyage AI large context embedding model',
    parameterRules: [],
  },

  // Voyage 3.x Embedding Models
  'voyage-3-large': {
    provider: 'anthropic',
    modelId: 'voyage-3-large',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage 3 Large',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00018, output: 0 },
    description: 'Voyage 3 Large - high-performance embedding with configurable dimensions',
    parameterRules: [
      {
        name: 'dimensions',
        type: 'int',
        label: 'Dimensions',
        help: 'Number of dimensions for the embedding vector',
        default: 1024,
        required: false,
        template: 'dimensions',
        options: ['256', '512', '1024', '2048'],
      },
    ],
  },

  'voyage-3.5': {
    provider: 'anthropic',
    modelId: 'voyage-3.5',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage 3.5',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00006, output: 0 },
    description: 'Voyage 3.5 - latest generation embedding model',
    parameterRules: [
      {
        name: 'dimensions',
        type: 'int',
        label: 'Dimensions',
        help: 'Number of dimensions for the embedding vector',
        default: 1024,
        required: false,
        template: 'dimensions',
        options: ['256', '512', '1024', '2048'],
      },
    ],
  },

  'voyage-3.5-lite': {
    provider: 'anthropic',
    modelId: 'voyage-3.5-lite',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage 3.5 Lite',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00002, output: 0 },
    description: 'Voyage 3.5 Lite - fast and efficient embedding model',
    parameterRules: [
      {
        name: 'dimensions',
        type: 'int',
        label: 'Dimensions',
        help: 'Number of dimensions for the embedding vector',
        default: 1024,
        required: false,
        template: 'dimensions',
        options: ['256', '512', '1024', '2048'],
      },
    ],
  },

  'voyage-code-3': {
    provider: 'anthropic',
    modelId: 'voyage-code-3',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage Code 3',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00018, output: 0 },
    description: 'Voyage Code 3 - optimized for code and technical content',
    parameterRules: [
      {
        name: 'dimensions',
        type: 'int',
        label: 'Dimensions',
        help: 'Number of dimensions for the embedding vector',
        default: 1024,
        required: false,
        template: 'dimensions',
        options: ['256', '512', '1024', '2048'],
      },
    ],
  },

  'voyage-finance-2': {
    provider: 'anthropic',
    modelId: 'voyage-finance-2',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage Finance 2',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00018, output: 0 },
    description: 'Voyage Finance 2 - optimized for financial documents (fixed 1024 dimensions)',
    parameterRules: [],
  },

  'voyage-law-2': {
    provider: 'anthropic',
    modelId: 'voyage-law-2',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Voyage Law 2',
    icon: 'anthropic',
    color: '#D97706',
    contextLength: 32000,
    maxTokens: 32000,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00018, output: 0 },
    description: 'Voyage Law 2 - optimized for legal documents (fixed 1024 dimensions)',
    parameterRules: [],
  },
}
