ALTER TABLE "AccountingDeliveryCoverage" DROP CONSTRAINT "AccountingDeliveryCoverage_book_effect_key";--> statement-breakpoint
ALTER TABLE "AccountingDelivery" DROP CONSTRAINT "AccountingDelivery_shape_check";--> statement-breakpoint
ALTER TABLE "AccountingDeliveryCoverage" DROP CONSTRAINT "AccountingDeliveryCoverage_component_check";--> statement-breakpoint
ALTER TABLE "AccountingDeliveryOperation" DROP CONSTRAINT "AccountingDeliveryOperation_state_check";--> statement-breakpoint
ALTER TABLE "ExternalAccountingObject" DROP CONSTRAINT "ExternalAccountingObject_shape_check";--> statement-breakpoint
ALTER TABLE "AccountingDeliveryCoverage" ADD COLUMN "lineKeys" jsonb;--> statement-breakpoint
ALTER TABLE "GlPosting" ADD COLUMN "basis" text;--> statement-breakpoint
UPDATE "AccountingDeliveryOperation" SET "objectType" = CASE "objectType" WHEN 'JournalEntry' THEN 'journal' WHEN 'Customer' THEN 'customer' WHEN 'Invoice' THEN 'invoice' WHEN 'Payment' THEN 'payment' WHEN 'CreditMemo' THEN 'credit_memo' ELSE "objectType" END;--> statement-breakpoint
UPDATE "ExternalAccountingObject" SET "objectType" = CASE "objectType" WHEN 'JournalEntry' THEN 'journal' WHEN 'Customer' THEN 'customer' WHEN 'Invoice' THEN 'invoice' WHEN 'Payment' THEN 'payment' WHEN 'CreditMemo' THEN 'credit_memo' ELSE "objectType" END;--> statement-breakpoint
ALTER TABLE "AccountingDeliveryCoverage" ADD CONSTRAINT "AccountingDeliveryCoverage_book_effect_component_key" UNIQUE("organizationId","bookId","effectId","componentKey");--> statement-breakpoint
ALTER TABLE "AccountingDelivery" ADD CONSTRAINT "AccountingDelivery_shape_check" CHECK ("AccountingDelivery"."representation" IN ('journal','invoice','payment','credit_memo') AND "AccountingDelivery"."state" IN ('pending','blocked','delivered'));--> statement-breakpoint
ALTER TABLE "AccountingDeliveryCoverage" ADD CONSTRAINT "AccountingDeliveryCoverage_component_check" CHECK ("AccountingDeliveryCoverage"."componentKey" ~ '^[a-z0-9][a-z0-9_.:-]{0,63}$' AND (("AccountingDeliveryCoverage"."componentKey" = 'whole_effect' AND "AccountingDeliveryCoverage"."lineKeys" IS NULL) OR ("AccountingDeliveryCoverage"."componentKey" <> 'whole_effect' AND jsonb_typeof("AccountingDeliveryCoverage"."lineKeys") = 'array' AND jsonb_array_length("AccountingDeliveryCoverage"."lineKeys") > 0)));--> statement-breakpoint
ALTER TABLE "AccountingDeliveryOperation" ADD CONSTRAINT "AccountingDeliveryOperation_state_check" CHECK ("AccountingDeliveryOperation"."state" IN ('pending','prepared','sending','uncertain','blocked','succeeded') AND "AccountingDeliveryOperation"."objectType" IN ('journal','customer','invoice','payment','credit_memo') AND "AccountingDeliveryOperation"."attempts" >= 0);--> statement-breakpoint
ALTER TABLE "ExternalAccountingObject" ADD CONSTRAINT "ExternalAccountingObject_shape_check" CHECK ("ExternalAccountingObject"."author" = 'auxx' AND "ExternalAccountingObject"."objectType" IN ('journal','customer','invoice','payment','credit_memo'));--> statement-breakpoint
ALTER TABLE "GlPosting" ADD CONSTRAINT "GlPosting_basis_check" CHECK ("GlPosting"."basis" IS NULL OR "GlPosting"."basis" IN ('accrual','cash'));