// apps/web/src/components/icons/brands.ts

/**
 * Manifest of brand marks shipped in `apps/web/public/icons/brands/`, referenced via the
 * `brand:<slug>` visual-ref grammar (rendered by VisualIcon/AppIcon). `hasDark` means a
 * `<slug>-dark.svg` twin exists for dark theme. Kept in sync with the files on disk and the
 * MCP template catalog by `__tests__/brands.test.ts`.
 */
export const BRAND_ICONS = {
  airtable: { hasDark: false },
  amex: { hasDark: false },
  anthropic: { hasDark: true },
  aws: { hasDark: true },
  'bank-of-america': { hasDark: true },
  barclays: { hasDark: false },
  box: { hasDark: false },
  'capital-one': { hasDark: false },
  chase: { hasDark: false },
  citi: { hasDark: false },
  cohere: { hasDark: false },
  context7: { hasDark: true },
  cratedb: { hasDark: false },
  deepseek: { hasDark: false },
  deepwiki: { hasDark: false },
  'deutsche-bank': { hasDark: true },
  discover: { hasDark: false },
  dropbox: { hasDark: false },
  exa: { hasDark: false },
  facebook: { hasDark: false },
  gemini: { hasDark: false },
  github: { hasDark: true },
  gmail: { hasDark: false },
  google: { hasDark: false },
  'google-drive': { hasDark: false },
  grok: { hasDark: false },
  groq: { hasDark: false },
  huggingface: { hasDark: false },
  instagram: { hasDark: false },
  kimi: { hasDark: false },
  linear: { hasDark: false },
  mercury: { hasDark: true },
  microsoft: { hasDark: false },
  notion: { hasDark: true },
  onedrive: { hasDark: false },
  openai: { hasDark: true },
  outlook: { hasDark: false },
  paypal: { hasDark: false },
  pnc: { hasDark: false },
  postgresql: { hasDark: false },
  quo: { hasDark: true },
  qwen: { hasDark: false },
  schwab: { hasDark: false },
  sentry: { hasDark: true },
  shopify: { hasDark: false },
  sofi: { hasDark: false },
  stripe: { hasDark: false },
  'td-bank': { hasDark: false },
  truist: { hasDark: true },
  ubs: { hasDark: true },
  'us-bank': { hasDark: false },
  'wells-fargo': { hasDark: false },
  zai: { hasDark: false },
  zapier: { hasDark: false },
} as const satisfies Record<string, { hasDark: boolean }>

export type BrandSlug = keyof typeof BRAND_ICONS
