// packages/lib/src/resources/registry/resources/invoice-fields.ts

import { FieldType } from '@auxx/database/enums'
import { type ResourceFieldId, toFieldId } from '@auxx/types/field'
import { BaseType } from '../../types'
import { CREATED_BY_FIELD } from '../common-fields'
import type { ResourceField } from '../field-types'

/** Invoice lifecycle status (README §domain, money MI1 build spec §B.1). */
export const INVOICE_STATUS_OPTIONS = [
  { label: 'Draft', value: 'draft', color: 'gray' },
  { label: 'Sent', value: 'sent', color: 'blue' },
  { label: 'Partially paid', value: 'partially_paid', color: 'amber' },
  { label: 'Paid', value: 'paid', color: 'green' },
  { label: 'Void', value: 'void', color: 'gray' },
] as const

/** Percent-of-subtotal vs flat-amount discount — same shape as the quote's. */
const INVOICE_DISCOUNT_TYPE_OPTIONS = [
  { label: 'Percent', value: 'percent', color: 'blue' },
  { label: 'Amount', value: 'amount', color: 'purple' },
] as const

/**
 * Field definitions for the Invoice resource (money MI1, README).
 * Visible, drawer-only system def (`hasDetailPage: false` — 01-ui #10 lock).
 */
export const INVOICE_FIELDS: Record<string, ResourceField> = {
  id: {
    id: toFieldId('id'),
    key: 'id',
    label: 'ID',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'id',
    systemSortOrder: 'a0',
    showInPanel: false,
    dbColumn: 'id',
    nullable: false,
    isIdentifier: true,
    operatorOverrides: ['is', 'is not', 'in', 'not in', 'exists', 'not exists'],
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Unique invoice identifier',
  },

  number: {
    id: toFieldId('number'),
    key: 'number',
    label: 'Number',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'invoice_number',
    systemSortOrder: 'a1',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false, // hook-generated (§F.2) — the hook is the ONLY writer
      updatable: false,
      configurable: false,
    },
    description: 'Auto-generated invoice number',
  },

  status: {
    id: toFieldId('status'),
    key: 'status',
    label: 'Status',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemAttribute: 'invoice_status',
    systemSortOrder: 'a2',
    nullable: false,
    options: { options: [...INVOICE_STATUS_OPTIONS] },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Select status',
    defaultValue: 'draft',
  },

  contact: {
    id: toFieldId('contact'),
    key: 'contact',
    label: 'Contact',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'invoice_contact',
    systemSortOrder: 'a3',
    nullable: false,
    required: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'contact:invoices' as ResourceFieldId,
      relationshipType: 'belongs_to',
      isInverse: false,
    },
    relationshipConfig: {
      relatedEntityType: 'contact',
      relationshipType: 'belongs_to',
      inverseName: 'Invoices',
      inverseSystemAttribute: 'contact_invoices',
    },
    description: 'Customer contact for this invoice — required, the billing party',
  },

  workOrder: {
    id: toFieldId('workOrder'),
    key: 'workOrder',
    label: 'Work Order',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'invoice_work_order',
    systemSortOrder: 'a4',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'work_order:invoices' as ResourceFieldId,
      relationshipType: 'belongs_to',
      isInverse: false,
    },
    relationshipConfig: {
      relatedEntityType: 'work_order',
      relationshipType: 'belongs_to',
      inverseName: 'Invoices',
      inverseSystemAttribute: 'work_order_invoices',
    },
    description: 'Job this invoice was gathered from — optional, standalone invoices have none',
  },

  issuedAt: {
    id: toFieldId('issuedAt'),
    key: 'issuedAt',
    label: 'Issued',
    type: BaseType.DATE,
    fieldType: FieldType.DATE,
    isSystem: true,
    systemAttribute: 'invoice_issued_at',
    systemSortOrder: 'a5',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Select issue date',
    description: 'Prefilled today at create; stamped by mark-sent if empty (§G.2)',
  },

  dueDate: {
    id: toFieldId('dueDate'),
    key: 'dueDate',
    label: 'Due Date',
    type: BaseType.DATE,
    fieldType: FieldType.DATE,
    isSystem: true,
    systemAttribute: 'invoice_due_date',
    systemSortOrder: 'a6',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Select due date',
    description: 'Overdue badge derives from this (UI-side) — never a status',
  },

  discountType: {
    id: toFieldId('discountType'),
    key: 'discountType',
    label: 'Discount Type',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemAttribute: 'invoice_discount_type',
    systemSortOrder: 'a7',
    nullable: true,
    options: { options: [...INVOICE_DISCOUNT_TYPE_OPTIONS] },
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Select discount type',
    description: 'Null = no discount',
  },

  discountValue: {
    id: toFieldId('discountValue'),
    key: 'discountValue',
    label: 'Discount Value',
    type: BaseType.NUMBER,
    fieldType: FieldType.NUMBER,
    isSystem: true,
    systemAttribute: 'invoice_discount_value',
    systemSortOrder: 'a8',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
  },

  taxName: {
    id: toFieldId('taxName'),
    key: 'taxName',
    label: 'Tax Name',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'invoice_tax_name',
    systemSortOrder: 'a9',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    description: "Snapshot of the picked tax rate's name (documents.taxRates)",
  },

  taxRate: {
    id: toFieldId('taxRate'),
    key: 'taxRate',
    label: 'Tax Rate',
    type: BaseType.NUMBER,
    fieldType: FieldType.NUMBER,
    isSystem: true,
    systemAttribute: 'invoice_tax_rate',
    systemSortOrder: 'aA',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    description: 'Snapshot of the picked tax rate, percent (e.g. 7.5)',
  },

  subtotal: {
    id: toFieldId('subtotal'),
    key: 'subtotal',
    label: 'Subtotal',
    type: BaseType.CURRENCY,
    fieldType: FieldType.CURRENCY,
    isSystem: true,
    systemAttribute: 'invoice_subtotal',
    systemSortOrder: 'aB',
    nullable: true,
    options: {
      currencyCode: 'USD',
      decimals: 2,
      useGrouping: true,
      currencyDisplay: 'symbol',
    },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false, // totals engine (§G.1) is the only writer
      updatable: false,
      configurable: false,
    },
    description: 'Sum of line totals — written by the totals engine hook',
  },

  taxTotal: {
    id: toFieldId('taxTotal'),
    key: 'taxTotal',
    label: 'Tax Total',
    type: BaseType.CURRENCY,
    fieldType: FieldType.CURRENCY,
    isSystem: true,
    systemAttribute: 'invoice_tax_total',
    systemSortOrder: 'aC',
    nullable: true,
    options: {
      currencyCode: 'USD',
      decimals: 2,
      useGrouping: true,
      currencyDisplay: 'symbol',
    },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false, // totals engine (§G.1) is the only writer
      updatable: false,
      configurable: false,
    },
    description: 'Written by the totals engine hook',
  },

  total: {
    id: toFieldId('total'),
    key: 'total',
    label: 'Total',
    type: BaseType.CURRENCY,
    fieldType: FieldType.CURRENCY,
    isSystem: true,
    systemAttribute: 'invoice_total',
    systemSortOrder: 'aD',
    nullable: true,
    options: {
      currencyCode: 'USD',
      decimals: 2,
      useGrouping: true,
      currencyDisplay: 'symbol',
    },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false, // totals engine (§G.1) is the only writer
      updatable: false,
      configurable: false,
    },
    description: 'Written by the totals engine hook',
  },

  amountPaid: {
    id: toFieldId('amountPaid'),
    key: 'amountPaid',
    label: 'Amount Paid',
    type: BaseType.CURRENCY,
    fieldType: FieldType.CURRENCY,
    isSystem: true,
    systemAttribute: 'invoice_amount_paid',
    systemSortOrder: 'aE',
    nullable: true,
    options: {
      currencyCode: 'USD',
      decimals: 2,
      useGrouping: true,
      currencyDisplay: 'symbol',
    },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false, // ledger sync (§E.4) is the only writer
      updatable: false,
      configurable: false,
    },
    description: 'Sum of succeeded payments — written by syncInvoicePaymentState',
  },

  balance: {
    id: toFieldId('balance'),
    key: 'balance',
    label: 'Balance',
    type: BaseType.CURRENCY,
    fieldType: FieldType.CURRENCY,
    isSystem: true,
    systemAttribute: 'invoice_balance',
    systemSortOrder: 'aF',
    nullable: true,
    options: {
      currencyCode: 'USD',
      decimals: 2,
      useGrouping: true,
      currencyDisplay: 'symbol',
    },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false, // ledger sync (§E.4) is the only writer
      updatable: false,
      configurable: false,
    },
    description: 'total - amountPaid — written by syncInvoicePaymentState',
  },

  notes: {
    id: toFieldId('notes'),
    key: 'notes',
    label: 'Notes',
    type: BaseType.STRING,
    fieldType: FieldType.RICH_TEXT,
    isSystem: true,
    systemAttribute: 'invoice_notes',
    systemSortOrder: 'aG',
    nullable: true,
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter internal notes',
    description: 'Internal notes — not shown to the customer',
  },

  terms: {
    id: toFieldId('terms'),
    key: 'terms',
    label: 'Terms',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'invoice_terms',
    systemSortOrder: 'aH',
    nullable: true,
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter customer-facing terms',
    description: 'Customer-facing terms (plain text, PDF-friendly)',
  },

  pdfAsset: {
    id: toFieldId('pdfAsset'),
    key: 'pdfAsset',
    label: 'PDF Asset',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'invoice_pdf_asset',
    systemSortOrder: 'aI',
    showInPanel: false,
    nullable: true,
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: false,
      updatable: true,
      configurable: false,
      hidden: true,
    },
    description:
      'MediaAsset id of the last-rendered invoice PDF (money MQ2 build spec §C.1 recipe) — ' +
      'written only by ensureDocumentPdf via FieldValueService, never user-editable',
  },

  lineItems: {
    id: toFieldId('lineItems'),
    key: 'lineItems',
    label: 'Line Items',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'invoice_line_items',
    systemSortOrder: 'aJ',
    showInPanel: false,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'line_item:invoice' as ResourceFieldId,
      relationshipType: 'has_many',
      isInverse: true,
    },
    description: 'Line items on this invoice',
  },

  payments: {
    id: toFieldId('payments'),
    key: 'payments',
    label: 'Payments',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'invoice_payments',
    systemSortOrder: 'aK',
    showInPanel: false,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'payment:invoice' as ResourceFieldId,
      relationshipType: 'has_many',
      isInverse: true,
    },
    description: 'Payment mirror records for this invoice (ledger-backed, §E)',
  },

  publicToken: {
    id: toFieldId('publicToken'),
    key: 'publicToken',
    label: 'Public Token',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'invoice_public_token',
    systemSortOrder: 'aL',
    showInPanel: false,
    nullable: true,
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: false,
      updatable: false,
      configurable: false,
      hidden: true,
    },
    description:
      'Unguessable capability token for the public /pay/{token} page (money MP1 build spec ' +
      '§H) — lazily minted by ensureInvoicePublicToken on first send/PDF-render, never ' +
      'user-editable. Mirrors the invoice_pdf_asset recipe (FieldValueService-only writer).',
  },

  createdAt: {
    id: toFieldId('createdAt'),
    key: 'createdAt',
    label: 'Created',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'created_at',
    systemSortOrder: 'b0',
    dbColumn: 'createdAt',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Automatically set when the invoice is created',
  },

  updatedAt: {
    id: toFieldId('updatedAt'),
    key: 'updatedAt',
    label: 'Updated',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'updated_at',
    systemSortOrder: 'b1',
    dbColumn: 'updatedAt',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Automatically updated when the invoice is modified',
  },

  createdBy: CREATED_BY_FIELD,
}
