// packages/lib/src/resources/registry/resources/kb-fields.ts

import { FieldType } from '@auxx/database/enums'
import { type ResourceFieldId, toFieldId } from '@auxx/types/field'
import { BaseType } from '../../types'
import { KbPublishStatus, KbVisibility } from '../enum-values'
import type { ResourceField } from '../field-types'

/**
 * Field definitions for the Knowledge Base resource.
 *
 * KBs live in the dedicated `KnowledgeBase` table. Scalar fields use `dbColumn`;
 * `kb_articles` is the virtual inverse of `article.knowledgeBase`.
 */
export const KB_FIELDS: Record<string, ResourceField> = {
  id: {
    id: toFieldId('id'),
    key: 'id',
    label: 'ID',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'id',
    systemSortOrder: 'a0',
    showInPanel: false,
    dbColumn: 'id',
    nullable: false,
    isIdentifier: true,
    operatorOverrides: ['is', 'is not', 'in', 'not in'],
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Unique knowledge base identifier',
  },

  name: {
    id: toFieldId('name'),
    key: 'name',
    label: 'Name',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'kb_name',
    systemSortOrder: 'a1',
    dbColumn: 'name',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    description: 'Knowledge base name',
  },

  slug: {
    id: toFieldId('slug'),
    key: 'slug',
    label: 'Slug',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'kb_slug',
    systemSortOrder: 'a2',
    dbColumn: 'slug',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    description: 'URL-safe slug for the knowledge base',
  },

  description: {
    id: toFieldId('description'),
    key: 'description',
    label: 'Description',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'kb_description',
    systemSortOrder: 'a3',
    dbColumn: 'description',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    description: 'Optional description of the knowledge base',
  },

  publishStatus: {
    id: toFieldId('publishStatus'),
    key: 'publishStatus',
    label: 'Publish Status',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemAttribute: 'kb_publish_status',
    systemSortOrder: 'a4',
    dbColumn: 'publishStatus',
    nullable: false,
    options: { options: KbPublishStatus.values },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: true,
      configurable: false,
    },
    defaultValue: 'DRAFT',
    description: 'Publishing status of the knowledge base',
  },

  visibility: {
    id: toFieldId('visibility'),
    key: 'visibility',
    label: 'Visibility',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemAttribute: 'kb_visibility',
    systemSortOrder: 'a5',
    dbColumn: 'visibility',
    nullable: false,
    options: { options: KbVisibility.values },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: true,
      configurable: false,
    },
    defaultValue: 'PUBLIC',
    description: 'Whether the knowledge base is public or internal',
  },

  kb_articles: {
    id: toFieldId('kb_articles'),
    key: 'kb_articles',
    label: 'Articles',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'kb_articles',
    systemSortOrder: 'a6',
    dbColumn: undefined,
    nullable: true,
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'article:knowledgeBase' as ResourceFieldId,
      relationshipType: 'has_many',
      isInverse: true,
    },
    description: 'Articles belonging to this knowledge base',
  },

  publishedAt: {
    id: toFieldId('publishedAt'),
    key: 'publishedAt',
    label: 'Published At',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'kb_published_at',
    systemSortOrder: 'a7',
    dbColumn: 'publishedAt',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Timestamp when the knowledge base was first published',
  },

  lastPublishedAt: {
    id: toFieldId('lastPublishedAt'),
    key: 'lastPublishedAt',
    label: 'Last Published At',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'kb_last_published_at',
    systemSortOrder: 'a8',
    dbColumn: 'lastPublishedAt',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Timestamp of the most recent publish',
  },

  createdAt: {
    id: toFieldId('createdAt'),
    key: 'createdAt',
    label: 'Created',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'created_at',
    systemSortOrder: 'a9',
    dbColumn: 'createdAt',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Automatically set when knowledge base is created',
  },

  updatedAt: {
    id: toFieldId('updatedAt'),
    key: 'updatedAt',
    label: 'Updated',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'updated_at',
    systemSortOrder: 'aA',
    dbColumn: 'updatedAt',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Automatically updated when knowledge base is modified',
  },
}
