// packages/lib/src/resources/registry/resources/line-item-fields.ts

import { FieldType } from '@auxx/database/enums'
import { type ResourceFieldId, toFieldId } from '@auxx/types/field'
import { BaseType } from '../../types'
import { CREATED_BY_FIELD } from '../common-fields'
import type { ResourceField } from '../field-types'
import { CATALOG_CATEGORY_OPTIONS } from './catalog-item-fields'

/**
 * Field definitions for the Line Item resource — quote/work-order/invoice line rows
 * (money module, README). Hidden system entity — rendered only by the embedded
 * line-builder UIs (§H.1), never shown in the entity sidebar or generic dialogs.
 */
export const LINE_ITEM_FIELDS: Record<string, ResourceField> = {
  id: {
    id: toFieldId('id'),
    key: 'id',
    label: 'ID',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'id',
    systemSortOrder: 'a0',
    showInPanel: false,
    dbColumn: 'id',
    nullable: false,
    isIdentifier: true,
    operatorOverrides: ['is', 'is not', 'in', 'not in', 'exists', 'not exists'],
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Unique line item identifier',
  },

  name: {
    id: toFieldId('name'),
    key: 'name',
    label: 'Name',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'line_item_name',
    systemSortOrder: 'a1',
    // Optional — the line builder creates EMPTY lines that the catalog picker
    // fills in afterwards.
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter line name',
    description: 'The catalog-combobox cell edits this field',
  },

  description: {
    id: toFieldId('description'),
    key: 'description',
    label: 'Description',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'line_item_description',
    systemSortOrder: 'a2',
    nullable: true,
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter description',
    description: 'Toggleable sub-line shown under the line name (01-ui #1)',
  },

  qty: {
    id: toFieldId('qty'),
    key: 'qty',
    label: 'Qty',
    type: BaseType.NUMBER,
    fieldType: FieldType.NUMBER,
    isSystem: true,
    systemAttribute: 'line_item_qty',
    systemSortOrder: 'a3',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    defaultValue: 1,
  },

  unitPrice: {
    id: toFieldId('unitPrice'),
    key: 'unitPrice',
    label: 'Unit Price',
    type: BaseType.CURRENCY,
    fieldType: FieldType.CURRENCY,
    isSystem: true,
    systemAttribute: 'line_item_unit_price',
    systemSortOrder: 'a4',
    nullable: true,
    options: {
      currencyCode: 'USD',
      decimals: 2,
      useGrouping: true,
      currencyDisplay: 'symbol',
    },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
  },

  lineTotal: {
    id: toFieldId('lineTotal'),
    key: 'lineTotal',
    label: 'Line Total',
    type: BaseType.CURRENCY,
    fieldType: FieldType.CURRENCY,
    isSystem: true,
    systemAttribute: 'line_item_line_total',
    systemSortOrder: 'a5',
    nullable: true,
    options: {
      currencyCode: 'USD',
      decimals: 2,
      useGrouping: true,
      currencyDisplay: 'symbol',
    },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false, // totals engine (§F) is the only writer
      updatable: false,
      configurable: false,
    },
    description: 'qty * unitPrice — written by the totals engine hook',
  },

  taxable: {
    id: toFieldId('taxable'),
    key: 'taxable',
    label: 'Taxable',
    type: BaseType.BOOLEAN,
    fieldType: FieldType.CHECKBOX,
    isSystem: true,
    systemAttribute: 'line_item_taxable',
    systemSortOrder: 'a6',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    defaultValue: true,
  },

  category: {
    id: toFieldId('category'),
    key: 'category',
    label: 'Category',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemAttribute: 'line_item_category',
    systemSortOrder: 'a7',
    nullable: true,
    options: { options: [...CATALOG_CATEGORY_OPTIONS] },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Select category',
  },

  discount: {
    id: toFieldId('discount'),
    key: 'discount',
    label: 'Discount',
    type: BaseType.NUMBER,
    fieldType: FieldType.NUMBER,
    isSystem: true,
    systemAttribute: 'line_item_discount',
    systemSortOrder: 'a8',
    showInPanel: false, // line-level discount is a later UI unlock (README); field ships now
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
  },

  sortOrder: {
    id: toFieldId('sortOrder'),
    key: 'sortOrder',
    label: 'Sort Order',
    type: BaseType.NUMBER,
    fieldType: FieldType.NUMBER,
    isSystem: true,
    systemAttribute: 'line_item_sort_order',
    systemSortOrder: 'a9',
    showInPanel: false,
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    description: 'Written by the reorder mutation (§G.4)',
  },

  visitId: {
    id: toFieldId('visitId'),
    key: 'visitId',
    label: 'Visit ID',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'line_item_visit_id',
    systemSortOrder: 'aA',
    showInPanel: false,
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    description: 'Plain text bridge to WorkOrderVisit — visits are not entities (dispatch lock)',
  },

  catalogItem: {
    id: toFieldId('catalogItem'),
    key: 'catalogItem',
    label: 'Catalog Item',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'line_item_catalog_item',
    systemSortOrder: 'aB',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'catalog_item:lineItems' as ResourceFieldId,
      relationshipType: 'belongs_to',
      isInverse: false,
    },
    relationshipConfig: {
      relatedEntityType: 'catalog_item',
      relationshipType: 'belongs_to',
      inverseName: 'Line Items',
      inverseSystemAttribute: 'catalog_item_line_items',
    },
    description: 'Catalog item this line was picked from — provenance only, values are snapshots',
  },

  quote: {
    id: toFieldId('quote'),
    key: 'quote',
    label: 'Quote',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'line_item_quote',
    systemSortOrder: 'aC',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'quote:lineItems' as ResourceFieldId,
      relationshipType: 'belongs_to',
      isInverse: false,
    },
    relationshipConfig: {
      relatedEntityType: 'quote',
      relationshipType: 'belongs_to',
      inverseName: 'Line Items',
      inverseSystemAttribute: 'quote_line_items',
    },
    description: 'Quote this line belongs to',
  },

  workOrder: {
    id: toFieldId('workOrder'),
    key: 'workOrder',
    label: 'Work Order',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'line_item_work_order',
    systemSortOrder: 'aD',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'work_order:lineItems' as ResourceFieldId,
      relationshipType: 'belongs_to',
      isInverse: false,
    },
    relationshipConfig: {
      relatedEntityType: 'work_order',
      relationshipType: 'belongs_to',
      inverseName: 'Line Items',
      inverseSystemAttribute: 'work_order_line_items',
    },
    description: 'Work order this line belongs to (copied from a converted quote)',
  },

  invoice: {
    id: toFieldId('invoice'),
    key: 'invoice',
    label: 'Invoice',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'line_item_invoice',
    systemSortOrder: 'aE',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'invoice:lineItems' as ResourceFieldId,
      relationshipType: 'belongs_to',
      isInverse: false,
    },
    relationshipConfig: {
      relatedEntityType: 'invoice',
      relationshipType: 'belongs_to',
      inverseName: 'Line Items',
      inverseSystemAttribute: 'invoice_line_items',
    },
    description: 'Parent invoice relation for invoice-owned snapshot lines only',
  },

  createdAt: {
    id: toFieldId('createdAt'),
    key: 'createdAt',
    label: 'Created',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'created_at',
    systemSortOrder: 'b0',
    dbColumn: 'createdAt',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Automatically set when the line item is created',
  },

  updatedAt: {
    id: toFieldId('updatedAt'),
    key: 'updatedAt',
    label: 'Updated',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'updated_at',
    systemSortOrder: 'b1',
    dbColumn: 'updatedAt',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Automatically updated when the line item is modified',
  },

  createdBy: CREATED_BY_FIELD,
}
