// packages/lib/src/resources/registry/resources/meeting-fields.ts

import { FieldType } from '@auxx/database/enums'
import { type ResourceFieldId, toFieldId } from '@auxx/types/field'
import { BaseType } from '../../types'
import { CREATED_BY_FIELD } from '../common-fields'
import type { ResourceField } from '../field-types'

/**
 * Meeting type options for the system Meeting entity.
 */
const MEETING_TYPE_OPTIONS = [
  { label: 'Call', value: 'call', color: 'blue' },
  { label: 'Video', value: 'video', color: 'purple' },
  { label: 'In-Person', value: 'in-person', color: 'green' },
  { label: 'Trade Show', value: 'trade-show', color: 'orange' },
  { label: 'Demo', value: 'demo', color: 'teal' },
] as const

/**
 * Field definitions for the Meeting resource.
 * Defines all fields, their types, capabilities, and validation rules.
 */
export const MEETING_FIELDS: Record<string, ResourceField> = {
  id: {
    id: toFieldId('id'),
    key: 'id',
    label: 'ID',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'id',
    systemSortOrder: 'a0',
    showInPanel: false,
    dbColumn: 'id',
    nullable: false,
    isIdentifier: true,
    operatorOverrides: ['is', 'is not', 'in', 'not in', 'exists', 'not exists'],
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Unique meeting identifier',
  },

  title: {
    id: toFieldId('title'),
    key: 'title',
    label: 'Title',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'meeting_title',
    systemSortOrder: 'a1',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      required: true,
      configurable: false,
    },
    placeholder: 'Enter meeting title',
  },

  type: {
    id: toFieldId('type'),
    key: 'type',
    label: 'Type',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemAttribute: 'meeting_type',
    systemSortOrder: 'a2',
    nullable: true,
    options: { options: [...MEETING_TYPE_OPTIONS] },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Select meeting type',
  },

  dateTime: {
    id: toFieldId('dateTime'),
    key: 'dateTime',
    label: 'Date & Time',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'meeting_date_time',
    systemSortOrder: 'a3',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
  },

  duration: {
    id: toFieldId('duration'),
    key: 'duration',
    label: 'Duration (minutes)',
    type: BaseType.NUMBER,
    fieldType: FieldType.NUMBER,
    isSystem: true,
    systemAttribute: 'meeting_duration_minutes',
    systemSortOrder: 'a4',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter duration in minutes',
  },

  location: {
    id: toFieldId('location'),
    key: 'location',
    label: 'Location',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'meeting_location',
    systemSortOrder: 'a5',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter location',
  },

  meetingUrl: {
    id: toFieldId('meetingUrl'),
    key: 'meetingUrl',
    label: 'Meeting URL',
    type: BaseType.URL,
    fieldType: FieldType.URL,
    isSystem: true,
    systemAttribute: 'meeting_url',
    systemSortOrder: 'a6',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter meeting URL',
  },

  organizer: {
    id: toFieldId('organizer'),
    key: 'organizer',
    label: 'Organizer',
    type: BaseType.ACTOR,
    fieldType: FieldType.ACTOR,
    isSystem: true,
    systemAttribute: 'meeting_organizer',
    systemSortOrder: 'a7',
    nullable: true,
    options: {
      actor: {
        target: 'user',
        multiple: false,
      },
    },
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    description: 'User responsible for organizing the meeting',
  },

  agenda: {
    id: toFieldId('agenda'),
    key: 'agenda',
    label: 'Agenda',
    type: BaseType.STRING,
    fieldType: FieldType.RICH_TEXT,
    isSystem: true,
    systemAttribute: 'meeting_agenda',
    systemSortOrder: 'a8',
    nullable: true,
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter meeting agenda',
  },

  meetingNotes: {
    id: toFieldId('meetingNotes'),
    key: 'meetingNotes',
    label: 'Meeting Notes',
    type: BaseType.STRING,
    fieldType: FieldType.RICH_TEXT,
    isSystem: true,
    systemAttribute: 'meeting_notes',
    systemSortOrder: 'a9',
    nullable: true,
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter meeting notes',
  },

  actionItems: {
    id: toFieldId('actionItems'),
    key: 'actionItems',
    label: 'Action Items',
    type: BaseType.STRING,
    fieldType: FieldType.RICH_TEXT,
    isSystem: true,
    systemAttribute: 'meeting_action_items',
    systemSortOrder: 'aA',
    nullable: true,
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter action items',
  },

  recordingUrl: {
    id: toFieldId('recordingUrl'),
    key: 'recordingUrl',
    label: 'Recording URL',
    type: BaseType.URL,
    fieldType: FieldType.URL,
    isSystem: true,
    systemAttribute: 'meeting_recording_url',
    systemSortOrder: 'aB',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter recording URL',
  },

  company: {
    id: toFieldId('company'),
    key: 'company',
    label: 'Company',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'meeting_company',
    systemSortOrder: 'aC',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'company:meetings' as ResourceFieldId,
      relationshipType: 'belongs_to',
      isInverse: false,
    },
    relationshipConfig: {
      relatedEntityType: 'company',
      relationshipType: 'belongs_to',
      inverseName: 'Meetings',
      inverseSystemAttribute: 'company_meetings',
    },
    description: 'Primary company associated with the meeting',
  },

  contact: {
    id: toFieldId('contact'),
    key: 'contact',
    label: 'Contact',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'meeting_contact',
    systemSortOrder: 'aD',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'contact:meetings' as ResourceFieldId,
      relationshipType: 'belongs_to',
      isInverse: false,
    },
    relationshipConfig: {
      relatedEntityType: 'contact',
      relationshipType: 'belongs_to',
      inverseName: 'Meetings',
      inverseSystemAttribute: 'contact_meetings',
    },
    description: 'Primary contact associated with the meeting',
  },

  createdAt: {
    id: toFieldId('createdAt'),
    key: 'createdAt',
    label: 'Created',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'created_at',
    systemSortOrder: 'aE',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Automatically set when the meeting is created',
  },

  updatedAt: {
    id: toFieldId('updatedAt'),
    key: 'updatedAt',
    label: 'Updated',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'updated_at',
    systemSortOrder: 'aF',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Automatically updated when the meeting is modified',
  },

  createdBy: CREATED_BY_FIELD,
}
