// packages/lib/src/workflow-engine/resources/registry/resources/ticket-fields.ts

import { FieldType } from '@auxx/database/enums'
import { BaseType } from '../../types'
import type { ResourceField } from '../field-types'
import { TicketType, TicketStatus, TicketPriority } from '../enum-values'

/**
 * Field definitions for the Ticket resource
 * Defines all fields, their types, capabilities, and validation rules
 */
export const TICKET_FIELDS: Record<string, ResourceField> = {
  id: {
    id: 'id',
    key: 'id',
    label: 'ID',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemSortOrder: -1,
    showInPanel: false,
    dbColumn: 'id',
    nullable: false,
    isIdentifier: true,
    operatorOverrides: ['is', 'is not', 'in', 'not in', 'exists', 'not exists'],
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: false,
      updatable: false,
    },
    description: 'Unique ticket identifier',
  },

  number: {
    id: 'number',
    key: 'number',
    label: 'Ticket #',
    type: BaseType.NUMBER,
    fieldType: FieldType.NUMBER,
    isSystem: true,
    systemSortOrder: 5,
    dbColumn: 'number',
    nullable: false,
    isIdentifier: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
    },
    description: 'Sequential ticket number',
  },

  title: {
    id: 'title',
    key: 'title',
    label: 'Title',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemSortOrder: 10,
    dbColumn: 'title',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      required: true,
    },
    placeholder: 'Enter ticket title',
    validation: {
      minLength: 1,
      maxLength: 500,
    },
  },

  type: {
    id: 'type',
    key: 'type',
    label: 'Type',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemSortOrder: 30,
    dbColumn: 'type',
    nullable: false,
    enumValues: TicketType.values,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: false, // Type cannot be changed after creation
      required: true,
    },
    placeholder: 'Select ticket type',
    description: 'Ticket type cannot be changed after creation',
    defaultValue: 'GENERAL',
  },

  status: {
    id: 'status',
    key: 'status',
    label: 'Status',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemSortOrder: 20,
    dbColumn: 'status',
    nullable: false,
    enumValues: TicketStatus.values,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
    },
    placeholder: 'Select status',
    defaultValue: 'OPEN',
  },

  priority: {
    id: 'priority',
    key: 'priority',
    label: 'Priority',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemSortOrder: 25,
    dbColumn: 'priority',
    nullable: false,
    enumValues: TicketPriority.values,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
    },
    placeholder: 'Select priority',
    defaultValue: 'MEDIUM',
  },

  contact: {
    id: 'contact',
    key: 'contact',
    label: 'Contact',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemSortOrder: 45,
    dynamicOptionsKey: 'contacts',
    dbColumn: 'contactId',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: false, // Cannot reassign ticket to different contact
      required: true,
    },
    relationship: {
      targetTable: 'contact',
      targetField: 'id',
      cardinality: 'many-to-one',
      reciprocalField: 'tickets',
      required: true,
      onDelete: 'RESTRICT',
    },
    placeholder: 'Select a contact',
    description: 'The contact this ticket belongs to',
  },

  description: {
    id: 'description',
    key: 'description',
    label: 'Description',
    type: BaseType.STRING,
    fieldType: FieldType.RICH_TEXT,
    isSystem: true,
    systemSortOrder: 15,
    dbColumn: 'description',
    nullable: true,
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: true,
      updatable: true,
    },
    placeholder: 'Enter ticket description',
  },

  assignee: {
    id: 'assignee',
    key: 'assignee',
    label: 'Assignee',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemSortOrder: 40,
    dynamicOptionsKey: 'teamMembers',
    dbColumn: 'assignedToId',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
    },
    relationship: {
      targetTable: 'user',
      targetField: 'id',
      cardinality: 'many-to-one',
      reciprocalField: 'assignedTickets',
      required: false,
      onDelete: 'SET_NULL',
    },
    placeholder: 'Select an assignee',
    description: 'Team member assigned to this ticket',
  },

  parentTicket: {
    id: 'parentTicket',
    key: 'parentTicket',
    label: 'Parent Ticket',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    showInPanel: false, // Hidden - not typically shown in property panel
    dbColumn: 'parentTicketId',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
    },
    relationship: {
      targetTable: 'ticket',
      targetField: 'id',
      cardinality: 'many-to-one',
      reciprocalField: 'childTickets',
      required: false,
    },
    placeholder: 'Select parent ticket',
    description: 'Parent ticket for hierarchical relationships',
  },

  // Reverse relationship: childTickets (one-to-many)
  childTickets: {
    id: 'childTickets',
    key: 'childTickets',
    label: 'Child Tickets',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    showInPanel: false, // Relationship reverse-field
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: false,
      updatable: false,
    },
    relationship: {
      targetTable: 'ticket',
      cardinality: 'one-to-many',
      reciprocalField: 'parentTicket',
    },
    description: 'All child tickets of this ticket',
  },

  dueDate: {
    id: 'dueDate',
    key: 'dueDate',
    label: 'Due Date',
    type: BaseType.DATE,
    fieldType: FieldType.DATE,
    isSystem: true,
    systemSortOrder: 35,
    dbColumn: 'dueDate',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
    },
    placeholder: 'Select due date',
  },

  createdAt: {
    id: 'createdAt',
    key: 'createdAt',
    label: 'Created',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemSortOrder: 100,
    dbColumn: 'createdAt',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
    },
    description: 'Automatically set when ticket is created',
  },

  updatedAt: {
    id: 'updatedAt',
    key: 'updatedAt',
    label: 'Updated',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemSortOrder: 101,
    dbColumn: 'updatedAt',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
    },
    description: 'Automatically updated when ticket is modified',
  },
}
