// packages/lib/src/workflow-engine/resources/registry/resources/ticket-fields.ts

import { FieldType } from '@auxx/database/enums'
import { type ResourceFieldId, toFieldId } from '@auxx/types/field'
import { BaseType } from '../../types'
import { CREATED_BY_FIELD } from '../common-fields'
import { TicketPriority, TicketStatus, TicketType } from '../enum-values'
import type { ResourceField } from '../field-types'

/**
 * Field definitions for the Ticket resource
 * Defines all fields, their types, capabilities, and validation rules
 */
export const TICKET_FIELDS: Record<string, ResourceField> = {
  id: {
    id: toFieldId('id'),
    key: 'id',
    label: 'ID',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'id',
    systemSortOrder: 'a0',
    showInPanel: false,
    dbColumn: 'id',
    nullable: false,
    isIdentifier: true,
    operatorOverrides: ['is', 'is not', 'in', 'not in', 'exists', 'not exists'],
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Unique ticket identifier',
  },

  number: {
    id: toFieldId('number'),
    key: 'number',
    label: 'Ticket #',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'ticket_number',
    systemSortOrder: 'a1',
    dbColumn: 'number',
    nullable: false,
    isIdentifier: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Auto-generated ticket number (e.g., 2501-0042)',
  },

  title: {
    id: toFieldId('title'),
    key: 'title',
    label: 'Title',
    type: BaseType.STRING,
    fieldType: FieldType.TEXT,
    isSystem: true,
    systemAttribute: 'ticket_title',
    systemSortOrder: 'a2',
    dbColumn: 'title',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      required: true,
      configurable: false,
    },
    placeholder: 'Enter ticket title',
    validation: {
      minLength: 1,
      maxLength: 500,
    },
  },

  type: {
    id: toFieldId('type'),
    key: 'type',
    label: 'Type',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemAttribute: 'ticket_type',
    systemSortOrder: 'a6',
    dbColumn: 'type',
    nullable: false,
    options: { options: TicketType.values },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: false, // Type cannot be changed after creation
      required: true,
      configurable: false,
    },
    placeholder: 'Select ticket type',
    description: 'Ticket type cannot be changed after creation',
    defaultValue: 'GENERAL',
  },

  status: {
    id: toFieldId('status'),
    key: 'status',
    label: 'Status',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemAttribute: 'ticket_status',
    systemSortOrder: 'a4',
    dbColumn: 'status',
    nullable: false,
    options: { options: TicketStatus.values },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Select status',
    defaultValue: 'OPEN',
  },

  priority: {
    id: toFieldId('priority'),
    key: 'priority',
    label: 'Priority',
    type: BaseType.ENUM,
    fieldType: FieldType.SINGLE_SELECT,
    isSystem: true,
    systemAttribute: 'ticket_priority',
    systemSortOrder: 'a5',
    dbColumn: 'priority',
    nullable: false,
    options: { options: TicketPriority.values },
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Select priority',
    defaultValue: 'MEDIUM',
  },

  contact: {
    id: toFieldId('contact'),
    key: 'contact',
    label: 'Contact',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'ticket_contact',
    systemSortOrder: 'a9',
    dynamicOptionsKey: 'contacts',
    dbColumn: 'contactId',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      required: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'contact:tickets' as ResourceFieldId,
      relationshipType: 'belongs_to',
      isInverse: false,
    },
    relationshipConfig: {
      relatedEntityType: 'contact',
      relationshipType: 'belongs_to',
      inverseName: 'Tickets',
      inverseSystemAttribute: 'contact_tickets',
    },
    placeholder: 'Select a contact',
    description: 'The contact this ticket belongs to',
  },

  description: {
    id: toFieldId('description'),
    key: 'description',
    label: 'Description',
    type: BaseType.STRING,
    fieldType: FieldType.RICH_TEXT,
    isSystem: true,
    systemAttribute: 'ticket_description',
    systemSortOrder: 'a3',
    dbColumn: 'description',
    nullable: true,
    capabilities: {
      filterable: false,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Enter ticket description',
  },

  assignee: {
    id: toFieldId('assignee'),
    key: 'assignee',
    label: 'Assignee',
    type: BaseType.ACTOR,
    fieldType: FieldType.ACTOR,
    isSystem: true,
    systemAttribute: 'assigned_to_id',
    systemSortOrder: 'a8',
    dynamicOptionsKey: 'teamMembers',
    dbColumn: 'assignedToId',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    options: {
      actor: {
        target: 'user',
        multiple: false,
      },
    },
    placeholder: 'Select an assignee',
    description: 'Team member assigned to this ticket',
  },

  parentTicket: {
    id: toFieldId('parentTicket'),
    key: 'parentTicket',
    label: 'Parent Ticket',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'parent_ticket_id',
    systemSortOrder: 'aA',
    showInPanel: false, // Hidden - not typically shown in property panel
    dbColumn: 'parentTicketId',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'ticket:childTickets' as ResourceFieldId,
      relationshipType: 'belongs_to',
      isInverse: false,
    },
    placeholder: 'Select parent ticket',
    description: 'Parent ticket for hierarchical relationships',
  },

  // Reverse relationship: childTickets (one-to-many)
  childTickets: {
    id: toFieldId('childTickets'),
    key: 'childTickets',
    label: 'Child Tickets',
    type: BaseType.RELATION,
    fieldType: FieldType.RELATIONSHIP,
    isSystem: true,
    systemAttribute: 'ticket_child_tickets',
    systemSortOrder: 'aB',
    showInPanel: false, // Relationship reverse-field
    capabilities: {
      filterable: true,
      sortable: false,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    relationship: {
      inverseResourceFieldId: 'ticket:parentTicket' as ResourceFieldId,
      relationshipType: 'has_many',
      isInverse: true,
    },
    description: 'All child tickets of this ticket',
  },

  dueDate: {
    id: toFieldId('dueDate'),
    key: 'dueDate',
    label: 'Due Date',
    type: BaseType.DATE,
    fieldType: FieldType.DATE,
    isSystem: true,
    systemAttribute: 'due_date',
    systemSortOrder: 'a7',
    dbColumn: 'dueDate',
    nullable: true,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: true,
      updatable: true,
      configurable: false,
    },
    placeholder: 'Select due date',
  },

  createdAt: {
    id: toFieldId('createdAt'),
    key: 'createdAt',
    label: 'Created',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'created_at',
    systemSortOrder: 'aC',
    dbColumn: 'createdAt',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Automatically set when ticket is created',
  },

  updatedAt: {
    id: toFieldId('updatedAt'),
    key: 'updatedAt',
    label: 'Updated',
    type: BaseType.DATETIME,
    fieldType: FieldType.DATETIME,
    isSystem: true,
    systemAttribute: 'updated_at',
    systemSortOrder: 'aD',
    dbColumn: 'updatedAt',
    nullable: false,
    capabilities: {
      filterable: true,
      sortable: true,
      creatable: false,
      updatable: false,
      configurable: false,
    },
    description: 'Automatically updated when ticket is modified',
  },

  createdBy: CREATED_BY_FIELD,
}
