// packages/lib/src/ai/providers/zai/zai-defaults.ts

import { FetchFrom, type ModelCapabilities, ModelType, type ProviderCapabilities } from '../types'

export const ZAI_CAPABILITIES: ProviderCapabilities = {
  id: 'zai',
  displayName: 'Z.AI',
  icon: 'zai',
  color: '#3859FF',
  supportedModelTypes: [ModelType.LLM],
  defaultModel: 'glm-5.2',
  requiresApiKey: true,
  toolFormat: 'openai',
  configurateMethods: ['predefined-model', 'customizable-model'],

  connectionVariables: [
    {
      key: 'apiKey',
      label: 'API Key',
      placeholder: 'Enter your Z.AI API Key',
      required: true,
      secret: true,
      description: 'Your API key from the Z.AI console',
      validation: {
        // z.ai keys are in `{id}.{secret}` format — permissive, just require the dot form.
        pattern: '^[A-Za-z0-9]+\\.[A-Za-z0-9]+$',
        message: 'API key must be in id.secret format',
      },
    },
  ],
  fieldMeta: {
    apiKey: { scope: 'both', priority: 'model-override' },
  },

  rateLimits: {
    requestsPerMinute: 60,
    tokensPerMinute: 10000,
    cacheTtl: 300,
  },
  description: 'GLM large language models by Z.AI (Zhipu AI)',
  documentationUrl: 'https://docs.z.ai/api-reference/introduction',
  setupInstructions:
    'Get your API key from the Z.AI console at https://z.ai/manage-apikey/apikey-list',
}

// GLM models accept the full standard parameter set — no fixed-parameter restrictions.
const ZAI_PARAMETER_RULES = [
  {
    name: 'temperature',
    type: 'float' as const,
    label: 'Temperature',
    help: 'Controls randomness in responses.',
    default: 0.7,
    min: 0,
    max: 2,
    precision: 2,
    required: false,
    template: 'temperature',
  },
  {
    name: 'topP',
    type: 'float' as const,
    label: 'Top P',
    help: 'Nucleus sampling threshold.',
    default: 0.9,
    min: 0,
    max: 1,
    precision: 2,
    required: false,
    template: 'top_p',
  },
  {
    name: 'presencePenalty',
    type: 'float' as const,
    label: 'Presence Penalty',
    help: 'Penalizes tokens that have already appeared.',
    default: 0,
    min: -2,
    max: 2,
    precision: 2,
    required: false,
    template: 'presence_penalty',
  },
  {
    name: 'maxOutputTokens',
    type: 'int' as const,
    label: 'Max Output Tokens',
    help: 'Maximum number of tokens to generate.',
    default: 8192,
    min: 1,
    max: 131072,
    precision: 0,
    required: false,
    template: 'max_tokens',
  },
]

// Vision models cap output at 16K tokens.
const ZAI_VISION_PARAMETER_RULES = [
  ...ZAI_PARAMETER_RULES.slice(0, 3),
  {
    name: 'maxOutputTokens',
    type: 'int' as const,
    label: 'Max Output Tokens',
    help: 'Maximum number of tokens to generate.',
    default: 8192,
    min: 1,
    max: 16384,
    precision: 0,
    required: false,
    template: 'max_tokens',
  },
]

export const ZAI_MODELS: Record<string, ModelCapabilities> = {
  'glm-5.2': {
    provider: 'zai',
    modelId: 'glm-5.2',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GLM-5.2',
    icon: 'zai',
    color: '#3859FF',
    contextLength: 1000000,
    maxTokens: 131072,
    modelType: ModelType.LLM,
    features: ['chat', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0014, output: 0.0044, cachedInput: 0.00026 },
    description:
      'Z.AI (Zhipu) flagship GLM-5.2: 1M context, agentic tool use, structured output, and built-in thinking (reasoning_effort configurable).',
    parameterRules: ZAI_PARAMETER_RULES,
  },
  'glm-5': {
    provider: 'zai',
    modelId: 'glm-5',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GLM-5',
    icon: 'zai',
    color: '#3859FF',
    contextLength: 1000000,
    maxTokens: 131072,
    modelType: ModelType.LLM,
    features: ['chat', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.001, output: 0.0032, cachedInput: 0.0002 },
    description:
      'Z.AI GLM-5: large-context reasoning and agentic model with tool calling, structured output, and built-in thinking.',
    parameterRules: ZAI_PARAMETER_RULES,
  },
  'glm-4.6': {
    provider: 'zai',
    modelId: 'glm-4.6',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GLM-4.6',
    icon: 'zai',
    color: '#3859FF',
    contextLength: 200000,
    maxTokens: 131072,
    modelType: ModelType.LLM,
    features: ['chat', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0006, output: 0.0022, cachedInput: 0.00011 },
    description:
      'Z.AI GLM-4.6: strong coding and agentic model with 200K context, tool calling, and thinking enabled by default.',
    parameterRules: ZAI_PARAMETER_RULES,
  },
  'glm-4.5': {
    provider: 'zai',
    modelId: 'glm-4.5',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GLM-4.5',
    icon: 'zai',
    color: '#3859FF',
    contextLength: 131072,
    maxTokens: 131072,
    modelType: ModelType.LLM,
    features: ['chat', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0006, output: 0.0022, cachedInput: 0.00011 },
    description:
      'Z.AI GLM-4.5: capable general-purpose model with 128K context, tool calling, structured output, and thinking.',
    parameterRules: ZAI_PARAMETER_RULES,
  },
  'glm-4.5-air': {
    provider: 'zai',
    modelId: 'glm-4.5-air',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GLM-4.5 Air',
    icon: 'zai',
    color: '#3859FF',
    contextLength: 131072,
    maxTokens: 131072,
    modelType: ModelType.LLM,
    features: ['chat', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0002, output: 0.0011, cachedInput: 0.00003 },
    description:
      'Z.AI GLM-4.5 Air: lightweight, cost-efficient model with 128K context, tool calling, and structured output.',
    parameterRules: ZAI_PARAMETER_RULES,
  },
  'glm-4.5-flash': {
    provider: 'zai',
    modelId: 'glm-4.5-flash',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GLM-4.5 Flash',
    icon: 'zai',
    color: '#3859FF',
    contextLength: 131072,
    maxTokens: 131072,
    modelType: ModelType.LLM,
    features: ['chat', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0, output: 0, cachedInput: 0 },
    description:
      'Z.AI GLM-4.5 Flash: free, fast model with 128K context, tool calling, and structured output.',
    parameterRules: ZAI_PARAMETER_RULES,
  },
  'glm-4.5v': {
    provider: 'zai',
    modelId: 'glm-4.5v',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GLM-4.5V',
    icon: 'zai',
    color: '#3859FF',
    contextLength: 65536,
    maxTokens: 16384,
    modelType: ModelType.LLM,
    features: ['chat', 'code', 'vision'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0006, output: 0.0018, cachedInput: 0.00011 },
    description:
      'Z.AI GLM-4.5V: multimodal model accepting image, video, and text input, with a thinking-mode switch.',
    parameterRules: ZAI_VISION_PARAMETER_RULES,
  },
  'glm-4.6v': {
    provider: 'zai',
    modelId: 'glm-4.6v',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GLM-4.6V',
    icon: 'zai',
    color: '#3859FF',
    contextLength: 65536,
    maxTokens: 16384,
    modelType: ModelType.LLM,
    features: ['chat', 'code', 'vision'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0003, output: 0.0009, cachedInput: 0.00005 },
    description:
      'Z.AI GLM-4.6V: cost-efficient multimodal model accepting image, video, and text input.',
    parameterRules: ZAI_VISION_PARAMETER_RULES,
  },
}
