// packages/lib/src/ai/providers/openai/openai-defaults.ts

import {
  FetchFrom,
  type ModelCapabilities,
  ModelType,
  // type ParameterRule,
  type ProviderCapabilities,
} from '../types'

export const OPENAI_CAPABILITIES: ProviderCapabilities = {
  id: 'openai',
  displayName: 'OpenAI',
  icon: 'openai',
  color: '#10A37F',
  supportedModelTypes: [ModelType.LLM, ModelType.TEXT_EMBEDDING, ModelType.TTS, ModelType.VISION],
  defaultModel: 'gpt-4o-mini',
  requiresApiKey: true,
  toolFormat: 'openai',
  configurateMethods: ['predefined-model', 'customizable-model'],

  // NEW: Unified credential schema with scope-based filtering
  credentialSchema: [
    {
      variable: 'openai_api_key',
      type: 'secret-input',
      label: 'API Key',
      placeholder: 'Enter your OpenAI API Key',
      required: true,
      scope: 'both', // Available for both provider and model config
      priority: 'model-override', // Model-level key overrides provider key
      helpText: 'Your OpenAI API key. Model-specific keys override provider keys.',
      validation: {
        pattern: '^sk-[a-zA-Z0-9\\-_]{10,}$',
        message: 'OpenAI API key must start with sk- followed by at least 10 characters',
      },
    },
    {
      variable: 'openai_organization',
      type: 'text-input',
      label: 'Organization ID',
      placeholder: 'Enter your Organization ID (optional)',
      required: false,
      scope: 'provider', // Only available at provider level
      helpText: 'Optional organization ID for enterprise accounts',
    },
    {
      variable: 'openai_api_base',
      type: 'text-input',
      label: 'API Base URL',
      placeholder: 'https://api.openai.com/v1',
      required: false,
      default: 'https://api.openai.com/v1',
      scope: 'both', // Can be overridden per model for custom endpoints
      priority: 'model-override',
      helpText: 'API base URL. Use custom URLs for OpenAI-compatible endpoints.',
    },
    {
      variable: 'custom_model_name',
      type: 'text-input',
      label: 'Custom Model Name',
      placeholder: 'gpt-4-custom',
      required: false,
      scope: 'model', // Only available for model-specific configuration
      helpText: 'Override the model name sent to the API endpoint',
    },
  ],

  rateLimits: {
    requestsPerMinute: 500,
    tokensPerMinute: 10000,
    cacheTtl: 300, // 5 minutes
  },
  description: 'Leading AI research company with GPT models',
  documentationUrl: 'https://platform.openai.com/docs/api-reference',
  setupInstructions:
    'Get your API key from the OpenAI dashboard at https://platform.openai.com/api-keys',
}

export const OPENAI_MODELS: Record<string, ModelCapabilities> = {
  'gpt-4-turbo': {
    provider: 'openai',
    modelId: 'gpt-4-turbo',
    displayName: 'GPT-4 Turbo',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.01, output: 0.03 },
    description: 'High-performance GPT-4 with vision capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'gpt-5-chat-latest': {
    provider: 'openai',
    modelId: 'gpt-5-chat-latest',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-5 Chat (Latest)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 16384,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools', 'audio'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.01, output: 0.04 },
    description: 'Latest GPT-5 model optimized for chat with advanced reasoning',
    parameterRules: [
      {
        name: 'reasoning_effort',
        type: 'string',
        label: 'Reasoning Effort',
        help: 'Controls how much reasoning the model performs',
        default: 'medium',
        required: false,
        template: 'reasoning_effort',
        options: ['minimal', 'low', 'medium', 'high'],
      },
      {
        name: 'verbosity',
        type: 'string',
        label: 'Verbosity',
        help: 'Controls output length and detail',
        default: 'medium',
        required: false,
        template: 'verbosity',
        options: ['medium'],
      },
      {
        name: 'max_completion_tokens',
        type: 'int',
        label: 'Max Completion Tokens',
        help: 'Maximum number of tokens to generate',
        default: 8192,
        min: 1,
        max: 128000,
        precision: 0,
        required: false,
        template: 'max_completion_tokens',
      },
    ],
    parameterRestrictions: {
      unsupportedParams: [
        'presence_penalty',
        'frequency_penalty',
        'logprobs',
        'top_logprobs',
        'logit_bias',
        'temperature',
        'top_p',
      ],
      defaultOnlyParams: {},
      parameterMapping: {
        max_tokens: 'max_completion_tokens',
      },
      supportedParams: ['reasoning_effort', 'verbosity', 'max_completion_tokens'],
      isReasoningModel: true,
    },
  },
  'gpt-5': {
    provider: 'openai',
    modelId: 'gpt-5',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-5',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 16384,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools', 'audio'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.01, output: 0.04 },
    description: 'GPT-5 base model with enhanced reasoning and multimodal capabilities',
    parameterRules: [
      {
        name: 'reasoning_effort',
        type: 'string',
        label: 'Reasoning Effort',
        help: 'Controls how much reasoning the model performs',
        default: 'medium',
        required: false,
        template: 'reasoning_effort',
        options: ['minimal', 'low', 'medium', 'high'],
      },
      {
        name: 'verbosity',
        type: 'string',
        label: 'Verbosity',
        help: 'Controls output length and detail',
        default: 'medium',
        required: false,
        template: 'verbosity',
        options: ['low', 'medium', 'high'],
      },
      {
        name: 'max_completion_tokens',
        type: 'int',
        label: 'Max Completion Tokens',
        help: 'Maximum number of tokens to generate',
        default: 8192,
        min: 1,
        max: 128000,
        precision: 0,
        required: false,
        template: 'max_completion_tokens',
      },
    ],
    parameterRestrictions: {
      unsupportedParams: [
        'presence_penalty',
        'frequency_penalty',
        'logprobs',
        'top_logprobs',
        'logit_bias',
        'temperature',
        'top_p',
      ],
      defaultOnlyParams: {},
      parameterMapping: {
        max_tokens: 'max_completion_tokens',
      },
      supportedParams: ['reasoning_effort', 'verbosity', 'max_completion_tokens'],
      isReasoningModel: true,
    },
  },
  'gpt-5.2-chat-latest': {
    provider: 'openai',
    modelId: 'gpt-5.2-chat-latest',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-5.2 Chat (Latest)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 400000,
    maxTokens: 128000,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools', 'audio'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.01, output: 0.04 },
    description: 'Latest GPT-5.2 chat alias for broad capability and reasoning',
    parameterRules: [
      {
        name: 'reasoning_effort',
        type: 'string',
        label: 'Reasoning Effort',
        help: 'Controls how much reasoning the model performs',
        default: 'medium',
        required: false,
        template: 'reasoning_effort',
        options: ['none', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        name: 'verbosity',
        type: 'string',
        label: 'Verbosity',
        help: 'Controls output length and detail',
        default: 'medium',
        required: false,
        template: 'verbosity',
        options: ['low', 'medium', 'high'],
      },
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness for compatible effort modes.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls nucleus sampling for compatible effort modes.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'logprobs',
        type: 'int',
        label: 'Logprobs',
        help: 'Returns token log probabilities for compatible effort modes.',
        default: 0,
        min: 0,
        max: 20,
        precision: 0,
        required: false,
        template: 'logprobs',
      },
      {
        name: 'top_logprobs',
        type: 'int',
        label: 'Top Logprobs',
        help: 'Number of most likely tokens to return logprobs for.',
        default: 0,
        min: 0,
        max: 20,
        precision: 0,
        required: false,
        template: 'top_logprobs',
      },
      {
        name: 'max_completion_tokens',
        type: 'int',
        label: 'Max Completion Tokens',
        help: 'Maximum number of tokens to generate',
        default: 8192,
        min: 1,
        max: 128000,
        precision: 0,
        required: false,
        template: 'max_completion_tokens',
      },
    ],
    parameterRestrictions: {
      unsupportedParams: ['presence_penalty', 'frequency_penalty', 'logit_bias'],
      defaultOnlyParams: {},
      parameterMapping: {
        max_tokens: 'max_completion_tokens',
      },
      isReasoningModel: true,
    },
  },
  'gpt-5.2': {
    provider: 'openai',
    modelId: 'gpt-5.2',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-5.2',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 400000,
    maxTokens: 128000,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools', 'audio'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.01, output: 0.04 },
    description: 'GPT-5.2 general-purpose model with updated reasoning controls',
    parameterRules: [
      {
        name: 'reasoning_effort',
        type: 'string',
        label: 'Reasoning Effort',
        help: 'Controls how much reasoning the model performs',
        default: 'medium',
        required: false,
        template: 'reasoning_effort',
        options: ['none', 'low', 'medium', 'high', 'xhigh'],
      },
      {
        name: 'verbosity',
        type: 'string',
        label: 'Verbosity',
        help: 'Controls output length and detail',
        default: 'medium',
        required: false,
        template: 'verbosity',
        options: ['low', 'medium', 'high'],
      },
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness for compatible effort modes.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls nucleus sampling for compatible effort modes.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'logprobs',
        type: 'int',
        label: 'Logprobs',
        help: 'Returns token log probabilities for compatible effort modes.',
        default: 0,
        min: 0,
        max: 20,
        precision: 0,
        required: false,
        template: 'logprobs',
      },
      {
        name: 'top_logprobs',
        type: 'int',
        label: 'Top Logprobs',
        help: 'Number of most likely tokens to return logprobs for.',
        default: 0,
        min: 0,
        max: 20,
        precision: 0,
        required: false,
        template: 'top_logprobs',
      },
      {
        name: 'max_completion_tokens',
        type: 'int',
        label: 'Max Completion Tokens',
        help: 'Maximum number of tokens to generate',
        default: 8192,
        min: 1,
        max: 128000,
        precision: 0,
        required: false,
        template: 'max_completion_tokens',
      },
    ],
    parameterRestrictions: {
      unsupportedParams: ['presence_penalty', 'frequency_penalty', 'logit_bias'],
      defaultOnlyParams: {},
      parameterMapping: {
        max_tokens: 'max_completion_tokens',
      },
      isReasoningModel: true,
    },
  },
  'gpt-5.1': {
    provider: 'openai',
    modelId: 'gpt-5.1',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-5.1',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 400000,
    maxTokens: 128000,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools', 'audio'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.01, output: 0.04 },
    description: 'GPT-5.1 model for compatibility with previous GPT-5 configurations',
    parameterRules: [
      {
        name: 'reasoning_effort',
        type: 'string',
        label: 'Reasoning Effort',
        help: 'Controls how much reasoning the model performs',
        default: 'medium',
        required: false,
        template: 'reasoning_effort',
        options: ['none', 'low', 'medium', 'high'],
      },
      {
        name: 'verbosity',
        type: 'string',
        label: 'Verbosity',
        help: 'Controls output length and detail',
        default: 'medium',
        required: false,
        template: 'verbosity',
        options: ['low', 'medium', 'high'],
      },
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness for compatible effort modes.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls nucleus sampling for compatible effort modes.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'logprobs',
        type: 'int',
        label: 'Logprobs',
        help: 'Returns token log probabilities for compatible effort modes.',
        default: 0,
        min: 0,
        max: 20,
        precision: 0,
        required: false,
        template: 'logprobs',
      },
      {
        name: 'top_logprobs',
        type: 'int',
        label: 'Top Logprobs',
        help: 'Number of most likely tokens to return logprobs for.',
        default: 0,
        min: 0,
        max: 20,
        precision: 0,
        required: false,
        template: 'top_logprobs',
      },
      {
        name: 'max_completion_tokens',
        type: 'int',
        label: 'Max Completion Tokens',
        help: 'Maximum number of tokens to generate',
        default: 8192,
        min: 1,
        max: 128000,
        precision: 0,
        required: false,
        template: 'max_completion_tokens',
      },
    ],
    parameterRestrictions: {
      unsupportedParams: ['presence_penalty', 'frequency_penalty', 'logit_bias'],
      defaultOnlyParams: {},
      parameterMapping: {
        max_tokens: 'max_completion_tokens',
      },
      isReasoningModel: true,
    },
  },
  'gpt-5-mini': {
    provider: 'openai',
    modelId: 'gpt-5-mini',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-5 Mini',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.002, output: 0.008 },
    description: 'Efficient GPT-5 mini model with core capabilities',
    parameterRules: [
      {
        name: 'reasoning_effort',
        type: 'string',
        label: 'Reasoning Effort',
        help: 'Controls how much reasoning the model performs',
        default: 'medium',
        required: false,
        template: 'reasoning_effort',
        options: ['minimal', 'low', 'medium', 'high'],
      },
      {
        name: 'verbosity',
        type: 'string',
        label: 'Verbosity',
        help: 'Controls output length and detail',
        default: 'medium',
        required: false,
        template: 'verbosity',
        options: ['low', 'medium', 'high'],
      },
      {
        name: 'max_completion_tokens',
        type: 'int',
        label: 'Max Completion Tokens',
        help: 'Maximum number of tokens to generate',
        default: 4096,
        min: 1,
        max: 64000,
        precision: 0,
        required: false,
        template: 'max_completion_tokens',
      },
    ],
    parameterRestrictions: {
      unsupportedParams: [
        'presence_penalty',
        'frequency_penalty',
        'logprobs',
        'top_logprobs',
        'logit_bias',
        'temperature',
        'top_p',
      ],
      defaultOnlyParams: {},
      parameterMapping: {
        max_tokens: 'max_completion_tokens',
      },
      supportedParams: ['reasoning_effort', 'verbosity', 'max_completion_tokens'],
      isReasoningModel: true,
    },
  },
  'gpt-5-mini-2025-08-07': {
    provider: 'openai',
    modelId: 'gpt-5-mini-2025-08-07',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-5 Mini (2025-08-07)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.002, output: 0.008 },
    description: 'GPT-5 Mini snapshot from August 7, 2025',
    parameterRules: [
      {
        name: 'reasoning_effort',
        type: 'string',
        label: 'Reasoning Effort',
        help: 'Controls how much reasoning the model performs',
        default: 'medium',
        required: false,
        template: 'reasoning_effort',
        options: ['minimal', 'low', 'medium', 'high'],
      },
      {
        name: 'verbosity',
        type: 'string',
        label: 'Verbosity',
        help: 'Controls output length and detail',
        default: 'medium',
        required: false,
        template: 'verbosity',
        options: ['low', 'medium', 'high'],
      },
      {
        name: 'max_completion_tokens',
        type: 'int',
        label: 'Max Completion Tokens',
        help: 'Maximum number of tokens to generate',
        default: 4096,
        min: 1,
        max: 64000,
        precision: 0,
        required: false,
        template: 'max_completion_tokens',
      },
    ],
    parameterRestrictions: {
      unsupportedParams: [
        'presence_penalty',
        'frequency_penalty',
        'logprobs',
        'top_logprobs',
        'logit_bias',
        'temperature',
        'top_p',
      ],
      defaultOnlyParams: {},
      parameterMapping: {
        max_tokens: 'max_completion_tokens',
      },
      supportedParams: ['reasoning_effort', 'verbosity', 'max_completion_tokens'],
      isReasoningModel: true,
    },
  },
  'gpt-5-nano': {
    provider: 'openai',
    modelId: 'gpt-5-nano',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-5 Nano',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.0005, output: 0.002 },
    description: 'Ultra-efficient GPT-5 nano model for simple tasks',
    parameterRules: [
      {
        name: 'reasoning_effort',
        type: 'string',
        label: 'Reasoning Effort',
        help: 'Controls how much reasoning the model performs',
        default: 'medium',
        required: false,
        template: 'reasoning_effort',
        options: ['minimal', 'low', 'medium', 'high'],
      },
      {
        name: 'verbosity',
        type: 'string',
        label: 'Verbosity',
        help: 'Controls output length and detail',
        default: 'medium',
        required: false,
        template: 'verbosity',
        options: ['low', 'medium', 'high'],
      },
      {
        name: 'max_completion_tokens',
        type: 'int',
        label: 'Max Completion Tokens',
        help: 'Maximum number of tokens to generate',
        default: 2048,
        min: 1,
        max: 32000,
        precision: 0,
        required: false,
        template: 'max_completion_tokens',
      },
    ],
    parameterRestrictions: {
      unsupportedParams: [
        'presence_penalty',
        'frequency_penalty',
        'logprobs',
        'top_logprobs',
        'logit_bias',
        'temperature',
        'top_p',
      ],
      defaultOnlyParams: {},
      parameterMapping: {
        max_tokens: 'max_completion_tokens',
      },
      supportedParams: ['reasoning_effort', 'verbosity', 'max_completion_tokens'],
      isReasoningModel: true,
    },
  },
  'gpt-5-nano-2025-08-07': {
    provider: 'openai',
    modelId: 'gpt-5-nano-2025-08-07',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-5 Nano (2025-08-07)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.0005, output: 0.002 },
    description: 'GPT-5 Nano snapshot from August 7, 2025',
    parameterRules: [
      {
        name: 'reasoning_effort',
        type: 'string',
        label: 'Reasoning Effort',
        help: 'Controls how much reasoning the model performs',
        default: 'medium',
        required: false,
        template: 'reasoning_effort',
        options: ['minimal', 'low', 'medium', 'high'],
      },
      {
        name: 'verbosity',
        type: 'string',
        label: 'Verbosity',
        help: 'Controls output length and detail',
        default: 'medium',
        required: false,
        template: 'verbosity',
        options: ['low', 'medium', 'high'],
      },
      {
        name: 'max_completion_tokens',
        type: 'int',
        label: 'Max Completion Tokens',
        help: 'Maximum number of tokens to generate',
        default: 2048,
        min: 1,
        max: 32000,
        precision: 0,
        required: false,
        template: 'max_completion_tokens',
      },
    ],
    parameterRestrictions: {
      unsupportedParams: [
        'presence_penalty',
        'frequency_penalty',
        'logprobs',
        'top_logprobs',
        'logit_bias',
        'temperature',
        'top_p',
      ],
      defaultOnlyParams: {},
      parameterMapping: {
        max_tokens: 'max_completion_tokens',
      },
      supportedParams: ['reasoning_effort', 'verbosity', 'max_completion_tokens'],
      isReasoningModel: true,
    },
  },
  'gpt-4.1': {
    provider: 'openai',
    modelId: 'gpt-4.1',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4.1',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.005, output: 0.015 },
    description: 'GPT-4.1 with enhanced capabilities and improved efficiency',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'response_format',
        type: 'string',
        label: 'Response Format',
        help: 'Specifying the format that the model must output',
        default: 'text',
        required: false,
        template: 'response_format',
        options: ['text', 'json_object'],
      },
    ],
  },
  'gpt-4.1-2025-04-14': {
    provider: 'openai',
    modelId: 'gpt-4.1-2025-04-14',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4.1 (2025-04-14)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.005, output: 0.015 },
    description: 'GPT-4.1 snapshot from April 14, 2025',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'response_format',
        type: 'string',
        label: 'Response Format',
        help: 'Specifying the format that the model must output',
        default: 'text',
        required: false,
        template: 'response_format',
        options: ['text', 'json_object'],
      },
    ],
  },
  'gpt-4.1-mini': {
    provider: 'openai',
    modelId: 'gpt-4.1-mini',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4.1 Mini',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.001, output: 0.004 },
    description: 'Efficient GPT-4.1 mini model',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 2048,
        min: 1,
        max: 4096,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'gpt-4.1-mini-2025-04-14': {
    provider: 'openai',
    modelId: 'gpt-4.1-mini-2025-04-14',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4.1 Mini (2025-04-14)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.001, output: 0.004 },
    description: 'GPT-4.1 Mini snapshot from April 14, 2025',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 2048,
        min: 1,
        max: 4096,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'gpt-4.1-nano': {
    provider: 'openai',
    modelId: 'gpt-4.1-nano',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4.1 Nano',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 64000,
    maxTokens: 2048,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.0003, output: 0.0012 },
    description: 'Ultra-efficient GPT-4.1 nano model',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 1024,
        min: 1,
        max: 2048,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'gpt-4.1-nano-2025-04-14': {
    provider: 'openai',
    modelId: 'gpt-4.1-nano-2025-04-14',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4.1 Nano (2025-04-14)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 64000,
    maxTokens: 2048,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.0003, output: 0.0012 },
    description: 'GPT-4.1 Nano snapshot from April 14, 2025',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 1024,
        min: 1,
        max: 2048,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'chatgpt-4o-latest': {
    provider: 'openai',
    modelId: 'chatgpt-4o-latest',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'ChatGPT-4o Latest',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'vision'], // Removed 'tools' from features
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: false, // Updated to false - this model doesn't support tools
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.0025, output: 0.01 },
    description: 'Latest ChatGPT-4o model with optimized chat performance',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'response_format',
        type: 'string',
        label: 'Response Format',
        help: 'Specifying the format that the model must output',
        default: 'text',
        required: false,
        template: 'response_format',
        options: ['text', 'json_object'],
      },
    ],
  },
  'gpt-4o': {
    provider: 'openai',
    modelId: 'gpt-4o',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4o',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.0025, output: 0.01 },
    description: 'Most advanced GPT-4 model with vision and structured output support',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions. As the temperature approaches zero, the model will become deterministic and repetitive. Higher temperature results in more random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling: 0.5 means half of all likelihood-weighted options are considered.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'presence_penalty',
        type: 'float',
        label: 'Presence Penalty',
        help: 'Applies a penalty to the log-probability of tokens already in the text.',
        default: 0,
        min: -2,
        max: 2,
        precision: 2,
        required: false,
        template: 'presence_penalty',
      },
      {
        name: 'frequency_penalty',
        type: 'float',
        label: 'Frequency Penalty',
        help: 'Applies a penalty to the log-probability of tokens that appear in the text.',
        default: 0,
        min: -2,
        max: 2,
        precision: 2,
        required: false,
        template: 'frequency_penalty',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Specifies the upper limit on the length of generated results. If the generated results are truncated, you can increase this parameter.',
        default: 4096,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'response_format',
        type: 'string',
        label: 'Response Format',
        help: 'Specifying the format that the model must output',
        default: 'text',
        required: false,
        template: 'response_format',
        options: ['text', 'json_object'],
      },
    ],
  },
  'gpt-4o-mini': {
    provider: 'openai',
    modelId: 'gpt-4o-mini',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4o Mini',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.00015, output: 0.0006 },
    description: 'Cost-effective GPT-4 model with full feature support',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'gpt-4o-2024-05-13': {
    provider: 'openai',
    modelId: 'gpt-4o-2024-05-13',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4o (2024-05-13)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.0025, output: 0.01 },
    description: 'GPT-4o snapshot from May 13, 2024',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'response_format',
        type: 'string',
        label: 'Response Format',
        help: 'Specifying the format that the model must output',
        default: 'text',
        required: false,
        template: 'response_format',
        options: ['text', 'json_object'],
      },
    ],
  },
  'gpt-4o-2024-08-06': {
    provider: 'openai',
    modelId: 'gpt-4o-2024-08-06',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4o (2024-08-06)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.0025, output: 0.01 },
    description: 'GPT-4o snapshot from August 6, 2024',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'response_format',
        type: 'string',
        label: 'Response Format',
        help: 'Specifying the format that the model must output',
        default: 'text',
        required: false,
        template: 'response_format',
        options: ['text', 'json_object'],
      },
    ],
  },
  'gpt-4o-2024-11-20': {
    provider: 'openai',
    modelId: 'gpt-4o-2024-11-20',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4o (2024-11-20)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.0025, output: 0.01 },
    description: 'GPT-4o snapshot from November 20, 2024',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
      {
        name: 'response_format',
        type: 'string',
        label: 'Response Format',
        help: 'Specifying the format that the model must output',
        default: 'text',
        required: false,
        template: 'response_format',
        options: ['text', 'json_object'],
      },
    ],
  },
  'gpt-4o-audio-preview': {
    provider: 'openai',
    modelId: 'gpt-4o-audio-preview',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4o Audio Preview',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools', 'audio'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.0025, output: 0.01 },
    description: 'GPT-4o with audio input and output capabilities (preview)',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'gpt-4o-audio-preview-2025-06-03': {
    provider: 'openai',
    modelId: 'gpt-4o-audio-preview-2025-06-03',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4o Audio Preview (2025-06-03)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools', 'audio'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.0025, output: 0.01 },
    description: 'GPT-4o Audio Preview snapshot from June 3, 2025',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'gpt-4o-mini-2024-07-18': {
    provider: 'openai',
    modelId: 'gpt-4o-mini-2024-07-18',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4o Mini (2024-07-18)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.00015, output: 0.0006 },
    description: 'GPT-4o Mini snapshot from July 18, 2024',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'o4-mini': {
    provider: 'openai',
    modelId: 'o4-mini',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O4 Mini',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.001, output: 0.004 },
    description: 'O4 Mini model with enhanced reasoning capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'o4-mini-2025-04-16': {
    provider: 'openai',
    modelId: 'o4-mini-2025-04-16',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O4 Mini (2025-04-16)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.001, output: 0.004 },
    description: 'O4 Mini snapshot from April 16, 2025',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  o3: {
    provider: 'openai',
    modelId: 'o3',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O3',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 16384,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.01, output: 0.04 },
    description: 'O3 model with advanced reasoning capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 8192,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'o3-2025-04-16': {
    provider: 'openai',
    modelId: 'o3-2025-04-16',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O3 (2025-04-16)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 16384,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.01, output: 0.04 },
    description: 'O3 snapshot from April 16, 2025',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 8192,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'o3-mini': {
    provider: 'openai',
    modelId: 'o3-mini',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O3 Mini',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.002, output: 0.008 },
    description: 'O3 Mini model with efficient reasoning',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'o3-mini-2025-01-31': {
    provider: 'openai',
    modelId: 'o3-mini-2025-01-31',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O3 Mini (2025-01-31)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 8192,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.002, output: 0.008 },
    description: 'O3 Mini snapshot from January 31, 2025',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 4096,
        min: 1,
        max: 8192,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'o3-pro': {
    provider: 'openai',
    modelId: 'o3-pro',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O3 Pro',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 32768,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: false,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.02, output: 0.08 },
    description: 'O3 Pro model with maximum reasoning capabilities',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 16384,
        min: 1,
        max: 32768,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'o3-pro-2025-06-10': {
    provider: 'openai',
    modelId: 'o3-pro-2025-06-10',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O3 Pro (2025-06-10)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 200000,
    maxTokens: 32768,
    modelType: ModelType.LLM,
    features: ['chat', 'vision', 'tools'],
    supports: {
      streaming: false,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
    },
    costPer1kTokens: { input: 0.02, output: 0.08 },
    description: 'O3 Pro snapshot from June 10, 2025',
    parameterRules: [
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Controls randomness. Lower temperature results in less random completions.',
        default: 1,
        min: 0,
        max: 2,
        precision: 2,
        required: false,
        template: 'temperature',
      },
      {
        name: 'top_p',
        type: 'float',
        label: 'Top P',
        help: 'Controls diversity via nucleus sampling.',
        default: 1,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'top_p',
      },
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 16384,
        min: 1,
        max: 32768,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  o1: {
    provider: 'openai',
    modelId: 'o1',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O1',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 32768,
    modelType: ModelType.LLM,

    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.015, output: 0.06 },
    description: 'O1 reasoning model for complex problem solving',
    parameterRules: [
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 16384,
        min: 1,
        max: 32768,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'o1-mini': {
    provider: 'openai',
    modelId: 'o1-mini',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O1 Mini',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 16384,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.003, output: 0.012 },
    description: 'O1 Mini reasoning model for efficient problem solving',
    parameterRules: [
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 8192,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'o1-mini-2024-09-12': {
    provider: 'openai',
    modelId: 'o1-mini-2024-09-12',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O1 Mini (2024-09-12)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 16384,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: true,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.003, output: 0.012 },
    description: 'O1 Mini snapshot from September 12, 2024',
    parameterRules: [
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 8192,
        min: 1,
        max: 16384,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'o1-preview': {
    provider: 'openai',
    modelId: 'o1-preview',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O1 Preview',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 32768,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: true,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.015, output: 0.06 },
    description: 'O1 Preview reasoning model (preview version)',
    parameterRules: [
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 16384,
        min: 1,
        max: 32768,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'o1-preview-2024-09-12': {
    provider: 'openai',
    modelId: 'o1-preview-2024-09-12',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'O1 Preview (2024-09-12)',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 32768,
    modelType: ModelType.LLM,
    features: ['chat', 'tools'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: true,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.015, output: 0.06 },
    description: 'O1 Preview snapshot from September 12, 2024',
    parameterRules: [
      {
        name: 'max_tokens',
        type: 'int',
        label: 'Max Tokens',
        help: 'Maximum number of tokens to generate.',
        default: 16384,
        min: 1,
        max: 32768,
        precision: 0,
        required: false,
        template: 'max_tokens',
      },
    ],
  },
  'text-moderation-stable': {
    provider: 'openai',
    modelId: 'text-moderation-stable',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Text Moderation Stable',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 32768,
    maxTokens: 1,
    modelType: ModelType.MODERATION,
    features: ['moderation'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.0002, output: 0 },
    description: 'Text moderation model for content filtering',
    parameterRules: [],
  },
  'gpt-4o-mini-transcribe': {
    provider: 'openai',
    modelId: 'gpt-4o-mini-transcribe',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4o Mini Transcribe',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.SPEECH2TEXT,
    features: ['speech2text'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00015, output: 0 },
    description: 'GPT-4o Mini optimized for speech transcription',
    parameterRules: [],
  },
  'gpt-4o-transcribe': {
    provider: 'openai',
    modelId: 'gpt-4o-transcribe',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4o Transcribe',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 128000,
    maxTokens: 4096,
    modelType: ModelType.SPEECH2TEXT,
    features: ['speech2text'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.0025, output: 0 },
    description: 'GPT-4o optimized for speech transcription',
    parameterRules: [],
  },
  'whisper-1': {
    provider: 'openai',
    modelId: 'whisper-1',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Whisper-1',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 25000000,
    maxTokens: 448,
    modelType: ModelType.SPEECH2TEXT,
    features: ['speech2text'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.006, output: 0 },
    description: 'Whisper speech recognition model',
    parameterRules: [
      {
        name: 'language',
        type: 'string',
        label: 'Language',
        help: 'Language of the input audio in ISO-639-1 format',
        default: '',
        required: false,
        template: 'language',
      },
      {
        name: 'prompt',
        type: 'string',
        label: 'Prompt',
        help: "Optional text to guide the model's style or continue a previous audio segment",
        default: '',
        required: false,
        template: 'prompt',
      },
      {
        name: 'response_format',
        type: 'string',
        label: 'Response Format',
        help: 'Format of the transcript output',
        default: 'json',
        required: false,
        template: 'response_format',
        options: ['json', 'text', 'srt', 'verbose_json', 'vtt'],
      },
      {
        name: 'temperature',
        type: 'float',
        label: 'Temperature',
        help: 'Sampling temperature between 0 and 1',
        default: 0,
        min: 0,
        max: 1,
        precision: 2,
        required: false,
        template: 'temperature',
      },
    ],
  },
  'text-embedding-3-large': {
    provider: 'openai',
    modelId: 'text-embedding-3-large',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Text Embedding 3 Large',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 8192,
    maxTokens: 3072,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00013, output: 0 },
    description: 'Large text embedding model with configurable dimensions',
    parameterRules: [
      {
        name: 'dimensions',
        type: 'int',
        label: 'Dimensions',
        help: 'Number of dimensions for the embedding vector. Smaller dimensions reduce storage but may decrease accuracy.',
        default: 3072,
        required: false,
        template: 'dimensions',
        options: ['256', '512', '1024', '1536', '3072'],
      },
    ],
  },
  'text-embedding-3-small': {
    provider: 'openai',
    modelId: 'text-embedding-3-small',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Text Embedding 3 Small',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 8192,
    maxTokens: 1536,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00002, output: 0 },
    description: 'Small text embedding model with configurable dimensions',
    parameterRules: [
      {
        name: 'dimensions',
        type: 'int',
        label: 'Dimensions',
        help: 'Number of dimensions for the embedding vector. Smaller dimensions reduce storage but may decrease accuracy.',
        default: 1536,
        required: false,
        template: 'dimensions',
        options: ['256', '512', '1536'],
      },
    ],
  },
  'text-embedding-ada-002': {
    provider: 'openai',
    modelId: 'text-embedding-ada-002',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Text Embedding Ada 002',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 8192,
    maxTokens: 1536,
    modelType: ModelType.TEXT_EMBEDDING,
    features: ['text-embedding'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.0001, output: 0 },
    description: 'Legacy text embedding model with 1536 dimensions',
    parameterRules: [],
  },
  'gpt-4o-mini-tts': {
    provider: 'openai',
    modelId: 'gpt-4o-mini-tts',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'GPT-4o Mini TTS',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 4096,
    maxTokens: 4096,
    modelType: ModelType.TTS,
    features: ['tts'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.00015, output: 0 },
    description: 'GPT-4o Mini optimized for text-to-speech synthesis',
    parameterRules: [
      {
        name: 'voice',
        type: 'string',
        label: 'Voice',
        help: 'Voice to use for text-to-speech',
        default: 'alloy',
        required: false,
        template: 'voice',
        options: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer'],
      },
      {
        name: 'response_format',
        type: 'string',
        label: 'Response Format',
        help: 'Audio format for the output',
        default: 'mp3',
        required: false,
        template: 'response_format',
        options: ['mp3', 'opus', 'aac', 'flac', 'wav', 'pcm'],
      },
      {
        name: 'speed',
        type: 'float',
        label: 'Speed',
        help: 'Playback speed of the audio',
        default: 1.0,
        min: 0.25,
        max: 4.0,
        precision: 2,
        required: false,
        template: 'speed',
      },
    ],
  },
  'tts-1-hd': {
    provider: 'openai',
    modelId: 'tts-1-hd',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'TTS-1 HD',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 4096,
    maxTokens: 4096,
    modelType: ModelType.TTS,
    features: ['tts'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.03, output: 0 },
    description: 'High-definition text-to-speech model',
    parameterRules: [
      {
        name: 'voice',
        type: 'string',
        label: 'Voice',
        help: 'Voice to use for text-to-speech',
        default: 'alloy',
        required: false,
        template: 'voice',
        options: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer'],
      },
      {
        name: 'response_format',
        type: 'string',
        label: 'Response Format',
        help: 'Audio format for the output',
        default: 'mp3',
        required: false,
        template: 'response_format',
        options: ['mp3', 'opus', 'aac', 'flac', 'wav', 'pcm'],
      },
      {
        name: 'speed',
        type: 'float',
        label: 'Speed',
        help: 'Playback speed of the audio',
        default: 1.0,
        min: 0.25,
        max: 4.0,
        precision: 2,
        required: false,
        template: 'speed',
      },
    ],
  },
  'tts-1': {
    provider: 'openai',
    modelId: 'tts-1',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'TTS-1',
    icon: 'openai',
    color: '#10A37F',
    contextLength: 4096,
    maxTokens: 4096,
    modelType: ModelType.TTS,
    features: ['tts'],
    supports: {
      streaming: false,
      structured: false,
      vision: false,
      toolCalling: false,
      systemMessages: false,
    },
    costPer1kTokens: { input: 0.015, output: 0 },
    description: 'Standard text-to-speech model',
    parameterRules: [
      {
        name: 'voice',
        type: 'string',
        label: 'Voice',
        help: 'Voice to use for text-to-speech',
        default: 'alloy',
        required: false,
        template: 'voice',
        options: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer'],
      },
      {
        name: 'response_format',
        type: 'string',
        label: 'Response Format',
        help: 'Audio format for the output',
        default: 'mp3',
        required: false,
        template: 'response_format',
        options: ['mp3', 'opus', 'aac', 'flac', 'wav', 'pcm'],
      },
      {
        name: 'speed',
        type: 'float',
        label: 'Speed',
        help: 'Playback speed of the audio',
        default: 1.0,
        min: 0.25,
        max: 4.0,
        precision: 2,
        required: false,
        template: 'speed',
      },
    ],
  },
}
