// packages/lib/src/ai/providers/kimi/kimi-defaults.ts

import { FetchFrom, type ModelCapabilities, ModelType, type ProviderCapabilities } from '../types'

export const KIMI_CAPABILITIES: ProviderCapabilities = {
  id: 'kimi',
  displayName: 'Kimi',
  icon: 'kimi',
  color: '#027AFF',
  supportedModelTypes: [ModelType.LLM],
  defaultModel: 'kimi-k2.5',
  requiresApiKey: true,
  toolFormat: 'openai',
  configurateMethods: ['predefined-model', 'customizable-model'],

  credentialSchema: [
    {
      variable: 'kimi_api_key',
      type: 'secret-input',
      label: 'API Key',
      placeholder: 'Enter your Moonshot API Key',
      required: true,
      scope: 'both',
      priority: 'model-override',
      helpText: 'Your API key from the Kimi API Platform console',
      validation: {
        pattern: '^sk-[a-zA-Z0-9\\-_]{10,}$',
        message: 'API key must start with sk-',
      },
    },
  ],

  rateLimits: {
    requestsPerMinute: 60,
    tokensPerMinute: 10000,
    cacheTtl: 300,
  },
  description: 'Large language models by Moonshot AI',
  documentationUrl: 'https://platform.moonshot.ai/docs/overview',
  setupInstructions:
    'Get your API key from the Kimi API Platform at https://platform.moonshot.ai/console/api-keys',
}

const KIMI_PARAMETER_RULES = [
  {
    name: 'temperature',
    type: 'float' as const,
    label: 'Temperature',
    help: 'Controls randomness in responses.',
    default: 0.7,
    min: 0,
    max: 2,
    precision: 2,
    required: false,
    template: 'temperature',
  },
  {
    name: 'topP',
    type: 'float' as const,
    label: 'Top P',
    help: 'Nucleus sampling threshold.',
    default: 0.7,
    min: 0,
    max: 1,
    precision: 2,
    required: false,
    template: 'top_p',
  },
  {
    name: 'presencePenalty',
    type: 'float' as const,
    label: 'Presence Penalty',
    help: 'Penalizes tokens that have already appeared.',
    default: 0,
    min: -2,
    max: 2,
    precision: 2,
    required: false,
    template: 'presence_penalty',
  },
  {
    name: 'maxOutputTokens',
    type: 'int' as const,
    label: 'Max Output Tokens',
    help: 'Maximum number of tokens to generate.',
    default: 8192,
    min: 1,
    max: 65536,
    precision: 0,
    required: false,
    template: 'max_tokens',
  },
]

const KIMI_RESTRICTED_PARAMETER_RULES = [
  {
    name: 'maxOutputTokens',
    type: 'int' as const,
    label: 'Max Output Tokens',
    help: 'Maximum number of tokens to generate.',
    default: 8192,
    min: 1,
    max: 65536,
    precision: 0,
    required: false,
    template: 'max_tokens',
  },
]

const KIMI_K25_PARAMETER_RULES = [
  {
    name: 'maxOutputTokens',
    type: 'int' as const,
    label: 'Max Output Tokens',
    help: 'Maximum number of tokens to generate.',
    default: 8192,
    min: 1,
    max: 262144,
    precision: 0,
    required: false,
    template: 'max_tokens',
  },
]

const KIMI_RESTRICTED_PARAMS = {
  isReasoningModel: false,
  supportedParams: ['max_tokens'],
  unsupportedParams: ['temperature', 'top_p', 'presence_penalty', 'frequency_penalty'],
}

export const KIMI_MODELS: Record<string, ModelCapabilities> = {
  'kimi-k2.5': {
    provider: 'kimi',
    modelId: 'kimi-k2.5',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Kimi K2.5',
    icon: 'kimi',
    color: '#027AFF',
    contextLength: 262144,
    maxTokens: 262144,
    modelType: ModelType.LLM,
    features: ['chat', 'code', 'vision'],
    supports: {
      streaming: true,
      structured: true,
      vision: true,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0006, output: 0.0025 },
    description:
      'Moonshot AI most capable model with 262K context, native multimodal support, tool calling, and structured output. Sampling parameters (temperature, top_p) are fixed by the model.',
    parameterRestrictions: KIMI_RESTRICTED_PARAMS,
    parameterRules: KIMI_K25_PARAMETER_RULES,
  },
  'kimi-k2-0905-preview': {
    provider: 'kimi',
    modelId: 'kimi-k2-0905-preview',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Kimi K2 0905',
    icon: 'kimi',
    color: '#027AFF',
    contextLength: 256000,
    maxTokens: 65536,
    modelType: ModelType.LLM,
    features: ['chat', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0008, output: 0.00225 },
    description:
      'Enhanced agentic coding model with full parameter support. 256K context, 1T parameters (32B active MoE).',
    parameterRules: KIMI_PARAMETER_RULES,
  },
  'kimi-k2-turbo-preview': {
    provider: 'kimi',
    modelId: 'kimi-k2-turbo-preview',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Kimi K2 Turbo',
    icon: 'kimi',
    color: '#027AFF',
    contextLength: 256000,
    maxTokens: 65536,
    modelType: ModelType.LLM,
    features: ['chat', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0006, output: 0.0025 },
    description:
      'High-speed model with output up to 60-100 tokens/sec. 256K context. Sampling parameters are fixed by the model.',
    parameterRestrictions: KIMI_RESTRICTED_PARAMS,
    parameterRules: KIMI_RESTRICTED_PARAMETER_RULES,
  },
  'kimi-k2-thinking': {
    provider: 'kimi',
    modelId: 'kimi-k2-thinking',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Kimi K2 Thinking',
    icon: 'kimi',
    color: '#027AFF',
    contextLength: 256000,
    maxTokens: 65536,
    modelType: ModelType.LLM,
    features: ['chat', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0006, output: 0.0025 },
    description:
      'Deep reasoning model for complex multi-step tasks. 256K context. Built-in thinking mode with extended chain-of-thought.',
    parameterRestrictions: {
      isReasoningModel: true,
      supportedParams: ['max_tokens'],
      unsupportedParams: ['temperature', 'top_p', 'presence_penalty', 'frequency_penalty'],
    },
    parameterRules: KIMI_RESTRICTED_PARAMETER_RULES,
  },
  'kimi-k2-thinking-turbo': {
    provider: 'kimi',
    modelId: 'kimi-k2-thinking-turbo',
    fetchFrom: FetchFrom.PREDEFINED_MODEL,
    displayName: 'Kimi K2 Thinking Turbo',
    icon: 'kimi',
    color: '#027AFF',
    contextLength: 256000,
    maxTokens: 65536,
    modelType: ModelType.LLM,
    features: ['chat', 'code'],
    supports: {
      streaming: true,
      structured: true,
      vision: false,
      toolCalling: true,
      systemMessages: true,
      fileInput: false,
    },
    costPer1kTokens: { input: 0.0006, output: 0.0025 },
    description:
      'Fast reasoning model with output up to 60-100 tokens/sec. 256K context. Built-in thinking mode with high-speed chain-of-thought.',
    parameterRestrictions: {
      isReasoningModel: true,
      supportedParams: ['max_tokens'],
      unsupportedParams: ['temperature', 'top_p', 'presence_penalty', 'frequency_penalty'],
    },
    parameterRules: KIMI_RESTRICTED_PARAMETER_RULES,
  },
}
